/*
 * PWA admin module.
 * ASCII only.
 */
// pwa.js - PWA enrollment request management
async function loadPwaEnrollments() { try { const data = await api('/api/admin/enrollments/all'); pwaEnrollmentsCache = data.enrollments || []; renderPwaEnrollments(); } catch (err) { const msg = pwa('loadFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
function renderPwaEnrollments() { const root = document.getElementById('pwaEnrollmentList'); if (!root) return; if (!pwaEnrollmentsCache.length) { root.innerHTML = '<div class="hint">' + pwa('emptyList') + '</div>'; return; } root.innerHTML = '<div style="display:grid;gap:6px">' + pwaEnrollmentsCache.map(e => { const isPending = e.status === 'pending'; const badgeClass = isPending ? 'warn' : e.status === 'approved' ? 'ok' : 'danger'; const statusLabel = isPending ? pwa('statusPending') : e.status === 'approved' ? pwa('statusApproved') : pwa('statusRejected'); const actions = isPending ? '<div style="display:flex;gap:6px;justify-content:flex-end;flex-wrap:wrap"><button class="btn-primary" style="height:28px;font-size:11px;padding:0 10px" data-id="' + escapeHtml(String(e.id || '')) + '" data-email="' + escapeHtml(String(e.email || '')) + '" onclick="approvePwaEnrollment(this.dataset.id, this.dataset.email)">' + pwa('approve') + '</button><button class="btn-danger" style="height:28px;font-size:11px;padding:0 10px" data-id="' + escapeHtml(String(e.id || '')) + '" data-email="' + escapeHtml(String(e.email || '')) + '" onclick="rejectPwaEnrollment(this.dataset.id, this.dataset.email)">' + pwa('reject') + '</button></div>' : ''; return '<div class="item" style="padding:10px 12px;border-radius:12px;background:#fff;border:1px solid rgba(31,34,48,.06);box-shadow:none"><div style="display:grid;grid-template-columns:minmax(180px,1.2fr) minmax(0,1.2fr) minmax(120px,.85fr) auto ' + (isPending ? 'auto' : '') + ';gap:10px;align-items:center"><div style="min-width:0"><div class="item-title" style="font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + escapeHtml(e.email || '-') + '</div></div><div class="item-meta" style="font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + escapeHtml((e.note || '-')) + '</div><div class="item-meta" style="font-size:11px">' + escapeHtml(e.created_at || '-') + '</div><span class="badge ' + badgeClass + '" style="padding:4px 8px;font-size:10px">' + escapeHtml(statusLabel) + '</span>' + actions + '</div></div>'; }).join('') + '</div>'; }
async function approvePwaEnrollment(id, email) { if (!confirm(pwa('approveConfirm', { email }))) return; try { const data = await api('/api/admin/enrollments/approve', { method: 'POST', body: JSON.stringify({ id }) }); const msg = pwa('approveSuccess', { email, sn: data.user?.sn || '-' }); setOutput(msg); showToast(msg, 'success'); await loadPwaEnrollments(); } catch (err) { const msg = pwa('approveFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function rejectPwaEnrollment(id, email) { if (!confirm(pwa('rejectConfirm', { email }))) return; try { await api('/api/admin/enrollments/reject', { method: 'POST', body: JSON.stringify({ id }) }); const msg = pwa('rejectSuccess'); setOutput(msg); showToast(msg, 'success'); await loadPwaEnrollments(); } catch (err) { const msg = pwa('rejectFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function manualApprovePwaEmail() { const email = document.getElementById('pwaManualEmail').value.trim(); if (!email) return; try { const data = await api('/api/admin/users/manual-bind', { method: 'POST', body: JSON.stringify({ email }) }); const msg = pwa('manualApproveSuccess', { email, sn: data.user?.sn || '-' }); setOutput(msg); showToast(msg, 'success'); document.getElementById('pwaManualEmail').value = ''; await loadPwaEnrollments(); } catch (err) { const msg = pwa('manualApproveFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }

async function loadPendingLogins() { try { const data = await api('/api/admin/enrollments/pending-logins'); const logins = data.logins || []; const root = document.getElementById('pendingLoginsList'); if (!root) return; if (!logins.length) { root.innerHTML = '<div class="hint">' + pwa('pendingLoginsEmpty') + '</div>'; return; } root.innerHTML = '<div style="display:grid;gap:6px">' + logins.map(l => '<div class="item" style="padding:10px 12px;border-radius:12px;background:#fff;border:1px solid rgba(31,34,48,.06);box-shadow:none"><div style="display:grid;grid-template-columns:minmax(180px,1.3fr) minmax(120px,.9fr);gap:10px;align-items:center"><div style="min-width:0"><div class="item-title" style="font-size:12px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis">' + escapeHtml(l.email) + '</div></div><div class="item-meta" style="font-size:11px">' + escapeHtml(l.created_at || '') + '</div></div></div>').join('') + '</div>'; } catch (err) { setOutput(err.message); } }
