// actions.js - Admin actions: auth, governance, center, machines, system settings
async function lookupScopedUser(email) { if (!email) return null; const data = await api(`/api/admin/users/lookup?email=${encodeURIComponent(email)}`); return data.user || null; }
async function setupAdmin() { try { if (adminInitialized) { setSetupAvailability(false); showAuthStage('login'); document.getElementById('loginPassword').focus(); return; } const username = document.getElementById('setupUsername').value.trim(); const data = await api('/api/admin/setup', { method: 'POST', body: JSON.stringify({ username, password: document.getElementById('setupPassword').value }) }); document.getElementById('loginUsername').value = username; document.getElementById('loginPassword').value = ''; adminInitialized = true; setSetupAvailability(false); setOutput(tr('setupDone', { message: data.message || tr('administrator') }), 'loginOutput'); showAuthStage('login'); document.getElementById('loginPassword').focus(); } catch (err) { setOutput(tr('setupFailed', { error: err.message }), 'loginOutput'); } }
async function loginAdmin() { try { const data = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ username: document.getElementById('loginUsername').value.trim(), password: document.getElementById('loginPassword').value }) }); localStorage.setItem(adminTokenKey, data.access_token); localStorage.setItem(adminProfileKey, JSON.stringify(data.admin || {})); setAuthState(true); restoreTab(); await refreshAll(); } catch (err) { setOutput(tr('loginFailed', { error: err.message }), 'loginOutput'); } }
function logoutAdmin() { _stopCenterPoll(); localStorage.removeItem(adminTokenKey); localStorage.removeItem(adminProfileKey); var sra = document.getElementById('smartRouteAllToggle'); if (sra) { sra.checked = false; delete sra.dataset.loaded; } window._boundUsersAll = null; window._boundUsersPage = 1; window._boundUsersSearch = ''; setAuthState(false); }
async function manualBind() { try { const email = document.getElementById('bindEmail').value.trim(); const data = await api('/api/admin/users/manual-bind', { method: 'POST', body: JSON.stringify({ email }) }); const msg = tr('bindDone', { email: data.user?.email || email, sn: data.user?.sn || tr('na') }); setOutput(msg); showToast(msg, 'success'); await Promise.all([loadBoundUsers(), loadMachines()]); } catch (err) { const msg = tr('bindFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function loadBoundUsers() { try { const data = await api('/api/admin/users'); renderBoundUsers(data.users || []); } catch (err) { setOutput(tr('bindFailed', { error: err.message })); } }
async function addBlockedEmail() { try { await api('/api/admin/blocklist', { method: 'POST', body: JSON.stringify({ email: document.getElementById('blockedEmail').value.trim(), reason: document.getElementById('blockedReason').value.trim() }) }); setOutput(tr('blockedAdded')); await loadBlockedEmails(); } catch (err) { setOutput(tr('blockedAddFailed', { error: err.message })); } }
async function loadBlockedEmails() { try { const data = await api('/api/admin/blocklist'); renderBlockedEmails(data.blocked_emails || []); } catch (err) { setOutput(tr('blockedLoadFailed', { error: err.message })); } }
async function saveCenterConfig() { try { const data = await api('/api/admin/center/config', { method: 'POST', body: JSON.stringify({ base_url: document.getElementById('centerBaseURL').value.trim(), public_base_url: document.getElementById('centerPublicBaseURL').value.trim(), visibility: document.getElementById('centerVisibility').value, enrollment_mode: document.getElementById('centerEnrollmentMode').value }) }); renderCenterStatus(data); const msg = tr('centerSaved'); setOutput(msg); showToast(msg, 'success'); } catch (err) { const msg = tr('centerSaveFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function registerWithCenter() { try { const data = await api('/api/admin/center/register', { method: 'POST', body: JSON.stringify({}) }); renderCenterStatus(data); const msg = data.pending_confirmation ? ctr('registerSubmitted') : tr('centerRegisteredMsg'); setOutput(msg); showToast(msg, 'success'); } catch (err) { const msg = tr('centerRegisterFailed', { error: err.message }); document.getElementById('centerStatusDetail').textContent = msg; document.getElementById('centerStatusDetailTab').textContent = msg; document.getElementById('centerRegisteredNotice').classList.add('hidden'); document.getElementById('centerRegisterActions').classList.remove('hidden'); setOutput(msg); showToast(msg, 'error'); } }
async function loadCenterStatus() { try { const data = await api('/api/admin/center/status'); renderCenterStatus(data); } catch (err) { setOutput(tr('centerLoadFailed', { error: err.message })); } }
async function loadMachines() { try { machinePage = 1; const scope = document.getElementById('bindEmail').value.trim(); const emailScope = document.getElementById('machineEmailSearch').value.trim(); const showAll = document.getElementById('machinesShowAll')?.checked; let path = '/api/admin/debug/machines'; if (emailScope) { path = `/api/admin/debug/machines?email=${encodeURIComponent(emailScope)}`; } else if (scope) { const user = await lookupScopedUser(scope); if (!user || !user.id) throw new Error(tr('noHubUser', { email: scope })); path = `/api/admin/debug/machines?user_id=${encodeURIComponent(user.id)}`; } else if (showAll) { path = '/api/admin/debug/machines?all=1'; } const data = await api(path); renderMachineList(data.machines || []); } catch (err) { setOutput(tr('machinesLoadFailed', { error: err.message })); } }
async function searchMachinesByEmail() { const email = document.getElementById('machineEmailSearch').value.trim(); if (!email) { const msg = ml('emailRequired'); setOutput(msg); showToast(msg, 'error'); return; } await loadMachines(); }
async function deleteAllMachinesByEmail() { const email = document.getElementById('machineEmailSearch').value.trim(); if (!email) { const msg = ml('emailRequired'); setOutput(msg); showToast(msg, 'error'); return; } if (!confirm(ml('emailDeleteAllConfirm'))) return; try { const data = await api(`/api/admin/machines/by-email?email=${encodeURIComponent(email)}`, { method: 'DELETE' }); const msg = ml('emailDeleteAllSuccess').replace('{count}', String(data.deleted || 0)); setOutput(msg); showToast(msg, 'success'); await loadMachines(); } catch (err) { const msg = ml('emailDeleteAllFailed').replace('{error}', err.message); setOutput(msg); showToast(msg, 'error'); } }
async function forceDeleteAllMachinesByEmail() { const email = document.getElementById('machineEmailSearch').value.trim(); if (!email) { const msg = ml('emailRequired'); setOutput(msg); showToast(msg, 'error'); return; } if (!confirm(ml('emailForceDeleteConfirm'))) return; try { const data = await api(`/api/admin/machines/force-by-email?email=${encodeURIComponent(email)}`, { method: 'DELETE' }); const msg = ml('emailForceDeleteSuccess').replace('{count}', String(data.deleted || 0)); setOutput(msg); showToast(msg, 'success'); await loadMachines(); } catch (err) { const msg = ml('emailForceDeleteFailed').replace('{error}', err.message); setOutput(msg); showToast(msg, 'error'); } }
async function deleteMachine(machineID) { if (!confirm(ml('deleteConfirm'))) return; try { await api(`/api/admin/machines?machine_id=${encodeURIComponent(machineID)}`, { method: 'DELETE' }); const msg = ml('deleteSuccess'); setOutput(msg); showToast(msg, 'success'); await loadMachines(); } catch (err) { const msg = ml('deleteFailed').replace('{error}', err.message); setOutput(msg); showToast(msg, 'error'); } }
async function renameMachine(machineID, currentAlias) { const alias = prompt(ml('renamePrompt'), currentAlias || ''); if (alias === null) return; try { await api('/api/admin/machines/rename', { method: 'POST', body: JSON.stringify({ machine_id: machineID, alias: alias.trim() }) }); const msg = ml('renameSuccess'); setOutput(msg); showToast(msg, 'success'); await loadMachines(); } catch (err) { const msg = ml('renameFailed').replace('{error}', err.message); setOutput(msg); showToast(msg, 'error'); } }
async function clearOfflineMachines() { if (!confirm(ml('clearOfflineConfirm'))) return; try { const data = await api('/api/admin/machines/clear-offline', { method: 'POST' }); const msg = ml('clearSuccess').replace('{count}', String(data.cleared || 0)); setOutput(msg); showToast(msg, 'success'); await loadMachines(); } catch (err) { const msg = ml('clearFailed').replace('{error}', err.message); setOutput(msg); showToast(msg, 'error'); } }
async function sendTestMail() { try { const email = document.getElementById('testMailEmail').value.trim(); if (!email) { const msg = currentLang === 'zh' ? '\u8bf7\u8f93\u5165\u6d4b\u8bd5\u6536\u4ef6\u4eba\u90ae\u7bb1\u3002' : 'Please enter a test recipient email.'; setOutput(msg); showToast(msg, 'error'); return; } await saveMailConfig(); const data = await api('/api/admin/mail/test', { method: 'POST', body: JSON.stringify({ email }) }); const msg = data.message || tr('mailSent'); setOutput(msg); showToast(msg, 'success'); } catch (err) { const msg = tr('mailFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function changeAdminPassword() { const currentPassword = document.getElementById('currentPasswordInput').value; const newPassword = document.getElementById('newPasswordInput').value; const confirmPassword = document.getElementById('confirmPasswordInput').value; if (!currentPassword || !newPassword) { const msg = tr('requestFailed'); setOutput(msg); showToast(msg, 'error'); return; } if (newPassword !== confirmPassword) { const msg = ptr('mismatch'); setOutput(msg); showToast(msg, 'error'); return; } try { const data = await api('/api/admin/password', { method: 'POST', body: JSON.stringify({ current_password: currentPassword, new_password: newPassword }) }); if (data.access_token) localStorage.setItem(adminTokenKey, data.access_token); if (data.admin) localStorage.setItem(adminProfileKey, JSON.stringify(data.admin)); document.getElementById('currentPasswordInput').value = ''; document.getElementById('newPasswordInput').value = ''; document.getElementById('confirmPasswordInput').value = ''; refreshAdminHeader(); const msg = ptr('changed'); setOutput(msg); showToast(msg, 'success'); } catch (err) { setOutput(err.message); showToast(err.message, 'error'); } }
async function updateAdminProfile() { const email = document.getElementById('adminEmailInput').value.trim(); if (!email) { const msg = prf('required'); setOutput(msg); showToast(msg, 'error'); return; } try { const data = await api('/api/admin/profile', { method: 'POST', body: JSON.stringify({ email }) }); if (data.access_token) localStorage.setItem(adminTokenKey, data.access_token); if (data.admin) localStorage.setItem(adminProfileKey, JSON.stringify(data.admin)); refreshAdminHeader(); const msg = prf('saved'); setOutput(msg); showToast(msg, 'success'); } catch (err) { const msg = prf('failed').replace('{error}', err.message); setOutput(msg); showToast(msg, 'error'); } }

// --- Smart Route ---
async function toggleSmartRoute(userID, enabled) { try { await api('/api/admin/users/smart_route', { method: 'POST', body: JSON.stringify({ user_id: userID, enabled }) }); var items = window._boundUsersAll || []; for (var i = 0; i < items.length; i++) { if (items[i].id === userID) { items[i].smart_route = enabled; break; } } _renderBoundUsersPage(); } catch (err) { showToast(err.message, 'error'); var cb = document.getElementById('sr_' + userID); if (cb) cb.checked = !enabled; } }
async function loadSmartRouteAll() { try { const data = await api('/api/admin/smart_route_all'); return data.enabled || false; } catch { return false; } }
async function toggleSmartRouteAll(enabled) { try { await api('/api/admin/smart_route_all', { method: 'PUT', body: JSON.stringify({ enabled }) }); showToast(enabled ? '已开启全员智能路由' : '已关闭全员智能路由', 'success'); } catch (err) { showToast(err.message, 'error'); var el = document.getElementById('smartRouteAllToggle'); if (el) el.checked = !enabled; } }
