/*
 * Hub LLM admin module.
 * ASCII only.
 */
const HUB_LLM_I18N = {
  en: { saved: 'Hub LLM config saved.', saveFailed: 'Save Hub LLM config failed: {error}', loadFailed: 'Load Hub LLM config failed: {error}', testing: 'Testing...', testBtn: 'Test Connection', testOk: '\u2705 LLM connected ({ms}ms), reply: {reply}', testFail: '\u274c LLM connection failed: {error}', testError: '\u274c LLM test failed: {error}', statusHealthy: '\ud83d\udfe2 Healthy', statusHalfOpen: '\ud83d\udfe1 Recovering', statusOpen: '\ud83d\udd34 Circuit Open', statusNone: '\u26aa Not Configured' },
  zh: { saved: 'Hub LLM \u914d\u7f6e\u5df2\u4fdd\u5b58\u3002', saveFailed: '\u4fdd\u5b58 Hub LLM \u914d\u7f6e\u5931\u8d25\uff1a{error}', loadFailed: '\u52a0\u8f7d Hub LLM \u914d\u7f6e\u5931\u8d25\uff1a{error}', testing: '\u6d4b\u8bd5\u4e2d...', testBtn: '\u6d4b\u8bd5\u8fde\u63a5', testOk: '\u2705 LLM \u8fde\u63a5\u6210\u529f ({ms}ms)\uff0c\u56de\u590d: {reply}', testFail: '\u274c LLM \u8fde\u63a5\u5931\u8d25: {error}', testError: '\u274c LLM \u6d4b\u8bd5\u5931\u8d25: {error}', statusHealthy: '\ud83d\udfe2 \u6b63\u5e38', statusHalfOpen: '\ud83d\udfe1 \u6062\u590d\u4e2d', statusOpen: '\ud83d\udd34 \u7194\u65ad\u4e2d', statusNone: '\u26aa \u672a\u914d\u7f6e' }
};
const hli = (key, vars = {}) => ((HUB_LLM_I18N[currentLang] || HUB_LLM_I18N.en)[key] || HUB_LLM_I18N.en[key] || key).replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? '');

async function loadHubLlmConfig() { try { const data = await api('/api/admin/hub_llm_config'); document.getElementById('hubLlmEnabled').checked = !!data.enabled; document.getElementById('hubLlmSmartRouteSingle').checked = !!data.smart_route_single_device; document.getElementById('hubLlmApiUrl').value = data.api_url || ''; const keyInput = document.getElementById('hubLlmApiKey'); keyInput.value = ''; keyInput.placeholder = data.has_api_key ? (currentLang === 'zh' ? '\u5df2\u914d\u7f6e\uff08\u7559\u7a7a\u4fdd\u6301\u4e0d\u53d8\uff09' : 'Configured (leave empty to keep)') : (currentLang === 'zh' ? '\u8bf7\u8f93\u5165 API Key' : 'Enter API Key'); document.getElementById('hubLlmModel').value = data.model || ''; document.getElementById('hubLlmProtocol').value = data.protocol || 'openai'; } catch (err) { const msg = hli('loadFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function saveHubLlmConfig() { try { const payload = { enabled: document.getElementById('hubLlmEnabled').checked, smart_route_single_device: document.getElementById('hubLlmSmartRouteSingle').checked, api_url: document.getElementById('hubLlmApiUrl').value.trim(), api_key: document.getElementById('hubLlmApiKey').value, model: document.getElementById('hubLlmModel').value.trim(), protocol: document.getElementById('hubLlmProtocol').value }; const data = await api('/api/admin/hub_llm_config', { method: 'PUT', body: JSON.stringify(payload) }); document.getElementById('hubLlmEnabled').checked = !!data.enabled; document.getElementById('hubLlmApiUrl').value = data.api_url || ''; const keyInput = document.getElementById('hubLlmApiKey'); keyInput.value = ''; keyInput.placeholder = data.has_api_key ? (currentLang === 'zh' ? '\u5df2\u914d\u7f6e\uff08\u7559\u7a7a\u4fdd\u6301\u4e0d\u53d8\uff09' : 'Configured (leave empty to keep)') : (currentLang === 'zh' ? '\u8bf7\u8f93\u5165 API Key' : 'Enter API Key'); document.getElementById('hubLlmModel').value = data.model || ''; document.getElementById('hubLlmProtocol').value = data.protocol || 'openai'; const msg = hli('saved'); setOutput(msg); showToast(msg, 'success'); loadHubLlmStatus(); } catch (err) { const msg = hli('saveFailed', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } }
async function testHubLlm() { const btn = document.getElementById('hubLlmTestBtn'); if (btn) { btn.disabled = true; btn.textContent = hli('testing'); } try { const data = await api('/api/admin/hub_llm_test', { method: 'POST' }); if (data.success) { const msg = hli('testOk', { ms: data.latency_ms, reply: data.reply || '' }); setOutput(msg); showToast(msg, 'success'); } else { const msg = hli('testFail', { error: data.error || 'Unknown' }); setOutput(msg); showToast(msg, 'error'); } } catch (err) { const msg = hli('testError', { error: err.message }); setOutput(msg); showToast(msg, 'error'); } finally { if (btn) { btn.disabled = false; btn.textContent = hli('testBtn'); } } }
async function loadHubLlmStatus() { try { const data = await api('/api/admin/hub_llm_status'); const badge = document.getElementById('hubLlmStatusBadge'); if (badge) { const s = data.status || 'not_configured'; const map = { healthy: [hli('statusHealthy'), 'ok'], half_open: [hli('statusHalfOpen'), 'warn'], open: [hli('statusOpen'), 'danger'], not_configured: [hli('statusNone'), 'info'] }; const [text, cls] = map[s] || ['\u26aa ' + s, 'info']; badge.textContent = text; badge.className = 'badge ' + cls; } } catch (_) {} }
