#pragma once

/* Waveshare codec/I2S electrical facts. PMIC, touch and IMU remain in the
 * independently selected Peripheral adapter. */

#include "driver/gpio.h"
#include "driver/i2s_std.h"

#define WAVESHARE_AUDIO_I2C_SCL GPIO_NUM_14
#define WAVESHARE_AUDIO_I2C_SDA GPIO_NUM_15
#define WAVESHARE_AUDIO_MCLK GPIO_NUM_16
#define WAVESHARE_AUDIO_BCLK GPIO_NUM_9
#define WAVESHARE_AUDIO_WS GPIO_NUM_45
#define WAVESHARE_AUDIO_DOUT GPIO_NUM_8
#define WAVESHARE_AUDIO_DIN GPIO_NUM_10
#define WAVESHARE_AUDIO_PA_ENABLE GPIO_NUM_46
#define WAVESHARE_AUDIO_ES7210_ADDRESS 0x40
#define WAVESHARE_AUDIO_ES8311_ADDRESS 0x18
#define WAVESHARE_AUDIO_ES8311_DAC_MUTE_REG 0x31
#define WAVESHARE_AUDIO_ES8311_DAC_VOLUME_REG 0x32
#define WAVESHARE_AUDIO_OUTPUT_VOLUME_DEFAULT 70
#define WAVESHARE_AUDIO_RATE 16000
#define WAVESHARE_AUDIO_MCLK_MULTIPLE I2S_MCLK_MULTIPLE_256
