// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AckGoalPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['AckGoalPush'](arg1, arg2, arg3);
}

export function AutoHandleGoalPush(arg1) {
  return window['go']['main']['App']['AutoHandleGoalPush'](arg1);
}

export function AutoHandleRecommendedGoalPushes() {
  return window['go']['main']['App']['AutoHandleRecommendedGoalPushes']();
}

export function CheckCenterHealth() {
  return window['go']['main']['App']['CheckCenterHealth']();
}

export function DiscoverCenterEnrollment(arg1) {
  return window['go']['main']['App']['DiscoverCenterEnrollment'](arg1);
}

export function ApplyCenterEnrollment(arg1) {
  return window['go']['main']['App']['ApplyCenterEnrollment'](arg1);
}


export function DeleteWorkerMemory(arg1) {
  return window['go']['main']['App']['DeleteWorkerMemory'](arg1);
}
export function FetchAgentInstances() {
  return window['go']['main']['App']['FetchAgentInstances']();
}

export function FetchGoalPushes(arg1) {
  return window['go']['main']['App']['FetchGoalPushes'](arg1);
}

export function FetchInstalledTools() {
  return window['go']['main']['App']['FetchInstalledTools']();
}

export function FetchWorkerMemoryStats() {
  return window['go']['main']['App']['FetchWorkerMemoryStats']();
}

export function GetAgentRuntimeSnapshot() {
  return window['go']['main']['App']['GetAgentRuntimeSnapshot']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetGoalWatchAutoHandleStatus() {
  return window['go']['main']['App']['GetGoalWatchAutoHandleStatus']();
}

export function GetWelcomeData() {
  return window['go']['main']['App']['GetWelcomeData']();
}

export function HeartbeatAgentRuntime() {
  return window['go']['main']['App']['HeartbeatAgentRuntime']();
}

export function LoadDiWorkerSettings() {
  return window['go']['main']['App']['LoadDiWorkerSettings']();
}

export function LoadTaskHistory() {
  return window['go']['main']['App']['LoadTaskHistory']();
}

export function RecallWorkerMemories(arg1) {
  return window['go']['main']['App']['RecallWorkerMemories'](arg1);
}

export function SaveDiWorkerSettings(arg1) {
  return window['go']['main']['App']['SaveDiWorkerSettings'](arg1);
}

export function SaveTaskHistory(arg1) {
  return window['go']['main']['App']['SaveTaskHistory'](arg1);
}

export function SaveWorkerMemory(arg1) {
  return window['go']['main']['App']['SaveWorkerMemory'](arg1);
}

export function SubmitTask(arg1) {
  return window['go']['main']['App']['SubmitTask'](arg1);
}
