// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckCenterHealth() {
  return window['go']['main']['App']['CheckCenterHealth']();
}


export function DeleteWorkerMemory(arg1) {
  return window['go']['main']['App']['DeleteWorkerMemory'](arg1);
}
export function FetchWorkerMemoryStats() {
  return window['go']['main']['App']['FetchWorkerMemoryStats']();
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetWelcomeData() {
  return window['go']['main']['App']['GetWelcomeData']();
}

export function LoadDiWorkerSettings() {
  return window['go']['main']['App']['LoadDiWorkerSettings']();
}

export function LoadTaskHistory() {
  return window['go']['main']['App']['LoadTaskHistory']();
}

export function RecallWorkerMemories(arg1) {
  return window['go']['main']['App']['RecallWorkerMemories'](arg1);
}

export function SaveDiWorkerSettings(arg1) {
  return window['go']['main']['App']['SaveDiWorkerSettings'](arg1);
}

export function SaveTaskHistory(arg1) {
  return window['go']['main']['App']['SaveTaskHistory'](arg1);
}

export function SaveWorkerMemory(arg1) {
  return window['go']['main']['App']['SaveWorkerMemory'](arg1);
}

export function SubmitTask(arg1) {
  return window['go']['main']['App']['SubmitTask'](arg1);
}
