// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AckGoalPush(arg1:string,arg2:string,arg3:string):Promise<main.CenterGoalPushAckResult>;

export function AutoHandleGoalPush(arg1:string):Promise<main.AutoHandleGoalPushResult>;

export function AutoHandleRecommendedGoalPushes():Promise<Array<main.AutoHandleGoalPushResult>>;

export function CheckCenterHealth():Promise<main.CenterHealthStatus>;

export function DiscoverCenterEnrollment(arg1:main.CenterEnrollmentRequest):Promise<main.CenterEnrollmentDiscovery>;

export function ApplyCenterEnrollment(arg1:main.ApplyCenterEnrollmentRequest):Promise<main.DiWorkerSettings>;

export function DeleteWorkerMemory(arg1:string):Promise<void>;

export function FetchAgentInstances():Promise<Array<main.CenterAgentInstance>>;

export function FetchConfigBundle():Promise<main.CenterConfigBundle>;

export function FetchCollaborations(arg1:string):Promise<Array<main.CenterCollabTask>>;

export function FetchGoalPushes(arg1:number):Promise<Array<main.CenterGoalPush>>;

export function FetchWorkflowInstances():Promise<Array<main.CenterWorkflowInstance>>;

export function RecoverGoalPush(arg1:string,arg2:string):Promise<main.CenterGoalPushRecoverResult>;

export function FetchInstalledTools():Promise<main.CenterInstalledTools>;

export function FetchWorkerMemoryStats():Promise<main.WorkerMemoryStats>;

export function GetAgentRuntimeSnapshot():Promise<main.AgentRuntimeSnapshot>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetGoalWatchAutoHandleStatus():Promise<main.GoalWatchAutoHandleStatus>;

export function GetWelcomeData():Promise<main.WelcomeData>;

export function HeartbeatAgentRuntime():Promise<Array<main.CenterAgentInstance>>;

export function LoadDiWorkerSettings():Promise<main.DiWorkerSettings>;

export function RecallWorkerMemories(arg1:string):Promise<Array<main.WorkerMemoryEntry>>;

export function RecommendColleague(arg1:string):Promise<Array<main.CenterRecommendation>>;

export function LoadTaskHistory():Promise<Array<main.HistoryTaskItem>>;

export function SaveDiWorkerSettings(arg1:main.DiWorkerSettings):Promise<void>;

export function SaveWorkerMemory(arg1:main.SaveWorkerMemoryRequest):Promise<main.WorkerMemoryEntry>;

export function SaveTaskHistory(arg1:Array<main.HistoryTaskItem>):Promise<void>;

export function SubmitTask(arg1:main.SubmitTaskRequest):Promise<main.SubmitTaskResult>;

export function TransitionCollaborationTask(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CenterCollabTask>;

export function TransitionWorkflowStep(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.CenterWorkflowStepTransitionResult>;
