from __future__ import annotations

import plistlib
import sys
import tempfile
import unittest
from contextlib import redirect_stdout
from io import StringIO
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import verify_ios_wrapper


def write_plist(path: Path, value: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open('wb') as fh:
        plistlib.dump(value, fh)


class VerifyIosWrapperTest(unittest.TestCase):
    def setUp(self) -> None:
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        self.mobile = self.root / 'mobile/maclaw_mobile'
        self._write_valid_fixture()

    def tearDown(self) -> None:
        self.tmp.cleanup()

    def _write_valid_fixture(self) -> None:
        ios = self.mobile / 'ios'
        runner_info = {
            **verify_ios_wrapper.IOS_USAGE_DESCRIPTIONS,
            'AppGroupId': '$(CUSTOM_GROUP_ID)',
            'CFBundleURLTypes': [
                {'CFBundleURLSchemes': ['maclaw']},
                {'CFBundleURLSchemes': ['ShareMedia-$(PRODUCT_BUNDLE_IDENTIFIER)']},
            ],
        }
        share_info = {
            'AppGroupId': '$(CUSTOM_GROUP_ID)',
            'NSExtension': {
                'NSExtensionPointIdentifier': 'com.apple.share-services',
                'NSExtensionPrincipalClass': '$(PRODUCT_MODULE_NAME).ShareViewController',
                'NSExtensionAttributes': {
                    'PHSupportedMediaTypes': ['Image'],
                    'NSExtensionActivationRule': {
                        'NSExtensionActivationSupportsText': True,
                        'NSExtensionActivationSupportsWebURLWithMaxCount': 1,
                        'NSExtensionActivationSupportsFileWithMaxCount': 10,
                        'NSExtensionActivationSupportsImageWithMaxCount': 20,
                    },
                },
            },
        }
        entitlements = {'com.apple.security.application-groups': ['$(CUSTOM_GROUP_ID)']}
        write_plist(ios / 'Runner/Info.plist', runner_info)
        write_plist(ios / 'Runner/Runner.entitlements', entitlements)
        write_plist(ios / 'ShareExtension/Info.plist', share_info)
        write_plist(ios / 'ShareExtension/ShareExtension.entitlements', entitlements)
        controller = ios / 'ShareExtension/ShareViewController.swift'
        controller.write_text('class ShareViewController: RSIShareViewController {}', encoding='utf-8')
        project = ios / 'Runner.xcodeproj/project.pbxproj'
        project.parent.mkdir(parents=True)
        project.write_text(
            'PRODUCT_BUNDLE_IDENTIFIER = top.mypapers.maclaw.mobile;\n'
            'PRODUCT_BUNDLE_IDENTIFIER = top.mypapers.maclaw.mobile.RunnerTests;\n'
            'CUSTOM_GROUP_ID = group.top.mypapers.maclaw.mobile;\n'
            'MaClaw Mobile Share Extension files are generated by tool/configure_platforms.py\n',
            encoding='utf-8',
        )

    def test_valid_ios_wrapper_passes(self) -> None:
        self.assertEqual([], verify_ios_wrapper.verify_ios_wrapper(self.mobile))

    def test_rejects_unreadable_usage_description(self) -> None:
        path = self.mobile / 'ios/Runner/Info.plist'
        plist = verify_ios_wrapper.read_plist(path)
        plist['NSCameraUsageDescription'] = '????'
        write_plist(path, plist)

        errors = verify_ios_wrapper.verify_ios_wrapper(self.mobile)

        self.assertTrue(any('NSCameraUsageDescription' in error for error in errors))

    def test_rejects_missing_share_activation_rule(self) -> None:
        path = self.mobile / 'ios/ShareExtension/Info.plist'
        plist = verify_ios_wrapper.read_plist(path)
        extension = plist['NSExtension']
        attrs = extension['NSExtensionAttributes']
        activation = attrs['NSExtensionActivationRule']
        activation.pop('NSExtensionActivationSupportsFileWithMaxCount')
        write_plist(path, plist)

        errors = verify_ios_wrapper.verify_ios_wrapper(self.mobile)

        self.assertTrue(any('NSExtensionActivationSupportsFileWithMaxCount' in error for error in errors))

    def test_rejects_missing_app_group_entitlement(self) -> None:
        write_plist(
            self.mobile / 'ios/Runner/Runner.entitlements',
            {'com.apple.security.application-groups': []},
        )

        errors = verify_ios_wrapper.verify_ios_wrapper(self.mobile)

        self.assertTrue(any('Runner entitlements' in error for error in errors))

    def test_rejects_missing_project_generation_marker(self) -> None:
        project = self.mobile / 'ios/Runner.xcodeproj/project.pbxproj'
        project.write_text(
            project.read_text(encoding='utf-8').replace(
                'MaClaw Mobile Share Extension files are generated by tool/configure_platforms.py\n',
                '',
            ),
            encoding='utf-8',
        )

        errors = verify_ios_wrapper.verify_ios_wrapper(self.mobile)

        self.assertTrue(any('Share Extension files are generated' in error for error in errors))

    def test_main_prints_success(self) -> None:
        output = StringIO()

        with redirect_stdout(output):
            exit_code = verify_ios_wrapper.main(['--root', str(self.mobile)])

        self.assertEqual(0, exit_code)
        self.assertIn('verified', output.getvalue())


if __name__ == '__main__':
    unittest.main()
