// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckCenterHealth():Promise<main.CenterHealthStatus>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetWelcomeData():Promise<main.WelcomeData>;

export function LoadDiWorkerSettings():Promise<main.DiWorkerSettings>;

export function LoadTaskHistory():Promise<Array<main.HistoryTaskItem>>;

export function SaveDiWorkerSettings(arg1:main.DiWorkerSettings):Promise<void>;

export function SaveTaskHistory(arg1:Array<main.HistoryTaskItem>):Promise<void>;

export function SubmitTask(arg1:main.SubmitTaskRequest):Promise<main.SubmitTaskResult>;
