package main

import (
	"context"
	"fmt"
	"log"
	"os"
	"strings"
	"time"

	"github.com/RapidAI/CodeClaw/corelib"
	"github.com/RapidAI/CodeClaw/corelib/agent"
	"github.com/RapidAI/CodeClaw/corelib/i18n"
	"github.com/RapidAI/CodeClaw/corelib/intent"
	"github.com/RapidAI/CodeClaw/corelib/workflow"
)

type agentLoopNeedsConfirmGateResult struct {
	Response                 *IMAgentResponse
	MsgContent               string
	PostStreamReturnPrepTime bool
}

type agentLoopToolBranchNeedsConfirmResult struct {
	Response   *IMAgentResponse
	MsgContent string
}

// getWorkflowEngine returns the workflow engine if available and enabled, or nil.
// This is the single enforcement point for the "workflow enabled" config toggle.
// All workflow consumers (handleWorkflowInterception, applyWorkflowToolFilter,
// needsConfirmFromEngine, needsConfirmToolBranch, etc.) go through this method.
// When it returns nil, all downstream checks naturally short-circuit.
//
// The workflowDisabled atomic.Bool is synced by App.SaveConfig/LoadConfig
// whenever the config changes; zero per-call overhead (no mutex, no disk I/O).
func (h *IMMessageHandler) getWorkflowEngine() *workflow.WorkflowEngine {
	// Check the atomic flag first (zero-cost).
	if h.app != nil && h.app.workflowDisabled.Load() {
		return nil
	}
	if h.workflowEngine != nil {
		return h.workflowEngine
	}
	if h.app == nil {
		return nil
	}
	return h.app.workflowEngine
}

// getWorkflowLang returns the user-facing language for workflow messages.
// Delegates to the same source as the engine's callbacks.GetLang() — the
// app's CurrentLanguage field — ensuring all workflow messages use the same
// language regardless of whether they're generated by the engine or the handler.
func (h *IMMessageHandler) getWorkflowLang() string {
	if h.app != nil {
		return h.app.CurrentLanguage
	}
	return ""
}

func (h *IMMessageHandler) agentLoopUserTextForWorkflow(msg IMUserMessage, workflowAgentLoop bool) string {
	if !workflowAgentLoop {
		return msg.Text
	}
	if orig, ok := h.workflowOriginalRequest.LoadAndDelete(msg.UserID); ok {
		agentLoopUserText, _ := orig.(string)
		log.Printf("[WorkflowInterception] using original request as userText for agent loop: %q (msg.Text was %q)",
			truncateRunes(agentLoopUserText, 80), truncateRunes(msg.Text, 30))
		if strings.TrimSpace(agentLoopUserText) != "" {
			return agentLoopUserText
		}
	}
	return msg.Text
}

func (h *IMMessageHandler) applyAgentLoopNeedsConfirmGate(
	ctx *LoopContext,
	userID string,
	iteration int,
	platform string,
	gateConfig codingToolGateConfig,
	msgContent string,
	lengthContinuationText string,
	phase *agentLoopPhase,
	steeringDetector *SteeringWorkflowDetector,
	history []agent.ConversationEntry,
	streamDone bool,
	attachLLMTelemetry func(*IMAgentResponse),
	attachPendingVisibleArtifacts func(*IMAgentResponse),
) agentLoopNeedsConfirmGateResult {
	result := agentLoopNeedsConfirmGateResult{MsgContent: msgContent}
	needsConfirmFromEngine := false
	if h.getWorkflowEngine() != nil {
		semanticBypass := false
		if !gateConfig.active && gateConfig.intent == intentCoding {
			semanticBypass = true
		}
		if gateConfig.bugFix {
			semanticBypass = true
		}
		if ctx.SkipNeedsConfirmGate && !gateConfig.active {
			semanticBypass = true
		}
		if !semanticBypass {
			needsConfirmFromEngine = h.getWorkflowEngine().IsPhaseNeedsConfirm(userID)
		} else {
			log.Printf("[workflow-gate] NeedsConfirm no-tool engine bypassed: semantic intent=%v active=%v bugFix=%v skipConfirmOther=%v",
				gateConfig.intent, gateConfig.active, gateConfig.bugFix, ctx.SkipNeedsConfirmGate)
		}
	}

	needsConfirmFromSteering := false
	if gateConfig.active && iteration > 0 {
		if h.getWorkflowEngine() != nil && h.getWorkflowEngine().GetActiveWorkflow(userID) != nil {
			needsConfirmFromSteering = h.getWorkflowEngine().IsPhaseNeedsConfirm(userID)
			if !needsConfirmFromSteering && normalizeIMMessagePlatformKind(platform).IsDesktop() {
				log.Printf("[agent-loop] NeedsConfirm steering bypassed: engine workflow active, phase NeedsConfirm=false (iter=%d user=%s)", iteration, userID)
			}
		} else {
			needsConfirmFromSteering = true
		}
	}
	engineGateActive := needsConfirmFromEngine
	if normalizeIMMessagePlatformKind(platform).IsDesktop() && (engineGateActive || needsConfirmFromSteering) {
		log.Printf("[agent-loop] NeedsConfirm check: engine=%v steering=%v iteration=%d msgLen=%d steeringDetector=%v user=%s",
			needsConfirmFromEngine, needsConfirmFromSteering, iteration, len(strings.TrimSpace(stripThinkingTags(msgContent))), steeringDetector != nil, userID)
	}
	if !engineGateActive && !needsConfirmFromSteering {
		return result
	}

	trimmedForGate := strings.TrimSpace(stripThinkingTags(msgContent))
	if containsSelfConfirmationPattern(trimmedForGate) {
		originalLen := len(trimmedForGate)
		trimmedForGate = truncateAtConfirmationBoundary(trimmedForGate)
		msgContent = trimmedForGate
		result.MsgContent = msgContent
		log.Printf("NeedsConfirm gate: detected self-confirmation pattern, truncated at confirmation boundary (originalLen=%d truncatedLen=%d)", originalLen, len(trimmedForGate))
		if h.traceService != nil && ctx.RunID != "" {
			h.appendTraceEvent(ctx, "gate.self_confirm_truncated", "warn",
				fmt.Sprintf("Self-confirmation detected and truncated (originalLen=%d truncatedLen=%d)", originalLen, len(trimmedForGate)),
				truncateTraceText(trimmedForGate, 220), "", "")
		}
	}

	if trimmedForGate == "" || looksLikeNoToolStallReply(msgContent) {
		return result
	}
	if !isSubstantivePhaseDocument(trimmedForGate) {
		log.Printf("[agent-loop] NeedsConfirm gate: skipping non-substantive preamble (len=%d), allowing loop to continue", len([]rune(trimmedForGate)))
		return result
	}

	gateSource := needsConfirmGateSourceWorkflow
	if needsConfirmFromSteering && !engineGateActive {
		gateSource = needsConfirmGateSourceSteering
	}
	log.Printf("[agent-loop] NeedsConfirm gate (%s): returning response for user confirmation (iteration=%d len=%d)", gateSource, iteration, len(trimmedForGate))
	if h.traceService != nil && ctx.RunID != "" {
		h.appendTraceEvent(ctx, "gate.needs_confirm", "info",
			fmt.Sprintf("NeedsConfirm phase gate (%s) - pausing for user confirmation", gateSource),
			truncateTraceText(trimmedForGate, 220), "", "")
	}
	if phase != nil {
		phase.Stage = agentStageFinalize
	}
	gateText := lengthContinuationText + msgContent
	finalResp := &IMAgentResponse{Text: stripThinkingTags(gateText)}
	result.PostStreamReturnPrepTime = streamDone

	docPreviewText := strings.TrimSpace(stripThinkingTags(gateText))
	if normalizeIMMessagePlatformKind(platform).IsDesktop() && h.getWorkflowEngine() != nil {
		h.emitNeedsConfirmDocPreview(userID, docPreviewText, engineGateActive, steeringDetector)
	} else if normalizeIMMessagePlatformKind(platform).IsDesktop() {
		log.Printf("[agent-loop] NeedsConfirm gate: skipped doc preview emission (workflowEngine=%v)", h.getWorkflowEngine() != nil)
	}
	attachLLMTelemetry(finalResp)
	attachPendingVisibleArtifacts(finalResp)
	h.saveConversationHistoryTimed(userID, history, finalResp)
	result.Response = finalResp
	return result
}

func (h *IMMessageHandler) emitNeedsConfirmDocPreview(userID, docPreviewText string, engineGateActive bool, steeringDetector *SteeringWorkflowDetector) {
	adapter, ok := h.getWorkflowEngine().GetCallbacks().(*GUIWorkflowAdapter)
	if !ok {
		return
	}
	emitted := false
	if steeringDetector != nil {
		steeringDetector.interceptTextOutput(docPreviewText, func(phaseID, content string) {
			_ = adapter.EmitDocUpdate(userID, phaseID, content)
			log.Printf("[SteeringWorkflow] emitted doc_update from text output for user=%s phase=%s len=%d", userID, phaseID, len(content))
			emitted = true
		})
	}
	if emitted || !engineGateActive || len(docPreviewText) < 50 {
		return
	}
	if ws := h.getWorkflowEngine().GetActiveWorkflow(userID); ws != nil {
		_ = adapter.EmitDocUpdate(userID, ws.CurrentPhase, docPreviewText)
		adapter.EmitSuggestMaximize(userID, string(ws.Type))
		log.Printf("[WorkflowEngine] emitted doc_update for user=%s phase=%s type=%s len=%d", userID, ws.CurrentPhase, ws.Type, len(docPreviewText))
	} else {
		log.Printf("[WorkflowEngine] WARNING: engineGateActive=true but GetActiveWorkflow returned nil for user=%s", userID)
	}
}

func (h *IMMessageHandler) applyAgentLoopToolBranchNeedsConfirmGate(
	ctx *LoopContext,
	userID string,
	iteration int,
	platform string,
	gateConfig codingToolGateConfig,
	msgContent string,
	lengthContinuationText string,
	phase *agentLoopPhase,
	steeringDetector *SteeringWorkflowDetector,
	history []agent.ConversationEntry,
	voiceData string,
	voiceFileName string,
	voiceMimeType string,
	attachLLMTelemetry func(*IMAgentResponse),
	attachPendingVisibleArtifacts func(*IMAgentResponse),
) agentLoopToolBranchNeedsConfirmResult {
	result := agentLoopToolBranchNeedsConfirmResult{MsgContent: msgContent}
	needsConfirm := h.shouldNeedsConfirmToolBranch(ctx, userID, iteration, gateConfig)
	if !needsConfirm {
		return result
	}
	trimmedAfterTools := strings.TrimSpace(stripThinkingTags(msgContent))
	if containsSelfConfirmationPattern(trimmedAfterTools) {
		originalLen := len(trimmedAfterTools)
		trimmedAfterTools = truncateAtConfirmationBoundary(trimmedAfterTools)
		msgContent = trimmedAfterTools
		result.MsgContent = msgContent
		log.Printf("NeedsConfirm gate (tool branch): detected self-confirmation pattern, truncated at confirmation boundary (originalLen=%d truncatedLen=%d)", originalLen, len(trimmedAfterTools))
		if h.traceService != nil && ctx.RunID != "" {
			h.appendTraceEvent(ctx, "gate.self_confirm_truncated", "warn",
				fmt.Sprintf("Self-confirmation detected and truncated in tool branch (originalLen=%d truncatedLen=%d)", originalLen, len(trimmedAfterTools)),
				truncateTraceText(trimmedAfterTools, 220), "", "")
		}
	}
	if trimmedAfterTools == "" || looksLikeNoToolStallReply(msgContent) {
		return result
	}
	if !isSubstantivePhaseDocument(trimmedAfterTools) {
		log.Printf("[workflow-gate] NeedsConfirm (tool branch): skipping non-substantive preamble (len=%d), allowing loop to continue", len([]rune(trimmedAfterTools)))
		return result
	}

	log.Printf("[workflow-gate] NeedsConfirm (tool branch): force-returning after tool execution for user confirmation (iteration=%d len=%d)", iteration, len(trimmedAfterTools))
	if phase != nil {
		phase.Stage = agentStageFinalize
	}
	finalResp := &IMAgentResponse{Text: stripThinkingTags(lengthContinuationText + msgContent)}
	if normalizeIMMessagePlatformKind(platform).IsDesktop() && h.getWorkflowEngine() != nil {
		h.emitToolBranchNeedsConfirmDocPreview(userID, trimmedAfterTools, steeringDetector)
	}
	attachLLMTelemetry(finalResp)
	attachPendingVisibleArtifacts(finalResp)
	attachVoiceArtifact(finalResp, voiceData, voiceFileName, voiceMimeType)
	h.saveConversationHistoryTimed(userID, history, finalResp)
	result.Response = finalResp
	return result
}

func (h *IMMessageHandler) shouldNeedsConfirmToolBranch(ctx *LoopContext, userID string, iteration int, gateConfig codingToolGateConfig) bool {
	needsConfirm := false
	if gateConfig.active && iteration > 0 {
		if h.getWorkflowEngine() != nil && h.getWorkflowEngine().GetActiveWorkflow(userID) != nil {
			needsConfirm = h.getWorkflowEngine().IsPhaseNeedsConfirm(userID)
			if !needsConfirm {
				log.Printf("[workflow-gate] NeedsConfirm tool-branch bypassed: engine workflow active, phase NeedsConfirm=false (iter=%d user=%s)", iteration, userID)
			}
		} else {
			needsConfirm = true
		}
	}
	if !needsConfirm && iteration > 0 && h.getWorkflowEngine() != nil {
		semanticBypass := false
		if gateConfig.intent == intentCoding && !gateConfig.active {
			semanticBypass = true
		}
		if gateConfig.bugFix {
			semanticBypass = true
		}
		if !semanticBypass {
			needsConfirm = h.getWorkflowEngine().IsPhaseNeedsConfirm(userID)
		} else {
			log.Printf("[workflow-gate] NeedsConfirm tool-branch fallback bypassed: semantic intent=%v active=%v bugFix=%v reason=%q",
				gateConfig.intent, gateConfig.active, gateConfig.bugFix, gateConfig.reason)
		}
	}
	if needsConfirm && ctx.SkipNeedsConfirmGate && !gateConfig.active {
		log.Printf("[workflow-gate] NeedsConfirm tool-branch bypassed: pending confirm classified as 'other' (iter=%d user=%s)", iteration, userID)
		return false
	}
	return needsConfirm
}

func (h *IMMessageHandler) emitToolBranchNeedsConfirmDocPreview(userID, trimmedAfterTools string, steeringDetector *SteeringWorkflowDetector) {
	adapter, ok := h.getWorkflowEngine().GetCallbacks().(*GUIWorkflowAdapter)
	if !ok {
		return
	}
	emitted := false
	if steeringDetector != nil {
		steeringDetector.interceptTextOutput(trimmedAfterTools, func(phaseID, content string) {
			_ = adapter.EmitDocUpdate(userID, phaseID, content)
			log.Printf("[SteeringWorkflow] emitted doc_update from tool-branch gate for user=%s phase=%s len=%d", userID, phaseID, len(content))
			emitted = true
		})
	}
	if emitted || len(trimmedAfterTools) < 50 {
		return
	}
	if ws := h.getWorkflowEngine().GetActiveWorkflow(userID); ws != nil {
		_ = adapter.EmitDocUpdate(userID, ws.CurrentPhase, trimmedAfterTools)
		adapter.EmitSuggestMaximize(userID, string(ws.Type))
		log.Printf("[WorkflowEngine] emitted doc_update from tool-branch for user=%s phase=%s type=%s len=%d", userID, ws.CurrentPhase, ws.Type, len(trimmedAfterTools))
	} else {
		log.Printf("[WorkflowEngine] WARNING: NeedsConfirm tool-branch but GetActiveWorkflow returned nil for user=%s", userID)
	}
}

// getTaskOrchestrator returns the per-user task execution orchestrator.
// Creates one on demand if the registry exists but no orchestrator for
// this user yet. Returns nil if the registry is not initialized.
func (h *IMMessageHandler) getTaskOrchestrator(userID string) *TaskExecutionOrchestrator {
	if h.taskOrchestratorRegistry == nil {
		return nil
	}
	return h.taskOrchestratorRegistry.GetOrCreate(userID)
}

// getTaskOrchestratorReadOnly returns the per-user orchestrator if it exists,
// without creating one. Used for read-only checks (IsActive, ShouldUseSubAgent)
// to avoid polluting the registry with empty orchestrator entries.
func (h *IMMessageHandler) getTaskOrchestratorReadOnly(userID string) *TaskExecutionOrchestrator {
	if h.taskOrchestratorRegistry == nil {
		return nil
	}
	return h.taskOrchestratorRegistry.Get(userID)
}

// extractOriginalRequest returns the best available representation of the
// user's original task request from the workflow state. Returns "" if the
// current text already IS the original request (no substitution needed).
//
// Priority:
//  1. Goals[0]: structured callers store the raw user task here
//  2. Summary: only used when no explicit goal is available
//  3. "": text is already the original request
func extractOriginalRequest(state *workflow.WorkflowState, currentText string) string {
	if state == nil {
		return ""
	}
	if len(state.Intent.Goals) > 0 && state.Intent.Goals[0] != "" {
		candidate := state.Intent.Goals[0]
		if candidate != currentText {
			return candidate
		}
		return ""
	}
	if state.Intent.Summary != "" && state.Intent.Summary != currentText {
		return state.Intent.Summary
	}
	return ""
}

func (h *IMMessageHandler) confirmWorkflowStart(userID, text string, intent workflow.StructuredIntent, startReply string) *IMAgentResponse {
	if h == nil || h.confirmationStore == nil {
		return nil
	}
	item := buildPendingWorkflowConfirmation(userID, text, intent, startReply)
	h.confirmationStore.set(item)
	return buildWorkflowConfirmationResponse(item)
}

type workflowIMRouteResult struct {
	Response             *IMAgentResponse
	WorkflowAgentLoop    bool
	SkipNeedsConfirmGate bool
}

func (h *IMMessageHandler) routeWorkflowIMMessage(msg IMUserMessage, trimmed string, confirmedResume, hasPendingUserReply bool) workflowIMRouteResult {
	result := workflowIMRouteResult{WorkflowAgentLoop: confirmedResume}

	skipWorkflowForAttachment := false
	if !confirmedResume && h.getWorkflowEngine() != nil && !msg.IsBackground && !hasPendingUserReply {
		skipWorkflowForAttachment = workflowAttachmentBypass(msg.Attachments, trimmed)
		if !skipWorkflowForAttachment {
			if wfResp := h.handleWorkflowInterception(msg.UserID, trimmed); wfResp != nil {
				h.pendingAskUser.Delete(msg.UserID)
				result.Response = wfResp
				return result
			}
			if _, ok := h.workflowAgentLoopMarker.LoadAndDelete(msg.UserID); ok {
				result.WorkflowAgentLoop = true
			}
		}
	}

	_, result.SkipNeedsConfirmGate = h.workflowPendingConfirmOther.LoadAndDelete(msg.UserID)
	if skipWorkflowForAttachment || hasPendingUserReply {
		result.SkipNeedsConfirmGate = true
	}
	return result
}

func workflowAttachmentBypass(attachments []MessageAttachment, trimmed string) bool {
	hasImageAttachment := false
	for _, att := range attachments {
		attKind := normalizeIMMediaKind(att.Type)
		if attKind == imMediaImage || attKind == imMediaFile {
			hasImageAttachment = true
			break
		}
	}
	return hasImageAttachment && len([]rune(trimmed)) < 50
}

func buildPendingWorkflowConfirmation(userID, text string, intent workflow.StructuredIntent, startReply string) *pendingConfirmation {
	now := time.Now()
	goals := normalizeWorkflowConfirmationGoals(intent.Goals)
	originalText := workflowConfirmationTaskText(text, goals, intent.Summary)
	projectPath := corelib.EffectiveWorkspaceDir()
	targetPaths := make([]string, 0, 1)
	if projectPath != "" {
		targetPaths = append(targetPaths, projectPath)
	}
	summary := fmt.Sprintf("Matched workflow %s for: %s", intent.Category, originalText)
	if len(goals) == 0 {
		if intentSummary := strings.TrimSpace(intent.Summary); intentSummary != "" {
			summary += "\n\nSummary: " + intentSummary
		}
	}
	return &pendingConfirmation{
		ID:                  fmt.Sprintf("confirm-%d", now.UnixNano()),
		UserID:              strings.TrimSpace(userID),
		OriginalText:        originalText,
		ResumeText:          originalText,
		Summary:             summary,
		TaskType:            "workflow:" + string(intent.Category),
		TargetPaths:         targetPaths,
		PlannedActions:      []string{"Start the matched multi-phase workflow", "Generate and review workflow phase outputs", "Use direct execution for simple one-shot tasks"},
		RiskFlags:           []string{"Workflow mode may add planning/review phases that are unnecessary for simple tasks"},
		RevisionHints:       []string{"Choose direct execution for a simple task", "Reply with adjustments if the matched workflow type is wrong"},
		Status:              confirmationStatusPending,
		CreatedAt:           now,
		UpdatedAt:           now,
		LastProjectPath:     projectPath,
		WorkflowType:        string(intent.Category),
		WorkflowSummary:     strings.TrimSpace(intent.Summary),
		WorkflowGoals:       goals,
		WorkflowConstraints: append([]string(nil), intent.Constraints...),
		WorkflowConfidence:  intent.Confidence,
		WorkflowStartReply:  strings.TrimSpace(startReply),
	}
}

func normalizeWorkflowConfirmationGoals(goals []string) []string {
	normalized := make([]string, 0, len(goals))
	for _, goal := range goals {
		if trimmed := strings.TrimSpace(goal); trimmed != "" {
			normalized = append(normalized, trimmed)
		}
	}
	return normalized
}

func workflowConfirmationTaskText(text string, goals []string, summary string) string {
	if len(goals) > 0 {
		return goals[0]
	}
	if summary := strings.TrimSpace(summary); summary != "" {
		return summary
	}
	return strings.TrimSpace(text)
}

func buildWorkflowConfirmationResponse(item *pendingConfirmation) *IMAgentResponse {
	if item == nil {
		return &IMAgentResponse{Text: "Please confirm whether to start the workflow."}
	}
	return &IMAgentResponse{
		Text:         "This request matches workflow mode. Start the workflow for staged execution, or choose direct execution for a simple agent loop.",
		Confirmation: buildConfirmationPayload(item),
		Actions: []IMResponseAction{
			{Label: "Start workflow", Command: buildConfirmationActionCommand("confirm", item.ID), Style: "primary"},
			{Label: "Direct execution", Command: buildConfirmationActionCommand("cancel", item.ID), Style: "secondary"},
		},
	}
}

func (h *IMMessageHandler) approvePendingWorkflowConfirmation(userID string, pending *pendingConfirmation) pendingExecutionConfirmationResult {
	engine := h.getWorkflowEngine()
	if engine == nil || pending == nil {
		return pendingExecutionConfirmationResult{Handled: true, Response: &IMAgentResponse{Error: "Workflow engine is unavailable; please try again."}}
	}
	wfIntent := workflow.StructuredIntent{
		Category:    workflow.WorkflowType(strings.TrimSpace(pending.WorkflowType)),
		Summary:     strings.TrimSpace(firstNonEmptyTraceText(pending.WorkflowSummary, pending.Summary)),
		Goals:       normalizeWorkflowConfirmationGoals(pending.WorkflowGoals),
		Constraints: append([]string(nil), pending.WorkflowConstraints...),
		Confidence:  pending.WorkflowConfidence,
		Ready:       true,
	}
	if len(wfIntent.Goals) == 0 && strings.TrimSpace(pending.OriginalText) != "" {
		wfIntent.Goals = []string{strings.TrimSpace(pending.OriginalText)}
	}
	state, err := engine.StartWorkflow(userID, wfIntent)
	if err != nil {
		log.Printf("[WorkflowInterception] confirmed StartWorkflow error for user %s: %v", userID, err)
		return pendingExecutionConfirmationResult{Handled: true, Response: &IMAgentResponse{Error: fmt.Sprintf("failed to start workflow: %v", err)}}
	}
	resp := h.handlePostStartWorkflow(engine, userID, firstNonEmptyTraceText(pending.ResumeText, pending.OriginalText), state, pending.WorkflowStartReply)
	if resp != nil {
		return pendingExecutionConfirmationResult{Handled: true, Response: resp}
	}
	result := pendingExecutionConfirmationResult{ConfirmedResume: true}
	if _, ok := h.workflowAgentLoopMarker.LoadAndDelete(userID); ok {
		result.WorkflowAgentLoop = true
	}
	return result
}

func shouldRunWorkflowInterception(confirmedResume bool, skipWorkflowOnce bool, engine *workflow.WorkflowEngine, msg IMUserMessage, hasPendingUserReply bool) bool {
	return !confirmedResume && !skipWorkflowOnce && engine != nil && !msg.IsBackground && !hasPendingUserReply
}

// handlePostStartWorkflow is the single post-StartWorkflow handler for all
// GUI-side workflow start paths (UIC and IUM). It:
//  1. Emits suggest_maximize for the desktop panel
//  2. Builds the workflow overview text
//  3. For input-required workflows: returns the overview + upload prompt
//  4. For other workflows: sends overview via callback, then re-routes to
//     handleActiveWorkflow which triggers the first phase's agent loop
//
// extraText is appended to the overview (e.g. IUM's reply text). Pass "" if none.
func (h *IMMessageHandler) handlePostStartWorkflow(
	engine *workflow.WorkflowEngine,
	userID, text string,
	state *workflow.WorkflowState,
	extraText string,
) *IMAgentResponse {
	// Suggest maximizing the AI panel for workflow experience.
	if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
		adapter.EmitSuggestMaximize(userID, string(state.Type))
	}

	lang := h.getWorkflowLang()
	overview := i18n.Tf(i18n.MsgWorkflowStarted, lang, state.Type, state.CurrentPhase)
	if extraText != "" {
		overview += "\n\n" + extraText
	}

	// Input-required workflows must wait for user to provide documents.
	if req := engine.GetInputRequirement(userID); req != nil {
		overview += i18n.Tf(i18n.MsgWorkflowInputRequired, lang, req.Description)
		if len(req.FileTypes) > 0 {
			overview += i18n.Tf(i18n.MsgWorkflowInputFormats, lang, strings.Join(req.FileTypes, ", "))
		}
		if req.AcceptText {
			overview += i18n.T(i18n.MsgWorkflowInputPasteHint, lang)
		}
		return &IMAgentResponse{Text: overview}
	}

	// Non-input workflows: send overview, then re-route to handleActiveWorkflow
	// which calls HandleInput -> PhasePrompt + RunAgentLoop -> agent loop runs.
	if cb := engine.GetCallbacks(); cb != nil {
		_ = cb.SendTextToUser(userID, overview)
	}

	// Stash the original task request.
	//
	// When a workflow starts via multi-round IUM, `text` is the IUM
	// completion message, not the original task request. The original request is
	// preserved in state.Intent: either in Goals[0] (UIC direct path
	// stores the raw user text) or in Summary (IUM LLM generates a
	// structured summary of the user's intent).
	//
	// The agent loop's userText must carry task semantics so the LLM
	// knows what to produce. We stash the best available source here;
	// runAgentLoop consumes it via LoadAndDelete when workflowAgentLoop=true.
	if originalRequest := extractOriginalRequest(state, text); originalRequest != "" {
		h.workflowOriginalRequest.Store(userID, originalRequest)
		log.Printf("[WorkflowInterception] stashed original request for user=%s: %q (current text=%q)",
			userID, truncateRunes(originalRequest, 80), truncateRunes(text, 30))
	}

	log.Printf("[WorkflowInterception] StartWorkflow succeeded, re-routing to handleActiveWorkflow for user=%s type=%s phase=%s",
		userID, state.Type, state.CurrentPhase)
	return h.handleActiveWorkflow(engine, userID, text)
}

// handleWorkflowInterception checks if the message should be handled by the
// workflow engine (corelib/workflow). Returns an IMAgentResponse if the message
// was fully handled, or nil if it should proceed to the normal agent loop.
//
// Called from handleIMMessageWithLoop after slash commands and LLM config check,
// before the main agent loop logic.
func (h *IMMessageHandler) handleWorkflowInterception(userID, text string) *IMAgentResponse {
	engine := h.getWorkflowEngine()
	if engine == nil {
		return nil
	}

	// Let the unified intent classifier decide whether a workflow is allowed to
	// take over. The workflow filter is intentionally broad, so executable tasks
	// such as installs, deployments, server work, bug fixes, and maintenance can
	// otherwise be mistaken for a new multi-phase coding workflow just because
	// they mention a project or document. UIC owns the semantic distinction:
	// workflow_type + CreationOriented means multi-phase; confident non-workflow
	// labels mean the normal agent loop should execute directly.
	if h.shouldBypassWorkflowForIntent(userID, text) && !engine.IsAwaitingReview(userID) {
		if engine.GetActiveWorkflow(userID) != nil {
			h.stashedPhasePrompt.Delete(userID)
			h.workflowAgentLoopMarker.Delete(userID)
			log.Printf("[WorkflowInterception] bypassing active workflow by UIC intent: user=%s text=%q", userID, truncateRunes(text, 80))
		} else {
			log.Printf("[WorkflowInterception] bypassing workflow start by UIC intent: user=%s text=%q", userID, truncateRunes(text, 80))
		}
		return nil
	}

	filter := engine.GetFilter()
	if filter == nil {
		return nil
	}

	classification := filter.Classify(userID, text)

	switch classification {
	case workflow.FilterActiveWorkflow:
		return h.handleActiveWorkflow(engine, userID, text)

	case workflow.FilterActiveUnderstanding:
		return h.handleActiveUnderstanding(engine, userID, text)

	case workflow.FilterNeedsUnderstanding:
		return h.handleNeedsUnderstanding(engine, userID, text)

	case workflow.FilterSimpleDirective:
		// Pass through to normal agent loop -no workflow interception needed.
		return nil
	}

	return nil
}

func (h *IMMessageHandler) shouldBypassWorkflowForIntent(userID, text string) bool {
	if strings.TrimSpace(text) == "" {
		return false
	}
	uic := h.getUnifiedClassifier()
	if uic == nil {
		return false
	}

	result := uic.Classify(intent.MessageContext{
		Text:   text,
		UserID: userID,
	})
	threshold := uic.GetWorkflowRejectThreshold()

	if result.Primary == intent.LabelContinuation {
		history := h.recentConversationTexts(userID, 8)
		if len(history) > 0 {
			result = uic.Classify(intent.MessageContext{
				Text:          text,
				UserID:        userID,
				RecentHistory: history,
			})
		}
		bypass := h.recentContextResolvesToNonWorkflow(uic, userID, history, threshold)
		log.Printf("[WorkflowInterception] UIC continuation context: user=%s bypass=%v conf=%.2f", userID, bypass, result.Confidence)
		return bypass
	}

	bypass := shouldBypassWorkflowForClassification(result, uic.IsWorkflowCandidate(result.Primary), threshold)
	if bypass {
		log.Printf("[WorkflowInterception] UIC rejected workflow takeover: user=%s intent=%s conf=%.2f layer=%d workflow_type=%q creation=%v",
			userID, result.Primary, result.Confidence, result.Layer, result.WorkflowType, result.CreationOriented)
	}
	return bypass
}

func shouldBypassWorkflowForClassification(result intent.ClassificationResult, isWorkflowCandidate bool, rejectThreshold float64) bool {
	if isConcreteWorkflowType(result.WorkflowType) {
		return false
	}
	if rejectThreshold <= 0 {
		rejectThreshold = intent.DefaultWorkflowRejectThreshold
	}
	if result.Confidence < rejectThreshold {
		return false
	}

	switch result.Primary {
	case intent.LabelContinuation, intent.LabelWorkflowTask, intent.LabelAmbiguous, intent.LabelUnknown:
		return false
	case intent.LabelCoding:
		return !result.CreationOriented && !result.Degraded && (result.Layer == 3 || result.Layer == 23)
	case intent.LabelBugFix, intent.LabelMaintenance, intent.LabelSSH:
		return true
	default:
		return !isWorkflowCandidate
	}
}

func (h *IMMessageHandler) recentContextResolvesToNonWorkflow(uic *intent.UnifiedIntentClassifier, userID string, history []string, threshold float64) bool {
	if uic == nil || len(history) == 0 {
		return false
	}
	for i := len(history) - 1; i >= 0; i-- {
		entry := strings.TrimSpace(history[i])
		if entry == "" {
			continue
		}
		result := uic.Classify(intent.MessageContext{
			Text:          entry,
			UserID:        userID,
			RecentHistory: history[:i],
		})
		if result.Primary == intent.LabelContinuation || result.Primary == intent.LabelAmbiguous || result.Primary == intent.LabelUnknown {
			continue
		}
		return shouldBypassWorkflowForClassification(result, uic.IsWorkflowCandidate(result.Primary), threshold)
	}
	return false
}

func (h *IMMessageHandler) recentConversationTexts(userID string, maxEntries int) []string {
	if h == nil || h.memory == nil || maxEntries <= 0 {
		return nil
	}
	history := h.memory.Load(userID)
	if len(history) == 0 {
		return nil
	}
	start := len(history) - maxEntries
	if start < 0 {
		start = 0
	}
	texts := make([]string, 0, len(history)-start)
	for _, e := range history[start:] {
		if text := strings.TrimSpace(conversationEntryText(e.Content)); text != "" {
			texts = append(texts, text)
		}
	}
	return texts
}

func conversationEntryText(content any) string {
	switch v := content.(type) {
	case string:
		return v
	case []interface{}:
		var b strings.Builder
		for _, item := range v {
			if m, ok := item.(map[string]interface{}); ok {
				if s, ok := m["text"].(string); ok {
					b.WriteString(s)
					b.WriteByte('\n')
				}
			}
		}
		return b.String()
	default:
		return fmt.Sprint(v)
	}
}

// handleActiveWorkflow processes input for a user with an active workflow.
func (h *IMMessageHandler) handleActiveWorkflow(engine *workflow.WorkflowEngine, userID, text string) *IMAgentResponse {
	// Cross-type task detection via UIC.
	//
	// Before delegating to the engine, check if the message is a completely
	// different type of workflow task. The UIC (UnifiedIntentClassifier)
	// maps messages to workflow types via semantic embedding and LLM tree
	// tree reasoning, the same mechanism handleNeedsUnderstanding uses to
	// decide which workflow to start.
	//
	// This MUST run before HandleInput because HandleInput has multiple
	// branches (PendingConfirm, WaitingForInput, default) and cross-type
	// detection needs to work regardless of which branch would fire.
	//
	// When the UIC determines a workflow type that DIFFERS from the active
	// workflow with sufficient confidence, the user has moved on. Cancel
	// the current workflow and re-route through the full pipeline.
	if uic := h.getUnifiedClassifier(); uic != nil {
		ws := engine.GetActiveWorkflow(userID)
		if ws != nil {
			uicResult := uic.Classify(intent.MessageContext{
				Text:   text,
				UserID: userID,
			})
			if isConcreteWorkflowType(uicResult.WorkflowType) &&
				normalizeWorkflowType(uicResult.WorkflowType) != ws.Type &&
				uicResult.Confidence >= 0.70 {
				log.Printf("[WorkflowInterception] cross-type replacement: user=%s "+
					"active=%s uic_workflow=%s intent=%s conf=%.2f -"+
					"cancelling active workflow and re-routing",
					userID, ws.Type, uicResult.WorkflowType,
					uicResult.Primary, uicResult.Confidence)
				_ = engine.CancelWorkflow(userID)
				return h.handleWorkflowInterception(userID, text)
			}
		}
	}

	resp, err := engine.HandleInput(userID, text)
	if err != nil {
		log.Printf("[WorkflowInterception] HandleInput error for user %s: %v", userID, err)
		return &IMAgentResponse{Error: fmt.Sprintf("workflow handling failed: %v", err)}
	}
	if resp == nil {
		return nil
	}

	// --- Workflow review: lightweight LLM intent classification ---
	// The engine detected that the user is responding to a NeedsConfirm phase
	// that already has output. The GUI classifies the free-form reply into a
	// typed ReviewIntent, then the engine applies the state transition.
	if resp.PendingReview || resp.PendingConfirm {
		return h.handleWorkflowReview(engine, userID, text)
	}

	if !resp.RunAgentLoop {
		if resp.Complete {
			if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
				adapter.ResetSuggestMaximize(userID)
			}
		}
		return &IMAgentResponse{Text: resp.Text}
	}

	// When the engine signals an execution phase, attempt to activate the
	// task orchestrator. The engine provides the preceding phase's output
	// as TaskBreakdownText. If it parses as a task list, use orchestrator +
	// SubAgent. If not (e.g. PPT's slide_scripting output), fall through
	// to the normal agent loop which handles execution via tools directly.
	if resp.ActivateOrchestrator {
		taskOrch := h.getTaskOrchestrator(userID)
		if taskOrch != nil && !taskOrch.IsActive() && resp.TaskBreakdownText != "" {
			tasks := ParseTaskListFromText(resp.TaskBreakdownText)
			if len(tasks) > 0 {
				projectPath := h.traceProjectPath()
				if projectPath == "" {
					home, _ := os.UserHomeDir()
					projectPath = home
				}
				taskOrch.Activate(tasks, resp.RequirementsContext, resp.DesignContext, projectPath, "")
				log.Printf("[WorkflowInterception] orchestrator activated by engine: "+
					"%d tasks for user=%s project=%s", len(tasks), userID, projectPath)
			} else {
				log.Printf("[WorkflowInterception] execution phase entered but "+
					"preceding output is not a task list; using normal agent loop "+
					"for user=%s", userID)
			}
		}
	}

	// RunAgentLoop=true means the workflow engine wants the agent loop to
	// generate phase output.
	//
	// Phase prompt injection and doc capture marker are ALWAYS set when
	// the engine provides a PhasePrompt. The phase prompt is the engine's
	// instruction to the LLM ("you are in the audience_goal phase,
	// generate..."). Without it, the LLM has no idea what to produce.
	// The marker enables doc capture (SavePhaseOutput) so the generated
	// document is saved and the workflow can advance.
	//
	// DefaultInput=true means the user's message reached the engine's
	// default branch (no confirm/skip match). This happens both for
	// legitimate phase triggers and unrelated messages ("check
	// server status"). In both cases, the phase prompt guides the LLM
	// to produce the phase deliverable. If the LLM instead answers the
	// unrelated question, the NeedsConfirm gate will force-return the
	// output for user review; the user can then re-trigger the phase.
	//
	// Previously, DefaultInput=true suppressed both phase prompt injection
	// and doc capture, causing the workflow to stall completely; the LLM
	// received no phase instructions and produced no captured output.
	if resp.PhasePrompt != "" {
		h.stashedPhasePrompt.Store(userID, resp.PhasePrompt)
	}
	h.workflowAgentLoopMarker.Store(userID, true)
	if resp.Advance && resp.Text != "" {
		if cb := engine.GetCallbacks(); cb != nil {
			_ = cb.SendTextToUser(userID, resp.Text)
		}
	}
	return nil
}

// handleWorkflowReview uses a lightweight LLM call to classify the user's
// intent after viewing a phase document, then lets the workflow engine apply
// the typed review-state transition.
//
// Token budget: ~300-500 input + ~10 output vs ~55000 input for full agent loop.
// Latency: 1-3s (lightweight) vs 5-15s (full loop).
func (h *IMMessageHandler) handleWorkflowReview(engine *workflow.WorkflowEngine, userID, text string) *IMAgentResponse {
	ctx := context.Background()

	// Cross-type detection is handled by handleActiveWorkflow BEFORE
	// HandleInput is called. By the time we reach here, the message is
	// confirmed to be directed at the current workflow (same type or
	// non-workflow). We classify the remaining review-level intent.

	ws := engine.GetActiveWorkflow(userID)

	// Build compact context: phase name + first ~200 chars of the document +
	// the system's last prompt to the user + the last assistant message.
	// The last assistant message is critical; it often contains instructions
	// telling the user how to confirm, and the LLM needs that context to avoid
	// treating the reply as unrelated.
	phaseContext := ""
	if ws != nil {
		tmpl := engine.GetRegistry().Match(ws.Type)
		if tmpl != nil && ws.PhaseIndex < len(tmpl.Phases) {
			phase := &tmpl.Phases[ws.PhaseIndex]
			phaseContext = fmt.Sprintf("Current workflow phase: %s (%s)\n", phase.Name, phase.Description)

			// Add a snippet of the phase output (first ~200 runes).
			if output, ok := ws.PhaseOutputs[ws.CurrentPhase]; ok && len(output) > 0 {
				snippet := output
				runes := []rune(snippet)
				if len(runes) > 200 {
					snippet = string(runes[:200]) + "..."
				}
				phaseContext += fmt.Sprintf("Document snippet: %s\n", snippet)
			}

			phaseContext += "System prompt to user: review the document and confirm, or request changes.\n"

			// Inject the last assistant message from conversation history.
			// This provides the immediate conversational context, so the classifier
			// can treat a short confirmation reply as a response to that prompt.
			if lastAssistant := h.getLastAssistantSnippet(userID, 300); lastAssistant != "" {
				phaseContext += fmt.Sprintf("Last assistant message: %s\n", lastAssistant)
			}
		}
	}

	userMessage := text
	if phaseContext != "" {
		userMessage = fmt.Sprintf("[Context]\n%s\n\n[User reply]\n%s", phaseContext, text)
	}

	classifyResult, err := h.LLMClassify(ctx, LLMClassifyRequest{
		SystemPrompt: `You are a user intent classifier for a document review workflow.

The user was shown a document/plan and asked to confirm or request changes. You will receive:
- The workflow context: phase name, document snippet, the system prompt shown to the user
- The assistant's last message (if available): this is what the user is directly responding to
- The user's response

IMPORTANT: Pay close attention to the assistant's last message. If the assistant asked the user to say a specific word or phrase to proceed, and the user replies with exactly that word or phrase, it is a confirmation, not an unrelated message.

Classify the user's response into exactly one category. Reply with ONLY the category word, nothing else:
- "confirm": user approves and wants to proceed. This includes any form of agreement, acceptance, or readiness signal in the context of the ongoing review. A short or vague reply after being shown a document almost always means approval.
- "supplement": user provides specific feedback, corrections, additions, questions, or requests changes to the DOCUMENT CONTENT itself. Use this for both modifications and additional information.
- "skip": user wants to skip the current review phase while keeping the workflow active. The engine will decide whether this phase is skippable.
- "cancel": user wants to abandon, cancel, or discard the current workflow entirely. This includes:
  - Explicit cancellation such as "cancel" or "abort"
  - NOTE: Starting a completely different task type (e.g. coding task during a PPT workflow) is usually handled separately by cross-type detection.
- "switch_task": user is clearly asking to abandon the current workflow and start a different task, especially a different workflow type.
- "other": user is asking something clearly unrelated to the document or workflow. This includes:
  - Server/infrastructure operations such as login, restart, npm install, or deploy
  - Information queries: weather, search, off-topic questions
  - File operations such as opening files or taking screenshots
  - Any request that involves EXECUTING an action on a system/server/tool, rather than editing the document

CRITICAL: "update" can mean either "update the document" or "update software on a server". If the object of "update" is a software package, service, server component, or tool name (not a section/content of the document), classify as "other".

When in doubt between "confirm" and "other", prefer "confirm" - the conversational context is a document review, so the user's response is most likely directed at the document.`,
		UserMessage: userMessage,
		TimeoutSec:  10,
		Tag:         "workflow-confirm",
	})

	if err != nil {
		log.Printf("[workflow-review] LLM classify failed, keeping review barrier active: %v", err)
		return h.applyWorkflowReviewIntent(engine, userID, workflow.ReviewIntentOther, text)
	}

	reviewIntent := normalizeWorkflowReviewIntent(classifyResult.Text)
	log.Printf("[workflow-review] user=%s text=%q intent=%q raw=%q (input=%d output=%d latency=%.1fs)",
		userID, truncateForLogGUI(text, 30), reviewIntent, strings.TrimSpace(classifyResult.Text), classifyResult.InputTokens, classifyResult.OutputTokens, classifyResult.Latency.Seconds())

	return h.applyWorkflowReviewIntent(engine, userID, reviewIntent, text)
}

func normalizeWorkflowReviewIntent(raw string) workflow.ReviewIntent {
	return workflow.ParseReviewIntent(raw)
}

func (h *IMMessageHandler) applyWorkflowReviewIntent(engine *workflow.WorkflowEngine, userID string, intent workflow.ReviewIntent, feedback string) *IMAgentResponse {
	resp, err := engine.ApplyReviewIntent(userID, intent, feedback)
	if err != nil {
		log.Printf("[workflow-review] ApplyReviewIntent error: user=%s intent=%s err=%v", userID, intent, err)
		return h.reviewBarrierResponse(engine, userID)
	}
	if intent == workflow.ReviewIntentSwitchTask {
		return h.handleWorkflowInterception(userID, feedback)
	}
	return h.handleWorkflowEngineResponse(engine, userID, resp)
}

func (h *IMMessageHandler) handleWorkflowEngineResponse(engine *workflow.WorkflowEngine, userID string, resp *workflow.WorkflowResponse) *IMAgentResponse {
	if resp == nil {
		return nil
	}
	if !resp.RunAgentLoop {
		if resp.Complete {
			if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
				adapter.ResetSuggestMaximize(userID)
			}
		}
		return &IMAgentResponse{Text: resp.Text}
	}
	if resp.PhasePrompt != "" {
		h.stashedPhasePrompt.Store(userID, resp.PhasePrompt)
	}
	h.workflowAgentLoopMarker.Store(userID, true)
	if ws := engine.GetActiveWorkflow(userID); ws != nil {
		if orig := extractOriginalRequest(ws, ""); orig != "" {
			h.workflowOriginalRequest.Store(userID, orig)
		}
	}
	if resp.Text != "" {
		if cb := engine.GetCallbacks(); cb != nil {
			_ = cb.SendTextToUser(userID, resp.Text)
		}
	}
	return nil
}

func (h *IMMessageHandler) reviewBarrierResponse(engine *workflow.WorkflowEngine, userID string) *IMAgentResponse {
	ws := engine.GetActiveWorkflow(userID)
	if ws == nil {
		return nil
	}
	phaseName := ws.CurrentPhase
	if tmpl := engine.GetRegistry().Match(ws.Type); tmpl != nil && ws.PhaseIndex < len(tmpl.Phases) {
		phaseName = tmpl.Phases[ws.PhaseIndex].Name
	}
	return &IMAgentResponse{Text: fmt.Sprintf("Current workflow is waiting for confirmation/supplement at phase %q. Reply confirm to continue, provide changes to update this phase, or reply cancel to stop the workflow.", phaseName)}
}

// handleActiveUnderstanding processes input for a user with an active
// intent understanding session.
func (h *IMMessageHandler) handleActiveUnderstanding(engine *workflow.WorkflowEngine, userID, text string) *IMAgentResponse {
	understanding := engine.GetUnderstanding()
	if understanding == nil {
		return nil
	}

	reply, ready, cancelled, intent, err := understanding.HandleInput(userID, text)
	if err != nil {
		log.Printf("[WorkflowInterception] understanding HandleInput error for user %s: %v", userID, err)
		// Keep the active understanding session bound to the user. A transient
		// clarification error should not hand the follow-up to the normal agent
		// loop, where task-context may classify it against unrelated history.
		return &IMAgentResponse{Text: "I received your supplement, but the workflow understanding step failed temporarily. Please send the supplement again or confirm to continue the current task."}
	}
	if cancelled {
		return &IMAgentResponse{Text: "Cancelled. Anything else I can help with?"}
	}
	if ready && intent != nil {
		// Guard: if the LLM returned category="none" or empty with ready=true,
		// it means the task is NOT a workflow task (e.g., content processing).
		// Do NOT call StartWorkflow; fall through to the normal agent loop.
		// The understanding session has already been cleaned up by HandleInput
		// when isReady=true, so no additional cleanup is needed.
		if intent.Category == workflow.WorkflowNone || intent.Category == "" {
			log.Printf("[WorkflowInterception] understanding returned ready=true with category=%q for user %s, falling through to agent loop", intent.Category, userID)
			return nil
		}

		// Intent understanding is complete - start the workflow.
		if resp := h.confirmWorkflowStart(userID, text, *intent, reply); resp != nil {
			return resp
		}
		state, err := engine.StartWorkflow(userID, *intent)
		if err != nil {
			log.Printf("[WorkflowInterception] StartWorkflow error for user %s: %v", userID, err)
			return &IMAgentResponse{Error: fmt.Sprintf("failed to start workflow: %v", err)}
		}
		return h.handlePostStartWorkflow(engine, userID, text, state, reply)
	}
	return &IMAgentResponse{Text: reply}
}

// handleNeedsUnderstanding starts a new intent understanding session for a
// message that needs LLM classification. The LLM will decide:
//   - Is this a workflow task? (if not, returns nil 閳?normal agent loop)
//   - Which workflow template?
//   - Structured intent extraction
func (h *IMMessageHandler) handleNeedsUnderstanding(engine *workflow.WorkflowEngine, userID, text string) *IMAgentResponse {
	understanding := engine.GetUnderstanding()
	if understanding == nil {
		// No understanding manager; fall through to normal agent loop.
		return nil
	}

	// Unified classification: UIC fusion produces both IntentLabel and WorkflowType.
	//
	// DESIGN PRINCIPLE: UIC has "fast reject" power but NOT "fast accept" power.
	//
	// UIC is a single-round LLM call with limited context (no conversation
	// history, no knowledge of maclaw's own features). Its classification can
	// be wrong — e.g., "帮我测试 ag ui功能，生成一个用户信息输入界面" gets
	// classified as coding (conf=0.87) because "生成"+"界面" looks like a
	// development task, but the user actually wants to test maclaw's GUI
	// automation feature.
	//
	// IUM (IntentUnderstandingManager) has richer context (system prompt with
	// maclaw feature descriptions, workflow template descriptions) and can make
	// more accurate judgments. It previously correctly rejected this same intent
	// three times.
	//
	// Therefore:
	//   - UIC can REJECT (fast path): confident non-workflow intent → skip IUM
	//   - UIC can HINT (pass-through): WorkflowType as hint to IUM for faster processing
	//   - UIC CANNOT ACCEPT (no fast path): never directly start a workflow
	//
	// The "accept" power belongs to IUM (deep semantic confirmation) or the
	// user (via confirmation panel after IUM confirms).
	if uic := h.getUnifiedClassifier(); uic != nil {
		uicResult := uic.Classify(intent.MessageContext{
			Text:   text,
			UserID: userID,
		})

		// UIC says no workflow - check if it's a confident non-workflow signal.
		//
		// Rejection policy based on MayTriggerWorkflow:
		//   - MayTriggerWorkflow=false intents (document_delivery, search, non_coding, etc.):
		//     A semantic result with confidence >= threshold is sufficient.
		//     These intents can NEVER trigger a workflow by definition.
		//   - MayTriggerWorkflow=true intents (coding, office, workflow_task) or Ambiguous/Unknown:
		//     IsWorkflowCandidate returns true → canReject is false → falls through to IUM.
		//     This prevents L1 misclassification from blocking a legitimate workflow task.
		if uicResult.WorkflowType == "" {
			isNonWorkflowIntent := !uic.IsWorkflowCandidate(uicResult.Primary)
			threshold := uic.GetWorkflowRejectThreshold()

			if isNonWorkflowIntent && uicResult.Confidence >= threshold {
				log.Printf("[WorkflowInterception] UIC rejected workflow for user %s: "+
					"intent=%s conf=%.2f layer=%d threshold=%.2f - text=%q",
					userID, uicResult.Primary, uicResult.Confidence, uicResult.Layer, threshold,
					truncateRunes(text, 80))
				return nil
			}
		}

		// Log UIC's recommendation (hint) for diagnostics. The hint is NOT
		// used to directly start a workflow — it falls through to IUM below.
		if isConcreteWorkflowType(uicResult.WorkflowType) {
			log.Printf("[WorkflowInterception] UIC recommends workflow_type=%s for user %s "+
				"(intent=%s conf=%.2f layer=%d) — delegating to IUM for confirmation. text=%q",
				uicResult.WorkflowType, userID, uicResult.Primary, uicResult.Confidence,
				uicResult.Layer, truncateRunes(text, 80))
		} else {
			// UIC not confident enough or ambiguous.
			log.Printf("[WorkflowInterception] UIC fusion: intent=%s conf=%.2f layer=%d wf=%s — "+
				"not decisive, proceeding to IUM",
				uicResult.Primary, uicResult.Confidence, uicResult.Layer, uicResult.WorkflowType)
		}
	}

	result, err := understanding.Start(userID, text)
	if err != nil {
		log.Printf("[WorkflowInterception] understanding Start error for user %s: %v", userID, err)
		return nil
	}

	// LLM determined this is NOT a workflow task - trust the LLM's judgment
	// and fall through to the normal agent loop. No session was created.
	if result.Rejected {
		log.Printf("[WorkflowInterception] understanding rejected task for user %s: %q - trusting LLM, no keyword override", userID, truncateRunes(text, 80))
		return nil
	}

	// First-round ready: IUM is confident enough to start the workflow
	// immediately without multi-round clarification. Proceed to confirmation
	// panel (same UX as the old UIC fast-accept path, but with IUM's deeper
	// semantic validation as the gatekeeper instead of UIC's single-round guess).
	if result.Ready && result.Intent != nil {
		// Guard: category="none" or empty with ready=true means not a workflow.
		if result.Intent.Category == workflow.WorkflowNone || result.Intent.Category == "" {
			log.Printf("[WorkflowInterception] understanding returned ready=true with category=%q for user %s, falling through to agent loop",
				result.Intent.Category, userID)
			return nil
		}

		log.Printf("[WorkflowInterception] IUM first-round ready for user %s: category=%s conf=%.2f text=%q",
			userID, result.Intent.Category, result.Intent.Confidence, truncateRunes(text, 80))

		if resp := h.confirmWorkflowStart(userID, text, *result.Intent, result.Reply); resp != nil {
			return resp
		}
		state, err := engine.StartWorkflow(userID, *result.Intent)
		if err != nil {
			log.Printf("[WorkflowInterception] IUM-driven StartWorkflow error for user %s: %v", userID, err)
			return &IMAgentResponse{Error: fmt.Sprintf("failed to start workflow: %v", err)}
		}
		return h.handlePostStartWorkflow(engine, userID, text, state, result.Reply)
	}

	// LLM says it IS a workflow task but needs clarification - an understanding
	// session has been created. The user will go through multi-round clarification
	// before the workflow actually starts.
	return &IMAgentResponse{Text: result.Reply}
}

// getUnifiedClassifier returns the UIC instance if available, or nil.
// Checks the direct field first (set at construction or by TUI), then
// falls back to h.app for GUI late-init compatibility.
func (h *IMMessageHandler) getUnifiedClassifier() *intent.UnifiedIntentClassifier {
	if h == nil {
		return nil
	}
	if h.unifiedClassifier != nil {
		return h.unifiedClassifier
	}
	if h.app == nil {
		return nil
	}
	return h.app.unifiedClassifier
}

// cancelWorkflowForUser cancels any active workflow and understanding session
// for the given user. Called from /new, /reset, /clear, and /cancel handlers.
func (h *IMMessageHandler) cancelWorkflowForUser(userID string) {
	engine := h.getWorkflowEngine()
	if engine == nil {
		return
	}
	// Cancel active workflow (ignore error if none active).
	_ = engine.CancelWorkflow(userID)
	// Cancel active understanding session without invoking the LLM.
	if understanding := engine.GetUnderstanding(); understanding != nil {
		if understanding.HasActiveSession(userID) {
			understanding.CancelSession(userID)
		}
	}
	// Reset the suggest_maximize dedup flag so the next workflow can
	// trigger the fullscreen banner again.
	if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
		adapter.ResetSuggestMaximize(userID)
	}
	// Clear any pending ask_user state.
	h.pendingAskUser.Delete(userID)
}

// applyWorkflowToolFilter restricts the tool list based on the current
// workflow phase's ToolFilterPolicy.
func (h *IMMessageHandler) applyWorkflowToolFilter(userID string, tools []map[string]interface{}) []map[string]interface{} {
	engine := h.getWorkflowEngine()
	if engine == nil {
		return tools
	}
	policy := engine.GetPhaseToolFilter(userID)
	return workflow.FilterToolDefinitions(policy, tools)
}

// getLastAssistantSnippet returns the tail of the last assistant message from
// conversation history, truncated to maxRunes from the END. We take the tail
// because assistant messages are often long documents followed by a short
// confirmation prompt at the end. The tail
// captures this prompt, which is the most relevant context for classifying
// the user's response.
func (h *IMMessageHandler) getLastAssistantSnippet(userID string, maxRunes int) string {
	if h.memory == nil {
		return ""
	}
	entries := h.memory.Load(userID)
	// Walk backwards to find the last assistant message.
	for i := len(entries) - 1; i >= 0; i-- {
		if entries[i].Role != "assistant" {
			continue
		}
		content, ok := entries[i].Content.(string)
		if !ok || content == "" {
			continue
		}
		runes := []rune(content)
		if len(runes) > maxRunes {
			// Take the tail - the confirmation prompt is at the end.
			return "..." + string(runes[len(runes)-maxRunes:])
		}
		return content
	}
	return ""
}
