package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/RapidAI/CodeClaw/corelib"
	"github.com/RapidAI/CodeClaw/corelib/agent"
	"github.com/RapidAI/CodeClaw/corelib/experience/lifecycle"
	"github.com/RapidAI/CodeClaw/corelib/i18n"
	"github.com/RapidAI/CodeClaw/corelib/intent"
	v2 "github.com/RapidAI/CodeClaw/corelib/workflow/v2"
)

type agentLoopNeedsConfirmGateResult struct {
	Response                 *IMAgentResponse
	MsgContent               string
	PostStreamReturnPrepTime bool
}

type agentLoopToolBranchNeedsConfirmResult struct {
	Response   *IMAgentResponse
	MsgContent string
}

// getWorkflowLang returns the user-facing language for workflow messages.
// Delegates to the same source as the engine's callbacks.GetLang(): the
// app's CurrentLanguage field, ensuring all workflow messages use the same
// language regardless of whether they're generated by the engine or the handler.
func (h *IMMessageHandler) getWorkflowLang() string {
	if h.app != nil {
		return h.app.CurrentLanguage
	}
	return ""
}

func (h *IMMessageHandler) agentLoopUserTextForWorkflow(msg IMUserMessage, workflowAgentLoop bool) string {
	// Check if user cancelled a workflow but wants direct execution.
	// In this case, replace the cancel message (e.g. "取消，直接处理") with
	// the original task request that started the workflow.
	if orig, ok := h.pendingCancelExecuteRequest.LoadAndDelete(msg.UserID); ok {
		originalText, _ := orig.(string)
		if strings.TrimSpace(originalText) != "" {
			log.Printf("[WorkflowInterception] cancel_execute: replacing %q with original request %q",
				truncateRunes(msg.Text, 30), truncateRunes(originalText, 80))
			return originalText
		}
	}

	if !workflowAgentLoop {
		return msg.Text
	}
	if orig, ok := h.workflowOriginalRequest.LoadAndDelete(msg.UserID); ok {
		agentLoopUserText, _ := orig.(string)
		log.Printf("[WorkflowInterception] using original request as userText for agent loop: %q (msg.Text was %q)",
			truncateRunes(agentLoopUserText, 80), truncateRunes(msg.Text, 30))
		if strings.TrimSpace(agentLoopUserText) != "" {
			return agentLoopUserText
		}
	}
	return msg.Text
}

func (h *IMMessageHandler) applyAgentLoopNeedsConfirmGate(
	ctx *LoopContext,
	userID string,
	iteration int,
	platform string,
	msgContent string,
	lengthContinuationText string,
	phase *agentLoopPhase,
	history []agent.ConversationEntry,
	streamDone bool,
	attachLLMTelemetry func(*IMAgentResponse),
	attachPendingVisibleArtifacts func(*IMAgentResponse),
) agentLoopNeedsConfirmGateResult {
	// V2 workflow: NeedsConfirm gate is no longer used mid-loop.
	// Each doc phase runs as a complete independent agent loop. Output capture
	// happens AFTER the loop returns (via recordWorkflowV2Output in im_message_handler.go).
	return agentLoopNeedsConfirmGateResult{MsgContent: msgContent}
}

func (h *IMMessageHandler) applyAgentLoopToolBranchNeedsConfirmGate(
	ctx *LoopContext,
	userID string,
	iteration int,
	platform string,
	msgContent string,
	lengthContinuationText string,
	phase *agentLoopPhase,
	history []agent.ConversationEntry,
	voiceData string,
	voiceFileName string,
	voiceMimeType string,
	attachLLMTelemetry func(*IMAgentResponse),
	attachPendingVisibleArtifacts func(*IMAgentResponse),
) agentLoopToolBranchNeedsConfirmResult {
	// V2 workflow: tool-branch NeedsConfirm gate is no longer used.
	// V2 runs each phase as a complete agent loop; output capture happens after.
	return agentLoopToolBranchNeedsConfirmResult{MsgContent: msgContent}
}

func (h *IMMessageHandler) shouldNeedsConfirmToolBranch(ctx *LoopContext, userID string, iteration int) bool {
	// V2 workflow: NeedsConfirm tool-branch is not used. Always returns false.
	return false
}

// getTaskOrchestrator returns the per-user task execution orchestrator.
// Creates one on demand if the registry exists but no orchestrator for
// this user yet. Returns nil if the registry is not initialized.
func (h *IMMessageHandler) getTaskOrchestrator(userID string) *TaskExecutionOrchestrator {
	if h.taskOrchestratorRegistry == nil {
		return nil
	}
	return h.taskOrchestratorRegistry.GetOrCreate(userID)
}

// getTaskOrchestratorReadOnly returns the per-user orchestrator if it exists,
// without creating one. Used for read-only checks (IsActive, ShouldUseSubAgent)
// to avoid polluting the registry with empty orchestrator entries.
func (h *IMMessageHandler) getTaskOrchestratorReadOnly(userID string) *TaskExecutionOrchestrator {
	if h.taskOrchestratorRegistry == nil {
		return nil
	}
	return h.taskOrchestratorRegistry.Get(userID)
}

// extractOriginalRequest returns the best available representation of the
// user's original task request from the workflow state. Returns "" if the
// current text already IS the original request (no substitution needed).
//
// Priority:
//  1. Goals[0]: structured callers store the raw user task here
//  2. Summary: only used when no explicit goal is available
//  3. "": text is already the original request
func extractOriginalRequest(state *v2.EngineState, currentText string) string {
	if state == nil {
		return ""
	}
	if len(state.Intent.Goals) > 0 && state.Intent.Goals[0] != "" {
		candidate := state.Intent.Goals[0]
		if candidate != currentText {
			return candidate
		}
		return ""
	}
	if state.Intent.Summary != "" && state.Intent.Summary != currentText {
		return state.Intent.Summary
	}
	return ""
}

func (h *IMMessageHandler) workflowStartProjectPath() string {
	return h.workflowStartProjectPathForOwner("")
}

func (h *IMMessageHandler) workflowStartProjectPathForOwner(ownerID string) string {
	if projectPath := projectPathFromSessionOwnerID(ownerID); projectPath != "" {
		return projectPath
	}
	if h != nil && h.app != nil {
		if projectPath := strings.TrimSpace(h.app.GetCurrentProjectPath()); projectPath != "" {
			return projectPath
		}
	}
	if projectPath := h.traceProjectPath(); projectPath != "" {
		return projectPath
	}
	return strings.TrimSpace(corelib.EffectiveWorkspaceDir())
}

func (h *IMMessageHandler) workflowStartProjectPathForIntent(ownerID, text string, intent v2.StructuredIntent) string {
	if intent.Category == v2.WorkflowCoding {
		candidates := []string{text, intent.Summary}
		candidates = append(candidates, intent.Goals...)
		candidates = append(candidates, intent.Constraints...)
		for _, candidate := range candidates {
			if projectPath := extractCodingDelegateProjectPath(candidate); projectPath != "" {
				return projectPath
			}
		}
	}
	return h.workflowStartProjectPathForOwner(ownerID)
}

func (h *IMMessageHandler) resolveWorkflowStartProjectPath() (string, error) {
	projectPath := strings.TrimSpace(h.workflowStartProjectPath())
	return h.resolveWorkflowProjectPath(projectPath)
}

func (h *IMMessageHandler) resolveWorkflowProjectPath(projectPath string) (string, error) {
	normalized, _, err := normalizeWorkflowProjectPath(projectPath)
	return normalized, err
}

func (h *IMMessageHandler) confirmWorkflowStart(userID, text string, intent v2.StructuredIntent, startReply string) *IMAgentResponse {
	if h == nil || h.confirmationStore == nil {
		return nil
	}
	lang := h.getWorkflowLang()
	item := buildPendingWorkflowConfirmation(userID, text, intent, startReply, lang, h.workflowStartProjectPathForIntent(userID, text, intent))
	h.confirmationStore.set(item)
	return buildWorkflowConfirmationResponse(item, lang)
}

type workflowIMRouteResult struct {
	Response             *IMAgentResponse
	WorkflowAgentLoop    bool
	WorkflowDocPhase     bool // true for doc phases (requirements/design/tasks), false for execution phases
	WorkflowPhaseID      string
	SkipNeedsConfirmGate bool
	ReplayText           string // When non-empty, replace the current msg.Text with this for agent loop processing
}

func (h *IMMessageHandler) routeWorkflowIMMessage(msg IMUserMessage, trimmed string, confirmedResume, hasPendingUserReply bool) workflowIMRouteResult {
	result := workflowIMRouteResult{WorkflowAgentLoop: confirmedResume}
	_, result.SkipNeedsConfirmGate = h.workflowPendingConfirmOther.LoadAndDelete(msg.UserID)
	wf := h.getWorkflowV2()
	if wf == nil || wf.machine == nil || msg.IsBackground || hasPendingUserReply {
		return result
	}
	engine := h.app.workflowEngine
	// Check StateMachine first; fall back to WorkflowEngine adapter.
	hasActiveWorkflow := wf.machine.GetActive(msg.UserID) != nil
	if !hasActiveWorkflow && engine != nil {
		hasActiveWorkflow = engine.GetActiveWorkflow(msg.UserID) != nil
	}
	if hasActiveWorkflow {
		if resp, handled := h.submitWorkflowInputIfWaiting(engine, msg.UserID, trimmed, msg.Attachments, msg.Platform); handled {
			result.Response = resp
			result.WorkflowAgentLoop = resp == nil
			if state := wf.machine.GetActive(msg.UserID); state != nil {
				if phase := state.ActivePhase(); phase != nil {
					result.WorkflowPhaseID = phase.ID
					result.WorkflowDocPhase = phase.ToolPolicy != v2.ToolPolicyFull
				}
			}
			return result
		}
	}
	return result
}

func workflowInterceptionAttachments(items [][]MessageAttachment) []MessageAttachment {
	if len(items) == 0 {
		return nil
	}
	return items[0]
}

func workflowAttachmentBypass(engine *v2.WorkflowEngine, userID string, attachments []MessageAttachment, trimmed string) bool {
	if engine != nil {
		if ws := engine.GetActiveWorkflow(userID); ws != nil {
			if tmpl := engine.GetRegistry().Match(ws.Type); ws.IsWaitingForInput(tmpl) {
				return false
			}
		}
	}
	hasImageAttachment := false
	for _, att := range attachments {
		attKind := normalizeIMMediaKind(att.Type)
		if attKind == imMediaImage || attKind == imMediaFile {
			hasImageAttachment = true
			break
		}
	}
	return hasImageAttachment && len([]rune(trimmed)) < 50
}

func workflowHasPendingPhaseForm(engine *v2.WorkflowEngine, userID string) bool {
	if engine == nil {
		return false
	}
	ws := engine.GetActiveWorkflow(userID)
	if ws == nil {
		return false
	}
	tmpl := engine.GetRegistry().Match(ws.Type)
	if tmpl == nil || ws.PhaseIndex < 0 || ws.PhaseIndex >= len(tmpl.Phases) {
		return false
	}
	phase := tmpl.Phases[ws.PhaseIndex]
	if phase.ID != ws.CurrentPhase || phase.InputSchema == nil {
		return false
	}
	return !ws.PhaseFormSubmitted && !ws.PhaseFormSkipped && len(ws.PhaseFormData) == 0
}

func isWorkflowFormDirectRunCommand(text string) bool {
	trimmed := strings.ToLower(strings.TrimSpace(text))
	trimmed = strings.Trim(trimmed, " .\u3002!\uff01")
	switch trimmed {
	case "\u76f4\u63a5\u5199", "\u76f4\u63a5\u6267\u884c", "\u76f4\u63a5\u505a", "\u76f4\u63a5\u5f00\u59cb", "\u76f4\u63a5\u751f\u6210", "\u5f00\u5de5", "\u5f00\u59cb", "\u542f\u52a8", "\u7ee7\u7eed", "\u8df3\u8fc7", "\u8df3\u8fc7\u8868\u5355", "\u4e0d\u7528\u586b", "\u4e0d\u586b\u4e86", "go", "go ahead", "start", "continue", "skip", "skip form":
		return true
	}
	return strings.Contains(trimmed, "\u4e0d\u7528\u586b") || strings.Contains(trimmed, "\u8df3\u8fc7\u8868\u5355") || strings.Contains(trimmed, "\u76f4\u63a5") && (strings.Contains(trimmed, "\u505a") || strings.Contains(trimmed, "\u5199") || strings.Contains(trimmed, "\u6267\u884c") || strings.Contains(trimmed, "\u751f\u6210"))
}

func isWorkflowCancelText(text string) bool {
	trimmed := strings.ToLower(strings.TrimSpace(text))
	trimmed = strings.Trim(trimmed, " .\u3002!\uff01")
	switch trimmed {
	case "/cancel", "cancel", "abort", "stop", "quit", "\u53d6\u6d88", "\u505c\u6b62", "\u653e\u5f03", "\u9000\u51fa":
		return true
	}
	return false
}

func buildPendingWorkflowConfirmation(userID, text string, intent v2.StructuredIntent, startReply string, lang string, projectPaths ...string) *pendingConfirmation {
	now := time.Now()
	goals := normalizeWorkflowConfirmationGoals(intent.Goals)
	originalText := workflowConfirmationTaskText(text, goals, intent.Summary)
	projectPath := ""
	if len(projectPaths) > 0 {
		projectPath = strings.TrimSpace(projectPaths[0])
	}
	targetPaths := make([]string, 0, 1)
	if projectPath != "" {
		targetPaths = append(targetPaths, projectPath)
	}
	summary := i18n.Tf(i18n.MsgWorkflowConfirmSummary, lang, intent.Category, originalText)
	if len(goals) == 0 {
		if intentSummary := strings.TrimSpace(intent.Summary); intentSummary != "" {
			summary += "\n\n" + intentSummary
		}
	}
	return &pendingConfirmation{
		ID:                  fmt.Sprintf("confirm-%d", now.UnixNano()),
		UserID:              strings.TrimSpace(userID),
		OriginalText:        originalText,
		ResumeText:          originalText,
		Summary:             summary,
		TaskType:            "workflow:" + string(intent.Category),
		TargetPaths:         targetPaths,
		PlannedActions:      []string{i18n.T(i18n.MsgWorkflowConfirmAction1, lang), i18n.T(i18n.MsgWorkflowConfirmAction2, lang), i18n.T(i18n.MsgWorkflowConfirmAction3, lang)},
		RiskFlags:           []string{i18n.T(i18n.MsgWorkflowConfirmRisk1, lang)},
		RevisionHints:       []string{i18n.T(i18n.MsgWorkflowConfirmRevision1, lang), i18n.T(i18n.MsgWorkflowConfirmRevision2, lang)},
		Status:              confirmationStatusPending,
		CreatedAt:           now,
		UpdatedAt:           now,
		LastProjectPath:     projectPath,
		WorkflowType:        string(intent.Category),
		WorkflowSummary:     strings.TrimSpace(intent.Summary),
		WorkflowGoals:       goals,
		WorkflowConstraints: append([]string(nil), intent.Constraints...),
		WorkflowConfidence:  intent.Confidence,
		WorkflowStartReply:  strings.TrimSpace(startReply),
	}
}

func normalizeWorkflowConfirmationGoals(goals []string) []string {
	normalized := make([]string, 0, len(goals))
	for _, goal := range goals {
		if trimmed := strings.TrimSpace(goal); trimmed != "" {
			normalized = append(normalized, trimmed)
		}
	}
	return normalized
}

func workflowConfirmationTaskText(text string, goals []string, summary string) string {
	if len(goals) > 0 {
		return goals[0]
	}
	if summary := strings.TrimSpace(summary); summary != "" {
		return summary
	}
	return strings.TrimSpace(text)
}

func firstNonEmptyWorkflowString(values ...string) string {
	for _, value := range values {
		if trimmed := strings.TrimSpace(value); trimmed != "" {
			return trimmed
		}
	}
	return ""
}

func buildWorkflowConfirmationResponse(item *pendingConfirmation, lang string) *IMAgentResponse {
	if item == nil {
		return &IMAgentResponse{Text: i18n.T(i18n.MsgWorkflowConfirmNilText, lang)}
	}
	return &IMAgentResponse{
		Text:         i18n.T(i18n.MsgWorkflowConfirmText, lang),
		Confirmation: buildConfirmationPayload(item, lang),
		Actions: []IMResponseAction{
			{Label: i18n.T(i18n.MsgWorkflowConfirmBtnStart, lang), Command: buildConfirmationActionCommand("confirm", item.ID), Style: "primary"},
			{Label: i18n.T(i18n.MsgWorkflowConfirmBtnDirect, lang), Command: buildConfirmationActionCommand("cancel", item.ID), Style: "secondary"},
		},
	}
}

func (h *IMMessageHandler) approvePendingWorkflowConfirmation(userID string, pending *pendingConfirmation, platform string) pendingExecutionConfirmationResult {
	lang := h.getWorkflowLang()
	wf := h.getWorkflowV2()
	if wf == nil || wf.machine == nil || pending == nil {
		return pendingExecutionConfirmationResult{Handled: true, Response: &IMAgentResponse{Error: i18n.T(i18n.MsgWorkflowUnavailable, lang)}}
	}
	intent := v2.StructuredIntent{
		Category:    v2.WorkflowType(strings.TrimSpace(pending.WorkflowType)),
		Summary:     firstNonEmptyWorkflowString(pending.WorkflowSummary, pending.Summary, pending.OriginalText),
		Goals:       normalizeWorkflowConfirmationGoals(pending.WorkflowGoals),
		Constraints: append([]string(nil), pending.WorkflowConstraints...),
		Confidence:  pending.WorkflowConfidence,
		Ready:       true,
	}
	if intent.Category == "" || intent.Category == v2.WorkflowNone {
		return pendingExecutionConfirmationResult{Handled: true, Response: &IMAgentResponse{Error: i18n.T(i18n.MsgWorkflowUnavailable, lang)}}
	}
	text := workflowConfirmationTaskText(pending.OriginalText, intent.Goals, intent.Summary)
	projectPath := strings.TrimSpace(pending.LastProjectPath)
	if projectPath == "" && len(pending.TargetPaths) > 0 {
		projectPath = strings.TrimSpace(pending.TargetPaths[0])
	}
	if projectPath == "" {
		projectPath = h.workflowStartProjectPathForIntent(userID, text, intent)
	}
	projectPath, prepErr := h.resolveWorkflowProjectPath(projectPath)
	if prepErr != nil {
		return pendingExecutionConfirmationResult{Handled: true, Response: &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowPrepareProjectError, lang, prepErr)}}
	}
	// Create workflow via V2 StateMachine directly
	summary := intent.Summary
	if summary == "" && len(intent.Goals) > 0 {
		summary = intent.Goals[0]
	}
	v2State, err := wf.machine.Create(userID, string(intent.Category), projectPath, summary)
	if err != nil {
		return pendingExecutionConfirmationResult{Handled: true, Response: &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowStartError, lang, err)}}
	}
	state := mapV2StateToV1(v2State)
	// Store in WorkflowEngine adapter so HandleInput/GetActiveWorkflow can find it.
	if engine := h.app.workflowEngine; engine != nil {
		engine.StoreActiveState(userID, state)
	}
	return pendingExecutionConfirmationResult{
		Handled:  true,
		Response: h.handlePostStartWorkflow(h.app.workflowEngine, userID, text, state, pending.WorkflowStartReply, platform),
	}
}

// handlePostStartWorkflow is the single post-StartWorkflow handler for all
// GUI-side workflow start paths (UIC and IUM). It:
//  1. Emits suggest_maximize for the desktop panel
//  2. Builds the workflow overview text
//  3. For input-required workflows: returns the overview + upload prompt
//  4. For other workflows: sends overview via callback, then re-routes to
//     handleActiveWorkflow which triggers the first phase's agent loop
//
// extraText is appended to the overview (e.g. IUM's reply text). Pass "" if none.
func (h *IMMessageHandler) handlePostStartWorkflow(
	engine *v2.WorkflowEngine,
	userID, text string,
	state *v2.EngineState,
	extraText string,
	platform string,
) *IMAgentResponse {
	// Clean up stale state from previous workflow sessions.
	//
	// When a new workflow starts, the previous workflow's persisted documents
	// remain on disk ({projectPath}/.maclaw/workflow/*.md). If the LLM's
	// conversation history still contains the old workflow's context, it may
	// reproduce old content which then gets captured as the new workflow's
	// phase output. Clean the persisted docs directory to prevent stale
	// content from leaking into the new workflow.
	//
	// Conversation history is only cleared when it contains substantial
	// content from a previous workflow session (>= 6 entries indicates
	// multi-turn workflow dialogue). Short histories (e.g. user just said
	// Short confirmation histories are preserved so supplementary details
	// the user provided during the confirmation flow are not lost.
	//
	// NOTE: We only clear memory here, NOT clearPerUserSessionState; that
	// would cancel the workflow we just started (it calls cancelWorkflowForUser).
	if engine != nil {
		if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
			adapter.CleanPersistedWorkflowDocs()
			adapter.EmitSuggestMaximize(userID, string(state.Type))
		}
	}
	if h.memory != nil {
		entries := h.memory.Load(userID)
		if len(entries) >= 6 {
			h.memory.Clear(userID)
		}
	}

	lang := h.getWorkflowLang()
	overview := i18n.Tf(i18n.MsgWorkflowStarted, lang, state.Type, state.CurrentPhase)
	if extraText != "" {
		overview += "\n\n" + extraText
	}

	// Input-required workflows must wait for user to provide documents.
	if engine != nil {
		if req := engine.GetInputRequirement(userID); req != nil {
			overview += i18n.Tf(i18n.MsgWorkflowInputRequired, lang, req.Description)
			if len(req.FileTypes) > 0 {
				overview += i18n.Tf(i18n.MsgWorkflowInputFormats, lang, strings.Join(req.FileTypes, ", "))
			}
			if req.AcceptText {
				overview += i18n.T(i18n.MsgWorkflowInputPasteHint, lang)
			}
			return &IMAgentResponse{Text: overview}
		}
	}

	// Non-input workflows: send overview, then re-route to handleActiveWorkflow
	// which calls HandleInput -> PhasePrompt + RunAgentLoop -> agent loop runs.
	if engine != nil {
		if cb := engine.GetCallbacks(); cb != nil {
			_ = cb.SendTextToUser(userID, overview)
		}
	}

	// Stash the original task request.
	//
	// When a workflow starts via multi-round IUM, `text` is the IUM
	// completion message, not the original task request. The original request is
	// preserved in state.Intent: either in Goals[0] (UIC direct path
	// stores the raw user text) or in Summary (IUM LLM generates a
	// structured summary of the user's intent).
	//
	// The agent loop's userText must carry task semantics so the LLM
	// knows what to produce. We stash the best available source here;
	// runAgentLoop consumes it via LoadAndDelete when workflowAgentLoop=true.
	if originalRequest := extractOriginalRequest(state, text); originalRequest != "" {
		h.workflowOriginalRequest.Store(userID, originalRequest)
		log.Printf("[WorkflowInterception] stashed original request for user=%s original_len=%d current_len=%d",
			userID, len([]rune(originalRequest)), len([]rune(text)))
	}

	log.Printf("[WorkflowInterception] StartWorkflow succeeded, re-routing to handleActiveWorkflow for user=%s type=%s phase=%s",
		userID, state.Type, state.CurrentPhase)
	return h.handleActiveWorkflow(engine, userID, text, platform, nil)
}

// handleWorkflowInterception checks if the message should be handled by the
// workflow engine (corelib/workflow). Returns an IMAgentResponse if the message
// was fully handled, or nil if it should proceed to the normal agent loop.
//
// Called from handleIMMessageWithLoop after slash commands and LLM config check,
// before the main agent loop logic.
func (h *IMMessageHandler) handleWorkflowInterception(userID, text, platform string, attachments ...[]MessageAttachment) *IMAgentResponse {
	if h == nil || h.app == nil || h.app.workflowEngine == nil {
		return nil
	}
	engine := h.app.workflowEngine
	wf := h.getWorkflowV2()
	atts := workflowInterceptionAttachments(attachments)
	if workflowAttachmentBypass(engine, userID, atts, text) {
		return nil
	}
	if wf != nil && wf.machine != nil && wf.machine.GetActive(userID) != nil {
		return h.handleActiveWorkflow(engine, userID, text, platform, atts)
	} else if engine.HasActiveWorkflow(userID) {
		return h.handleActiveWorkflow(engine, userID, text, platform, atts)
	}
	if understanding := engine.GetUnderstanding(); understanding != nil && understanding.HasActiveSession(userID) {
		return h.handleActiveUnderstanding(engine, userID, text)
	}
	if h.shouldBypassWorkflowForIntent(userID, text, false) {
		return nil
	}
	return h.handleNeedsUnderstanding(engine, userID, text, platform)
}

func (h *IMMessageHandler) shouldBypassWorkflowForIntent(userID, text string, classifyShortMessages bool) bool {
	if strings.TrimSpace(text) == "" {
		return false
	}

	// Short message optimization: skip L2 embedding + L3 tree classification
	// for messages with fewer than 10 runes. These are typically continuation
	// signals (for example "continue" or "ok") or very short commands that do not benefit
	// from expensive semantic classification. L1 keyword matching in the
	// QuickFilter.Classify path is preserved for fast-path intent detection.
	const shortMessageThreshold = 10
	trimmedText := strings.TrimSpace(text)
	runeCount := utf8.RuneCountInString(trimmedText)
	if runeCount < shortMessageThreshold && !classifyShortMessages {
		log.Printf("[WorkflowInterception] UIC fusion skipped: short message (%d runes < %d threshold)",
			runeCount, shortMessageThreshold)
		return false
	}

	uic := h.getUnifiedClassifier()
	if uic == nil {
		return false
	}

	threshold := uic.GetWorkflowRejectThreshold()

	// Fast path: embedding-only classification (<100ms). It may only reject
	// labels that cannot trigger a workflow by definition. Workflow-capable
	// labels such as office must continue to full fusion because embedding-only
	// does not carry WorkflowType (e.g. presentation_design).
	embResult := uic.ClassifyEmbeddingOnly(intent.MessageContext{
		Text:   text,
		UserID: userID,
	})
	if shouldBypassWorkflowForClassification(embResult, uic.IsWorkflowCandidate(embResult.Primary), threshold) {
		log.Printf("[WorkflowInterception] UIC fast-bypass (embedding-only): user=%s intent=%s conf=%.2f",
			userID, embResult.Primary, embResult.Confidence)
		return true
	}

	// Slow path: full fusion (embedding + tree LLM) for messages where embedding
	// is not confident enough for the fast path. This call writes to UIC cache,
	// so subsequent uic.Classify calls (e.g., in handleNeedsUnderstanding) will
	// hit cache and return instantly (0ms) instead of re-triggering fusion.
	result := uic.Classify(intent.MessageContext{
		Text:   text,
		UserID: userID,
	})

	if result.Primary == intent.LabelContinuation {
		history := h.recentConversationTexts(userID, 8)
		if len(history) > 0 {
			result = uic.Classify(intent.MessageContext{
				Text:          text,
				UserID:        userID,
				RecentHistory: history,
			})
		}
		bypass := h.recentContextResolvesToNonWorkflow(uic, userID, history, threshold)
		log.Printf("[WorkflowInterception] UIC continuation context: user=%s bypass=%v conf=%.2f", userID, bypass, result.Confidence)
		return bypass
	}

	bypass := shouldBypassWorkflowForClassification(result, uic.IsWorkflowCandidate(result.Primary), threshold)
	if bypass {
		log.Printf("[WorkflowInterception] UIC rejected workflow takeover: user=%s intent=%s conf=%.2f layer=%d workflow_type=%q creation=%v",
			userID, result.Primary, result.Confidence, result.Layer, result.WorkflowType, result.CreationOriented)
	}
	return bypass
}

func shouldBypassWorkflowForClassification(result intent.ClassificationResult, isWorkflowCandidate bool, rejectThreshold float64) bool {
	if isConcreteWorkflowType(result.WorkflowType) {
		return false
	}
	if rejectThreshold <= 0 {
		rejectThreshold = intent.DefaultWorkflowRejectThreshold
	}
	if result.Confidence < rejectThreshold {
		return false
	}

	switch result.Primary {
	case intent.LabelContinuation, intent.LabelWorkflowTask, intent.LabelAmbiguous, intent.LabelUnknown:
		return false
	case intent.LabelCoding:
		return !result.CreationOriented && !result.Degraded && (result.Layer == 3 || result.Layer == 23)
	case intent.LabelOffice:
		return !result.Degraded && (result.Layer == 3 || result.Layer == 23)
	case intent.LabelBugFix, intent.LabelMaintenance, intent.LabelSSH:
		return true
	default:
		return !isWorkflowCandidate
	}
}

func shouldEscapeActiveUnderstandingForClassification(result intent.ClassificationResult, isWorkflowCandidate bool, rejectThreshold float64) bool {
	if isConcreteWorkflowType(result.WorkflowType) {
		return false
	}
	if rejectThreshold <= 0 {
		rejectThreshold = intent.DefaultWorkflowRejectThreshold
	}
	if result.Confidence < rejectThreshold {
		return false
	}

	switch result.Primary {
	case intent.LabelContinuation, intent.LabelWorkflowTask, intent.LabelAmbiguous, intent.LabelUnknown, intent.LabelCoding, intent.LabelOffice:
		return false
	case intent.LabelBugFix, intent.LabelMaintenance, intent.LabelSSH:
		return true
	default:
		return !isWorkflowCandidate
	}
}

func (h *IMMessageHandler) recentContextResolvesToNonWorkflow(uic *intent.UnifiedIntentClassifier, userID string, history []string, threshold float64) bool {
	if uic == nil || len(history) == 0 {
		return false
	}
	for i := len(history) - 1; i >= 0; i-- {
		entry := strings.TrimSpace(history[i])
		if entry == "" {
			continue
		}
		// Use embedding-only classification for history entries to avoid
		// triggering a full tree-channel LLM call per entry.
		// This function is on the critical path; rough history scoring is enough.
		result := uic.ClassifyEmbeddingOnly(intent.MessageContext{
			Text:   entry,
			UserID: userID,
		})
		if result.Primary == intent.LabelContinuation || result.Primary == intent.LabelAmbiguous || result.Primary == intent.LabelUnknown {
			continue
		}
		return shouldBypassWorkflowForClassification(result, uic.IsWorkflowCandidate(result.Primary), threshold)
	}
	return false
}

func (h *IMMessageHandler) recentConversationTexts(userID string, maxEntries int) []string {
	if h == nil || h.memory == nil || maxEntries <= 0 {
		return nil
	}
	history := h.memory.Load(userID)
	if len(history) == 0 {
		return nil
	}
	start := len(history) - maxEntries
	if start < 0 {
		start = 0
	}
	texts := make([]string, 0, len(history)-start)
	for _, e := range history[start:] {
		if text := strings.TrimSpace(conversationEntryText(e.Content)); text != "" {
			texts = append(texts, text)
		}
	}
	return texts
}

func conversationEntryText(content any) string {
	switch v := content.(type) {
	case string:
		return v
	case []interface{}:
		var b strings.Builder
		for _, item := range v {
			if m, ok := item.(map[string]interface{}); ok {
				if s, ok := m["text"].(string); ok {
					b.WriteString(s)
					b.WriteByte('\n')
				}
			}
		}
		return b.String()
	default:
		return fmt.Sprint(v)
	}
}

// handleActiveWorkflow processes input for a user with an active workflow.
func (h *IMMessageHandler) handleActiveWorkflow(engine *v2.WorkflowEngine, userID, text, platform string, attachments []MessageAttachment) *IMAgentResponse {
	if workflowHasPendingPhaseForm(engine, userID) && isWorkflowFormDirectRunCommand(text) {
		if err := engine.SkipPhaseForm(userID); err != nil {
			log.Printf("[WorkflowEngine] SkipPhaseForm direct-run failed: user=%s err=%v", userID, err)
			return &IMAgentResponse{Text: i18n.Tf(i18n.MsgWorkflowFormSaveError, h.getWorkflowLang(), err)}
		}
		log.Printf("[WorkflowEngine] skipped pending workflow form by direct-run command: user=%s text_len=%d", userID, len([]rune(text)))
	}

	// Active workflow state owns the message. UIC workflow_type is only a
	// candidate hint for starting new workflows; it must not cancel or replace
	// an already-active workflow.
	if resp, handled := h.submitWorkflowInputIfWaiting(engine, userID, text, attachments, platform); handled {
		return resp
	}

	resp, err := engine.HandleInput(userID, text)
	if err != nil {
		log.Printf("[WorkflowInterception] HandleInput error for user %s: %v", userID, err)
		return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowHandleError, h.getWorkflowLang(), err)}
	}
	if resp == nil {
		return nil
	}

	// --- Workflow review: lightweight LLM intent classification ---
	// The engine detected that the user is responding to a NeedsConfirm phase
	// that already has output. The GUI classifies the free-form reply into a
	// typed ReviewIntent, then the engine applies the state transition.
	if resp.PendingReview || resp.PendingConfirm {
		return h.handleWorkflowReview(engine, userID, text, platform)
	}

	if resp.ShowForm && resp.FormSchema != nil {
		return h.workflowFormResponse(engine, userID, platform, resp)
	}

	if !resp.RunAgentLoop {
		if resp.Complete {
			if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
				adapter.ResetSuggestMaximize(userID)
			}
		}
		return &IMAgentResponse{Text: resp.Text}
	}

	// When the engine signals an execution phase, attempt to activate the
	// task orchestrator. The engine provides the preceding phase's output
	// as TaskBreakdownText. If it parses as a task list, use orchestrator +
	// SubAgent. If not (e.g. PPT's slide_scripting output), fall through
	// to the normal agent loop which handles execution via tools directly.
	h.backfillExecutionOrchestratorActivation(engine, userID, resp)
	if activated, errResp := h.activateWorkflowTaskOrchestrator(engine, userID, resp); errResp != nil {
		return errResp
	} else if !activated {
		if repairResp, repaired := h.repairInvalidCodingTaskBreakdownExecution(engine, userID, resp); repaired {
			return repairResp
		}
	}

	// RunAgentLoop=true means the workflow engine wants the agent loop to
	// generate phase output.
	//
	// Phase prompt injection and doc capture marker are ALWAYS set when
	// the engine provides a PhasePrompt. The phase prompt is the engine's
	// instruction to the LLM ("you are in the audience_goal phase,
	// generate..."). Without it, the LLM has no idea what to produce.
	// The marker enables doc capture (SavePhaseOutput) so the generated
	// document is saved and the workflow can advance.
	//
	// DefaultInput=true means the user's message reached the engine's
	// default branch (no confirm/skip match). This happens both for
	// legitimate phase triggers and unrelated messages ("check
	// server status"). In both cases, the phase prompt guides the LLM
	// to produce the phase deliverable. If the LLM instead answers the
	// unrelated question, the NeedsConfirm gate will force-return the
	// output for user review; the user can then re-trigger the phase.
	//
	// Previously, DefaultInput=true suppressed both phase prompt injection
	// and doc capture, causing the workflow to stall completely; the LLM
	// received no phase instructions and produced no captured output.
	if resp.PhasePrompt != "" {
		h.stashedPhasePrompt.Store(userID, resp.PhasePrompt)
	}
	h.workflowAgentLoopMarker.Store(userID, true)
	if resp.Advance && resp.Text != "" {
		if cb := engine.GetCallbacks(); cb != nil {
			_ = cb.SendTextToUser(userID, resp.Text)
		}
	}
	return nil
}

func (h *IMMessageHandler) workflowFormResponse(engine *v2.WorkflowEngine, userID, platform string, resp *v2.WorkflowResponse) *IMAgentResponse {
	if resp == nil || resp.FormSchema == nil {
		return nil
	}
	ws := engine.GetActiveWorkflow(userID)
	phaseID := ""
	if ws != nil {
		phaseID = ws.CurrentPhase
	}
	if normalizeIMMessagePlatformKind(platform).IsIMChannel() {
		formSchema := localizeWorkflowPhaseInputSchema(resp.FormSchema, h.getWorkflowLang())
		guidance := buildIMFormGuidanceText(formSchema)
		if guidance == "" {
			guidance = formSchema.Description
		}
		if err := engine.SkipPhaseForm(userID); err != nil {
			log.Printf("[WorkflowEngine] SkipPhaseForm failed: user=%s err=%v", userID, err)
			return &IMAgentResponse{Text: i18n.Tf(i18n.MsgWorkflowFormSaveError, h.getWorkflowLang(), err)}
		}
		if strings.TrimSpace(resp.Text) != "" {
			guidance = strings.TrimSpace(resp.Text) + "\n\n" + guidance
		}
		return &IMAgentResponse{Text: strings.TrimSpace(guidance)}
	}
	h.emitWorkflowPhaseForm(userID, resp.FormSchema, phaseID)
	text := i18n.T(i18n.MsgWorkflowFormPanelPrompt, h.getWorkflowLang())
	if strings.TrimSpace(resp.Text) != "" {
		text = strings.TrimSpace(resp.Text) + "\n\n" + text
	}
	return &IMAgentResponse{Text: text}
}

func (h *IMMessageHandler) submitWorkflowInputIfWaiting(engine *v2.WorkflowEngine, userID, text string, attachments []MessageAttachment, platform string) (*IMAgentResponse, bool) {
	if engine == nil {
		return nil, false
	}
	ws := engine.GetActiveWorkflow(userID)
	if ws == nil {
		return nil, false
	}
	tmpl := engine.GetRegistry().Match(ws.Type)
	if !ws.IsWaitingForInput(tmpl) {
		return nil, false
	}
	payload := workflowInputPayloadFromMessage(text, attachments)
	if payload == nil {
		return nil, false
	}
	resp, err := engine.SubmitInputPayload(userID, payload)
	if err != nil {
		log.Printf("[WorkflowInterception] SubmitInputPayload error for user %s: %v", userID, err)
		return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowInputHandleError, h.getWorkflowLang(), err)}, true
	}
	if resp == nil {
		return nil, true
	}
	if resp.ShowForm && resp.FormSchema != nil {
		return h.workflowFormResponse(engine, userID, platform, resp), true
	}
	if resp.PhasePrompt != "" {
		h.stashedPhasePrompt.Store(userID, resp.PhasePrompt)
		h.workflowAgentLoopMarker.Store(userID, true)
	}
	return nil, true
}

func workflowInputPayloadFromMessage(text string, attachments []MessageAttachment) *v2.WorkflowInputPayload {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" && len(attachments) == 0 {
		return nil
	}
	payload := &v2.WorkflowInputPayload{Text: trimmed, ReceivedAt: time.Now()}
	for _, att := range attachments {
		payload.Attachments = append(payload.Attachments, v2.WorkflowInputAttachment{
			Type:     att.Type,
			FileName: att.FileName,
			MimeType: att.MimeType,
			Size:     att.Size,
		})
	}
	return payload
}

// handleWorkflowReview uses a lightweight LLM call to classify the user's
// intent after viewing a phase document, then lets the workflow engine apply
// the typed review-state transition.
//
// Token budget: ~300-500 input + ~10 output vs ~55000 input for full agent loop.
// Latency: one lightweight classifier call vs the full agent loop.
func (h *IMMessageHandler) handleWorkflowReview(engine *v2.WorkflowEngine, userID, text, platform string) *IMAgentResponse {
	ctx := context.Background()

	// Cross-type detection is handled by handleActiveWorkflow BEFORE
	// HandleInput is called. By the time we reach here, the message is
	// confirmed to be directed at the current workflow (same type or
	// non-workflow). We classify the remaining review-level intent.

	ws := engine.GetActiveWorkflow(userID)

	// Build compact context: phase name + first ~200 chars of the document +
	// the system's last prompt to the user + the last assistant message.
	// The last assistant message is critical; it often contains instructions
	// telling the user how to confirm, and the LLM needs that context to avoid
	// treating the reply as unrelated.
	phaseContext := ""
	if ws != nil {
		tmpl := engine.GetRegistry().Match(ws.Type)
		if tmpl != nil && ws.PhaseIndex < len(tmpl.Phases) {
			phase := &tmpl.Phases[ws.PhaseIndex]
			phaseContext = fmt.Sprintf("Current workflow phase: %s (%s)\n", phase.Name, phase.Description)

			// Add a snippet of the phase output (first ~200 runes).
			if output, ok := ws.PhaseOutputs[ws.CurrentPhase]; ok && len(output) > 0 {
				snippet := output
				runes := []rune(snippet)
				if len(runes) > 200 {
					snippet = string(runes[:200]) + "..."
				}
				phaseContext += fmt.Sprintf("Document snippet: %s\n", snippet)
			}

			phaseContext += "System prompt to user: review the document and confirm, or request changes.\n"

			// Inject the last assistant message from conversation history.
			// This provides the immediate conversational context, so the classifier
			// can treat a short confirmation reply as a response to that prompt.
			if lastAssistant := h.getLastAssistantSnippet(userID, 300); lastAssistant != "" {
				phaseContext += fmt.Sprintf("Last assistant message: %s\n", lastAssistant)
			}
		}
	}

	userMessage := text
	if phaseContext != "" {
		userMessage = fmt.Sprintf("[Context]\n%s\n\n[User reply]\n%s", phaseContext, text)
	}

	if reviewIntent, ok := detectWorkflowReviewIntentFast(text); ok {
		log.Printf("[workflow-review] user=%s text_len=%d intent=%q source=fast-path", userID, len([]rune(text)), reviewIntent)
		return h.applyWorkflowReviewIntent(engine, userID, reviewIntent, text, platform)
	}

	if reviewIntent, ok := detectCodingTaskBreakdownReviewAdvanceIntent(engine, userID, text); ok {
		log.Printf("[workflow-review] user=%s text_len=%d intent=%q source=coding-task-breakdown-advance", userID, len([]rune(text)), reviewIntent)
		return h.applyWorkflowReviewIntent(engine, userID, reviewIntent, text, platform)
	}

	if detectWorkflowReviewBlockedExecutionIntent(text) {
		log.Printf("[workflow-review] user=%s text_len=%d intent=%q source=execution-block", userID, len([]rune(text)), v2.ReviewIntentOther)
		return h.workflowReviewExecutionBlockedResponse(engine, userID)
	}

	classifyResult, err := h.LLMClassify(ctx, LLMClassifyRequest{
		SystemPrompt: `You are a user intent classifier for a document review workflow.

The user was shown a document/plan and asked to confirm or request changes. You will receive:
- The workflow context: phase name, document snippet, the system prompt shown to the user
- The assistant's last message (if available): this is what the user is directly responding to
- The user's response

IMPORTANT: Pay close attention to the assistant's last message. If the assistant asked the user to say a specific word or phrase to proceed, and the user replies with exactly that word or phrase, it is a confirmation, not an unrelated message.

Classify the user's response into exactly one category. Reply with ONLY the category word, nothing else:
- "confirm": user approves and wants to proceed. This includes any form of agreement, acceptance, or readiness signal in the context of the ongoing review. A short or vague reply after being shown a document almost always means approval.
- "supplement": user provides specific feedback, corrections, additions, questions, or requests changes to the DOCUMENT CONTENT itself. Use this for both modifications and additional information.
- "skip": user wants to skip the current review phase while keeping the workflow active. The engine will decide whether this phase is skippable.
- "cancel": user wants to abandon, cancel, or discard the current workflow entirely. This includes:
  - Explicit cancellation such as "cancel" or "abort"
  - NOTE: Starting a completely different task type (e.g. coding task during a PPT workflow) is usually handled separately by cross-type detection.
- "switch_task": user is clearly asking to abandon the current workflow and start a different task, especially a different workflow type.
- "other": user is asking something clearly unrelated to the document or workflow. This includes:
  - Server/infrastructure operations such as login, restart, npm install, or deploy
  - Information queries: weather, search, off-topic questions
  - File operations such as opening files or taking screenshots
  - Any request that involves EXECUTING an action on a system/server/tool, rather than editing the document

CRITICAL: "update" can mean either "update the document" or "update software on a server". If the object of "update" is a software package, service, server component, or tool name (not a section/content of the document), classify as "other".

When in doubt between "confirm" and "other", prefer "confirm" - the conversational context is a document review, so the user's response is most likely directed at the document.`,
		UserMessage: userMessage,
		TimeoutSec:  30,
		Tag:         "workflow-confirm",
	})

	if err != nil {
		log.Printf("[workflow-review] LLM classify failed, keeping review barrier active: %v", err)
		return h.applyWorkflowReviewIntent(engine, userID, v2.ReviewIntentOther, text, platform)
	}

	reviewIntent := normalizeWorkflowReviewIntent(classifyResult.Text)
	log.Printf("[workflow-review] user=%s text_len=%d intent=%q raw_len=%d (input=%d output=%d latency=%.1fs)",
		userID, len([]rune(text)), reviewIntent, len([]rune(strings.TrimSpace(classifyResult.Text))), classifyResult.InputTokens, classifyResult.OutputTokens, classifyResult.Latency.Seconds())

	return h.applyWorkflowReviewIntent(engine, userID, reviewIntent, text, platform)
}

func normalizeWorkflowReviewIntent(raw string) v2.ReviewIntent {
	return v2.ParseReviewIntent(raw)
}

func (h *IMMessageHandler) workflowReviewPending(userID string, background bool) bool {
	if h == nil || background {
		return false
	}
	return false
}

func detectWorkflowReviewIntentFast(text string) (v2.ReviewIntent, bool) {
	trimmed := strings.ToLower(strings.TrimSpace(text))
	trimmed = strings.Trim(trimmed, " \t\r\n.\u3002!\uff01\uff1f?")
	if trimmed == "" {
		return v2.ReviewIntentOther, false
	}
	switch trimmed {
	case "\u786e\u8ba4", "\u786e\u8ba4\u901a\u8fc7", "\u786e\u5b9a", "\u786e\u5b9a\u7ee7\u7eed", "\u786e\u5b9a\u901a\u8fc7", "\u901a\u8fc7", "\u540c\u610f", "\u53ef\u4ee5", "\u6ca1\u95ee\u9898", "\u6ca1\u610f\u89c1", "\u7ee7\u7eed", "\u7ee7\u7eed\u63a8\u8fdb", "\u5f00\u5de5", "\u5f00\u59cb", "\u5f00\u59cb\u5427", "\u6267\u884c", "\u8d70\u8d77", "\u597d", "\u597d\u7684", "\u5f00\u59cb\u7f16\u7801", "\u5f00\u59cb\u7f16\u7801\u5427", "\u5f00\u59cb\u5199\u4ee3\u7801", "\u5f00\u59cb\u5b9e\u73b0", "\u5f00\u59cb\u5f00\u53d1", "\u5f00\u59cb\u6267\u884c", "\u786e\u8ba4\u5f00\u59cb\u7f16\u7801", "\u786e\u8ba4\u5f00\u59cb\u5b9e\u73b0", "\u786e\u5b9a\u5f00\u59cb\u7f16\u7801", "\u786e\u5b9a\u5f00\u59cb\u5b9e\u73b0":
		return v2.ReviewIntentConfirm, true
	case "\u8df3\u8fc7", "skip", "skip it":
		return v2.ReviewIntentSkip, true
	case "\u53d6\u6d88", "\u505c\u6b62", "\u7ec8\u6b62", "\u653e\u5f03", "cancel", "stop", "abort", "quit":
		return v2.ReviewIntentCancel, true
	}
	if looksLikeWorkflowReviewApproval(trimmed) {
		return v2.ReviewIntentConfirm, true
	}
	switch trimmed {
	case "ok", "okay", "yes", "y", "go", "go ahead", "start", "continue", "proceed", "approved", "approve", "confirmed", "confirm":
		return v2.ReviewIntentConfirm, true
	}
	return v2.ReviewIntentOther, false
}

func detectCodingTaskBreakdownReviewAdvanceIntent(engine *v2.WorkflowEngine, userID, text string) (v2.ReviewIntent, bool) {
	trimmed := strings.ToLower(strings.TrimSpace(text))
	trimmed = strings.Trim(trimmed, " \t\r\n.\u3002!\uff01\uff1f?")
	if trimmed == "" || engine == nil {
		return v2.ReviewIntentOther, false
	}
	ws := engine.GetActiveWorkflow(userID)
	if ws == nil ||
		ws.Type != v2.WorkflowCoding ||
		ws.CurrentPhase != v2.PhaseCodingTaskBreakdown ||
		ws.PendingReviewPhaseID != v2.PhaseCodingTaskBreakdown {
		return v2.ReviewIntentOther, false
	}
	if looksLikeTaskBreakdownDocumentChange(trimmed) {
		return v2.ReviewIntentOther, false
	}
	if looksLikeCodingImplementationAdvance(trimmed) {
		return v2.ReviewIntentConfirm, true
	}
	return v2.ReviewIntentOther, false
}

func looksLikeTaskBreakdownDocumentChange(text string) bool {
	revisionMarkers := []string{
		"\u4fee\u6539", "\u8c03\u6574", "\u8865\u5145", "\u66f4\u65b0", "\u6539\u6210", "\u6539\u4e3a", "\u5220\u9664", "\u79fb\u9664",
		"\u52a0\u4e0a", "\u52a0\u5230", "\u589e\u52a0", "\u5199\u8fdb", "\u653e\u5230", "\u653e\u5165",
		"modify", "change", "revise", "update", "add", "remove",
	}
	documentTargets := []string{
		"\u6587\u6863", "\u4efb\u52a1", "\u62c6\u5206", "\u5217\u8868", "\u8ba1\u5212", "\u8bbe\u8ba1", "\u9700\u6c42",
		"t1", "t2", "t3", "task", "tasks", "plan", "document", "doc",
	}
	return containsAnyWorkflowReviewMarker(text, revisionMarkers) && containsAnyWorkflowReviewMarker(text, documentTargets)
}

func looksLikeCodingImplementationAdvance(text string) bool {
	markers := []string{
		"\u5b9e\u73b0", "\u5f00\u53d1", "\u7f16\u7801", "\u5199\u4ee3\u7801", "\u6539\u4ee3\u7801", "\u8dd1\u4ee3\u7801",
		"\u6838\u5fc3\u529f\u80fd", "\u5f00\u59cb\u5b9e\u73b0", "\u5f00\u59cb\u5f00\u53d1", "\u5f00\u59cb\u7f16\u7801",
		"\u521b\u5efa\u76ee\u5f55", "\u65b0\u5efa\u76ee\u5f55", "\u521b\u5efa\u6587\u4ef6\u5939", "\u65b0\u5efa\u6587\u4ef6\u5939",
		"\u521b\u5efa\u6587\u4ef6", "\u65b0\u5efa\u6587\u4ef6", "\u751f\u6210\u6587\u4ef6", "\u843d\u5730\u4ee3\u7801",
		"\u5199 cmake", "\u5199 cmakelists",
		"implement", "implementation", "develop", "coding", "write code", "start coding",
		"mkdir", "create cmake", "create cmakelists", "write cmake", "write cmakelists",
	}
	return containsAnyWorkflowReviewMarker(text, markers)
}

func looksLikeWorkflowReviewApproval(text string) bool {
	if !strings.Contains(text, "\u7ee7\u7eed") && !strings.Contains(text, "continue") && !strings.Contains(text, "proceed") {
		return false
	}
	approvalMarkers := []string{"\u5408\u7406", "\u53ef\u4ee5", "\u6ca1\u95ee\u9898", "\u6ca1\u610f\u89c1", "\u540c\u610f", "\u786e\u8ba4", "\u901a\u8fc7", "\u597d", "ok", "approve", "approved", "looks good"}
	return containsAnyWorkflowReviewMarker(text, approvalMarkers)
}

func detectWorkflowReviewBlockedExecutionIntent(text string) bool {
	trimmed := strings.ToLower(strings.TrimSpace(text))
	if trimmed == "" {
		return false
	}
	if _, ok := detectWorkflowReviewIntentFast(trimmed); ok {
		return false
	}
	documentTargets := []string{"\u6587\u6863", "\u9700\u6c42", "\u8bbe\u8ba1", "\u65b9\u6848", "\u4efb\u52a1", "\u8ba1\u5212", "\u62a5\u544a", "document", "doc", "requirements", "design", "plan"}
	executionMarkers := []string{
		"\u5199\u4ee3\u7801", "\u7f16\u5199\u4ee3\u7801", "\u5f00\u59cb\u7f16\u7801", "\u7f16\u7801", "\u5b9e\u73b0\u4ee3\u7801", "\u6539\u4ee3\u7801", "\u8dd1\u4ee3\u7801",
		"build", "compile", "cmake", "npm", "git", "bash", "powershell",
		"\u547d\u4ee4", "\u811a\u672c", "\u521b\u5efa\u76ee\u5f55", "\u65b0\u5efa\u76ee\u5f55", "\u521b\u5efa\u6587\u4ef6\u5939", "\u65b0\u5efa\u6587\u4ef6\u5939",
		"mkdir", "d:\\\\", "c:\\\\", "src/", "assets/",
	}
	for _, marker := range executionMarkers {
		if strings.Contains(trimmed, marker) {
			return true
		}
	}
	if (strings.Contains(trimmed, "\u521b\u5efa") || strings.Contains(trimmed, "\u65b0\u5efa")) && !containsAnyWorkflowReviewMarker(trimmed, documentTargets) {
		return true
	}
	return false
}

func containsAnyWorkflowReviewMarker(text string, markers []string) bool {
	for _, marker := range markers {
		if strings.Contains(text, marker) {
			return true
		}
	}
	return false
}

func (h *IMMessageHandler) applyWorkflowReviewIntent(engine *v2.WorkflowEngine, userID string, intent v2.ReviewIntent, feedback, platform string) *IMAgentResponse {
	if intent == v2.ReviewIntentConfirm && h.shouldRegenerateInvalidCodingTaskBreakdown(engine, userID) {
		log.Printf("[workflow-review] blocking confirm for invalid coding task breakdown: user=%s", userID)
		intent = v2.ReviewIntentSupplement
		feedback = invalidCodingTaskBreakdownFeedbackText()
	}

	// Use V2 StateMachine directly for review intent processing.
	wf := h.getWorkflowV2()
	if wf != nil && wf.machine != nil && wf.machine.GetActive(userID) != nil {
		hr, err := wf.machine.ApplyReviewIntent(userID, string(intent), feedback)
		if err != nil {
			log.Printf("[workflow-review] V2 ApplyReviewIntent error: user=%s intent=%s err=%v", userID, intent, err)
			return h.reviewBarrierResponse(engine, userID)
		}
		h.recordWorkflowReviewFeedbackExperience(userID, intent, feedback)
		if intent == v2.ReviewIntentSwitchTask {
			return h.handleWorkflowInterception(userID, feedback, platform)
		}
		if hr == nil {
			return nil
		}
		// Map HandleResult to WorkflowResponse for existing handler.
		resp := mapHandleResultToWorkflowResponse(hr)
		return h.handleWorkflowEngineResponse(engine, userID, resp, platform)
	}

	// Fallback: engine stub (returns nil, nil).
	resp, err := engine.ApplyReviewIntent(userID, intent, feedback)
	if err != nil {
		log.Printf("[workflow-review] ApplyReviewIntent error: user=%s intent=%s err=%v", userID, intent, err)
		return h.reviewBarrierResponse(engine, userID)
	}
	h.recordWorkflowReviewFeedbackExperience(userID, intent, feedback)
	if intent == v2.ReviewIntentSwitchTask {
		return h.handleWorkflowInterception(userID, feedback, platform)
	}
	return h.handleWorkflowEngineResponse(engine, userID, resp, platform)
}

// mapHandleResultToWorkflowResponse converts a V2 HandleResult to the WorkflowResponse
// format that handleWorkflowEngineResponse expects.
func mapHandleResultToWorkflowResponse(hr *v2.HandleResult) *v2.WorkflowResponse {
	if hr == nil {
		return nil
	}
	resp := &v2.WorkflowResponse{}
	switch hr.Action {
	case v2.ActionRunPhase, v2.ActionModify:
		resp.RunAgentLoop = true
		if hr.Phase != nil {
			resp.PhasePrompt = v2.BuildPhasePrompt(hr.State)
		}
		if hr.ModifyHint != "" {
			resp.PhasePrompt += "\n\nUser modification request: " + hr.ModifyHint
		}
	case v2.ActionConfirmed:
		// Phase advanced — check if next phase needs agent loop.
		if hr.State != nil && hr.State.Status == v2.StatusCompleted {
			resp.Complete = true
		} else {
			resp.Advance = true
			resp.RunAgentLoop = true
			resp.PhasePrompt = v2.BuildPhasePrompt(hr.State)
		}
	case v2.ActionShowForm:
		resp.ShowForm = true
		if hr.Phase != nil && hr.Phase.InputSchema != nil {
			resp.FormSchema = v2MapPhaseInputSchema(hr.Phase.InputSchema)
		}
	case v2.ActionCancelled, v2.ActionCancelAndExecute:
		// Caller handles these before reaching here.
	}
	return resp
}

// v2MapPhaseInputSchema converts V2 PhaseInputSchema to PhaseInputSchemaSpec.
func v2MapPhaseInputSchema(schema *v2.PhaseInputSchema) *v2.PhaseInputSchemaSpec {
	if schema == nil {
		return nil
	}
	spec := &v2.PhaseInputSchemaSpec{
		Title:       schema.Title,
		Description: schema.Description,
	}
	for _, f := range schema.Fields {
		field := v2.PhaseInputFieldSpec{
			Name:        f.Name,
			Label:       f.Label,
			Type:        f.Type,
			Required:    f.Required,
			Description: f.Description,
			Placeholder: f.Placeholder,
			Default:     f.Default,
		}
		for _, o := range f.Options {
			field.Options = append(field.Options, v2.PhaseInputOptionSpec{Label: o.Label, Value: o.Value})
		}
		spec.Fields = append(spec.Fields, field)
	}
	return spec
}

func (h *IMMessageHandler) recordWorkflowReviewFeedbackExperience(userID string, intent v2.ReviewIntent, feedback string) {
	if h == nil {
		return
	}
	value, ok := h.workflowReviewExperienceContext.Load(userID)
	if !ok {
		return
	}
	ctx, ok := value.(workflowReviewExperienceContext)
	if !ok || strings.TrimSpace(ctx.TraceID) == "" {
		return
	}
	if workflowReviewIntentEndsCurrentContext(intent) {
		h.workflowReviewExperienceContext.Delete(userID)
	}
	h.recordExperienceLifecycleEvent(ctx.Apply(lifecycle.Event{
		EventType: lifecycle.EventUserFeedbackReceived,
		Outcome:   string(intent),
		Reason:    ctx.PhaseID,
		Query:     feedback,
		CreatedAt: time.Now(),
	}))
}

func workflowReviewIntentEndsCurrentContext(intent v2.ReviewIntent) bool {
	switch intent {
	case v2.ReviewIntentConfirm, v2.ReviewIntentSkip, v2.ReviewIntentCancel, v2.ReviewIntentSwitchTask:
		return true
	default:
		return false
	}
}

func (h *IMMessageHandler) handleWorkflowEngineResponse(engine *v2.WorkflowEngine, userID string, resp *v2.WorkflowResponse, platform string) *IMAgentResponse {
	if resp == nil {
		return nil
	}
	if resp.ShowForm && resp.FormSchema != nil {
		return h.workflowFormResponse(engine, userID, platform, resp)
	}
	if !resp.RunAgentLoop {
		if resp.Complete {
			if adapter, ok := engine.GetCallbacks().(*GUIWorkflowAdapter); ok {
				adapter.ResetSuggestMaximize(userID)
			}
		}
		return &IMAgentResponse{Text: resp.Text}
	}
	if activated, errResp := h.activateWorkflowTaskOrchestrator(engine, userID, resp); errResp != nil {
		return errResp
	} else if !activated {
		if repairResp, repaired := h.repairInvalidCodingTaskBreakdownExecution(engine, userID, resp); repaired {
			return repairResp
		}
	}
	if resp.PhasePrompt != "" {
		h.stashedPhasePrompt.Store(userID, resp.PhasePrompt)
	}
	h.workflowAgentLoopMarker.Store(userID, true)
	if ws := engine.GetActiveWorkflow(userID); ws != nil {
		if orig := extractOriginalRequest(ws, ""); orig != "" {
			h.workflowOriginalRequest.Store(userID, orig)
		}
	}
	if resp.Text != "" {
		if cb := engine.GetCallbacks(); cb != nil {
			_ = cb.SendTextToUser(userID, resp.Text)
		}
	}
	return nil
}

func (h *IMMessageHandler) reviewBarrierResponse(engine *v2.WorkflowEngine, userID string) *IMAgentResponse {
	phaseName := h.workflowReviewPhaseName(engine, userID)
	if phaseName == "" {
		return nil
	}
	lang := h.getWorkflowLang()
	return &IMAgentResponse{Text: i18n.Tf(i18n.MsgWorkflowAwaitingReview, lang, phaseName)}
}

func (h *IMMessageHandler) workflowReviewExecutionBlockedResponse(engine *v2.WorkflowEngine, userID string) *IMAgentResponse {
	phaseName := h.workflowReviewPhaseName(engine, userID)
	if phaseName == "" {
		return nil
	}
	return &IMAgentResponse{Text: i18n.Tf(i18n.MsgWorkflowReviewExecutionBlock, h.getWorkflowLang(), phaseName)}
}

func (h *IMMessageHandler) workflowReviewPhaseName(engine *v2.WorkflowEngine, userID string) string {
	ws := engine.GetActiveWorkflow(userID)
	if ws == nil {
		return ""
	}
	phaseName := ws.CurrentPhase
	if tmpl := engine.GetRegistry().Match(ws.Type); tmpl != nil && ws.PhaseIndex < len(tmpl.Phases) {
		phaseName = tmpl.Phases[ws.PhaseIndex].Name
	}
	return phaseName
}

// handleActiveUnderstanding processes input for a user with an active
// intent understanding session.
func (h *IMMessageHandler) handleActiveUnderstanding(engine *v2.WorkflowEngine, userID, text string) *IMAgentResponse {
	understanding := engine.GetUnderstanding()
	if understanding == nil {
		return nil
	}
	understanding.SetUserLanguage(userID, h.getWorkflowLang())

	reply, ready, cancelled, intent, err := understanding.HandleInput(userID, text)
	if err != nil {
		log.Printf("[WorkflowInterception] understanding HandleInput error for user %s: %v", userID, err)
		if errors.Is(err, v2.ErrIntentUnderstandingContractBreach) {
			return nil
		}
		return &IMAgentResponse{Text: i18n.T(i18n.MsgWorkflowUnderstandError, h.getWorkflowLang())}
	}
	if cancelled {
		lang := h.getWorkflowLang()
		return &IMAgentResponse{Text: i18n.T(i18n.MsgWorkflowCancelled, lang)}
	}
	if ready && intent != nil {
		// Guard: if the LLM returned category="none" or empty with ready=true,
		// it means the task is NOT a workflow task (e.g., content processing).
		// Do NOT call StartWorkflow; fall through to the normal agent loop.
		// The understanding session has already been cleaned up by HandleInput
		// when isReady=true, so no additional cleanup is needed.
		if intent.Category == v2.WorkflowNone || intent.Category == "" {
			log.Printf("[WorkflowInterception] understanding returned ready=true with category=%q for user %s, falling through to agent loop", intent.Category, userID)
			return nil
		}

		// Intent understanding is complete - start the workflow.
		if resp := h.confirmWorkflowStart(userID, text, *intent, reply); resp != nil {
			return resp
		}
		projectPath := h.workflowStartProjectPathForIntent(userID, text, *intent)
		projectPath, prepErr := h.resolveWorkflowProjectPath(projectPath)
		if prepErr != nil {
			log.Printf("[WorkflowInterception] invalid workflow project path for user %s: %v", userID, prepErr)
			return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowPrepareProjectError, h.getWorkflowLang(), prepErr)}
		}
		state, err := engine.StartWorkflowWithOptions(userID, *intent, v2.WorkflowStartOptions{ProjectPath: projectPath})
		if err != nil {
			log.Printf("[WorkflowInterception] StartWorkflow error for user %s: %v", userID, err)
			return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowStartError, h.getWorkflowLang(), err)}
		}
		return h.handlePostStartWorkflow(engine, userID, text, state, reply, "")
	}
	return &IMAgentResponse{Text: reply}
}

// handleNeedsUnderstanding starts a new intent understanding session for a
// message that needs LLM classification. The LLM will decide:
//   - Is this a workflow task? (if not, returns nil for the normal agent loop)
//   - Which workflow template?
//   - Structured intent extraction
func (h *IMMessageHandler) handleNeedsUnderstanding(engine *v2.WorkflowEngine, userID, text, platform string) *IMAgentResponse {
	understanding := engine.GetUnderstanding()
	if understanding == nil {
		// No understanding manager; fall through to normal agent loop.
		return nil
	}
	understanding.SetUserLanguage(userID, h.getWorkflowLang())
	var uicForUnderstanding *intent.UnifiedIntentClassifier
	var uicResultForUnderstanding *intent.ClassificationResult

	// Unified classification: UIC fusion produces both IntentLabel and WorkflowType.
	//
	// DESIGN PRINCIPLE: UIC has "fast reject" power but NOT "fast accept" power.
	//
	// UIC is a single-round LLM call with limited context (no conversation
	// history, no knowledge of maclaw's own features). Its classification can
	// be wrong, for example when a GUI automation request superficially looks like a development task.
	//
	// IUM (IntentUnderstandingManager) has richer context (system prompt with
	// maclaw feature descriptions, workflow template descriptions) and can make
	// more accurate judgments. It previously correctly rejected this same intent
	// three times.
	//
	// Therefore:
	//   - UIC can REJECT (fast path): confident non-workflow intent -> skip IUM
	//   - UIC can HINT (pass-through): WorkflowType as hint to IUM for faster processing
	//   - UIC CANNOT ACCEPT (no fast path): never directly start a workflow
	//
	// The "accept" power belongs to IUM (deep semantic confirmation) or the
	// user (via confirmation panel after IUM confirms).
	if uic := h.getUnifiedClassifier(); uic != nil {
		uicForUnderstanding = uic
		uicResult := uic.Classify(intent.MessageContext{
			Text:   text,
			UserID: userID,
		})
		uicResultForUnderstanding = &uicResult

		// UIC says no workflow - check if it's a confident non-workflow signal.
		//
		// Rejection policy based on MayTriggerWorkflow:
		//   - MayTriggerWorkflow=false intents (document_delivery, search, non_coding, etc.):
		//     A semantic result with confidence >= threshold is sufficient.
		//     These intents can NEVER trigger a workflow by definition.
		//   - MayTriggerWorkflow=true intents (coding, office, workflow_task) or Ambiguous/Unknown:
		//     IsWorkflowCandidate returns true -> canReject is false -> falls through to IUM.
		//     This prevents L1 misclassification from blocking a legitimate workflow task.
		if uicResult.WorkflowType == "" {
			isNonWorkflowIntent := !uic.IsWorkflowCandidate(uicResult.Primary)
			threshold := uic.GetWorkflowRejectThreshold()

			if isNonWorkflowIntent && uicResult.Confidence >= threshold {
				log.Printf("[WorkflowInterception] UIC rejected workflow for user %s: "+
					"intent=%s conf=%.2f layer=%d threshold=%.2f text_len=%d",
					userID, uicResult.Primary, uicResult.Confidence, uicResult.Layer, threshold,
					len([]rune(text)))
				return nil
			}
		}

		// Log UIC's recommendation (hint) for diagnostics. The hint is NOT
		// used to directly start a workflow -> it falls through to IUM below.
		if isConcreteWorkflowType(uicResult.WorkflowType) {
			log.Printf("[WorkflowInterception] UIC recommends workflow_type=%s for user %s "+
				"(intent=%s conf=%.2f layer=%d) -> delegating to IUM for confirmation. text_len=%d",
				uicResult.WorkflowType, userID, uicResult.Primary, uicResult.Confidence,
				uicResult.Layer, len([]rune(text)))
		} else {
			// UIC not confident enough or ambiguous.
			log.Printf("[WorkflowInterception] UIC fusion: intent=%s conf=%.2f layer=%d wf=%s - "+
				"not decisive, proceeding to IUM",
				uicResult.Primary, uicResult.Confidence, uicResult.Layer, uicResult.WorkflowType)
		}
	}

	result, err := understanding.Start(userID, text)
	if err != nil {
		log.Printf("[WorkflowInterception] understanding Start error for user %s: %v", userID, err)
		if shouldSurfaceWorkflowUnderstandingStartError(uicForUnderstanding, uicResultForUnderstanding) {
			return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowUnderstandStartError, h.getWorkflowLang(), err)}
		}
		return nil
	}

	// LLM determined this is NOT a workflow task - trust the LLM's judgment
	// and fall through to the normal agent loop. No session was created.
	if result.Rejected {
		log.Printf("[WorkflowInterception] understanding rejected task for user %s: %q - trusting LLM, no keyword override", userID, truncateRunes(text, 80))
		return nil
	}

	// First-round ready: IUM is confident enough to start the workflow
	// immediately without multi-round clarification. Proceed to confirmation
	// panel (same UX as the old UIC fast-accept path, but with IUM's deeper
	// semantic validation as the gatekeeper instead of UIC's single-round guess).
	if result.Ready && result.Intent != nil {
		// Guard: category="none" or empty with ready=true means not a workflow.
		if result.Intent.Category == v2.WorkflowNone || result.Intent.Category == "" {
			log.Printf("[WorkflowInterception] understanding returned ready=true with category=%q for user %s, falling through to agent loop",
				result.Intent.Category, userID)
			return nil
		}

		log.Printf("[WorkflowInterception] IUM first-round ready for user %s: category=%s conf=%.2f text_len=%d",
			userID, result.Intent.Category, result.Intent.Confidence, len([]rune(text)))

		if resp := h.confirmWorkflowStart(userID, text, *result.Intent, result.Reply); resp != nil {
			return resp
		}
		projectPath := h.workflowStartProjectPathForIntent(userID, text, *result.Intent)
		projectPath, prepErr := h.resolveWorkflowProjectPath(projectPath)
		if prepErr != nil {
			log.Printf("[WorkflowInterception] invalid workflow project path for user %s: %v", userID, prepErr)
			return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowPrepareProjectError, h.getWorkflowLang(), prepErr)}
		}
		state, err := engine.StartWorkflowWithOptions(userID, *result.Intent, v2.WorkflowStartOptions{ProjectPath: projectPath})
		if err != nil {
			log.Printf("[WorkflowInterception] IUM-driven StartWorkflow error for user %s: %v", userID, err)
			return &IMAgentResponse{Error: i18n.Tf(i18n.MsgWorkflowStartError, h.getWorkflowLang(), err)}
		}
		return h.handlePostStartWorkflow(engine, userID, text, state, result.Reply, platform)
	}

	// LLM says it IS a workflow task but needs clarification - an understanding
	// session has been created. The user will go through multi-round clarification
	// before the workflow actually starts.
	return &IMAgentResponse{Text: result.Reply}
}

func shouldSurfaceWorkflowUnderstandingStartError(uic *intent.UnifiedIntentClassifier, result *intent.ClassificationResult) bool {
	if uic == nil || result == nil {
		return false
	}
	if isConcreteWorkflowType(result.WorkflowType) {
		return result.Confidence >= 0.50
	}
	if result.Primary == intent.LabelUnknown || result.Primary == intent.LabelAmbiguous || result.Primary == intent.LabelContinuation {
		return false
	}
	if !uic.IsWorkflowCandidate(result.Primary) {
		return false
	}
	threshold := uic.GetWorkflowRejectThreshold()
	if threshold <= 0 {
		threshold = intent.DefaultWorkflowRejectThreshold
	}
	return result.Confidence >= threshold
}

// getUnifiedClassifier returns the UIC instance if available, or nil.
// Checks the direct field first (set at construction or by TUI), then
// falls back to h.app for GUI late-init compatibility.
func (h *IMMessageHandler) getUnifiedClassifier() *intent.UnifiedIntentClassifier {
	if h == nil {
		return nil
	}
	if h.unifiedClassifier != nil {
		return h.unifiedClassifier
	}
	if h.app == nil {
		return nil
	}
	return h.app.unifiedClassifier
}

// cancelWorkflowForUser cancels any active workflow and understanding session
// for the given user. Called from /new, /reset, /clear, and /cancel handlers.
func (h *IMMessageHandler) cancelWorkflowForUser(userID string) {
	// Always cancel workflow regardless of engine adapter state.
	h.cancelWorkflowV2(userID)
	// Clear any pending ask_user state.
	h.pendingAskUser.Delete(userID)
}

// applyWorkflowToolFilter restricts the tool list based on the current
// workflow phase's ToolFilterPolicy.
func (h *IMMessageHandler) applyWorkflowToolFilter(userID string, tools []map[string]interface{}) []map[string]interface{} {
	return h.applyWorkflowToolFilterWithCatalog(userID, tools, nil)
}

func (h *IMMessageHandler) applyWorkflowToolFilterWithCatalog(userID string, tools, allTools []map[string]interface{}) []map[string]interface{} {
	return h.applyWorkflowToolFilterWithCatalogV2Compat(userID, tools, allTools)
}

func (h *IMMessageHandler) applyWorkflowToolFilterWithCatalogV2Compat(userID string, tools, allTools []map[string]interface{}) []map[string]interface{} {
	policy := v2.ToolFilterNone
	if h != nil && h.isWorkflowV2Active(userID) {
		if wf := h.getWorkflowV2(); wf != nil {
			if state := wf.machine.GetActive(userID); state != nil {
				if phase := state.ActivePhase(); phase != nil {
					switch phase.ToolPolicy {
					case v2.ToolPolicyDocOnly:
						policy = v2.ToolFilterDocOnly
					}
				}
			}
		}
	}
	if policy == v2.ToolFilterNone && h != nil && h.app != nil {
		if wf := h.getWorkflowV2(); wf != nil && wf.machine != nil {
			if state := wf.machine.GetActive(userID); state != nil {
				if phase := state.ActivePhase(); phase != nil {
					policy = v2.ToolFilterPolicy(phase.ToolPolicy)
					if policy == v2.ToolFilterNone && phase.Status == v2.PhaseWaitingConfirm {
						return nil
					}
				}
			}
		}
	}
	if len(allTools) == 0 && h != nil {
		allTools = h.getTools()
	}
	if h != nil && h.isWorkflowArtifactPhase(userID) {
		tools = ensureWorkflowRequiredToolsForNames(workflowArtifactPhaseRequiredTools(), tools, allTools)
		return filterWorkflowArtifactPhaseTools(tools)
	}
	if policy == v2.ToolFilterNone || policy == v2.ToolFilterFull {
		if h != nil && h.shouldConstrainCodingWorkflowImplementationMainLoop(userID) {
			tools = ensureWorkflowRequiredToolsForNames(codingWorkflowImplementationMainLoopRequiredTools(), tools, allTools)
			tools = filterCodingWorkflowImplementationMainLoopTools(tools)
			return specializeCodingWorkflowImplementationMainLoopTools(tools)
		}
		if policy == v2.ToolFilterFull {
			return ensureWorkflowRequiredTools(policy, tools, allTools)
		}
		return tools
	}
	tools = ensureWorkflowRequiredTools(policy, tools, allTools)
	return v2.FilterToolDefinitions(policy, tools)
}

// getLastAssistantSnippet returns the tail of the last assistant message from
// conversation history, truncated to maxRunes from the END. We take the tail
// because assistant messages are often long documents followed by a short
// confirmation prompt at the end. The tail
// captures this prompt, which is the most relevant context for classifying
// the user's response.
func (h *IMMessageHandler) getLastAssistantSnippet(userID string, maxRunes int) string {
	if h.memory == nil {
		return ""
	}
	entries := h.memory.Load(userID)
	// Walk backwards to find the last assistant message.
	for i := len(entries) - 1; i >= 0; i-- {
		if entries[i].Role != "assistant" {
			continue
		}
		content, ok := entries[i].Content.(string)
		if !ok || content == "" {
			continue
		}
		runes := []rune(content)
		if len(runes) > maxRunes {
			// Take the tail - the confirmation prompt is at the end.
			return "..." + string(runes[len(runes)-maxRunes:])
		}
		return content
	}
	return ""
}
