package main

import (
	"fmt"
	"log"
	"strings"
	"time"

	"github.com/RapidAI/CodeClaw/corelib/agent"
)

// isInternalCommand returns true if the text is a structured command generated
// by UI buttons (workflow choice, execution confirmation, etc.). These commands
// have deterministic routing and must never be sent through LLM classification
// which can block on scheduler pauses.
func isInternalCommand(text string) bool {
	trimmed := strings.TrimSpace(text)
	for _, prefix := range internalCommandPrefixes {
		if strings.HasPrefix(trimmed, prefix) {
			return true
		}
	}
	return false
}

// internalCommandPrefixes lists all structured command prefixes generated by UI
// buttons. These bypass pending-reply LLM classification because their routing
// is deterministic (handled by handleCodingComplexityCommand,
// handlePendingExecutionConfirmation, or applyExplicitTaskSlotAction).
var internalCommandPrefixes = []string{
	"__workflow_choice__ ",
	"__confirm_execution__ ",
	"__cancel_execution__ ",
	"__resume_unfinished__ ",
	"__dismiss_unfinished__ ",
	"__start_new_task__",
}

func shouldResumeIncompleteTask(text string) bool {
	lower := strings.ToLower(strings.TrimSpace(text))
	if lower == "" {
		return false
	}

	resumePhrases := []string{
		"继续", "继续上次", "继续做完", "恢复", "接着做",
		"继续", "继续完成", "继续上次", "接着完成", "接着上次", "恢复上次", "做完上次",
		"continue", "continue it", "continue this", "resume", "resume it", "resume this", "pick up where you left off",
	}
	for _, phrase := range resumePhrases {
		if strings.Contains(lower, phrase) {
			return true
		}
	}
	return false
}

func looksLikeFreshTaskRequest(text string) bool {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" || shouldResumeIncompleteTask(trimmed) {
		return false
	}
	if countWords(trimmed) < 4 {
		return false
	}
	lower := strings.ToLower(trimmed)
	freshTaskHints := []string{
		"帮我", "现在", "移动", "复制", "写", "生成", "总结", "分析", "搜索", "导入", "放入",
		"甯垜", "璇蜂綘", "鏁寸悊", "鍒嗘瀽", "鎼滅储", "鐢熸垚", "绉诲姩", "澶嶅埗", "鏀惧叆", "瀵煎叆",
		"please", "help me", "can you", "now", "move", "copy", "write", "generate", "summarize", "analyze", "search", "import",
	}
	for _, hint := range freshTaskHints {
		if strings.Contains(lower, hint) {
			return true
		}
	}
	return false
}

func shouldClearHistoryForIncompleteTask(text string) bool {
	trimmed := strings.TrimSpace(text)
	if trimmed == "" {
		return false
	}
	if shouldResumeIncompleteTask(trimmed) {
		return false
	}
	if looksLikeFreshTaskRequest(trimmed) {
		return true
	}
	if countWords(trimmed) < 4 {
		return false
	}
	return true
}

// pendingReplyTTL bounds how long a pending user reply can claim the next
// message as an answer to the same task.
const pendingReplyTTL = 30 * time.Minute

// pendingAskUserState tracks an ask_user question that is waiting for the
// user's response. Stored in IMMessageHandler.pendingAskUser keyed by userID.
type pendingAskUserState struct {
	Question     string
	Options      []string
	InputType    string
	Context      string
	History      []agent.ConversationEntry
	Timestamp    time.Time
	WorkingState *agent.WorkingState
}

// pendingRecordAudioState tracks an interactive recording session waiting for
// the user to stop. Stored in IMMessageHandler.pendingRecordAudio keyed by userID.
type pendingRecordAudioState struct {
	Title        string
	Purpose      string
	History      []agent.ConversationEntry
	Timestamp    time.Time
	WorkingState *agent.WorkingState
}

// pendingUserReplyState binds a plain-text assistant question to the
// conversation snapshot that produced it. It covers normal prose follow-ups
// such as "which model should I deploy?" that do not use the ask_user tool.
type pendingUserReplyState struct {
	Question  string
	History   []agent.ConversationEntry
	Timestamp time.Time
}

func cloneConversationEntries(entries []agent.ConversationEntry) []agent.ConversationEntry {
	if len(entries) == 0 {
		return nil
	}
	clone := make([]agent.ConversationEntry, len(entries))
	copy(clone, entries)
	return clone
}

func latestAssistantText(entries []agent.ConversationEntry) string {
	for i := len(entries) - 1; i >= 0; i-- {
		if entries[i].Role != "assistant" {
			continue
		}
		if text, ok := entries[i].Content.(string); ok {
			return strings.TrimSpace(text)
		}
	}
	return ""
}

func conversationEntryTextEqual(a, b agent.ConversationEntry) bool {
	if a.Role != b.Role {
		return false
	}
	textA, okA := a.Content.(string)
	textB, okB := b.Content.(string)
	return okA && okB && strings.TrimSpace(textA) == strings.TrimSpace(textB)
}

func conversationHistoryEqual(a, b []agent.ConversationEntry) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if !conversationEntryTextEqual(a[i], b[i]) {
			return false
		}
	}
	return true
}

func conversationHistoryHasPrefix(current, prefix []agent.ConversationEntry) bool {
	if len(prefix) == 0 || len(current) < len(prefix) {
		return false
	}
	for i := range prefix {
		if !conversationEntryTextEqual(current[i], prefix[i]) {
			return false
		}
	}
	return true
}

func conversationExtensionHasUserMessage(current []agent.ConversationEntry, prefixLen int) bool {
	if prefixLen < 0 || prefixLen > len(current) {
		return true
	}
	for _, entry := range current[prefixLen:] {
		if entry.Role == "user" {
			return true
		}
	}
	return false
}

func formatPendingReplyHistoryExtension(current, prefix []agent.ConversationEntry) string {
	if len(prefix) == 0 || !conversationHistoryHasPrefix(current, prefix) || len(current) <= len(prefix) {
		return ""
	}
	var b strings.Builder
	for _, entry := range current[len(prefix):] {
		if entry.Role == "user" {
			continue
		}
		text, ok := entry.Content.(string)
		text = strings.TrimSpace(text)
		if !ok || text == "" {
			continue
		}
		if b.Len() == 0 {
			b.WriteString("\nCurrent task context added after that question:\n")
		}
		b.WriteString(entry.Role)
		b.WriteString(": ")
		b.WriteString(truncateRunes(text, 500))
		b.WriteString("\n")
	}
	return strings.TrimRight(b.String(), "\n")
}

func isPendingReplyBoundToCurrentHistory(pending []agent.ConversationEntry, current []agent.ConversationEntry, question string) bool {
	if len(pending) == 0 {
		return pendingQuestionIsAwaitingAnswer(question, current)
	}
	if len(current) == 0 {
		return true
	}
	if conversationHistoryHasPrefix(current, pending) {
		return !conversationExtensionHasUserMessage(current, len(pending))
	}
	return pendingQuestionIsAwaitingAnswer(question, current)
}

func pendingUserReplyForCurrentHistory(raw interface{}, current []agent.ConversationEntry) (*pendingUserReplyState, bool) {
	pending, ok := raw.(*pendingUserReplyState)
	if !ok || pending == nil || time.Since(pending.Timestamp) >= pendingReplyTTL {
		return nil, false
	}
	return pending, isPendingReplyBoundToCurrentHistory(pending.History, current, pending.Question)
}

func pendingAskUserForCurrentHistory(raw interface{}, current []agent.ConversationEntry) (*pendingAskUserState, bool) {
	pending, ok := raw.(*pendingAskUserState)
	if !ok || pending == nil || time.Since(pending.Timestamp) >= pendingReplyTTL {
		return nil, false
	}
	return pending, isPendingReplyBoundToCurrentHistory(pending.History, current, pending.Question)
}

func pendingQuestionIsAwaitingAnswer(question string, current []agent.ConversationEntry) bool {
	question = strings.TrimSpace(question)
	if question == "" || len(current) == 0 {
		return false
	}
	for i := len(current) - 1; i >= 0; i-- {
		entry := current[i]
		if entry.Role == "user" {
			return false
		}
		if entry.Role != "assistant" {
			continue
		}
		text, ok := entry.Content.(string)
		if !ok {
			continue
		}
		if pendingQuestionMatchesAssistant(question, text) {
			return true
		}
	}
	return false
}

func pendingQuestionMatchesAssistant(question, assistantText string) bool {
	q := strings.TrimSpace(question)
	a := strings.TrimSpace(assistantText)
	if q == "" || a == "" {
		return false
	}
	if q == a {
		return true
	}
	if len([]rune(q)) < 16 {
		return false
	}
	return strings.Contains(a, q)
}

func (h *IMMessageHandler) bindPendingUserReplyAnswer(msg IMUserMessage, trimmed string, entries *[]agent.ConversationEntry, unfinishedSlot **agent.UnfinishedTaskSlot) (string, bool) {
	if h == nil || msg.IsBackground || entries == nil || unfinishedSlot == nil {
		return "", false
	}
	// Structured internal commands (button clicks) are never "answers" to pending
	// questions — they are deterministic routing signals. Consume and discard
	// any pending reply state to avoid blocking on LLM classification (which uses
	// background scheduler priority and can be paused indefinitely after 503 errors).
	if isInternalCommand(trimmed) {
		if _, hadPending := h.pendingUserReply.LoadAndDelete(msg.UserID); hadPending {
			log.Printf("[PendingUserReply] discarded by internal command for user=%s cmd_len=%d", msg.UserID, len(trimmed))
		}
		return "", false
	}
	raw, ok := h.pendingUserReply.LoadAndDelete(msg.UserID)
	if !ok {
		return "", false
	}
	pending, pendingFresh := pendingUserReplyForCurrentHistory(raw, *entries)
	if !pendingFresh && pending != nil {
		log.Printf("[PendingUserReply] discarded stale pending reply for user=%s currentLen=%d boundLen=%d answer_len=%d", msg.UserID, len(*entries), len(pending.History), len([]rune(trimmed)))
		if len(pending.History) > 0 && conversationHistoryHasPrefix(*entries, pending.History) && conversationExtensionHasUserMessage(*entries, len(pending.History)) {
			currentTaskEntries := cloneConversationEntries((*entries)[len(pending.History):])
			// ConversationMemory.Save merges linear entries into the existing
			// branch tree, which would keep the stale bound prefix reachable.
			// Clear first so the active branch is exactly the current task.
			h.memory.Clear(msg.UserID)
			h.memory.Save(msg.UserID, currentTaskEntries)
			*entries = currentTaskEntries
			*unfinishedSlot = h.memory.GetUnfinishedSlot(msg.UserID)
			log.Printf("[PendingUserReply] removed stale bound prefix for user=%s restoredLen=%d answer_len=%d", msg.UserID, len(currentTaskEntries), len([]rune(trimmed)))
		}
	}
	isPendingAnswer, classifiedPendingAnswer := false, true
	if pendingFresh {
		isPendingAnswer, classifiedPendingAnswer = h.classifyPendingUserReplyAnswer(msg.UserID, pending.Question, trimmed)
		if !classifiedPendingAnswer && strings.TrimSpace(trimmed) != "" {
			// The auxiliary answer classifier is unavailable (hub timeout,
			// scheduler pause). Degrade to continuity, not amnesia: a fresh
			// pending question bound to the current history makes the next
			// user message overwhelmingly likely its answer. A genuine task
			// switch is still arbitrated downstream — the turn's own bare
			// classification wins whenever it is managed and confident.
			// (2026-08-27: the old fail-open-to-new-task path let a 16-rune
			// answer classify standalone as coding@0.80; the PPT task died
			// on the coding surface.)
			log.Printf("[PendingUserReply] answer intent unclassified; binding by fresh pending question for user=%s answer_len=%d", msg.UserID, len([]rune(trimmed)))
			isPendingAnswer = true
		}
	}
	if pendingFresh && isPendingAnswer {
		if len(pending.History) > 0 {
			current := h.memory.Load(msg.UserID)
			if len(current) == 0 {
				restored := cloneConversationEntries(pending.History)
				h.memory.Save(msg.UserID, restored)
				*entries = restored
				*unfinishedSlot = h.memory.GetUnfinishedSlot(msg.UserID)
				log.Printf("[PendingUserReply] restored bound question context for user=%s currentLen=%d restoredLen=%d answer_len=%d", msg.UserID, len(current), len(restored), len([]rune(trimmed)))
			}
		}
		extension := formatPendingReplyHistoryExtension(*entries, pending.History)
		context := fmt.Sprintf("[Context hint] The user is answering the assistant question from the current task, not starting or resuming another task.\nAssistant question: %s\nUser answer: %s%s", pending.Question, trimmed, extension)
		return context, true
	}
	if pendingFresh && strings.TrimSpace(trimmed) == "" {
		// Only an empty message keeps the pending question parked for the next
		// one. An unclassified non-empty reply has already been bound above.
		h.pendingUserReply.Store(msg.UserID, pending)
		h.suppressPendingUserReplyUpdate.Store(msg.UserID, true)
	}
	return "", false
}

func (h *IMMessageHandler) consumePendingAskUserAnswer(userID, trimmed string, entries []agent.ConversationEntry) (string, *agent.WorkingState, bool) {
	if h == nil {
		return "", nil, false
	}
	raw, ok := h.pendingAskUser.LoadAndDelete(userID)
	if !ok {
		return "", nil, false
	}
	pending, pendingFresh := pendingAskUserForCurrentHistory(raw, entries)
	if !pendingFresh && pending != nil {
		log.Printf("[AskUser] discarded stale pending ask_user for user %s, currentLen=%d boundLen=%d answer_len=%d", userID, len(entries), len(pending.History), len([]rune(trimmed)))
	}
	if !pendingFresh {
		return "", nil, false
	}
	context := agent.FormatPendingAskUserAnswerHint(pending.Question, trimmed, pending.Context)
	log.Printf("[AskUser] consumed pending ask_user for user %s, question_len=%d answer_len=%d", userID, len([]rune(pending.Question)), len([]rune(trimmed)))
	ws := agent.CloneWorkingState(pending.WorkingState)
	agent.AdvanceWorkingStateAfterUserReply(ws)
	return context, ws, true
}

func pendingRecordAudioForCurrentHistory(raw interface{}, entries []agent.ConversationEntry) (*pendingRecordAudioState, bool) {
	pending, ok := raw.(*pendingRecordAudioState)
	if !ok || pending == nil || time.Since(pending.Timestamp) >= pendingReplyTTL {
		return nil, false
	}
	return pending, isPendingReplyBoundToCurrentHistory(pending.History, entries, pending.Title)
}

// hasActivePendingRecordAudio reports whether the user still has a live
// interactive recording session waiting for a structured stop/save report.
func (h *IMMessageHandler) hasActivePendingRecordAudio(userID string, entries []agent.ConversationEntry) bool {
	if h == nil {
		return false
	}
	raw, ok := h.pendingRecordAudio.Load(userID)
	if !ok {
		return false
	}
	_, fresh := pendingRecordAudioForCurrentHistory(raw, entries)
	return fresh
}

func (h *IMMessageHandler) consumePendingRecordAudioAnswer(userID, trimmed string, entries []agent.ConversationEntry) (string, *agent.WorkingState, bool) {
	if h == nil {
		return "", nil, false
	}
	// Peek first — casual chat while the mic UI is open must NOT clear pending.
	raw, ok := h.pendingRecordAudio.Load(userID)
	if !ok {
		return "", nil, false
	}
	pending, pendingFresh := pendingRecordAudioForCurrentHistory(raw, entries)
	if !pendingFresh {
		// Stale binding / TTL: drop so it cannot block forever.
		h.pendingRecordAudio.Delete(userID)
		if pending != nil && recordDetailEnabled() {
			log.Printf("[record-audio] discarded stale pending recording user=%s currentLen=%d boundLen=%d answer_len=%d title=%q age=%s",
				userID, len(entries), len(pending.History), len([]rune(trimmed)), pending.Title, time.Since(pending.Timestamp).Round(time.Second))
		}
		return "", nil, false
	}
	if !isRecordAudioCompletionReport(trimmed) {
		if recordDetailEnabled() {
			log.Printf("[record-audio] keep pending (non-completion message) user=%s title=%q answer_len=%d",
				userID, pending.Title, len([]rune(trimmed)))
		}
		return "", nil, false
	}
	h.pendingRecordAudio.Delete(userID)

	// Desktop successful saves are usually short-circuited by offerPostRecordingChoice.
	// This fallback context covers cancelled/error/missing-path and non-desktop paths.
	context := fmt.Sprintf(
		"[Context hint] The user finished an interactive recording session started via record_audio, not a new request.\nRecording title: %s\nUser report: %s\n"+
			"On desktop, a successful save with a path is normally handled by engine-injected choice buttons (do not re-ask with plain 1/2/3 text). "+
			"If you still need to handle this report directly (cancelled/error/missing path, or non-desktop fallback): "+
			"for cancelled/error/missing path, acknowledge and do not invent a transcript; "+
			"if a path is present and the user wants minutes, produce BOTH markdown (write_file .md) and PDF (generate_pdf) with a mandatory full-transcript section of the original audio ASR text; deliver MP3 archive (prefer mp3_path from the report, else bash+ffmpeg) and send_file mp3+md (ensure PDF is delivered); "+
			"for transcribe-only, produce BOTH markdown and PDF of the full ASR transcript (not minutes structure) plus deliver MP3 (prefer mp3_path); "+
			"for keep-only, still deliver MP3 (prefer mp3_path).",
		pending.Title, trimmed,
	)
	if recordDetailEnabled() {
		pathHint := extractRecordedPathFromReport(trimmed)
		statusHint := extractRecordingFieldFromReport(trimmed, "status")
		durationHint := extractRecordingFieldFromReport(trimmed, "duration_sec")
		log.Printf("[record-audio] consumed pending recording user=%s title=%q purpose=%q status=%q path=%q duration=%q answer_len=%d session_age=%s",
			userID, pending.Title, pending.Purpose, statusHint, pathHint, durationHint, len([]rune(trimmed)), time.Since(pending.Timestamp).Round(time.Millisecond))
	}
	// Do not advance here: a successful save usually offers post-recording
	// buttons, and that is still a user pause. The LLM fallback path advances.
	return context, agent.CloneWorkingState(pending.WorkingState), true
}

// isRecordAudioCompletionReport reports whether the user message is the structured
// stop/save payload from the desktop recording card, as opposed to casual chat.
func isRecordAudioCompletionReport(trimmed string) bool {
	t := strings.TrimSpace(trimmed)
	if t == "" {
		return false
	}
	// Canonical payload from RecordingSessionCard / formatRecordingCompletionMessage.
	if strings.Contains(t, "[Recording completed]") {
		return true
	}
	// Fallback: status plus at least one other structured field (path/error/title/duration).
	// Bare "status: stopped" alone is too easy to false-positive in normal chat.
	status := strings.ToLower(extractRecordingFieldFromReport(t, "status"))
	switch status {
	case "stopped", "cancelled", "canceled", "error":
		if extractRecordingFieldFromReport(t, "path") != "" ||
			extractRecordingFieldFromReport(t, "error") != "" ||
			extractRecordingFieldFromReport(t, "title") != "" ||
			extractRecordingFieldFromReport(t, "duration_sec") != "" {
			return true
		}
	}
	return false
}

func extractRecordedPathFromReport(report string) string {
	return extractRecordingFieldFromReport(report, "path")
}

func extractRecordingFieldFromReport(report, key string) string {
	key = strings.ToLower(strings.TrimSpace(key))
	if key == "" || report == "" {
		return ""
	}
	for _, line := range strings.Split(report, "\n") {
		line = strings.TrimSpace(line)
		if line == "" {
			continue
		}
		// Split on first ':' so values may contain colons (Windows paths).
		idx := strings.IndexByte(line, ':')
		if idx <= 0 {
			continue
		}
		field := strings.ToLower(strings.TrimSpace(line[:idx]))
		if field != key {
			continue
		}
		return strings.TrimSpace(line[idx+1:])
	}
	return ""
}
