package knowledge

import "time"

func Capabilities() KnowledgeCapabilities {
	docLegacyStatus := "supported_native"
	docLegacyNotes := "Uses the built-in pure-Go DOC reader as the knowledge-import fallback; explicit OfficeRead rich-content opt-in can instead persist structured Markdown. Full paragraph/heading/header/footer extraction."
	xlsLegacyStatus := "supported_native"
	xlsLegacyNotes := "Uses the built-in pure-Go BIFF reader as the knowledge-import fallback for structured sheet/row/cell extraction; explicit OfficeRead rich-content opt-in additionally persists structured Markdown and managed images."
	return KnowledgeCapabilities{
		DefaultIncludeExts: append([]string(nil), DefaultIncludeExts...),
		DefaultAutoLabels:  true,
		AutoLabelRules:     []string{"kind:*", "scope:*", "domain:*", "folder:*"},
		QueryRequiresLLM:   false,
		WriteLLMOptional:   true,
		DistillModes:       []string{DistillModeAuto, DistillModeRules, DistillModeLLMIfAny},
		CoverageFilters:    coverageFilters(),
		CoverageAliases:    coverageAliases(),
		LocalIndexes:       []string{"cards_fts", "facts_fts", "document_nodes_fts", "search_facets", "fact_graph", "fact_index_entities", "fact_index_predicates", "entity_profile"},
		StorageBackend:     "sqlite",
		SearchBackend:      "sqlite_fts5_cards_facts_nodes",
		ImageRetrieval: ImageRetrievalCapabilities{
			TextToImage:        true,
			ImageToImage:       false,
			SearchEndpoint:     "/api/v1/knowledge/images/search",
			AgentTool:          "knowledge_image_search",
			IndexEvidence:      []string{"ocr", "vision_caption", "filename", "document_context"},
			Ranking:            "hybrid_text_ocr_caption",
			ImageToImageReason: "requires a configured shared multimodal image/text embedding model; the built-in embedding model is text-only",
		},
		GeneratedAt: time.Now().UTC(),
		Formats: []FormatCapability{
			{
				Kind:          SourceKindURL,
				Extensions:    []string{"http", "https"},
				Parser:        "public_http_fetch_text",
				SearchUnit:    "document_nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: false,
				Notes:         "Public HTTP(S) only; private, localhost, and unsafe redirects are blocked.",
			},
			{
				Kind:          SourceKindMarkdown,
				Extensions:    []string{".md", ".markdown"},
				Parser:        "markdown_heading_sections",
				SearchUnit:    "section nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
			},
			{
				Kind:          SourceKindText,
				Extensions:    []string{".txt", ".text"},
				Parser:        "paragraph_chunks",
				SearchUnit:    "paragraph nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
			},
			{
				Kind:          SourceKindDOCX,
				Extensions:    []string{".docx"},
				Parser:        "docx_native_or_officeread_structured_markdown_opt_in",
				SearchUnit:    "paragraph nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
				Notes:         "Uses native DOCX paragraph nodes by default; explicit OfficeRead rich-content opt-in persists structured Markdown and managed images. Native embedded images from word/media/ are processed via OCR/Vision.",
			},
			{
				Kind:          SourceKindPDF,
				Extensions:    []string{".pdf"},
				Parser:        "pdf_inspector_native_text_or_local_ocr",
				SearchUnit:    "page/paragraph nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
				Notes:         "Pure-Go inspection routes native-text pages to local extraction and scanned/mixed pages to the built-in local OCR engine. Decodable embedded images are extracted in-process through GoPDF2.",
			},
			{
				Kind:          SourceKindPPT,
				Extensions:    []string{".ppt"},
				Parser:        "officeread_structured_markdown_opt_in",
				SearchUnit:    "markdown section nodes/cards/facts",
				Status:        "staged_opt_in",
				Refreshable:   true,
				DefaultImport: true,
				Notes:         "Knowledge import has no native PPT parser. It requires OfficeRead rich-content opt-in; otherwise the source remains pending. Chat/read_document can still use the configured plain-text OfficeRead route.",
			},
			{
				Kind:          SourceKindPPTX,
				Extensions:    []string{".pptx"},
				Parser:        "pptx_native_or_officeread_structured_markdown_opt_in",
				SearchUnit:    "slide paragraph nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
				Notes:         "Uses native slide text, tables, and notes by default; explicit OfficeRead rich-content opt-in persists structured Markdown and managed images. Native embedded images from ppt/media/ are processed via OCR/Vision.",
			},
			{
				Kind:          SourceKindXLSX,
				Extensions:    []string{".xlsx"},
				Parser:        "xlsx_native_or_officeread_structured_markdown_opt_in",
				SearchUnit:    "sheet row-range nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
			},
			{
				Kind:          SourceKindCSV,
				Extensions:    []string{".csv"},
				Parser:        "csv_row_blocks",
				SearchUnit:    "row-range nodes/cards/facts",
				Status:        "supported",
				Refreshable:   true,
				DefaultImport: true,
			},
			{
				Kind:          SourceKindDOC,
				Extensions:    []string{".doc"},
				Parser:        "doc_native_or_officeread_structured_markdown_opt_in",
				SearchUnit:    "paragraph nodes/cards/facts",
				Status:        docLegacyStatus,
				Refreshable:   true,
				DefaultImport: true,
				Notes:         docLegacyNotes,
			},
			{
				Kind:          SourceKindXLS,
				Extensions:    []string{".xls"},
				Parser:        "xls_native_or_officeread_structured_markdown_opt_in",
				SearchUnit:    "sheet row-range nodes/cards/facts",
				Status:        xlsLegacyStatus,
				Refreshable:   true,
				DefaultImport: true,
				Notes:         xlsLegacyNotes,
			},
			{
				Kind:          SourceKindConversation,
				Parser:        "explicit_text_save",
				SearchUnit:    "paragraph nodes/cards/facts",
				Status:        "supported",
				Refreshable:   false,
				DefaultImport: false,
				Notes:         "Only saved when the user explicitly asks to remember or add text knowledge.",
			},
			{
				Kind:          SourceKindWorkflowArtifact,
				Parser:        "explicit_text_save",
				SearchUnit:    "paragraph nodes/cards/facts",
				Status:        "supported",
				Refreshable:   false,
				DefaultImport: false,
			},
			{
				Kind:          SourceKindImage,
				Extensions:    []string{".png", ".jpg", ".jpeg", ".gif", ".webp", ".bmp"},
				Parser:        "image_asset_ocr_vision",
				SearchUnit:    "image nodes/cards/facts",
				Status:        "supported",
				Refreshable:   false,
				DefaultImport: false,
				Notes:         "Image files are imported when --include-images is enabled. Description via Vision LLM (if configured) or built-in OCR + context inference.",
			},
		},
	}
}
