package knowledge

import (
	"bytes"
	"errors"
	"fmt"
	"image"
	"image/jpeg"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	_ "image/gif"
	_ "image/png"

	_ "golang.org/x/image/bmp"
	"golang.org/x/image/draw"
	_ "golang.org/x/image/webp"
)

const (
	// ThumbSize is the max edge length for list thumbnails.
	ThumbSize = 120
	// PreviewWidth is the max edge length for detail preview images. Keeping
	// both dimensions bounded prevents a narrow-but-very-tall source image from
	// creating an unexpectedly large preview raster.
	PreviewWidth = 480
	// MaxKnowledgeImageThumbnailBytes and MaxKnowledgeImagePreviewBytes bound
	// derived JPEG files before presentation layers inspect or serve them. They
	// protect against a locally corrupted asset cache being advertised as a
	// small generated image.
	MaxKnowledgeImageThumbnailBytes int64 = 256 * 1024
	MaxKnowledgeImagePreviewBytes   int64 = 2 * 1024 * 1024
	// MaxKnowledgeImageAssetBytes is the largest original image accepted by the
	// managed knowledge asset store. Every ingestion path (standalone files,
	// Office documents and PDFs) goes through this boundary.
	MaxKnowledgeImageAssetBytes int64 = 20 * 1024 * 1024
	// MaxKnowledgeImageAssetPixels bounds decoded image area before decoding or
	// resizing so compressed image bombs cannot cause unbounded allocations.
	MaxKnowledgeImageAssetPixels int64 = 40 * 1024 * 1024

	imageAssetsSubdir = "knowledge_assets"
)

var errKnowledgeImageAssetTooLarge = errors.New("knowledge image asset exceeds size limit")

// Image asset IDs are opaque identifiers generated by the knowledge store.
// Keep the grammar deliberately narrow because an asset ID is also used as a
// directory name by every desktop and HTTP consumer.
var safeImageAssetIDPattern = regexp.MustCompile(`^[A-Za-z0-9_-]{1,200}$`)

// IsSafeImageAssetID reports whether value can safely identify a managed
// knowledge image asset. Callers that receive an ID across a model, HTTP, or
// WebView boundary must validate it before looking up an asset.
func IsSafeImageAssetID(value string) bool {
	// Asset IDs cross model, HTTP, and WebView boundaries. Do not normalize
	// them during validation: accepting surrounding whitespace here while some
	// callers later use the original value would make one external token name a
	// different on-disk asset. Each presentation boundary must either reject the
	// token or explicitly canonicalize it before both validation and lookup.
	return safeImageAssetIDPattern.MatchString(value)
}

func imageAssetTooLargeError(size int64) error {
	return fmt.Errorf("%w (%d bytes)", errKnowledgeImageAssetTooLarge, size)
}

// ImageAsset holds paths and metadata for a stored image asset.
type ImageAsset struct {
	OriginalPath string // absolute path to original image
	ThumbPath    string // absolute path to 120px thumbnail
	PreviewPath  string // absolute path to 480px preview
	Width        int    // original image width in pixels
	Height       int    // original image height in pixels
	Format       string // detected format: "png", "jpeg", "gif", "bmp", "webp"
	SizeBytes    int64  // original file size
}

// ImageAssetManager manages image asset storage and lifecycle.
type ImageAssetManager struct {
	baseDir string // ~/.maclaw/knowledge_assets/
}

// NewImageAssetManager creates a manager rooted at the given base directory.
// The directory is created if it does not exist.
func NewImageAssetManager(maclawDataDir string) (*ImageAssetManager, error) {
	baseDir := filepath.Join(maclawDataDir, imageAssetsSubdir)
	if err := os.MkdirAll(baseDir, 0o755); err != nil {
		return nil, fmt.Errorf("knowledge image_assets: create base dir: %w", err)
	}
	return &ImageAssetManager{baseDir: baseDir}, nil
}

// BaseDir returns the absolute base directory for image assets.
func (m *ImageAssetManager) BaseDir() string {
	return m.baseDir
}

// SaveImageFromPath saves an image file and generates thumbnails.
// sourceID is used as the subdirectory name.
// Returns the asset metadata or an error.
func (m *ImageAssetManager) SaveImageFromPath(sourceID, imagePath string) (*ImageAsset, error) {
	f, err := os.Open(imagePath)
	if err != nil {
		return nil, fmt.Errorf("open image: %w", err)
	}
	defer f.Close()

	info, err := f.Stat()
	if err != nil {
		return nil, fmt.Errorf("stat image: %w", err)
	}
	if info.Size() > MaxKnowledgeImageAssetBytes {
		return nil, imageAssetTooLargeError(info.Size())
	}

	return m.saveImageFromReader(sourceID, f, filepath.Ext(imagePath), info.Size())
}

// SaveImageFromBytes saves raw image bytes and generates thumbnails.
// ext should include the dot (e.g. ".png", ".jpg").
func (m *ImageAssetManager) SaveImageFromBytes(sourceID string, data []byte, ext string) (*ImageAsset, error) {
	if int64(len(data)) > MaxKnowledgeImageAssetBytes {
		return nil, imageAssetTooLargeError(int64(len(data)))
	}
	r := &bytesReader{data: data}
	return m.saveImageFromReader(sourceID, r, ext, int64(len(data)))
}

// DeleteAssets removes the standalone image asset directory for an exact asset
// ID. It intentionally does not remove embedded-image assets, whose IDs are
// derived from the owning source ID with an underscore suffix.
// Returns nil if sourceID is invalid or directory doesn't exist.
func (m *ImageAssetManager) DeleteAssets(sourceID string) error {
	dir := m.AssetDir(sourceID)
	if dir == "" {
		return nil // invalid sourceID, nothing to delete
	}
	if err := os.RemoveAll(dir); err != nil {
		return err
	}
	return os.RemoveAll(imageAssetBackupDir(dir))
}

// DeleteAssetsForSource removes a source's standalone asset plus the exact
// embedded asset IDs recorded for that source. Embedded assets are deliberately
// supplied by the database caller rather than discovered by directory prefix:
// another valid source ID could otherwise happen to begin with sourceID+"_".
func (m *ImageAssetManager) DeleteAssetsForSource(sourceID string, embeddedAssetIDs ...string) error {
	if m == nil || m.AssetDir(sourceID) == "" {
		return nil
	}
	ids := append([]string{sourceID}, embeddedAssetIDs...)
	seen := make(map[string]struct{}, len(ids))
	prefix := sourceID + "_"
	for _, assetID := range ids {
		if !IsSafeImageAssetID(assetID) || (assetID != sourceID && !strings.HasPrefix(assetID, prefix)) {
			continue
		}
		if _, ok := seen[assetID]; ok {
			continue
		}
		seen[assetID] = struct{}{}
		dir := m.AssetDir(assetID)
		if dir == "" {
			continue
		}
		if err := os.RemoveAll(dir); err != nil {
			return err
		}
		if err := os.RemoveAll(imageAssetBackupDir(dir)); err != nil {
			return err
		}
	}
	return nil
}

// AssetDir returns the absolute directory path for a source's assets.
// Returns empty string if sourceID contains path traversal characters.
func (m *ImageAssetManager) AssetDir(sourceID string) string {
	if !IsSafeImageAssetID(sourceID) {
		return ""
	}
	return filepath.Join(m.baseDir, sourceID)
}

// OriginalPath returns the expected original image path for a source.
func (m *ImageAssetManager) OriginalPath(sourceID, ext string) string {
	dir := m.AssetDir(sourceID)
	if dir == "" {
		return ""
	}
	return filepath.Join(dir, "original"+ext)
}

// OriginalImage resolves the retained original only when it is a bounded,
// decodable raster image. Asset directories can contain original-only vector
// resources extracted from Office documents; those must not be passed to a
// browser or system viewer through an image-display API.
func (m *ImageAssetManager) OriginalImage(assetID string) (string, string, error) {
	dir, err := m.managedAssetDir(assetID)
	if err != nil {
		return "", "", err
	}
	root, err := os.OpenRoot(dir)
	if err != nil {
		return "", "", err
	}
	defer root.Close()
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", "", err
	}
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() || !isOriginalRasterImageName(entry.Name()) {
			continue
		}
		info, err := root.Lstat(entry.Name())
		if err != nil || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > MaxKnowledgeImageAssetBytes {
			continue
		}
		file, err := root.Open(entry.Name())
		if err != nil {
			continue
		}
		opened, statErr := file.Stat()
		if statErr != nil || !opened.Mode().IsRegular() || opened.Size() != info.Size() {
			_ = file.Close()
			continue
		}
		config, format, decodeErr := image.DecodeConfig(file)
		closeErr := file.Close()
		if decodeErr != nil || closeErr != nil || !isSupportedImageFormat(format) || config.Width <= 0 || config.Height <= 0 || int64(config.Width) > MaxKnowledgeImageAssetPixels/int64(config.Height) {
			continue
		}
		return filepath.Join(dir, entry.Name()), format, nil
	}
	return "", "", os.ErrNotExist
}

// OriginalImagePath is the path-only convenience form of OriginalImage.
func (m *ImageAssetManager) OriginalImagePath(assetID string) (string, error) {
	path, _, err := m.OriginalImage(assetID)
	return path, err
}

// DerivedImage resolves a generated thumbnail or preview only when it remains
// within the managed JPEG contract. Consumers use this rather than serving a
// predictable cache filename directly, because derived files can outlive a
// failed write or be externally corrupted on a shared local data volume.
func (m *ImageAssetManager) DerivedImage(assetID, variant string) (string, error) {
	var name string
	var maxEdge int
	var maxBytes int64
	switch strings.ToLower(strings.TrimSpace(variant)) {
	case "thumbnail":
		name = "thumb_120.jpg"
		maxEdge = ThumbSize
		maxBytes = MaxKnowledgeImageThumbnailBytes
	case "preview":
		name = "preview_480.jpg"
		maxEdge = PreviewWidth
		maxBytes = MaxKnowledgeImagePreviewBytes
	default:
		return "", fmt.Errorf("invalid image variant")
	}
	dir, err := m.managedAssetDir(assetID)
	if err != nil {
		return "", err
	}
	root, err := os.OpenRoot(dir)
	if err != nil {
		return "", err
	}
	defer root.Close()
	path := filepath.Join(dir, name)
	info, err := root.Lstat(name)
	if err != nil || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxBytes {
		return "", os.ErrNotExist
	}
	file, err := root.Open(name)
	if err != nil {
		return "", err
	}
	opened, statErr := file.Stat()
	if statErr != nil || !opened.Mode().IsRegular() || opened.Size() != info.Size() {
		_ = file.Close()
		return "", os.ErrNotExist
	}
	config, format, decodeErr := image.DecodeConfig(file)
	closeErr := file.Close()
	if decodeErr != nil || closeErr != nil || format != "jpeg" || config.Width <= 0 || config.Height <= 0 || config.Width > maxEdge || config.Height > maxEdge {
		return "", os.ErrNotExist
	}
	return path, nil
}

// ThumbPath returns the expected thumbnail path for a source.
func (m *ImageAssetManager) ThumbPath(sourceID string) string {
	dir := m.AssetDir(sourceID)
	if dir == "" {
		return ""
	}
	return filepath.Join(dir, "thumb_120.jpg")
}

// PreviewPath returns the expected preview path for a source.
func (m *ImageAssetManager) PreviewPath(sourceID string) string {
	dir := m.AssetDir(sourceID)
	if dir == "" {
		return ""
	}
	return filepath.Join(dir, "preview_480.jpg")
}

// HasAssets checks if the source has any image assets stored.
func (m *ImageAssetManager) HasAssets(sourceID string) bool {
	dir, err := m.managedAssetDir(sourceID)
	if err != nil {
		return false
	}
	info, err := os.Lstat(dir)
	return err == nil && info.IsDir() && info.Mode()&os.ModeSymlink == 0
}

// RegenerateThumb regenerates a missing thumbnail from the original image.
func (m *ImageAssetManager) RegenerateThumb(sourceID string) error {
	dir, err := m.managedAssetDir(sourceID)
	if err != nil {
		return err
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return fmt.Errorf("read asset dir: %w", err)
	}
	var originalPath string
	for _, e := range entries {
		if e.Type()&os.ModeSymlink == 0 && e.Type().IsRegular() && isOriginalRasterImageName(e.Name()) {
			originalPath = filepath.Join(dir, e.Name())
			break
		}
	}
	if originalPath == "" {
		return fmt.Errorf("original image not found in %s", dir)
	}

	f, err := os.Open(originalPath)
	if err != nil {
		return err
	}
	defer f.Close()
	if info, statErr := f.Stat(); statErr != nil {
		return fmt.Errorf("stat original: %w", statErr)
	} else if info.Size() > MaxKnowledgeImageAssetBytes {
		return imageAssetTooLargeError(info.Size())
	}
	if err := validateImageDimensions(f); err != nil {
		return fmt.Errorf("inspect original: %w", err)
	}
	if _, err := f.Seek(0, io.SeekStart); err != nil {
		return fmt.Errorf("rewind original: %w", err)
	}

	img, _, err := image.Decode(f)
	if err != nil {
		return fmt.Errorf("decode original: %w", err)
	}

	if err := saveScaledJPEG(img, filepath.Join(dir, "thumb_120.jpg"), ThumbSize, ThumbSize, true); err != nil {
		return fmt.Errorf("generate thumb: %w", err)
	}
	if err := saveScaledJPEG(img, filepath.Join(dir, "preview_480.jpg"), PreviewWidth, PreviewWidth, true); err != nil {
		return fmt.Errorf("generate preview: %w", err)
	}
	return nil
}

// ReadKnowledgeImageThumbnail reads a generated thumbnail through the same
// managed-asset boundary used by image viewers and HTTP handlers. It is for
// presentation code that has the asset root but must not construct a host path
// from an asset ID itself.
func ReadKnowledgeImageThumbnail(assetBaseDir, assetID string) ([]byte, error) {
	data, _, err := ReadKnowledgeImageAsset(assetBaseDir, assetID, "thumbnail")
	return data, err
}

// ReadKnowledgeImageAsset returns display-safe managed image bytes and their
// detected format without exposing a host path. Presentation layers use this
// after authorization so a local cache entry cannot be checked and then
// reopened by pathname after a concurrent replacement.
func ReadKnowledgeImageAsset(assetBaseDir, assetID, variant string) ([]byte, string, error) {
	dir, err := managedImageAssetDir(assetBaseDir, assetID)
	if err != nil {
		return nil, "", err
	}
	root, err := os.OpenRoot(dir)
	if err != nil {
		return nil, "", err
	}
	defer root.Close()

	variant = strings.ToLower(strings.TrimSpace(variant))
	if variant == "thumbnail" || variant == "preview" {
		name, maxEdge, maxBytes := "thumb_120.jpg", ThumbSize, MaxKnowledgeImageThumbnailBytes
		if variant == "preview" {
			name, maxEdge, maxBytes = "preview_480.jpg", PreviewWidth, MaxKnowledgeImagePreviewBytes
		}
		data, err := readManagedImageFile(root, name, maxBytes)
		if err != nil || !isSafeDerivedKnowledgeImage(data, maxEdge) {
			return nil, "", os.ErrNotExist
		}
		return data, "jpeg", nil
	}
	if variant != "original" {
		return nil, "", fmt.Errorf("invalid image variant")
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, "", err
	}
	for _, entry := range entries {
		if entry.Type()&os.ModeSymlink != 0 || !entry.Type().IsRegular() || !isOriginalRasterImageName(entry.Name()) {
			continue
		}
		data, err := readManagedImageFile(root, entry.Name(), MaxKnowledgeImageAssetBytes)
		if err != nil {
			continue
		}
		config, format, err := image.DecodeConfig(bytes.NewReader(data))
		if err != nil || !isSupportedImageFormat(format) || config.Width <= 0 || config.Height <= 0 || int64(config.Width) > MaxKnowledgeImageAssetPixels/int64(config.Height) {
			continue
		}
		return data, format, nil
	}
	return nil, "", os.ErrNotExist
}

func readManagedImageFile(root *os.Root, name string, maxBytes int64) ([]byte, error) {
	info, err := root.Lstat(name)
	if err != nil || !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxBytes {
		return nil, os.ErrNotExist
	}
	file, err := root.Open(name)
	if err != nil {
		return nil, os.ErrNotExist
	}
	defer file.Close()
	opened, statErr := file.Stat()
	if statErr != nil || !opened.Mode().IsRegular() || opened.Size() != info.Size() {
		return nil, os.ErrNotExist
	}
	data, err := io.ReadAll(io.LimitReader(file, maxBytes+1))
	if err != nil || int64(len(data)) != info.Size() || int64(len(data)) > maxBytes {
		return nil, os.ErrNotExist
	}
	return data, nil
}

func isSafeDerivedKnowledgeImage(data []byte, maxEdge int) bool {
	config, format, err := image.DecodeConfig(bytes.NewReader(data))
	return err == nil && format == "jpeg" && config.Width > 0 && config.Height > 0 && config.Width <= maxEdge && config.Height <= maxEdge
}

// managedAssetDir resolves an existing asset directory without following an
// asset-directory symlink. Assets are addressed by model-visible IDs, so a
// locally replaced cache entry must not turn an image preview into a read of
// an arbitrary host file.
func (m *ImageAssetManager) managedAssetDir(assetID string) (string, error) {
	if m == nil {
		return "", fmt.Errorf("image assets are not configured")
	}
	return managedImageAssetDir(m.baseDir, assetID)
}

func managedImageAssetDir(baseDir, assetID string) (string, error) {
	if !IsSafeImageAssetID(assetID) {
		return "", fmt.Errorf("invalid image asset ID")
	}
	baseDir = filepath.Clean(strings.TrimSpace(baseDir))
	if baseDir == "." || baseDir == "" {
		return "", fmt.Errorf("invalid image asset base directory")
	}
	resolvedBase, err := filepath.EvalSymlinks(baseDir)
	if err != nil {
		return "", err
	}
	assetDir := filepath.Join(resolvedBase, assetID)
	info, err := os.Lstat(assetDir)
	if err != nil || !info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
		return "", os.ErrNotExist
	}
	resolvedAsset, err := filepath.EvalSymlinks(assetDir)
	if err != nil {
		return "", err
	}
	rel, err := filepath.Rel(resolvedBase, resolvedAsset)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) || filepath.IsAbs(rel) {
		return "", fmt.Errorf("image asset is outside managed directory")
	}
	return resolvedAsset, nil
}

// --- internal ---

type bytesReader struct {
	data []byte
	pos  int
}

func (b *bytesReader) Read(p []byte) (int, error) {
	if b.pos >= len(b.data) {
		return 0, io.EOF
	}
	n := copy(p, b.data[b.pos:])
	b.pos += n
	return n, nil
}

func (m *ImageAssetManager) saveImageFromReader(sourceID string, r io.Reader, ext string, sizeBytes int64) (*ImageAsset, error) {
	if sizeBytes > MaxKnowledgeImageAssetBytes {
		return nil, imageAssetTooLargeError(sizeBytes)
	}
	dir := m.AssetDir(sourceID)
	if dir == "" {
		return nil, fmt.Errorf("invalid source ID: contains path traversal characters")
	}
	if err := os.MkdirAll(m.baseDir, 0o755); err != nil {
		return nil, fmt.Errorf("create asset base dir: %w", err)
	}
	tempDir, err := os.MkdirTemp(m.baseDir, ".image-asset-")
	if err != nil {
		return nil, fmt.Errorf("create temporary asset dir: %w", err)
	}
	published := false
	defer func() {
		if !published {
			_ = os.RemoveAll(tempDir)
		}
	}()

	ext = normalizeImageExt(ext)

	// Build the replacement asset away from the published directory. A failed
	// save must not leave partial files or overwrite the current asset.
	tempOriginalPath := filepath.Join(tempDir, "original"+ext)
	outFile, err := os.Create(tempOriginalPath)
	if err != nil {
		return nil, fmt.Errorf("create original: %w", err)
	}

	written, err := io.Copy(outFile, io.LimitReader(r, MaxKnowledgeImageAssetBytes+1))
	if err != nil {
		outFile.Close()
		return nil, fmt.Errorf("write original: %w", err)
	}
	if err := outFile.Close(); err != nil {
		return nil, fmt.Errorf("close original: %w", err)
	}
	if written > MaxKnowledgeImageAssetBytes {
		return nil, imageAssetTooLargeError(written)
	}

	// The copied size is authoritative: the source may have changed after Stat.
	sizeBytes = written

	imgFile, err := os.Open(tempOriginalPath)
	if err != nil {
		return nil, fmt.Errorf("reopen original: %w", err)
	}
	defer imgFile.Close()
	if err := validateImageDimensions(imgFile); err != nil {
		return nil, fmt.Errorf("inspect image: %w", err)
	}
	if _, err := imgFile.Seek(0, io.SeekStart); err != nil {
		return nil, fmt.Errorf("rewind image: %w", err)
	}

	img, format, err := image.Decode(imgFile)
	if closeErr := imgFile.Close(); closeErr != nil {
		return nil, fmt.Errorf("close inspected image: %w", closeErr)
	}
	if err != nil {
		// Image cannot be decoded (e.g. SVG, EMF, WMF) — retain the supported
		// original-only behavior, but still publish atomically.
		asset := &ImageAsset{
			OriginalPath: filepath.Join(dir, "original"+ext),
			Format:       strings.TrimPrefix(ext, "."),
			SizeBytes:    sizeBytes,
		}
		if err := publishImageAssetDir(dir, tempDir); err != nil {
			return nil, err
		}
		published = true
		return asset, nil
	}

	bounds := img.Bounds()
	asset := &ImageAsset{
		OriginalPath: filepath.Join(dir, "original"+ext),
		Width:        bounds.Dx(),
		Height:       bounds.Dy(),
		Format:       format,
		SizeBytes:    sizeBytes,
	}

	// Generate thumbnail (120x120, fit within square).
	tempThumbPath := filepath.Join(tempDir, "thumb_120.jpg")
	if err := saveScaledJPEG(img, tempThumbPath, ThumbSize, ThumbSize, true); err == nil {
		asset.ThumbPath = filepath.Join(dir, "thumb_120.jpg")
	}

	// Generate preview (fit within a 480px square).
	tempPreviewPath := filepath.Join(tempDir, "preview_480.jpg")
	if err := saveScaledJPEG(img, tempPreviewPath, PreviewWidth, PreviewWidth, true); err == nil {
		asset.PreviewPath = filepath.Join(dir, "preview_480.jpg")
	}

	if err := publishImageAssetDir(dir, tempDir); err != nil {
		return nil, err
	}
	published = true
	return asset, nil
}

// publishImageAssetDir swaps a complete staged asset into place. Should the
// final rename fail, the previous asset is restored before returning an error.
func publishImageAssetDir(dir, tempDir string) error {
	backupDir := imageAssetBackupDir(dir)
	if err := os.RemoveAll(backupDir); err != nil {
		return fmt.Errorf("clear prior asset backup: %w", err)
	}
	if err := os.Rename(dir, backupDir); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("stage prior asset: %w", err)
	}
	if err := os.Rename(tempDir, dir); err != nil {
		if restoreErr := os.Rename(backupDir, dir); restoreErr != nil && !os.IsNotExist(restoreErr) {
			return fmt.Errorf("publish image asset: %w (restore prior asset: %v)", err, restoreErr)
		}
		return fmt.Errorf("publish image asset: %w", err)
	}
	// The new asset is already published. A locked old file (common on Windows)
	// must not turn a successful import into an error or cause a later writer to
	// discard the just-published directory. Leave the stale backup for the next
	// successful replacement or normal source cleanup to reclaim.
	if err := os.RemoveAll(backupDir); err != nil && !os.IsNotExist(err) {
		return nil
	}
	return nil
}

func imageAssetBackupDir(dir string) string {
	return dir + ".previous"
}

// validateImageDimensions rejects images whose decoded pixel area would
// exceed the resource budget before image.Decode allocates their full raster.
// Unsupported/vector formats are retained as originals and therefore do not
// need a raster-dimension check here.
func validateImageDimensions(r io.Reader) error {
	config, _, err := image.DecodeConfig(r)
	if err != nil {
		if config.Width > 0 && config.Height > 0 && int64(config.Width) > MaxKnowledgeImageAssetPixels/int64(config.Height) {
			return fmt.Errorf("image dimensions exceed %d pixels", MaxKnowledgeImageAssetPixels)
		}
		return nil
	}
	if config.Width <= 0 || config.Height <= 0 {
		return fmt.Errorf("invalid image dimensions")
	}
	if int64(config.Width) > MaxKnowledgeImageAssetPixels/int64(config.Height) {
		return fmt.Errorf("image dimensions exceed %d pixels", MaxKnowledgeImageAssetPixels)
	}
	return nil
}

// saveScaledJPEG scales the image to fit within maxW x maxH and saves as JPEG.
// If fitSquare is true, both dimensions are capped. If fitSquare is false and
// maxH is 0, height is computed proportionally from maxW.
func saveScaledJPEG(src image.Image, dstPath string, maxW, maxH int, fitSquare bool) error {
	bounds := src.Bounds()
	srcW := bounds.Dx()
	srcH := bounds.Dy()

	if srcW == 0 || srcH == 0 {
		return fmt.Errorf("zero-dimension image")
	}

	var dstW, dstH int
	if fitSquare {
		// Fit within maxW x maxH square, maintaining aspect ratio.
		ratio := float64(srcW) / float64(srcH)
		if ratio > 1 {
			// Landscape
			dstW = maxW
			dstH = int(float64(maxW) / ratio)
		} else {
			// Portrait or square
			dstH = maxH
			dstW = int(float64(maxH) * ratio)
		}
	} else {
		// Scale to maxW, proportional height.
		if srcW <= maxW {
			// Already smaller — don't upscale.
			dstW = srcW
			dstH = srcH
		} else {
			dstW = maxW
			dstH = int(float64(srcH) * float64(maxW) / float64(srcW))
		}
	}

	if dstW <= 0 {
		dstW = 1
	}
	if dstH <= 0 {
		dstH = 1
	}

	dst := image.NewRGBA(image.Rect(0, 0, dstW, dstH))
	draw.BiLinear.Scale(dst, dst.Bounds(), src, bounds, draw.Over, nil)

	f, err := os.Create(dstPath)
	if err != nil {
		return err
	}
	defer f.Close()

	return jpeg.Encode(f, dst, &jpeg.Options{Quality: 80})
}

// normalizeImageExt ensures the extension has a dot and is lowercase.
func normalizeImageExt(ext string) string {
	ext = strings.ToLower(strings.TrimSpace(ext))
	if ext == "" {
		return ".png"
	}
	if !strings.HasPrefix(ext, ".") {
		ext = "." + ext
	}
	// Normalize common variants.
	switch ext {
	case ".jpeg":
		return ".jpg"
	default:
		return ext
	}
}

// IsImageExt returns true if the file extension is a supported image format.
func IsImageExt(ext string) bool {
	ext = strings.ToLower(strings.TrimSpace(ext))
	if !strings.HasPrefix(ext, ".") {
		ext = "." + ext
	}
	for _, e := range ImageIncludeExts {
		if ext == e {
			return true
		}
	}
	return false
}

func isOriginalRasterImageName(name string) bool {
	ext := strings.ToLower(filepath.Ext(name))
	return ext != "" && name == "original"+ext && IsImageExt(ext)
}

func isSupportedImageFormat(format string) bool {
	switch strings.ToLower(format) {
	case "png", "jpeg", "gif", "webp", "bmp":
		return true
	default:
		return false
	}
}

// IsVectorImageExt returns true for vector image formats that cannot be OCR'd.
func IsVectorImageExt(ext string) bool {
	ext = strings.ToLower(strings.TrimSpace(ext))
	switch ext {
	case ".emf", ".wmf", ".svg":
		return true
	}
	return false
}
