// Command genphasemeta is the anti-drift code generator for the workflow
// dashboard's phase metadata.
//
// It builds map[string][]workflow.PhaseMeta from the live workflow registry via
// workflow.PhaseMetadata and renders the TypeScript fallback artifact consumed
// by the dashboard's degraded-mode rendering and its contract test:
//
//	gui/frontend/src/components/ai/workflowPhaseMeta.generated.ts
//
// The backend workflow templates (corelib/workflow/templates.go) are the single
// source of truth; this generator projects them into a committed TypeScript file
// so the hand-maintained frontend fallback maps can never silently diverge.
//
// Usage (from the repository root):
//
//	go run ./cmd/genphasemeta
//	go run ./cmd/genphasemeta -out path/to/workflowPhaseMeta.generated.ts
//
// The output is byte-stable across runs: registry.All() iterates templates in a
// deterministic sorted order, and PhaseMetadata preserves each template's phase
// order, so re-running the generator without template changes produces an
// identical file.
package main

import (
	"flag"
	"fmt"
	"os"
	"strconv"
	"strings"

	"github.com/RapidAI/CodeClaw/corelib/workflow"
)

// generatedFilePath is the canonical, repository-root-relative location of the
// generated TypeScript artifact.
const generatedFilePath = "gui/frontend/src/components/ai/workflowPhaseMeta.generated.ts"

func main() {
	outPath := flag.String("out", generatedFilePath, "output path for the generated TypeScript artifact")
	flag.Parse()

	content := renderGeneratedTS(workflow.NewWorkflowRegistry())
	if err := os.WriteFile(*outPath, []byte(content), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "genphasemeta: write %s: %v\n", *outPath, err)
		os.Exit(1)
	}
	fmt.Printf("genphasemeta: wrote %s\n", *outPath)
}

// renderGeneratedTS builds the full TypeScript artifact content from the
// registry's templates. It iterates templates in the deterministic sorted order
// returned by registry.All() and projects each into PhaseMeta via
// workflow.PhaseMetadata, so the output is byte-stable across runs and mirrors
// PhaseMetadata's ordering exactly.
//
// The emitted shape is:
//
//	export interface GeneratedPhaseMeta { id; name; index; expectsDocument; canSkip; needsConfirm; kind; toolPolicy; mutationScope; activatesOrchestrator }
//	export const WORKFLOW_PHASE_META: Record<string, GeneratedPhaseMeta[]>
//
// renderGeneratedTS is package-private so the contract test can regenerate the
// artifact in memory and compare it against the committed file.
func renderGeneratedTS(r *workflow.WorkflowRegistry) string {
	var b strings.Builder

	b.WriteString("// AUTO-GENERATED by cmd/genphasemeta. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate with: go generate ./...\n")
	b.WriteString("// Source of truth: corelib/workflow/templates.go (RegisterBuiltinTemplates).\n")
	b.WriteString("\n")
	b.WriteString("export interface GeneratedPhaseMeta {\n")
	b.WriteString("  id: string;\n")
	b.WriteString("  name: string;\n")
	b.WriteString("  index: number;\n")
	b.WriteString("  expectsDocument: boolean;\n")
	b.WriteString("  canSkip: boolean;\n")
	b.WriteString("  needsConfirm: boolean;\n")
	b.WriteString("  kind: string;\n")
	b.WriteString("  toolPolicy: string;\n")
	b.WriteString("  mutationScope: string;\n")
	b.WriteString("  activatesOrchestrator: boolean;\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export const WORKFLOW_PHASE_META: Record<string, GeneratedPhaseMeta[]> = {\n")

	for _, tmpl := range r.All() {
		if tmpl == nil {
			continue
		}
		fmt.Fprintf(&b, "  %s: [\n", strconv.Quote(string(tmpl.Type)))
		for _, m := range workflow.PhaseMetadata(tmpl) {
			fmt.Fprintf(&b,
				"    { id: %s, name: %s, index: %d, expectsDocument: %t, canSkip: %t, needsConfirm: %t, kind: %s, toolPolicy: %s, mutationScope: %s, activatesOrchestrator: %t },\n",
				strconv.Quote(m.ID), strconv.Quote(m.Name), m.Index, m.ExpectsDocument, m.CanSkip, m.NeedsConfirm,
				strconv.Quote(string(m.Kind)), strconv.Quote(string(m.ToolPolicy)), strconv.Quote(string(m.MutationScope)), m.ActivatesOrchestrator,
			)
		}
		b.WriteString("  ],\n")
	}

	b.WriteString("};\n")
	return b.String()
}
