package ocr

import (
	"fmt"
	"image"
	_ "image/png"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"
	"testing"
	"time"
)

// Stress corpus generated by testdata/stress/gen_stress.py (deterministic,
// fixed seeds). Box-count bounds are generous to absorb minor float
// differences across SIMD backends; exact-line spot checks use lines that
// recognize at confidence ~1.0 on both AVX2 and fallback paths.

type stressCase struct {
	file       string
	minBoxes   int
	maxBoxes   int
	exactLines []string // each must appear as one exact result text
	anySubstr  []string // at least one result must contain one of these
}

var stressCorpus = []stressCase{
	{file: "ui_dense_1920x1080.png", minBoxes: 60, maxBoxes: 250,
		exactLines: []string{"File", "Terminal"}},
	{file: "blank_800x600.png", minBoxes: 0, maxBoxes: 2},
	{file: "single_word.png", minBoxes: 1, maxBoxes: 3,
		exactLines: []string{"Settings"}},
	{file: "wide_strip_3000x80.png", minBoxes: 1, maxBoxes: 2,
		exactLines: []string{"Invoice Total 1,234.56 CNY paid on 2026-08-07 ref A20240807"}},
	{file: "tall_strip_80x3000.png", minBoxes: 15, maxBoxes: 25,
		anySubstr: []string{"0", "1", "row"}},
	{file: "tiny_16x16.png", minBoxes: 1, maxBoxes: 2,
		exactLines: []string{"A"}},
	{file: "noisy_lowcontrast.png", minBoxes: 2, maxBoxes: 6,
		exactLines: []string{"Door code 4581"}},
	{file: "rotated_10_30deg.png", minBoxes: 3, maxBoxes: 8,
		exactLines: []string{"Quarterly report 2026"}},
	{file: "dense_blobs.png", minBoxes: 100, maxBoxes: 600},
	{file: "screenshot_2560x1440.png", minBoxes: 30, maxBoxes: 60,
		exactLines: []string{"[00] service-ok status=ok latency=9ms req=8048"}},
}

func loadStressImage(t testing.TB, name string) image.Image {
	t.Helper()
	f, err := os.Open(filepath.Join("testdata", "stress", name))
	if err != nil {
		t.Fatalf("stress image %s: %v (regenerate with testdata/stress/gen_stress.py)", name, err)
	}
	defer f.Close()
	img, _, err := image.Decode(f)
	if err != nil {
		t.Fatalf("decode %s: %v", name, err)
	}
	return img
}

// TestStressCorpus runs the full engine over realistic and adversarial image
// shapes: it must never panic, must return sane box counts, and must read
// clean text correctly.
func TestStressCorpus(t *testing.T) {
	e := testEngine(t)
	for _, tc := range stressCorpus {
		t.Run(tc.file, func(t *testing.T) {
			img := loadStressImage(t, tc.file)
			start := time.Now()
			results, err := e.Recognize(img)
			if err != nil {
				t.Fatalf("Recognize: %v", err)
			}
			el := time.Since(start)
			if len(results) < tc.minBoxes || len(results) > tc.maxBoxes {
				t.Errorf("boxes=%d outside [%d,%d]", len(results), tc.minBoxes, tc.maxBoxes)
			}
			texts := make([]string, len(results))
			totalLen := 0
			for i, r := range results {
				texts[i] = r.Text
				totalLen += len(r.Text)
				if r.Confidence < 0 || r.Confidence > 1 {
					t.Errorf("confidence %v out of range for %q", r.Confidence, r.Text)
				}
				if r.BBox[2] <= 0 || r.BBox[3] <= 0 {
					t.Errorf("degenerate bbox %v for %q", r.BBox, r.Text)
				}
			}
			for _, want := range tc.exactLines {
				found := false
				for _, g := range texts {
					if g == want {
						found = true
						break
					}
				}
				if !found {
					t.Errorf("expected exact line %q not found (got %d texts, e.g. %q)",
						want, len(texts), firstN(texts, 4))
				}
			}
			if len(tc.anySubstr) > 0 {
				found := false
				for _, g := range texts {
					for _, sub := range tc.anySubstr {
						if strings.Contains(g, sub) {
							found = true
						}
					}
				}
				if !found {
					t.Errorf("no result contains any of %q", tc.anySubstr)
				}
			}
			t.Logf("boxes=%d chars=%d time=%v", len(results), totalLen, el)
		})
	}
}

func firstN(s []string, n int) []string {
	if len(s) > n {
		return s[:n]
	}
	return s
}

// BenchmarkEngineStressCorpus is the reproducible end-to-end performance
// gate for the native PP-OCR pipeline. It measures warmed inference over the
// same adversarial/production-shaped images used by TestStressCorpus, while
// reporting allocations so scratch/arena regressions cannot hide behind a
// throughput-only number. Run it with a fixed CPU setting when comparing
// revisions, for example: go test ./corelib/ocr -run '^$' -bench
// BenchmarkEngineStressCorpus -benchtime=3x -cpu=1.
func BenchmarkEngineStressCorpus(b *testing.B) {
	e := testEngine(b)
	imgs := make([]image.Image, len(stressCorpus))
	for i, tc := range stressCorpus {
		imgs[i] = loadStressImage(b, tc.file)
	}
	// Warm each input once: model parsing, scratch high-water marks and the
	// runtime worker pool are intentionally outside the timed section.
	for _, img := range imgs {
		if _, err := e.Recognize(img); err != nil {
			b.Fatal(err)
		}
	}
	b.ReportAllocs()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		if _, err := e.Recognize(imgs[i%len(imgs)]); err != nil {
			b.Fatal(err)
		}
	}
}

// memSnapshot is the memory state we assert on in the soak test.
func memSnapshot() runtime.MemStats {
	runtime.GC()
	runtime.GC() // twice: let finalizers and pool shrinking settle
	var m runtime.MemStats
	runtime.ReadMemStats(&m)
	return m
}

// TestStressMemorySoak hammers the engine and the load/unload lifecycle in
// one process and asserts memory does not grow monotonically. Genuine leaks
// (pinned sync.Pool buffers, goroutine/timer leaks, retained initializers)
// would show up as HeapInuse drift far beyond this bound.
func TestStressMemorySoak(t *testing.T) {
	det := filepath.Join(testModelDir, "ppocrv6_small_det.onnx")
	rec := filepath.Join(testModelDir, "ppocrv6_small_rec.onnx")
	if _, err := os.Stat(det); err != nil {
		t.Skip("models not available")
	}

	// Mixed corpus weighted toward small images so 200 iterations stay fast;
	// one noisy mid-size image every 20 iterations exercises larger buffers.
	small := []string{"tiny_16x16.png", "single_word.png", "blank_800x600.png", "wide_strip_3000x80.png"}
	imgs := make([]image.Image, len(small))
	for i, name := range small {
		imgs[i] = loadStressImage(t, name)
	}
	noisy := loadStressImage(t, "noisy_lowcontrast.png")

	e, err := NewEngine(det, rec)
	if err != nil {
		t.Fatal(err)
	}
	defer e.Close()

	// Warmup: stabilize sync.Pool high-water marks and dict/graph caches.
	// Include the largest image used in the loop so its buffer classes are
	// counted in the baseline.
	for i := 0; i < 10; i++ {
		if _, err := e.Recognize(imgs[i%len(imgs)]); err != nil {
			t.Fatal(err)
		}
	}
	if _, err := e.Recognize(noisy); err != nil {
		t.Fatal(err)
	}

	before := memSnapshot()
	g0 := runtime.NumGoroutine()
	for i := 0; i < 200; i++ {
		img := imgs[i%len(imgs)]
		if i%20 == 19 {
			img = noisy
		}
		if _, err := e.Recognize(img); err != nil {
			t.Fatalf("iteration %d: %v", i, err)
		}
	}
	after := memSnapshot()
	t.Logf("engine soak: HeapInuse %d -> %d (drift %d), HeapAlloc %d -> %d, goroutines %d -> %d",
		before.HeapInuse, after.HeapInuse, int64(after.HeapInuse)-int64(before.HeapInuse),
		before.HeapAlloc, after.HeapAlloc, g0, runtime.NumGoroutine())
	assertNoMemGrowth(t, before, after, g0)

	// 50 unload/reload cycles through the Manager: every cycle re-parses both
	// ONNX models. A leak in graph loading (retained initializers, orphaned
	// timers) shows up here.
	m := NewManager(det, rec)
	tiny := imgs[0]
	if _, err := m.Recognize(tiny); err != nil { // warm load
		t.Fatal(err)
	}
	m.Unload()
	beforeM := memSnapshot()
	g0 = runtime.NumGoroutine()
	for i := 0; i < 50; i++ {
		if _, err := m.Recognize(tiny); err != nil {
			t.Fatalf("cycle %d: %v", i, err)
		}
		m.Unload()
		if m.Loaded() {
			t.Fatalf("cycle %d: still loaded after Unload", i)
		}
	}
	afterM := memSnapshot()
	m.Shutdown()
	t.Logf("manager soak: HeapInuse %d -> %d (drift %d), goroutines %d -> %d",
		beforeM.HeapInuse, afterM.HeapInuse, int64(afterM.HeapInuse)-int64(beforeM.HeapInuse),
		g0, runtime.NumGoroutine())
	assertNoMemGrowth(t, beforeM, afterM, g0)
}

func assertNoMemGrowth(t *testing.T, before, after runtime.MemStats, goroutinesBefore int) {
	t.Helper()
	const maxDrift = 50 << 20 // 50MB, generous vs the ~10MB model working set
	drift := int64(after.HeapInuse) - int64(before.HeapInuse)
	if drift > maxDrift {
		t.Errorf("HeapInuse drift %d bytes exceeds %d (before=%d after=%d)",
			drift, maxDrift, before.HeapInuse, after.HeapInuse)
	}
	if d := runtime.NumGoroutine() - goroutinesBefore; d > 2 {
		t.Errorf("goroutine count grew by %d (possible timer/goroutine leak)", d)
	}
}

// TestStressConcurrentDeterminism runs 8 goroutines x 50 Recognize calls on
// one shared Engine. The engine serializes calls internally; besides race
// safety (run with -race) the results must be bit-identical for identical
// inputs — map iteration or buffer reuse must not leak into results.
func TestStressConcurrentDeterminism(t *testing.T) {
	e := testEngine(t)
	names := []string{"tiny_16x16.png", "single_word.png", "blank_800x600.png", "wide_strip_3000x80.png"}
	imgs := make([]image.Image, len(names))
	for i, name := range names {
		imgs[i] = loadStressImage(t, name)
	}

	type signature string
	sign := func(res []Result, err error) signature {
		if err != nil {
			return signature("ERR: " + err.Error())
		}
		var b strings.Builder
		for _, r := range res {
			fmt.Fprintf(&b, "%q|%.6f|%v|", r.Text, r.Confidence, r.BBox)
		}
		return signature(b.String())
	}

	const goroutines = 8
	const calls = 50
	// unset sentinel: a legit signature can be "" (blank image, 0 boxes).
	const unset = signature("\x00unset")
	base := make([]signature, len(imgs)) // first observed signature per image
	for i := range base {
		base[i] = unset
	}
	var baseMu sync.Mutex
	errs := make(chan error, goroutines*calls)
	var wg sync.WaitGroup
	for g := 0; g < goroutines; g++ {
		wg.Add(1)
		go func(g int) {
			defer wg.Done()
			for i := 0; i < calls; i++ {
				idx := (g + i) % len(imgs)
				res, err := e.Recognize(imgs[idx])
				got := sign(res, err)
				baseMu.Lock()
				if base[idx] == unset {
					base[idx] = got
				} else if base[idx] != got {
					errs <- fmt.Errorf("image %s: nondeterministic result\ngot:  %s\nwant: %s",
						names[idx], truncate(string(got), 200), truncate(string(base[idx]), 200))
				}
				baseMu.Unlock()
			}
		}(g)
	}
	wg.Wait()
	close(errs)
	for err := range errs {
		t.Error(err)
	}
	// Sanity: the distinct images must not all collapse to one signature.
	seen := map[signature]bool{}
	for _, s := range base {
		seen[s] = true
	}
	if len(seen) < 2 {
		t.Error("all images produced identical signatures — suspicious")
	}
}

func truncate(s string, n int) string {
	if len(s) > n {
		return s[:n] + "..."
	}
	return s
}
