[CmdletBinding()]
param()
$ErrorActionPreference = 'Stop'
$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$src=Join-Path $root 'main\configuration_migration_journal.c'; $hdr=Join-Path $root 'main\configuration_migration_journal.h'; $test=Join-Path $PSScriptRoot 'host_tests\test_configuration_migration_journal.c'
$configuration=Join-Path $root 'main\configuration_service.c'
$factoryPolicy=Join-Path $root 'main\configuration_factory_reset_policy.c'; $factoryHeader=Join-Path $root 'main\configuration_factory_reset_policy.h'; $factoryService=Join-Path $root 'main\services\factory_reset_service.c'
$factoryTest=Join-Path $PSScriptRoot 'host_tests\test_configuration_factory_reset_policy.c'; $factoryServiceTest=Join-Path $PSScriptRoot 'host_tests\test_factory_reset_service.c'
$fail=@(); foreach($p in @($src,$hdr,$test,$configuration,$factoryPolicy,$factoryHeader,$factoryService,$factoryTest,$factoryServiceTest)){if(-not(Test-Path -LiteralPath $p)){$fail+="missing $p"}}
if((Test-Path -LiteralPath $hdr) -and (Get-Content -LiteralPath $hdr -Raw) -notmatch 'PREPARED|VALIDATED|COMMITTED'){$fail+='journal stages missing'}
if((Test-Path -LiteralPath $hdr) -and (Get-Content -LiteralPath $hdr -Raw) -notmatch 'configuration_migration_journal_set_generation'){$fail+='journal generation binding API missing'}
if((Test-Path -LiteralPath $src) -and (Get-Content -LiteralPath $src -Raw) -notmatch 'configuration_migration_journal_validate\(journal\)'){$fail+='journal encoder must validate records before persistence'}
if((Test-Path -LiteralPath $src) -and (Get-Content -LiteralPath $src -Raw) -notmatch 'journal->stage != CONFIGURATION_MIGRATION_STAGE_PREPARED'){$fail+='journal generation may only be rebound while PREPARED'}
if((Test-Path -LiteralPath $src) -and (Get-Content -LiteralPath $src -Raw) -notmatch 'next_stage != \(configuration_migration_stage_t\)\(journal->stage \+ 1\)'){$fail+='journal transitions must be strict single-step edges'}
if(Test-Path -LiteralPath $configuration){$t=Get-Content -LiteralPath $configuration -Raw; foreach($needle in @('configuration_migration_journal_begin','CONFIGURATION_MIGRATION_STAGE_VALIDATED','CONFIGURATION_MIGRATION_STAGE_COMMITTED')){if($t -notmatch [regex]::Escape($needle)){$fail+="configuration migration missing $needle"}}}
if(Test-Path -LiteralPath $configuration){$t=Get-Content -LiteralPath $configuration -Raw; foreach($needle in @('CONFIGURATION_MIGRATION_JOURNAL_KEY','CONFIGURATION_MIGRATION_LEGACY_SCALAR_SOURCE_BYTES','persist_migration_journal_locked','recover_migration_journal_locked','clear_migration_journal_locked','current_record_bytes','committed_target','validated_target','prepared_target','legacy_scalar_source','size_matches_stage','journal.target_version != CONFIGURATION_STORE_VERSION','journal.generation != s_scratch_store->revision','configuration_migration_journal_set_generation','legacy_scalar_source && !target_record_present','CONFIGURATION_MIGRATION_FINGERPRINT_KEY','persist_migration_fingerprint_locked','migration_fingerprint_matches_locked','clear_migration_fingerprint_locked','CONFIGURATION_MIGRATION_TARGET_FINGERPRINT_KEY','persist_migration_target_fingerprint_locked','migration_target_fingerprint_matches_locked','clear_migration_target_fingerprint_locked')){if($t -notmatch [regex]::Escape($needle)){$fail+="configuration journal persistence missing $needle"}}; $scalarCleanup=$t.IndexOf('/* Scalar-key migrations have no source blob fingerprint'); if($scalarCleanup -lt 0 -or $t.IndexOf('clear_migration_target_fingerprint_locked();',$scalarCleanup) -lt 0){$fail+='scalar migration must clear target fingerprint evidence'}}
if(Test-Path -LiteralPath $configuration){
  $t=Get-Content -LiteralPath $configuration -Raw
  $migrationBlock=$t.Substring($t.IndexOf('if (migrated || legacy_display_found)'))
  $targetFingerprint=$migrationBlock.IndexOf('persist_migration_target_fingerprint_locked(store)')
  $targetWrite=$migrationBlock.IndexOf('err = write_store_locked(store);')
  $validatedTransition=$migrationBlock.IndexOf('CONFIGURATION_MIGRATION_STAGE_VALIDATED')
  if($targetFingerprint -lt 0 -or $targetWrite -lt 0 -or $targetFingerprint -gt $targetWrite){$fail+='migration must stage target fingerprint before target publication'}
  if($validatedTransition -lt 0 -or $targetWrite -gt $validatedTransition){$fail+='migration must retain PREPARED marker through target publication'}
}
if(Test-Path -LiteralPath $factoryPolicy){$t=Get-Content -LiteralPath $factoryPolicy -Raw; foreach($needle in @('explicit_confirmation','CONFIGURATION_FACTORY_RESET_CLASS_ALL','configuration_factory_reset_journal_commit')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset policy missing $needle"}}}
$factoryRegistry=Join-Path $root 'main\device_tool_registry.c'; $factoryServiceHeader=Join-Path $root 'main\services\factory_reset_service.h'; $factoryServiceSource=Join-Path $root 'main\services\factory_reset_service.c'
if(Test-Path -LiteralPath $factoryRegistry){$t=Get-Content -LiteralPath $factoryRegistry -Raw; foreach($needle in @('"factory_reset"','idempotency_key','explicitConfirmation','generation')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset tool contract missing $needle"}}}
if(Test-Path -LiteralPath $factoryServiceHeader){$t=Get-Content -LiteralPath $factoryServiceHeader -Raw; foreach($needle in @('FACTORY_RESET_SERVICE_HOST_ABI_VERSION 4u','validate_authorization','verify_recovery_state','prepare_for_reset','abort_prepare_for_reset','complete_reset','reboot_after_reset')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset lifecycle callback missing $needle"}}}
if(Test-Path -LiteralPath $factoryServiceSource){$t=Get-Content -LiteralPath $factoryServiceSource -Raw; foreach($needle in @('validate_authorization','prepare_for_reset','abort_prepare_for_reset','clear_meeting_recording','clear_pet_cache','verify_personal_storage_absent','verify_recovery_state','FACTORY_RESET_DELIVERY_KEY','complete_reset','journal_clear','result_durable','esp_timer.h','remaining_timeout_ms','FACTORY_RESET_EXECUTE_TIMEOUT_MS','prepare_timeout_ms')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset service missing $needle"}}; if($t -match 'prepare_for_reset\s*\(\s*5000u\s*,'){ $fail+='factory reset PREPARE must consume remaining parent deadline, not restart nominal timeout' }; if($t -notmatch 'remaining_timeout_ms\(deadline_us\)'){ $fail+='factory reset PREPARE deadline propagation missing' }}
$factoryMatrix = Get-Content -LiteralPath $factoryServiceTest -Raw
foreach($needle in @('durable PREPARED record','Corrupt journal bytes','malformed delivery marker','factory_reset_service_recover() == DEVICE_STATUS_INTERNAL_ERROR','retained_size == sizeof(prepared)')) { if($factoryMatrix -notmatch [regex]::Escape($needle)) { $fail += "factory reset recovery matrix missing $needle" } }
$mainSource=Join-Path $root 'main\main.c'; if(Test-Path -LiteralPath $mainSource){$t=Get-Content -LiteralPath $mainSource -Raw; foreach($needle in @('bool result_durable','factory_reset_service_reboot_if_pending(false)','factory_reset_service_reboot_if_pending(')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset delivery gate missing $needle"}}}
if(Test-Path -LiteralPath $mainSource){$t=Get-Content -LiteralPath $mainSource -Raw; foreach($needle in @('s_factory_reset_fixed_keys','FACTORY_RESET_FIXED_KEY_COUNT','same table','s_factory_reset_fixed_keys[i].name_space','s_factory_reset_fixed_keys[i].key','configuration_migration_source_fingerprint','configuration_migration_target_fingerprint')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset fixed inventory gate missing $needle"}}}
if(Test-Path -LiteralPath $mainSource){$t=Get-Content -LiteralPath $mainSource -Raw; foreach($needle in @('task_registry_stop_owner','configuration_reconcile_service_prepare_system_sleep','configuration_reconcile_service_abort_system_sleep_prepare','configuration_service_prepare_system_sleep','configuration_service_abort_system_sleep_prepare','configuration_persistence_worker_service_prepare_system_sleep','startup_pet_worker_service_stop','wake_restart_worker_service_stop','deferred_setup_worker_service_stop','media_transfer_service_audio_download_active','persistence_service_write_u8("maclaw", "force_setup", 1u)','gateway_tool_result_outbox_peek','factory_reset_service_recover()')){if($t -notmatch [regex]::Escape($needle)){$fail+="factory reset drain/recovery missing $needle"}}; $prepareReconcile=$t.IndexOf('FACTORY_RESET_REQUIRE(configuration_reconcile_service_prepare_system_sleep('); $prepareConfig=$t.IndexOf('FACTORY_RESET_REQUIRE(configuration_service_prepare_system_sleep('); $preparePersistence=$t.IndexOf('FACTORY_RESET_REQUIRE(configuration_persistence_worker_service_prepare_system_sleep('); if($prepareReconcile -lt 0 -or $prepareConfig -lt 0 -or $preparePersistence -lt 0 -or $prepareReconcile -gt $prepareConfig -or $prepareConfig -gt $preparePersistence){$fail+='factory reset must fence reconcile, Configuration, then Persistence'}; $abortPersistence=$t.IndexOf('configuration_persistence_worker_service_abort_system_sleep_prepare();'); $abortConfig=$t.IndexOf('configuration_service_abort_system_sleep_prepare();'); $abortReconcile=$t.IndexOf('configuration_reconcile_service_abort_system_sleep_prepare();'); if($abortPersistence -lt 0 -or $abortConfig -lt 0 -or $abortReconcile -lt 0 -or $abortPersistence -gt $abortConfig -or $abortConfig -gt $abortReconcile){$fail+='factory reset abort must release Persistence, Configuration, then reconcile'}}
$cc=Get-Command gcc -ErrorAction SilentlyContinue; if(-not $cc){$cc=Get-Command clang -ErrorAction SilentlyContinue}; if(-not $cc){$fail+='host compiler required'}
if($fail.Count -eq 0){$out=Join-Path $root 'build-host-tests';New-Item -ItemType Directory -Force -Path $out|Out-Null;$include="-I$(Join-Path $root 'main')";$exe=Join-Path $out 'test_configuration_migration_journal.exe';&$cc.Source -std=c11 -Wall -Wextra -Werror $include $test $src -o $exe;if($LASTEXITCODE -ne 0){$fail+='migration journal compile failed'}else{&$exe;if($LASTEXITCODE -ne 0){$fail+='migration journal test failed'}};$factoryExe=Join-Path $out 'test_configuration_factory_reset_policy.exe';&$cc.Source -std=c11 -Wall -Wextra -Werror $include $factoryTest $factoryPolicy -o $factoryExe;if($LASTEXITCODE -ne 0){$fail+='factory reset policy compile failed'}else{&$factoryExe;if($LASTEXITCODE -ne 0){$fail+='factory reset policy test failed'}}}
if($fail.Count -eq 0){$serviceExe=Join-Path $out 'test_factory_reset_service.exe';$mock="-I$(Join-Path $PSScriptRoot 'host_tests\mocks')";&$cc.Source -std=c11 -Wall -Wextra -Werror $mock $include $factoryServiceTest $factoryService $factoryPolicy -o $serviceExe;if($LASTEXITCODE -ne 0){$fail+='factory reset service compile failed'}else{&$serviceExe;if($LASTEXITCODE -ne 0){$fail+='factory reset service test failed'}}}
if($fail.Count){Write-Error($fail -join "`n");exit 1};Write-Output 'Configuration migration journal check passed'
