import { useEffect, useState } from "react";
import { main } from "../../../wailsjs/go/models";
import { colors, radius } from "./styles";

type Props = { config: main.AppConfig | null; saveRemoteConfigField: (patch: Partial<main.AppConfig>) => void; lang: string; };
type GroupDiscussionConfig = { enabled?: boolean; discoverable?: boolean; availability?: string; suggest_consultation?: boolean; confirm_before_start?: boolean; display_name?: string; security_group_id?: string; skills?: string[]; description?: string; model_visibility?: string; languages?: string[]; invite_policy?: string; allow_security_group_free_discussion?: boolean; allowed_roles?: string[]; max_risk_level?: string; context_policy?: string; reject_when_dnd?: boolean; max_rounds?: number; timeout_seconds?: number; concurrent_limit?: number; };
const defaults: Required<GroupDiscussionConfig> = { enabled: true, discoverable: true, availability: "available", suggest_consultation: true, confirm_before_start: true, display_name: "", security_group_id: "", skills: [], description: "", model_visibility: "class_only", languages: ["zh-Hans"], invite_policy: "ask_always", allow_security_group_free_discussion: false, allowed_roles: ["observe", "speak", "review"], max_risk_level: "medium", context_policy: "summary_only", reject_when_dnd: true, max_rounds: 3, timeout_seconds: 300, concurrent_limit: 1 };
const copy = {
  en: { title: "Current-Hub Group Discussion", intro: "Let this MaClaw appear on the current Hub expert list, receive invitations, and suggest a consultation when a task becomes complex. Discussions never leave the current Hub.", on: "On", off: "Off", basic: "Basic", listed: "Show on current-Hub expert list", suggest: "Allow MaClaw to suggest starting a discussion", confirm: "Ask before starting", dnd: "Reject invites while do-not-disturb", status: "Availability", available: "Available", busy: "Busy", dndStatus: "Do not disturb", identity: "Expert Identity", name: "Expert name", skills: "Specialties", securityGroup: "Security group ID", securityGroupHint: "Required for same-security-group free discussion", modelVisibility: "Model visibility", hidden: "Hidden", classOnly: "Capability class only", providerAlias: "Provider and alias", description: "Specialty description", invite: "Invites and Limits", invitePolicy: "When receiving invites", askAlways: "Ask every time", autoTrusted: "Auto-accept trusted peers", observeOnly: "Auto-accept observe-only", rejectAll: "Reject all", sameSecurityGroup: "Allow same-security-group peers to discuss freely", contextPolicy: "Context scope", summaryOnly: "Summary only", summarySnippets: "Summary and necessary snippets", fullContext: "Full context", maxRisk: "Max risk", low: "Low", medium: "Medium", high: "High", maxRounds: "Max rounds", timeout: "Timeout seconds", concurrent: "Concurrent limit", note: "Free discussion is still limited to the current Hub and the same security group, and remains constrained by DND, risk, context, and concurrency limits.", roles: "Allowed roles", observe: "Observe", speak: "Speak", propose: "Propose", review: "Review", vote: "Vote", saved: "Saved" },
  zhHans: { title: "\u5f53\u524d Hub \u7fa4\u7ec4\u8ba8\u8bba", intro: "\u8ba9\u6b64 MaClaw \u51fa\u73b0\u5728\u5f53\u524d Hub \u7684\u4e13\u5bb6\u699c\u4e2d\uff0c\u63a5\u6536\u9080\u8bf7\uff0c\u5e76\u5728\u590d\u6742\u4efb\u52a1\u4e2d\u5efa\u8bae\u53d1\u8d77\u4f1a\u8bca\u3002\u8ba8\u8bba\u4e0d\u4f1a\u79bb\u5f00\u5f53\u524d Hub\u3002", on: "\u5df2\u5f00\u542f", off: "\u5df2\u5173\u95ed", basic: "\u57fa\u7840", listed: "\u663e\u793a\u5728\u5f53\u524d Hub \u4e13\u5bb6\u699c", suggest: "\u5141\u8bb8 MaClaw \u5efa\u8bae\u53d1\u8d77\u8ba8\u8bba", confirm: "\u53d1\u8d77\u524d\u9700\u8981\u786e\u8ba4", dnd: "\u52ff\u6270\u65f6\u81ea\u52a8\u62d2\u7edd\u9080\u8bf7", status: "\u5f53\u524d\u72b6\u6001", available: "\u53ef\u7528", busy: "\u5fd9\u788c", dndStatus: "\u52ff\u6270", identity: "\u4e13\u5bb6\u8eab\u4efd", name: "\u4e13\u5bb6\u540d\u79f0", skills: "\u64c5\u957f\u6280\u80fd", securityGroup: "\u5b89\u5168\u7ec4 ID", securityGroupHint: "\u540c\u5b89\u5168\u7ec4\u81ea\u7531\u8ba8\u8bba\u9700\u8981\u586b\u5199", modelVisibility: "\u6a21\u578b\u80fd\u529b\u5c55\u793a", hidden: "\u9690\u85cf", classOnly: "\u4ec5\u5c55\u793a\u80fd\u529b\u7c7b\u578b", providerAlias: "\u5c55\u793a\u63d0\u4f9b\u5546\u4e0e\u522b\u540d", description: "\u64c5\u957f\u63cf\u8ff0", invite: "\u9080\u8bf7\u4e0e\u9650\u5236", invitePolicy: "\u6536\u5230\u9080\u8bf7\u65f6", askAlways: "\u6bcf\u6b21\u8be2\u95ee", autoTrusted: "\u4fe1\u4efb\u5bf9\u8c61\u81ea\u52a8\u63a5\u53d7", observeOnly: "\u4ec5\u65c1\u542c\u81ea\u52a8\u63a5\u53d7", rejectAll: "\u5168\u90e8\u62d2\u7edd", sameSecurityGroup: "\u540c\u4e00\u5b89\u5168\u7ec4\u53ef\u81ea\u7531\u8ba8\u8bba", contextPolicy: "\u4e0a\u4e0b\u6587\u8303\u56f4", summaryOnly: "\u4ec5\u6458\u8981", summarySnippets: "\u6458\u8981\u548c\u5fc5\u8981\u7247\u6bb5", fullContext: "\u5b8c\u6574\u4e0a\u4e0b\u6587", maxRisk: "\u6700\u5927\u98ce\u9669", low: "\u4f4e", medium: "\u4e2d", high: "\u9ad8", maxRounds: "\u6700\u5927\u8f6e\u6570", timeout: "\u8d85\u65f6\u79d2\u6570", concurrent: "\u5e76\u53d1\u4e0a\u9650", note: "\u81ea\u7531\u8ba8\u8bba\u4ecd\u4ec5\u9650\u5f53\u524d Hub \u4e14\u540c\u4e00\u5b89\u5168\u7ec4\uff0c\u5e76\u53d7\u52ff\u6270\u3001\u98ce\u9669\u3001\u4e0a\u4e0b\u6587\u548c\u5e76\u53d1\u9650\u5236\u7ea6\u675f\u3002", roles: "\u5141\u8bb8\u53c2\u4e0e\u65b9\u5f0f", observe: "\u65c1\u542c", speak: "\u53d1\u8a00", propose: "\u63d0\u6848", review: "\u8bc4\u5ba1", vote: "\u6295\u7968", saved: "\u5df2\u4fdd\u5b58" }
};
const zhHant = { ...copy.zhHans, title: "\u76ee\u524d Hub \u7fa4\u7d44\u8a0e\u8ad6", on: "\u5df2\u958b\u555f", off: "\u5df2\u95dc\u9589", securityGroup: "\u5b89\u5168\u7d44 ID", sameSecurityGroup: "\u540c\u4e00\u5b89\u5168\u7d44\u53ef\u81ea\u7531\u8a0e\u8ad6", saved: "\u5df2\u5132\u5b58" };
function normalize(config?: GroupDiscussionConfig): Required<GroupDiscussionConfig> { return { ...defaults, ...(config || {}), skills: Array.isArray(config?.skills) ? config.skills : defaults.skills, languages: Array.isArray(config?.languages) ? config.languages : defaults.languages, allowed_roles: Array.isArray(config?.allowed_roles) ? config.allowed_roles : defaults.allowed_roles }; }
function getExpertName(config: main.AppConfig | null, current: Required<GroupDiscussionConfig>): string { return ((config as any)?.maclaw_role_name || current.display_name || "MaClaw").trim(); }
function splitTags(value: string): string[] { return value.split(/[,;??\n]/).map((item) => item.trim()).filter(Boolean); }
export function GroupDiscussionSettingsPanel({ config, saveRemoteConfigField, lang }: Props) {
  const c = lang === "zh-Hant" ? zhHant : lang === "zh-Hans" ? copy.zhHans : copy.en;
  const current = normalize((config as any)?.group_discussion);
  const expertName = getExpertName(config, current);
  const [skillsText, setSkillsText] = useState(current.skills.join(", "));
  const [saved, setSaved] = useState(false);
  useEffect(() => setSkillsText(current.skills.join(", ")), [config]);
  const save = (patch: Partial<GroupDiscussionConfig>) => { saveRemoteConfigField({ group_discussion: normalize({ ...current, ...patch }) } as any); setSaved(true); window.setTimeout(() => setSaved(false), 1600); };
  const saveExpertName = (value: string) => { const displayName = value.trim() || "MaClaw"; saveRemoteConfigField({ maclaw_role_name: displayName, group_discussion: normalize({ ...current, display_name: displayName }) } as any); setSaved(true); window.setTimeout(() => setSaved(false), 1600); };
  const toggleRole = (role: string, checked: boolean) => { const roles = new Set(current.allowed_roles); if (checked) roles.add(role); else roles.delete(role); save({ allowed_roles: Array.from(roles) }); };
  const field = { border: "1px solid " + colors.border, borderRadius: radius.md, padding: "5px 8px", fontSize: "0.76rem", background: colors.surface, color: colors.text, width: "100%", boxSizing: "border-box" as const };
  const card = { border: "1px solid " + colors.border, borderRadius: radius.lg, padding: "12px 14px", background: colors.surface, marginBottom: "10px" };
  const label = { fontSize: "0.74rem", color: colors.textSecondary, fontWeight: 600, marginBottom: "4px" };
  return <div>
    <div style={{ ...card, background: colors.bg }}><div style={{ display: "flex", justifyContent: "space-between", gap: 12 }}><div><div style={{ fontSize: "0.82rem", fontWeight: 700, color: colors.text, marginBottom: 8 }}>{c.title}</div><div style={{ fontSize: "0.72rem", color: colors.textMuted, lineHeight: 1.45 }}>{c.intro}</div></div><label style={{ whiteSpace: "nowrap" }}><input type="checkbox" checked={current.enabled} onChange={(e) => save({ enabled: e.target.checked })} /> {current.enabled ? c.on : c.off}</label></div></div>
    <div style={card}><h4>{c.basic}</h4><label><input type="checkbox" checked={current.discoverable} onChange={(e) => save({ discoverable: e.target.checked })} /> {c.listed}</label><br /><label><input type="checkbox" checked={current.suggest_consultation} onChange={(e) => save({ suggest_consultation: e.target.checked })} /> {c.suggest}</label><br /><label><input type="checkbox" checked={current.confirm_before_start} onChange={(e) => save({ confirm_before_start: e.target.checked })} /> {c.confirm}</label><br /><label><input type="checkbox" checked={current.reject_when_dnd} onChange={(e) => save({ reject_when_dnd: e.target.checked })} /> {c.dnd}</label><div style={{ marginTop: 10, maxWidth: 260 }}><div style={label}>{c.status}</div><select style={field} value={current.availability} onChange={(e) => save({ availability: e.target.value })}><option value="available">{c.available}</option><option value="busy">{c.busy}</option><option value="dnd">{c.dndStatus}</option></select></div></div>
    <div style={card}><h4>{c.identity}</h4><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: 10 }}><div><div style={label}>{c.name}</div><input style={field} value={expertName} onChange={(e) => saveExpertName(e.target.value)} /></div><div><div style={label}>{c.skills}</div><input style={field} value={skillsText} onChange={(e) => setSkillsText(e.target.value)} onBlur={() => save({ skills: splitTags(skillsText) })} /></div><div><div style={label}>{c.securityGroup}</div><input style={field} value={current.security_group_id} placeholder="team-a" onChange={(e) => save({ security_group_id: e.target.value })} /><div style={{ fontSize: "0.68rem", color: colors.textMuted }}>{c.securityGroupHint}</div></div><div><div style={label}>{c.modelVisibility}</div><select style={field} value={current.model_visibility} onChange={(e) => save({ model_visibility: e.target.value })}><option value="hidden">{c.hidden}</option><option value="class_only">{c.classOnly}</option><option value="provider_alias">{c.providerAlias}</option></select></div></div><div style={{ marginTop: 10 }}><div style={label}>{c.description}</div><textarea style={{ ...field, minHeight: 70, resize: "vertical" }} value={current.description} onChange={(e) => save({ description: e.target.value })} /></div></div>
    <div style={card}><h4>{c.invite}</h4><div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))", gap: 10 }}><div><div style={label}>{c.invitePolicy}</div><select style={field} value={current.invite_policy} onChange={(e) => save({ invite_policy: e.target.value })}><option value="ask_always">{c.askAlways}</option><option value="auto_trusted">{c.autoTrusted}</option><option value="observe_only_auto">{c.observeOnly}</option><option value="reject_all">{c.rejectAll}</option></select></div><div><div style={label}>{c.contextPolicy}</div><select style={field} value={current.context_policy} onChange={(e) => save({ context_policy: e.target.value })}><option value="summary_only">{c.summaryOnly}</option><option value="summary_snippets">{c.summarySnippets}</option><option value="full_context">{c.fullContext}</option></select></div><div><div style={label}>{c.maxRisk}</div><select style={field} value={current.max_risk_level} onChange={(e) => save({ max_risk_level: e.target.value })}><option value="low">{c.low}</option><option value="medium">{c.medium}</option><option value="high">{c.high}</option></select></div><div><div style={label}>{c.maxRounds}</div><input type="number" style={field} min={1} max={20} value={current.max_rounds} onChange={(e) => save({ max_rounds: Number(e.target.value || 1) })} /></div><div><div style={label}>{c.timeout}</div><input type="number" style={field} min={30} max={3600} value={current.timeout_seconds} onChange={(e) => save({ timeout_seconds: Number(e.target.value || 300) })} /></div><div><div style={label}>{c.concurrent}</div><input type="number" style={field} min={1} max={8} value={current.concurrent_limit} onChange={(e) => save({ concurrent_limit: Number(e.target.value || 1) })} /></div></div><label style={{ display: "block", marginTop: 10 }}><input type="checkbox" checked={current.allow_security_group_free_discussion} onChange={(e) => save({ allow_security_group_free_discussion: e.target.checked })} /> {c.sameSecurityGroup}</label><div style={{ fontSize: "0.72rem", color: colors.textMuted, lineHeight: 1.45, marginTop: 6 }}>{c.note}</div></div>
    <div style={card}><h4>{c.roles}</h4>{[["observe", c.observe], ["speak", c.speak], ["propose", c.propose], ["review", c.review], ["vote", c.vote]].map(([role, text]) => <label key={role} style={{ display: "inline-flex", gap: 6, marginRight: 12 }}><input type="checkbox" checked={current.allowed_roles.includes(role)} onChange={(e) => toggleRole(role, e.target.checked)} /> {text}</label>)} {saved && <span style={{ color: colors.success, fontSize: "0.72rem" }}>{c.saved}</span>}</div>
  </div>;
}
