import { memo, useState, useEffect, useCallback, useRef } from "react";
import ReactMarkdown, { type Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import {
    DeleteIMAuditMessagesBefore,
    ExportIMAuditCSV,
    GetIMAuditUsers,
    OpenFileOrShowInFolder,
    QueryIMAuditMessages,
    RevealIMAuditAttachment,
} from "../../../wailsjs/go/main/App";
import { useSafeBackdropDismiss } from "../../hooks/useSafeBackdropDismiss";
import { useDialog } from "../CustomDialog";

interface IMAuditMessage {
    id: number;
    timestamp: string;
    user_id: string;
    platform: string;
    role: "user" | "assistant";
    content: string;
    attachment_path?: string;
    attachment_name?: string;
    attachment_media_type?: string;
    attachment_size?: number;
}

interface IMAuditQueryResult {
    messages: IMAuditMessage[];
    total: number;
    page: number;
    page_size: number;
}

type InitialAuditResult = {
    platform: string;
    result: IMAuditQueryResult;
};

interface IMAuditPanelProps {
    platform: string;
    onClose: () => void;
    lang: string;
}

const platformLabels: Record<string, { zh: string; en: string }> = {
    qq: { zh: "QQ", en: "QQ" },
    telegram: { zh: "Telegram", en: "Telegram" },
    weixin: { zh: "\u5fae\u4fe1", en: "WeChat" },
    lansenger: { zh: "\u84dd\u4fe1", en: "Lansenger" },
    thirdparty: { zh: "\u7b2c\u4e09\u65b9\u63a5\u5165", en: "Third-party" },
};

function isZhLang(lang: string) {
    return lang === "zh-Hans" || lang === "zh-Hant";
}

function labelForPlatform(platform: string, lang: string) {
    const item = platformLabels[platform];
    if (!item) return platform;
    return isZhLang(lang) ? item.zh : item.en;
}

function formatTimestamp(ts: string): string {
    try {
        const d = new Date(ts);
        if (Number.isNaN(d.getTime())) return ts;
        const pad = (n: number) => String(n).padStart(2, "0");
        return d.getFullYear() + "-" + pad(d.getMonth() + 1) + "-" + pad(d.getDate()) + " " + pad(d.getHours()) + ":" + pad(d.getMinutes()) + ":" + pad(d.getSeconds());
    } catch {
        return ts;
    }
}

function normalizeAuditResult(result: any): IMAuditQueryResult {
    const rawMessages = result?.messages ?? result?.Messages;
    const asPositiveInteger = (value: unknown, fallback: number) => {
        const parsed = Number(value);
        return Number.isFinite(parsed) && parsed > 0 ? Math.floor(parsed) : fallback;
    };
    const messages = Array.isArray(rawMessages)
        ? rawMessages.flatMap((raw, index): IMAuditMessage[] => {
            if (!raw || typeof raw !== "object") return [];
            const item = raw as Record<string, unknown>;
            const content = item.content ?? item.Content;
            if (typeof content !== "string") return [];
            const role = item.role ?? item.Role;
            return [{
                id: asPositiveInteger(item.id ?? item.ID, index + 1),
                timestamp: typeof (item.timestamp ?? item.Timestamp) === "string" ? String(item.timestamp ?? item.Timestamp) : "",
                user_id: typeof (item.user_id ?? item.UserID) === "string" ? String(item.user_id ?? item.UserID) : "",
                platform: typeof (item.platform ?? item.Platform) === "string" ? String(item.platform ?? item.Platform) : "",
                role: role === "user" ? "user" : "assistant",
                content,
                attachment_path: typeof (item.attachment_path ?? item.AttachmentPath) === "string" ? String(item.attachment_path ?? item.AttachmentPath) : "",
                attachment_name: typeof (item.attachment_name ?? item.AttachmentName) === "string" ? String(item.attachment_name ?? item.AttachmentName) : "",
                attachment_media_type: typeof (item.attachment_media_type ?? item.AttachmentMediaType) === "string" ? String(item.attachment_media_type ?? item.AttachmentMediaType) : "",
                attachment_size: Number(item.attachment_size ?? item.AttachmentSize) || 0,
            }];
        })
        : [];
    return {
        messages,
        total: asPositiveInteger(result?.total ?? result?.Total, 0),
        page: asPositiveInteger(result?.page ?? result?.Page, 1),
        page_size: asPositiveInteger(result?.page_size ?? result?.PageSize, 50),
    };
}

function isSafeAuditLink(href: string | undefined): href is string {
    return Boolean(href && /^https?:\/\//i.test(href));
}

/**
 * IM messages are often generated by assistants, so render the common GFM
 * structures instead of treating the whole payload as preformatted plain text.
 * Raw HTML remains disabled by react-markdown, which keeps audit content inert.
 */
const auditMarkdownComponents: Components = {
    a: ({ href, children }) => isSafeAuditLink(href)
        ? <a href={href} target="_blank" rel="noopener noreferrer" className="im-audit-link">{children}</a>
        : <span>{children}</span>,
    code: ({ className, children, inline, node: _node, ...props }) => {
        const isBlock = !inline;
        return isBlock
            ? <code className={className} {...props}>{children}</code>
            : <code className="im-audit-inline-code" {...props}>{children}</code>;
    },
    table: ({ children }) => (
        <div className="im-audit-table-scroll">
            <table>{children}</table>
        </div>
    ),
};
const auditMarkdownPlugins = [remarkGfm];

function formatFileSize(bytes?: number) {
    const value = Number(bytes) || 0;
	if (value <= 0) return "";
    if (value < 1024) return `${value} B`;
    if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`;
    return `${(value / (1024 * 1024)).toFixed(1)} MB`;
}

function auditAttachmentSubtitle(message: IMAuditMessage, isZh: boolean) {
    const size = formatFileSize(message.attachment_size);
	const action = message.attachment_path
		? (isZh ? "打开所在目录" : "Open containing folder")
		: (isZh ? "未保存到本地" : "Not saved locally");
	return size ? `${size} · ${action}` : action;
}

type AuditMessageCardProps = {
    message: IMAuditMessage;
    isZh: boolean;
    onRevealError: () => void;
};

/** Isolate expensive GFM parsing from toolbar-only state changes. */
const AuditMessageCard = memo(function AuditMessageCard({ message, isZh, onRevealError }: AuditMessageCardProps) {
    const isUser = message.role === "user";
    return (
        <div className="im-audit-item" data-role={isUser ? "user" : "assistant"}>
            <div className="im-audit-meta">
                <span>{isUser ? (message.user_id || (isZh ? "\u7528\u6237" : "User")) : "MaClaw"}</span>
                <span>{formatTimestamp(message.timestamp)}</span>
            </div>
            <div className="im-audit-bubble">
                {message.content && <ReactMarkdown remarkPlugins={auditMarkdownPlugins} components={auditMarkdownComponents}>{message.content}</ReactMarkdown>}
                {message.attachment_name && (message.attachment_path ? (
                    <button type="button" className="im-audit-attachment" onClick={() => void Promise.resolve(RevealIMAuditAttachment(message.attachment_path!)).catch(onRevealError)}>
                        <span className="im-audit-attachment__icon" aria-hidden="true">↗</span>
                        <span className="im-audit-attachment__copy">
                            <strong>{message.attachment_name || (isZh ? "文件附件" : "File attachment")}</strong>
                            <small>{auditAttachmentSubtitle(message, isZh)}</small>
                        </span>
                    </button>
                ) : (
                    <div className="im-audit-attachment im-audit-attachment--unavailable">
                        <span className="im-audit-attachment__icon" aria-hidden="true">–</span>
                        <span className="im-audit-attachment__copy"><strong>{message.attachment_name}</strong><small>{auditAttachmentSubtitle(message, isZh)}</small></span>
                    </div>
                ))}
            </div>
        </div>
    );
});

export function IMAuditPanel({ platform, onClose, lang }: IMAuditPanelProps) {
    const { showConfirm } = useDialog();
    const [messages, setMessages] = useState<IMAuditMessage[]>([]);
    const [total, setTotal] = useState(0);
    const [page, setPage] = useState(1);
    const [pageSize, setPageSize] = useState(50);
    const [keyword, setKeyword] = useState("");
    const [searchInput, setSearchInput] = useState("");
    const [userID, setUserID] = useState("");
    const [users, setUsers] = useState<string[]>([]);
    const [loading, setLoading] = useState(false);
    const [exporting, setExporting] = useState(false);
    const [cleaning, setCleaning] = useState(false);
    const [cleanupDays, setCleanupDays] = useState(30);
    const [showCleanup, setShowCleanup] = useState(false);
    const [message, setMessage] = useState("");
    const [refreshKey, setRefreshKey] = useState(0);
    const [initDone, setInitDone] = useState(false);
    const listRef = useRef<HTMLDivElement>(null);
    const scrollFrameRef = useRef<number | null>(null);
    const querySequenceRef = useRef(0);
    const initialResultRef = useRef<InitialAuditResult | null>(null);
    const cleanupPendingRef = useRef(false);
    const platformRef = useRef(platform);
    const { backdropProps, dialogProps } = useSafeBackdropDismiss(onClose);

    // Keep async completions scoped to the platform rendered in this commit.
    platformRef.current = platform;
    const isZh = isZhLang(lang);
    const isZhRef = useRef(isZh);
    const totalPages = Math.max(1, Math.ceil(total / pageSize));
    const title = labelForPlatform(platform, lang) + (isZh ? " \u804a\u5929\u5386\u53f2" : " Chat History");

    useEffect(() => { isZhRef.current = isZh; }, [isZh]);

    useEffect(() => {
        let active = true;
        GetIMAuditUsers(platform)
            .then((nextUsers) => { if (active) setUsers(nextUsers); })
            .catch(() => { if (active) setUsers([]); });
        return () => { active = false; };
    }, [platform]);

    useEffect(() => {
        setInitDone(false);
        querySequenceRef.current += 1;
        initialResultRef.current = null;
        setCleaning(false);
        setShowCleanup(false);
        setPage(1);
        setKeyword("");
        setSearchInput("");
        setUserID("");
        setMessage("");
    }, [platform]);

    useEffect(() => {
        if (initDone) return;
        let active = true;
        (async () => {
            try {
                const result = normalizeAuditResult(await QueryIMAuditMessages(platform, "", "", 1));
                if (!active || platformRef.current !== platform) return;
                const lastPage = Math.max(1, Math.ceil(result.total / (result.page_size || 50)));
                // The startup result is page one. Reuse it only when page one is
                // also the page we will show; otherwise keeping it around would
                // make a later "empty" search render stale data.
                initialResultRef.current = lastPage === 1 ? { platform, result } : null;
                setTotal(result.total);
                setPageSize(result.page_size || 50);
                setPage(lastPage);
            } catch (err) {
                if (active && platformRef.current === platform) console.error("[im-audit] init error:", err);
            } finally {
                if (active && platformRef.current === platform) setInitDone(true);
            }
        })();
        return () => { active = false; };
    }, [platform, initDone]);

    const loadMessages = useCallback(async () => {
        if (!initDone) return;
        const querySequence = ++querySequenceRef.current;
        setLoading(true);
        try {
            const initial = initialResultRef.current;
            const canUseInitialResult = !userID && !keyword && page === 1 && initial?.platform === platform;
            const result = canUseInitialResult
                ? initial.result
                : normalizeAuditResult(await QueryIMAuditMessages(platform, userID, keyword, page));
            if (canUseInitialResult) initialResultRef.current = null;
            if (querySequence !== querySequenceRef.current || platformRef.current !== platform) return;
            setMessages(result.messages || []);
            setTotal(result.total);
            setPageSize(result.page_size || 50);
            setMessage("");
        } catch (err) {
            if (querySequence !== querySequenceRef.current || platformRef.current !== platform) return;
            console.error("[im-audit] query error:", err);
            setMessage(isZhRef.current ? "\u52a0\u8f7d\u6d88\u606f\u8bb0\u5f55\u5931\u8d25" : "Failed to load audit messages");
        } finally {
            if (querySequence === querySequenceRef.current && platformRef.current === platform) setLoading(false);
        }
    }, [platform, userID, keyword, page, refreshKey, initDone]);

    useEffect(() => { loadMessages(); }, [loadMessages]);

    useEffect(() => {
        if (messages.length > 0) {
            if (scrollFrameRef.current !== null) cancelAnimationFrame(scrollFrameRef.current);
            scrollFrameRef.current = requestAnimationFrame(() => {
                const list = listRef.current;
                if (list && typeof list.scrollTo === "function") {
                    list.scrollTo({ top: list.scrollHeight });
                }
                scrollFrameRef.current = null;
            });
        }
        return () => {
            if (scrollFrameRef.current !== null) {
                cancelAnimationFrame(scrollFrameRef.current);
                scrollFrameRef.current = null;
            }
        };
    }, [messages]);

    const handleSearch = () => {
        setKeyword(searchInput.trim());
        setPage(1);
        setRefreshKey(k => k + 1);
    };

    const handleRefresh = () => {
        setPage(Math.max(1, Math.ceil(total / pageSize)));
        setRefreshKey(k => k + 1);
    };

    const handleRevealError = useCallback(() => {
		setMessage(isZhRef.current ? "无法打开文件所在目录，文件可能已被移动或删除" : "Could not open the containing folder; the file may have moved or been deleted");
	}, []);

    const handleCleanup = async () => {
        if (cleaning || cleanupPendingRef.current) return;
        cleanupPendingRef.current = true;
        const cleanupPlatform = platform;
        let confirmed = false;
        try {
            confirmed = await showConfirm(isZh ? "确定删除 " + cleanupDays + " 天前的记录？" : "Delete records older than " + cleanupDays + " days?", isZh ? '清理记录' : 'Clean up records', { confirmText: isZh ? '删除' : 'Delete', cancelText: isZh ? '取消' : 'Cancel', confirmVariant: 'danger' });
        } catch (err) {
            console.error("[im-audit] cleanup confirmation error:", err);
            if (platformRef.current === cleanupPlatform) {
                setMessage(isZhRef.current ? "清理消息记录失败" : "Failed to clean up audit messages");
            }
        }
        if (!confirmed) {
            cleanupPendingRef.current = false;
            return;
        }
        setCleaning(true);
        try {
            const n = await DeleteIMAuditMessagesBefore(cleanupDays);
            if (platformRef.current !== cleanupPlatform) return;
            setMessage(isZh ? "\u5df2\u5220\u9664 " + n + " \u6761\u8bb0\u5f55" : "Deleted " + n + " records");
            setPage(1);
            setKeyword("");
            setSearchInput("");
            setUserID("");
            setRefreshKey(k => k + 1);
            GetIMAuditUsers(cleanupPlatform)
                .then((nextUsers) => { if (platformRef.current === cleanupPlatform) setUsers(nextUsers); })
                .catch(() => {});
        } catch (err) {
            console.error("[im-audit] cleanup error:", err);
            if (platformRef.current === cleanupPlatform) {
                setMessage(isZh ? "\u6e05\u7406\u6d88\u606f\u8bb0\u5f55\u5931\u8d25" : "Failed to clean up audit messages");
            }
        } finally {
            cleanupPendingRef.current = false;
            setCleaning(false);
            setShowCleanup(false);
        }
    };

    const handleExport = async () => {
        setExporting(true);
        try {
            const filePath = await ExportIMAuditCSV(platform, userID, keyword);
            if (!filePath) throw new Error("empty export path");
            await OpenFileOrShowInFolder(filePath);
            setMessage(isZh ? "\u5df2\u5bfc\u51fa CSV" : "CSV exported");
        } catch (err) {
            console.error("[im-audit] export error:", err);
            setMessage(isZh ? "\u5bfc\u51fa CSV \u5931\u8d25" : "Failed to export CSV");
        } finally {
            setExporting(false);
        }
    };

    return (
        <div className="im-audit-overlay" {...backdropProps}>
            <div
                className="im-audit-panel"
                {...dialogProps}
            >
                <div className="im-audit-header">
                    <div className="im-audit-title-wrap">
                        <span className="im-audit-title">{title}</span>
                        <span className="im-audit-total">{isZh ? "\u5171 " + total + " \u6761" : total + " total"}</span>
                    </div>
                    <button type="button" onClick={onClose} aria-label={isZh ? "\u5173\u95ed" : "Close"} className="im-audit-close">{"\u00d7"}</button>
                </div>

                <div className="im-audit-toolbar">
                    <input
                        type="text"
                        value={searchInput}
                        onChange={e => setSearchInput(e.target.value)}
                        onKeyDown={e => { if (e.key === "Enter") handleSearch(); }}
                        placeholder={isZh ? "\u641c\u7d22\u6d88\u606f\u5185\u5bb9..." : "Search messages..."}
                        aria-label={isZh ? "\u641c\u7d22\u6d88\u606f\u5185\u5bb9" : "Search message content"}
                        className="im-audit-input"
                    />
                    <button type="button" onClick={handleSearch} className="im-audit-toolbar-button">{isZh ? "\u641c\u7d22" : "Search"}</button>
                    <button type="button" onClick={handleRefresh} disabled={loading} className="im-audit-toolbar-button">{loading ? "..." : (isZh ? "\u5237\u65b0" : "Refresh")}</button>

                    {users.length > 0 && (
                        <select aria-label={isZh ? "\u7528\u6237\u7b5b\u9009" : "User filter"} value={userID} onChange={e => { setUserID(e.target.value); setPage(1); }} className="im-audit-select">
                            <option value="">{isZh ? "\u5168\u90e8\u7528\u6237" : "All users"}</option>
                            {users.map(u => <option key={u} value={u}>{u}</option>)}
                        </select>
                    )}

                    <button type="button" onClick={handleExport} disabled={exporting} className="im-audit-toolbar-button">{exporting ? "..." : (isZh ? "\u5bfc\u51fa CSV" : "Export CSV")}</button>

                    <div className="im-audit-cleanup-wrap">
                        <button type="button" onClick={() => setShowCleanup(!showCleanup)} disabled={cleaning} aria-expanded={showCleanup} className="im-audit-toolbar-button im-audit-toolbar-button--danger">
                            {isZh ? "\u6e05\u7406" : "Cleanup"}
                        </button>
                        {showCleanup && (
                            <div className="im-audit-cleanup-popover" role="dialog" aria-label={isZh ? "\u6e05\u7406\u6d88\u606f\u8bb0\u5f55" : "Clean up audit messages"}>
                                <div className="im-audit-cleanup-copy">
                                    {isZh ? "\u5220\u9664\u591a\u5c11\u5929\u524d\u7684\u8bb0\u5f55\uff1f" : "Delete records older than:"}
                                </div>
                                <div className="im-audit-cleanup-days">
                                    {[7, 14, 30, 60, 90].map(d => (
                                        <button type="button" key={d} onClick={() => setCleanupDays(d)} disabled={cleaning} className="im-audit-day-button" data-active={cleanupDays === d ? "true" : "false"}>{d} {isZh ? "\u5929" : "days"}</button>
                                    ))}
                                </div>
                                <button type="button" onClick={handleCleanup} disabled={cleaning} className="im-audit-cleanup-confirm">
                                    {cleaning ? "..." : (isZh ? "\u786e\u8ba4\u5220\u9664 " + cleanupDays + " \u5929\u524d\u7684\u8bb0\u5f55" : "Delete records older than " + cleanupDays + " days")}
                                </button>
                            </div>
                        )}
                    </div>
                </div>

                {message && <div className="im-audit-message" role="status">{message}</div>}

                <div ref={listRef} className="im-audit-list" aria-busy={loading}>
                    {loading && messages.length === 0 && <div className="im-audit-empty">{isZh ? "\u52a0\u8f7d\u4e2d..." : "Loading..."}</div>}
                    {loading && messages.length > 0 && <div className="im-audit-refreshing" role="status">{isZh ? "\u6b63\u5728\u66f4\u65b0..." : "Refreshing..."}</div>}
                    {!loading && messages.length === 0 && <div className="im-audit-empty">{isZh ? "\u6682\u65e0\u6d88\u606f\u8bb0\u5f55" : "No messages found"}</div>}
                    {messages.map(msg => <AuditMessageCard key={msg.id} message={msg} isZh={isZh} onRevealError={handleRevealError} />)}
                </div>

                {totalPages > 1 && (
                    <div className="im-audit-pagination">
                        <button type="button" aria-label={isZh ? "\u4e0a\u4e00\u9875" : "Previous page"} disabled={page <= 1 || loading} onClick={() => setPage(p => Math.max(1, p - 1))} className="im-audit-page-button">{isZh ? "\u4e0a\u4e00\u9875" : "Prev"}</button>
                        <span className="im-audit-page-label">{page} / {totalPages}</span>
                        <button type="button" aria-label={isZh ? "\u4e0b\u4e00\u9875" : "Next page"} disabled={page >= totalPages || loading} onClick={() => setPage(p => Math.min(totalPages, p + 1))} className="im-audit-page-button">{isZh ? "\u4e0b\u4e00\u9875" : "Next"}</button>
                    </div>
                )}
            </div>
        </div>
    );
}
