// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function Download(arg1) {
  return window['go']['main']['App']['Download'](arg1);
}

export function ExecuteToolMessage(arg1) {
  return window['go']['main']['App']['ExecuteToolMessage'](arg1);
}

export function Poll(arg1) {
  return window['go']['main']['App']['Poll'](arg1);
}

export function SelectUploadFiles(arg1) {
  return window['go']['main']['App']['SelectUploadFiles'](arg1);
}

export function Send(arg1) {
  return window['go']['main']['App']['Send'](arg1);
}
