// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Connect(arg1:main.ConnectInput):Promise<main.ConnectResult>;

export function Poll(arg1:main.PollInput):Promise<main.OutgoingResponse>;

export function Send(arg1:main.SendInput):Promise<main.IncomingResponse>;
