// KB image marker validation, extracted from aiAssistantMarkdown.tsx
// (line-count guard). Pure string/byte checks; no React or theme deps.
// Security contract: only thumbnail data URLs produced by the local
// knowledge-image tool may reach an <img> — see comments below.

// KB image markers are emitted by the local knowledge-image tool. Accept only
// the thumbnail data URLs generated by that tool: letting model-authored marker
// text point img.src at an arbitrary http(s) URL would silently make a network
// request while rendering a chat reply.
const KB_IMAGE_DATA_URL_RE = /^data:image\/jpeg;base64,[A-Za-z0-9+/]+={0,2}$/i;
export const KB_IMAGE_MARKER_RE = /^\[KB_IMAGE:([A-Za-z0-9_-]{1,200})\|([^|\]]+)\]$/;
// Mirrors knowledge.MaxKBImageMarkerDataBytes. A marker is model-visible text,
// so syntax validation alone must not allow an arbitrary data URL to be handed
// to the browser image decoder. This is intentionally a character ceiling to
// avoid decoding untrusted base64 in the WebView.
const KB_IMAGE_MAX_DECODED_BYTES = 256 * 1024;

export function isSafeKBImageDataURL(value: string): boolean {
    if (!KB_IMAGE_DATA_URL_RE.test(value)) return false;
    const payload = value.slice("data:image/jpeg;base64,".length);
    if (payload.length % 4 !== 0) return false;
    const padding = payload.endsWith("==") ? 2 : payload.endsWith("=") ? 1 : 0;
    // The regex above has already guaranteed a valid quartet length. Computing
    // decoded size from its final padding avoids allocating a model-authored
    // base64 string just to enforce the same byte ceiling as the Go producer.
    if (Math.floor(payload.length / 4) * 3 - padding > KB_IMAGE_MAX_DECODED_BYTES) return false;
    // A syntactically valid data URL is not sufficient: before it reaches an
    // img element, require the same bounded JPEG-thumbnail shape produced by
    // the managed knowledge asset pipeline. The browser's onLoad below still
    // performs a complete decode before the opaque asset can be opened.
    try {
        return isBoundedKBImageJPEG(atob(payload));
    } catch {
        return false;
    }
}

// isBoundedKBImageJPEG performs a bounded JPEG header scan after base64 decode.
// It is not a replacement for browser decoding; it rejects non-JPEG bytes and
// oversized SOF dimensions synchronously, while KBImageThumbnail waits for
// onLoad before enabling the asset-ID-only open action. This mirrors the Go
// producer's JPEG and ThumbSize boundary without accepting arbitrary base64 as
// an image.
function isBoundedKBImageJPEG(bytes: string): boolean {
    const length = bytes.length;
    if (length < 12 || bytes.charCodeAt(0) !== 0xff || bytes.charCodeAt(1) !== 0xd8 || bytes.charCodeAt(length - 2) !== 0xff || bytes.charCodeAt(length - 1) !== 0xd9) {
        return false;
    }
    // Look only at the first frame marker. This intentionally avoids treating
    // a later SOF-looking byte sequence as an alternate small image after an
    // oversized frame declaration. Browser onLoad remains the definitive
    // decoder check before the asset-ID action is enabled.
    for (let offset = 2; offset + 8 < length; offset++) {
        if (bytes.charCodeAt(offset) !== 0xff) continue;
        const marker = bytes.charCodeAt(offset + 1);
        const isFrame = (marker >= 0xc0 && marker <= 0xc3)
            || (marker >= 0xc5 && marker <= 0xc7)
            || (marker >= 0xc9 && marker <= 0xcb)
            || (marker >= 0xcd && marker <= 0xcf);
        if (!isFrame) continue;
        const segmentLength = (bytes.charCodeAt(offset + 2) << 8) | bytes.charCodeAt(offset + 3);
        if (segmentLength < 8 || offset + 2 + segmentLength > length) return false;
        const height = (bytes.charCodeAt(offset + 5) << 8) | bytes.charCodeAt(offset + 6);
        const width = (bytes.charCodeAt(offset + 7) << 8) | bytes.charCodeAt(offset + 8);
        return width > 0 && height > 0 && width <= 120 && height <= 120;
    }
    return false;
}
