// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckEnvironment(arg1:boolean):Promise<void>;

export function CheckToolsStatus():Promise<Array<main.ToolStatus>>;

export function CheckUpdate(arg1:string):Promise<main.UpdateResult>;

export function ClipboardGetText():Promise<string>;

export function DeleteSkill(arg1:string,arg2:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function ActivateRemote(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ProbeRemoteHub(arg1:string,arg2:string):Promise<any>;

export function ClearRemoteActivation():Promise<void>;

export function VerifyRemoteActivation():Promise<boolean>;

export function GetCurrentProjectPath():Promise<string>;

export function GetDownloadsFolder():Promise<string>;

export function GetEnvCheckInterval():Promise<number>;

export function GetLocalCacheDir():Promise<string>;

export function GetRemoteActivationStatus():Promise<any>;

export function GetRemoteClaudeReadiness(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolReadiness(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemoteConnectionStatus():Promise<any>;

export function GetRemoteClaudeLaunchProbe(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolLaunchProbe(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemotePTYProbe():Promise<any>;

export function GetLastRemoteSmokeReport():Promise<any>;

export function StartRemoteClaudeSession(arg1:string,arg2:boolean):Promise<any>;

export function StartRemoteSession(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<any>;

export function StartRemoteHandoffSession(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<any>;

export function ListValidProviders(arg1:string):Promise<any>;

export function GetSkillsDir(arg1:string):Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUserHomeDir():Promise<string>;

export function GetBrandInfo():Promise<main.BrandInfo>;

export function InstallDefaultMarketplace():Promise<void>;

export function InstallSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function InstallTool(arg1:string):Promise<void>;

export function InstallToolOnDemand(arg1:string):Promise<void>;

export function IsToolBeingInstalled(arg1:string):Promise<boolean>;

export function IsWindowsTerminalAvailable():Promise<boolean>;

export function LaunchInstallerAndExit(arg1:string):Promise<void>;

export function LaunchTool(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ListPythonEnvironments():Promise<Array<main.PythonEnvironment>>;

export function ListRemoteHubs(arg1:string,arg2:string):Promise<Array<any>>;

export function ListRemoteSessions():Promise<Array<any>>;

export function ListRemoteToolMetadata():Promise<Array<any>>;

export function ListSkills(arg1:string):Promise<Array<main.Skill>>;

export function ListSkillsWithInstallStatus(arg1:string,arg2:string,arg3:string):Promise<Array<main.Skill>>;

export function LoadConfig():Promise<main.AppConfig>;

export function OpenSystemUrl(arg1:string):Promise<void>;

export function PackLog(arg1:string):Promise<string>;

export function ReadBBS():Promise<string>;

export function ReadThanks():Promise<string>;

export function ReadTutorial():Promise<string>;

export function ReconnectRemoteHub():Promise<void>;

export function RunRemoteClaudeSmoke(arg1:string,arg2:boolean):Promise<any>;

export function RunRemoteToolSmoke(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function RecoverCC():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RunEnvironmentCheckCLI():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SelectSkillFile():Promise<string>;

export function SendRemoteSessionImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CaptureRemoteScreenshot(arg1:string):Promise<void>;

export function CaptureRemoteWindowScreenshot(arg1:string,arg2:string):Promise<void>;

export function SendRemoteSessionInput(arg1:string,arg2:string):Promise<void>;

export function SendRemoteSessionRawInput(arg1:string,arg2:string):Promise<void>;

export function SetEnvCheckInterval(arg1:number):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShouldCheckEnvironment():Promise<boolean>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function InterruptRemoteSession(arg1:string):Promise<void>;

export function KillRemoteSession(arg1:string):Promise<void>;

export function UpdateLastEnvCheckTime():Promise<void>;

export function UpdateTool(arg1:string):Promise<void>;

export function WindowHide():Promise<void>;

// NL Skill management bindings
export function ListNLSkills():Promise<Array<any>>;

export function DiagnoseSkillFiles():Promise<Array<any>>;

export function CreateNLSkill(arg1:any):Promise<void>;

export function UpdateNLSkill(arg1:any):Promise<void>;

export function DeleteNLSkill(arg1:string):Promise<void>;

export function ImportNLSkillZip():Promise<string>;

export function ExportLearnedSkillsZip(arg1:Array<string>):Promise<void>;

export function ImportLearnedSkillsZip():Promise<any>;

// MCP management bindings
export function ListMCPServers():Promise<Array<any>>;

export function RegisterMCPServer(arg1:any):Promise<void>;

export function UpdateMCPServer(arg1:any):Promise<void>;

export function UnregisterMCPServer(arg1:string):Promise<void>;

export function GetMCPServerTools(arg1:string):Promise<Array<any>>;

export function CheckMCPServerHealth(arg1:string):Promise<void>;

// Local MCP server management bindings
export function ListLocalMCPServers():Promise<Array<any>>;

export function RegisterLocalMCPServer(arg1:any):Promise<void>;

export function UpdateLocalMCPServer(arg1:any):Promise<void>;

export function UnregisterLocalMCPServer(arg1:string):Promise<void>;

export function SyncLocalMCPServers():Promise<void>;

export function GetLocalMCPServerStatuses():Promise<Array<any>>;

// MaClaw LLM configuration bindings
export function GetMaclawLLMConfig():Promise<any>;

export function SaveMaclawLLMConfig(arg1:any):Promise<void>;

export function GetMaclawLLMProviders():Promise<any>;

export function SaveMaclawLLMProviders(arg1:any, arg2:string):Promise<void>;

export function TestMaclawLLM(arg1:any):Promise<string>;

export function StartOpenAIOAuth():Promise<string>;

export function GetOpenAIUsage():Promise<any>;

export function GetMaclawAgentMaxIterations():Promise<number>;

export function SetMaclawAgentMaxIterations(arg1:number):Promise<void>;

export function GetLLMTrajectoryLogging():Promise<boolean>;

export function SetLLMTrajectoryLogging(arg1:boolean):Promise<void>;

export function GetUIZoomFactor():Promise<number>;

export function SetUIZoomFactor(arg1:number):Promise<void>;

export function GetLLMTokenUsage(arg1:string):Promise<any>;

export function GetAllLLMTokenUsage():Promise<any>;

export function ResetLLMTokenUsage(arg1:string):Promise<void>;

export function PingMaclawLLM():Promise<any>;

export function PingSkillHub(arg1:string):Promise<any>;

export function ValidateSkillHub(arg1:string):Promise<any>;

// SkillHub market bindings
export function SearchSkillHub(arg1:string):Promise<Array<any>>;

export function InstallHubSkill(arg1:string, arg2:string):Promise<void>;

export function CheckHubSkillUpdates():Promise<Array<any>>;

export function UpdateHubSkill(arg1:string):Promise<void>;

export function RateHubSkill(arg1:string, arg2:number):Promise<void>;

// Memory management bindings
export function ListMemories(arg1:string, arg2:string):Promise<Array<any>>;

export function SaveMemory(arg1:string, arg2:string, arg3:Array<string>):Promise<void>;

export function UpdateMemory(arg1:string, arg2:string, arg3:string, arg4:Array<string>):Promise<void>;

export function DeleteMemory(arg1:string):Promise<void>;

// Memory compression & backup bindings
export function CompressMemories():Promise<any>;

export function ListMemoryBackups():Promise<Array<any>>;

export function RestoreMemoryBackup(arg1:string):Promise<void>;

export function DeleteMemoryBackup(arg1:string):Promise<void>;

export function SetAutoCompress(arg1:boolean):Promise<void>;

export function GetAutoCompressStatus():Promise<any>;

export function GetMemoryMaxBackups():Promise<number>;

export function SetMemoryMaxBackups(arg1:number):Promise<void>;

// Scheduled task management bindings
export function ListScheduledTasks():Promise<Array<any>>;

export function CreateScheduledTask(arg1:string, arg2:string, arg3:number, arg4:number, arg5:number, arg6:number, arg7:string, arg8:string):Promise<string>;

export function UpdateScheduledTask(arg1:string, arg2:any):Promise<void>;

export function DeleteScheduledTask(arg1:string):Promise<void>;

export function PauseScheduledTask(arg1:string):Promise<void>;

export function ResumeScheduledTask(arg1:string):Promise<void>;

export function TriggerScheduledTask(arg1:string):Promise<void>;

// ClawNet P2P network bindings
export function ClawNetEnsureDaemon():Promise<any>;

export function ClawNetStopDaemon():Promise<void>;

export function ClawNetIsRunning():Promise<boolean>;

export function ClawNetGetStatus():Promise<any>;

export function ClawNetGetPeers():Promise<any>;

export function ClawNetGetCredits():Promise<any>;

export function ClawNetCreateTask(arg1:string, arg2:number):Promise<any>;

export function ClawNetSearchKnowledge(arg1:string):Promise<any>;
export function ClawNetPublishKnowledge(arg1:string, arg2:string):Promise<any>;
export function ClawNetSendDM(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetDMInbox():Promise<any>;
export function ClawNetListSwarmSessions():Promise<any>;
export function ClawNetCreateSwarmSession(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetResume():Promise<any>;
export function ClawNetListPredictions():Promise<any>;

export function ClawNetGetBinaryPath():Promise<string>;

export function ClawNetInstallBinary():Promise<any>;

export function ClawNetEnsureDaemonWithDownload():Promise<any>;

export function ClawNetManualUpdate():Promise<any>;

export function ClawNetListTasks(arg1:string):Promise<any>;

// ClawNet extended bindings
export function ClawNetGetProfile():Promise<any>;
export function ClawNetUpdateProfile(arg1:string, arg2:string):Promise<any>;
export function ClawNetSetMotto(arg1:string):Promise<any>;
export function ClawNetListTopics():Promise<any>;
export function ClawNetCreateTopic(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetTopicMessages(arg1:string):Promise<any>;
export function ClawNetPostTopicMessage(arg1:string, arg2:string):Promise<any>;
export function ClawNetBidOnTask(arg1:string, arg2:number, arg3:string):Promise<any>;
export function ClawNetSubmitTaskResult(arg1:string, arg2:string):Promise<any>;
export function ClawNetApproveTask(arg1:string):Promise<any>;
export function ClawNetRejectTask(arg1:string):Promise<any>;
export function ClawNetCancelTask(arg1:string):Promise<any>;
export function ClawNetGetTaskBids(arg1:string):Promise<any>;
export function ClawNetMatchTasks():Promise<any>;
export function ClawNetGetTaskBoard():Promise<any>;
export function ClawNetGetTransactions():Promise<any>;
export function ClawNetGetLeaderboard():Promise<any>;
export function ClawNetGetDaemonInfo():Promise<any>;
export function ClawNetGetDiagnostics():Promise<any>;
export function ClawNetGetCreditsAudit():Promise<any>;
export function ClawNetSelfUpdate():Promise<any>;
export function ClawNetGetKnowledgeFeed(arg1:string, arg2:number):Promise<any>;
export function ClawNetGetDMThread(arg1:string, arg2:number):Promise<any>;
export function ClawNetHasIdentity():Promise<any>;
export function ClawNetExportIdentity():Promise<any>;
export function ClawNetImportIdentity():Promise<any>;
export function ClawNetOnlineBackupKey(arg1:string):Promise<any>;
export function ClawNetOnlineRestoreKey(arg1:string):Promise<any>;

// ClawNet Hub-relayed task discovery
export function ClawNetBrowseNetworkTasks():Promise<any>;
export function ClawNetPublishTasksToHub():Promise<any>;

// ClawNet Auto Task Picker
export function ClawNetAutoPickerGetStatus():Promise<any>;
export function ClawNetAutoPickerConfigure(arg1:boolean, arg2:number, arg3:number, arg4:Array<string>):Promise<any>;
export function ClawNetAutoPickerTriggerNow():Promise<any>;
export function ClawNetManualPickTask(arg1:string):Promise<any>;

// ClawNet extended bindings (Swarm, Knowledge, Resume, etc.)
export function ClawNetUpdateResume(arg1:Array<string>, arg2:Array<string>, arg3:string):Promise<any>;
export function ClawNetJoinSwarm(arg1:string):Promise<any>;
export function ClawNetContributeToSwarm(arg1:string, arg2:string, arg3:string):Promise<any>;
export function ClawNetSynthesizeSwarm(arg1:string):Promise<any>;
export function ClawNetReactKnowledge(arg1:string, arg2:string):Promise<any>;
export function ClawNetReplyKnowledge(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetKnowledgeReplies(arg1:string):Promise<any>;
export function ClawNetPublishKnowledgeFull(arg1:string, arg2:string, arg3:Array<string>):Promise<any>;
export function ClawNetAssignTask(arg1:string, arg2:string):Promise<any>;
export function ClawNetClaimTask(arg1:string):Promise<any>;
export function ClawNetCreateTaskFull(arg1:string, arg2:string, arg3:number, arg4:Array<string>, arg5:string):Promise<any>;
export function ClawNetMatchAgentsForTask(arg1:string):Promise<any>;
export function ClawNetSubmitTaskWork(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetTaskSubmissions(arg1:string):Promise<any>;
export function ClawNetPickTaskWinner(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetOverlayStatus():Promise<any>;
export function ClawNetGetOverlayPeersGeo():Promise<any>;
export function ClawNetCreatePrediction(arg1:string, arg2:Array<string>):Promise<any>;
export function ClawNetPlaceBet(arg1:string, arg2:string, arg3:number):Promise<any>;
export function ClawNetResolvePrediction(arg1:string, arg2:string):Promise<any>;
export function ClawNetAppealPrediction(arg1:string, arg2:string):Promise<any>;
export function ClawNetGetPredictionLeaderboard():Promise<any>;

// Nutshell bindings
export function ClawNetNutshellStatus():Promise<any>;
export function ClawNetNutshellInstall():Promise<any>;
export function ClawNetNutshellInit(arg1:string):Promise<any>;
export function ClawNetNutshellCheck(arg1:string):Promise<any>;
export function ClawNetNutshellPublish(arg1:string, arg2:number):Promise<any>;
export function ClawNetNutshellClaim(arg1:string, arg2:string):Promise<any>;
export function ClawNetNutshellDeliver(arg1:string):Promise<any>;
export function ClawNetNutshellPack(arg1:string, arg2:string, arg3:string):Promise<any>;
export function ClawNetNutshellUnpack(arg1:string, arg2:string):Promise<any>;

// AI Assistant bindings
export function SendAIAssistantMessage(arg1:string):Promise<any>;

export function ClearAIAssistantHistory():Promise<void>;

// Background Loop bindings
export function ListBackgroundLoops():Promise<Array<any>>;

export function StopBackgroundLoop(arg1:string):Promise<void>;

export function ContinueBackgroundLoop(arg1:string, arg2:number):Promise<void>;

export function GetBackgroundLoopOutput(arg1:string):Promise<Array<string>>;

// Agent Skill compatibility bindings
export function ImportAgentSkillDir(arg1:string):Promise<string>;

export function ExportAgentSkillDir(arg1:string, arg2:string):Promise<void>;

// QQ Bot gateway bindings
export function GetQQBotStatus():Promise<string>;

export function RestartQQBot():Promise<string>;

// Telegram Bot gateway bindings
export function GetTelegramStatus():Promise<string>;

export function RestartTelegram():Promise<string>;

// WeChat gateway bindings
export function GetWeixinStatus():Promise<string>;

export function RestartWeixin():Promise<string>;

export function StopWeixin():Promise<void>;

export function StartWeixinQRLogin():Promise<Record<string, string>>;

export function WaitWeixinQRLogin(arg1:string):Promise<Record<string, string>>;

export function GetWeixinLocalMode():Promise<boolean>;

export function SetWeixinLocalMode(arg1:boolean):Promise<void>;

export function GetQQBotLocalMode():Promise<boolean>;

export function SetQQBotLocalMode(arg1:boolean):Promise<void>;

export function GetTelegramLocalMode():Promise<boolean>;

export function SetTelegramLocalMode(arg1:boolean):Promise<void>;

// Gossip bindings
export function GossipSnapshot(arg1:string):Promise<any>;

export function GossipPublish(arg1:string, arg2:string):Promise<any>;

export function GossipComment(arg1:string, arg2:string, arg3:number):Promise<any>;

export function GossipRate(arg1:string, arg2:number):Promise<any>;

export function GossipGetComments(arg1:string, arg2:number):Promise<any>;

export function IsGossipAllowed():Promise<boolean>;

export function GetHubSecurityPolicy():Promise<any>;

export function IsHubSecurityReadOnly():Promise<boolean>;

// NL Skill upload binding
export function UploadNLSkillToMarket(arg1:string):Promise<string>;


// Free proxy bindings
export function StartFreeProxy():Promise<string>;

export function StopFreeProxy():Promise<string>;

export function IsFreeProxyRunning():Promise<boolean>;

export function DetectChrome():Promise<string>;

export function LaunchChromeDebug():Promise<string>;

export function IsDangbeiLoggedIn():Promise<boolean>;

export function DetectBrowser():Promise<Record<string, string>>;

export function DangbeiLogin():Promise<void>;

export function DangbeiFinishLogin():Promise<string>;

export function DangbeiEnsureAuth():Promise<string>;

export function GetFreeProxyModels():Promise<Array<Record<string, string>>>;

export function GetFreeProxyModel():Promise<string>;

export function SetFreeProxyModel(arg1:string):Promise<void>;

export function GetVectorSearchEnabled():Promise<boolean>;

export function SetVectorSearchEnabled(arg1:boolean):Promise<void>;

export function CheckEmbeddingModel():Promise<{[key:string]:any}>;

export function DownloadEmbeddingModel():Promise<void>;
