// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckEnvironment(arg1:boolean):Promise<void>;

export function CheckToolsStatus():Promise<Array<main.ToolStatus>>;

export function CheckUpdate(arg1:string):Promise<main.UpdateResult>;

export function ClipboardGetText():Promise<string>;

export function DeleteSkill(arg1:string,arg2:string):Promise<void>;

export function DeletePassthroughCommand(arg1:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function ExportPassthroughCommand(arg1:string):Promise<string>;

export function GetPassthroughCommand(arg1:string):Promise<any>;

export function GetPassthroughSettings():Promise<any>;

export function ListPassthroughCommands():Promise<Array<any>>;

export function ListPassthroughAudit(arg1:number):Promise<Array<any>>;

export function PassthroughRegistryPath():Promise<string>;

export function PreviewPassthroughCommand(arg1:string,arg2:any):Promise<Array<string>>;

export function PreviewPassthroughDraftCommand(arg1:any,arg2:any):Promise<Array<string>>;

export function RunPassthroughCommand(arg1:string,arg2:any,arg3:boolean):Promise<any>;

export function SavePassthroughCommand(arg1:any):Promise<any>;

export function SavePassthroughSettings(arg1:any):Promise<any>;

export function SetPassthroughCommandEnabled(arg1:string,arg2:boolean):Promise<void>;

export function ActivateRemote(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ProbeRemoteHub(arg1:string,arg2:string):Promise<any>;

export function ClearRemoteActivation():Promise<void>;

export function VerifyRemoteActivation():Promise<boolean>;

export function GetCurrentProjectPath():Promise<string>;

export function GetDownloadsFolder():Promise<string>;

export function GetEnvCheckInterval():Promise<number>;

export function GetLocalCacheDir():Promise<string>;

export function GetRemoteActivationStatus():Promise<any>;

export function GroupDiscussionStatus():Promise<any>;

export function GroupDiscussionPublishProfile():Promise<any>;

export function GroupDiscussionListExperts():Promise<any>;

export function GroupDiscussionListMine(arg1:string):Promise<any>;

export function GroupDiscussionListInvites():Promise<any>;

export function GroupDiscussionProcessPendingInvites():Promise<any>;

export function GroupDiscussionCreateConsultation(arg1:any):Promise<any>;

export function GroupDiscussionStartAuthorizedConsultation(arg1:any):Promise<any>;

export function GroupDiscussionRankExperts(arg1:any):Promise<any>;

export function GroupDiscussionGetConsultation(arg1:string):Promise<any>;

export function GroupDiscussionGetConsultationDetail(arg1:string):Promise<any>;

export function GroupDiscussionGetReadiness(arg1:string):Promise<any>;

export function GroupDiscussionGetWorkflowState(arg1:string):Promise<any>;

export function GroupDiscussionSuggestEscalationRoute(arg1:string):Promise<any>;

export function GroupDiscussionBuildWorkflowActionDraft(arg1:string):Promise<any>;

export function GroupDiscussionGetRollbackReadiness(arg1:string,arg2:string):Promise<any>;

export function GroupDiscussionSummarizeResult(arg1:any):Promise<any>;

export function GroupDiscussionSendInvitation(arg1:string,arg2:any):Promise<string>;

export function GroupDiscussionAcceptInvite(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionRejectInvite(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionSendMessage(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionAddProposal(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionAddReview(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionDecide(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionEscalate(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionSubmitResult(arg1:string,arg2:any):Promise<void>;

export function GroupDiscussionSetState(arg1:string,arg2:string):Promise<void>;

export function GroupDiscussionCleanupStale(arg1:any):Promise<any>;

export function GetRemoteClaudeReadiness(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolReadiness(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemoteConnectionStatus():Promise<any>;

export function GetRemoteClaudeLaunchProbe(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolLaunchProbe(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemotePTYProbe():Promise<any>;

export function SearchProjects(arg1:string,arg2:number):Promise<Array<main.ProjectSearchResult>>;

export function CreateRecentTask(arg1:string):Promise<main.ProjectSearchResult>;

export function ResumeProject(arg1:string):Promise<string>;

export function RenameTask(arg1:string,arg2:string):Promise<string>;

export function PinTask(arg1:string,arg2:boolean):Promise<void>;

export function HideTask(arg1:string):Promise<void>;

export function GetTTSEnabled():Promise<boolean>;

export function GetTTSVoiceID():Promise<string>;

export function SetTTSEnabled(arg1:boolean):Promise<void>;

export function SetTTSVoiceID(arg1:string):Promise<void>;

export function SpeakText(arg1:string):Promise<void>;
export function SpeakPlainText(arg1:string):Promise<void>;

export function CheckTTSModel():Promise<{exists: boolean, size: number, voice_id?: string, model_exists?: boolean, voices_exists?: boolean, voice_zip_exists?: boolean, path?: string}>;

export function DownloadTTSModel():Promise<void>;

export function GetLastRemoteSmokeReport():Promise<any>;

export function StartRemoteClaudeSession(arg1:string,arg2:boolean):Promise<any>;

export function StartRemoteSession(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<any>;

export function StartRemoteHandoffSession(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<any>;

export function ListValidProviders(arg1:string):Promise<any>;

export function GetSkillsDir(arg1:string):Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUserHomeDir():Promise<string>;

export function GetMaclawBaseDir():Promise<string>;

export function SetDataDir(newDir:string):Promise<string>;

export function GetBrandInfo():Promise<main.BrandInfo>;

export function InstallDefaultMarketplace():Promise<void>;

export function InstallSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function InstallTool(arg1:string):Promise<void>;

export function InstallToolOnDemand(arg1:string):Promise<void>;

export function IsToolBeingInstalled(arg1:string):Promise<boolean>;

export function IsWindowsTerminalAvailable():Promise<boolean>;

export function IsNativeRoundedCorners():Promise<boolean>;

export function IsWebviewTransparent():Promise<boolean>;

export function GetFramelessTopInset():Promise<number>;

export function LaunchInstallerAndExit(arg1:string):Promise<void>;

export function LaunchTool(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ListPythonEnvironments():Promise<Array<main.PythonEnvironment>>;

export function ListRemoteHubs(arg1:string,arg2:string):Promise<Array<any>>;

export function ListRemoteSessions():Promise<Array<any>>;

export function GetExperienceAuditHealth():Promise<any>;

export function ListExperienceAudit():Promise<Array<any>>;

export function ListRemoteToolMetadata():Promise<Array<any>>;

export function ListToolProviders(arg1:string):Promise<Array<any>>;

export function ListSkills(arg1:string):Promise<Array<main.Skill>>;

export function ListSkillsWithInstallStatus(arg1:string,arg2:string,arg3:string):Promise<Array<main.Skill>>;

export function LoadConfig():Promise<main.AppConfig>;

export function MaximiseAndSaveGeometry():Promise<boolean>;

export function OpenSystemUrl(arg1:string):Promise<void>;

export function PackLog(arg1:string):Promise<string>;

export function ReadBBS():Promise<string>;

export function ReadThanks():Promise<string>;

export function ReadTutorial():Promise<string>;

export function ReconnectRemoteHub():Promise<void>;

export function RunRemoteClaudeSmoke(arg1:string,arg2:boolean):Promise<any>;

export function RunRemoteToolSmoke(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function RecoverCC():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RestoreWindowGeometry():Promise<void>;

export function RunEnvironmentCheckCLI():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SetDefaultLaunchMode(arg1:string):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SelectWorkingDir():Promise<string>;

export function SetWorkflowWorkingDir(arg1:string):Promise<void>;

export function GetWorkflowWorkingDir():Promise<string>;

export function SelectSkillFile():Promise<string>;

export function SendRemoteSessionImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CaptureRemoteScreenshot(arg1:string):Promise<void>;

export function CaptureRemoteWindowScreenshot(arg1:string,arg2:string):Promise<void>;

export function SendRemoteSessionInput(arg1:string,arg2:string):Promise<void>;

export function SendRemoteSessionRawInput(arg1:string,arg2:string):Promise<void>;

export function SetEnvCheckInterval(arg1:number):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShouldCheckEnvironment():Promise<boolean>;

export function OpenFileOrShowInFolder(arg1:string):Promise<void>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function InterruptRemoteSession(arg1:string):Promise<void>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function KillRemoteSession(arg1:string):Promise<void>;

export function UpdateLastEnvCheckTime():Promise<void>;

export function UpdateTool(arg1:string):Promise<void>;

export function WindowHide():Promise<void>;

// NL Skill management bindings
export function ListNLSkills():Promise<Array<any>>;

export function DiagnoseSkillFiles():Promise<Array<any>>;

export function ListExternalSkillDirs():Promise<Array<string>>;

export function ListExternalSkillDirsDetailed():Promise<Array<any>>;

export function AddExternalSkillDir(arg1:string):Promise<number>;

export function RemoveExternalSkillDir(arg1:string):Promise<void>;

export function CreateNLSkill(arg1:any):Promise<void>;

export function UpdateNLSkill(arg1:any):Promise<void>;

export function DeleteNLSkill(arg1:string):Promise<void>;

export function ImportNLSkillZip():Promise<string>;

export function ExportLearnedSkillsZip(arg1:Array<string>):Promise<void>;

export function ImportLearnedSkillsZip():Promise<any>;

// MCP management bindings
export function ListMCPServers():Promise<Array<any>>;

export function RegisterMCPServer(arg1:any):Promise<void>;

export function UpdateMCPServer(arg1:any):Promise<void>;

export function UnregisterMCPServer(arg1:string):Promise<void>;

export function GetMCPServerTools(arg1:string):Promise<Array<any>>;

export function CheckMCPServerHealth(arg1:string):Promise<void>;

export function ProbeMCPServers():Promise<Array<any>>;

// Local MCP server management bindings
export function ListLocalMCPServers():Promise<Array<any>>;

export function RegisterLocalMCPServer(arg1:any):Promise<void>;

export function UpdateLocalMCPServer(arg1:any):Promise<void>;

export function UnregisterLocalMCPServer(arg1:string):Promise<void>;

export function SyncLocalMCPServers():Promise<void>;

export function SetLocalMCPAutoStart(arg1:string,arg2:boolean):Promise<void>;

export function GetLocalMCPServerStatuses():Promise<Array<any>>;

// MaClaw LLM configuration bindings
export function GetMaclawLLMConfig():Promise<any>;

export function SaveMaclawLLMConfig(arg1:any):Promise<void>;

export function GetMaclawLLMProviders():Promise<any>;

export function SaveMaclawLLMProviders(arg1:any, arg2:string):Promise<void>;

export function GetWebSearchProviders():Promise<any>;

export function SaveWebSearchProviders(arg1:any, arg2:string):Promise<void>;

export function TestMaclawLLM(arg1:any):Promise<main.MaclawLLMTestResult>;

export function StartOpenAIOAuth():Promise<string>;

export function CancelOpenAIOAuth():Promise<void>;

export function ImportCodexAuth():Promise<string>;

export function StartCodeGenSSO():Promise<any>;

export function StartCodeGenSSOEmbedded():Promise<any>;

export function WaitCodeGenSSOResult():Promise<any>;

export function CancelCodeGenSSOPolling():Promise<void>;

export function FetchCodeGenModels():Promise<Array<any>>;

export function FetchProviderModels(arg1:string,arg2:string,arg3:string):Promise<Array<any>>;

export function SaveCodeGenModelChoice(arg1:string,arg2:string):Promise<void>;

export function GetOpenAIUsage():Promise<any>;

export function GetMaclawAgentMaxIterations():Promise<number>;

export function SetMaclawAgentMaxIterations(arg1:number):Promise<void>;

export function GetLLMTrajectoryLogging():Promise<boolean>;

export function SetLLMTrajectoryLogging(arg1:boolean):Promise<void>;

export function GetUIZoomFactor():Promise<number>;

export function SetUIZoomFactor(arg1:number):Promise<void>;

export function GetChatFontSize():Promise<number>;

export function SetChatFontSize(arg1:number):Promise<void>;

export function GetLLMTokenUsage(arg1:string):Promise<any>;

export function GetAllLLMTokenUsage():Promise<any>;

export function ResetLLMTokenUsage(arg1:string):Promise<void>;

export function PingMaclawLLM():Promise<any>;

export function PingSkillHub(arg1:string):Promise<any>;

export function ValidateSkillHub(arg1:string):Promise<any>;

// SkillHub market bindings
export function SearchSkillHub(arg1:string):Promise<Array<any>>;

export function SearchMixedSkills(arg1:string):Promise<Array<any>>;

export function InstallHubSkill(arg1:string, arg2:string):Promise<void>;

export function InstallMixedSkill(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CheckHubSkillUpdates():Promise<Array<any>>;

export function UpdateHubSkill(arg1:string):Promise<void>;

export function RateHubSkill(arg1:string, arg2:number):Promise<void>;

export function GetHubRecommendations():Promise<Array<any>>;

// Memory management bindings
export function ListMemories(arg1:string, arg2:string):Promise<Array<any>>;

export function SaveMemory(arg1:string, arg2:string, arg3:Array<string>):Promise<void>;

export function UpdateMemory(arg1:string, arg2:string, arg3:string, arg4:Array<string>):Promise<void>;

export function DeleteMemory(arg1:string):Promise<void>;

// Memory compression & backup bindings
export function CompressMemories():Promise<any>;

export function ListMemoryBackups():Promise<Array<any>>;

export function RestoreMemoryBackup(arg1:string):Promise<void>;

export function DeleteMemoryBackup(arg1:string):Promise<void>;

export function SetAutoCompress(arg1:boolean):Promise<void>;

export function GetAutoCompressStatus():Promise<any>;

export function IsMemoryCompressing():Promise<boolean>;

export function GetMemoryHealth():Promise<any>;

export function GetMemoryStatus():Promise<any>;

export function GetExperienceLearningSnapshot():Promise<any>;

export function GetExperienceGovernanceSummary(arg1:any):Promise<any>;

export function QueryExperienceFollowUpActions(arg1:any):Promise<any>;

export function ReviewExperienceTrace(arg1:string, arg2:any):Promise<any>;

export function BuildExperienceTraceFollowUp(arg1:string):Promise<any>;

export function BuildExperienceMemoryMaintenanceDraft(arg1:any):Promise<any>;

export function BuildExperienceRoutingAdjustmentDraft(arg1:any):Promise<any>;

export function BuildExperienceSkillDraft(arg1:string):Promise<any>;

export function BuildExperienceRollbackWorkflowDraft(arg1:string):Promise<any>;

export function BuildExperienceEscalationBrief(arg1:string):Promise<any>;

export function BuildExperienceConflictReconciliationDraft(arg1:string):Promise<any>;

export function RecordExperienceTraceFollowUp(arg1:string, arg2:any):Promise<any>;

export function RecordExperienceDraftReview(arg1:any):Promise<any>;

export function ListArchiveMemories(arg1:string, arg2:string):Promise<Array<any>>;

export function RestoreArchiveMemory(arg1:string):Promise<void>;

export function PinMemory(arg1:string):Promise<void>;

export function UnpinMemory(arg1:string):Promise<void>;

export function ListSessionHistory(arg1:number):Promise<Array<any>>;

export function SearchSessionHistory(arg1:string, arg2:number):Promise<Array<any>>;

export function GetSessionFullText(arg1:string):Promise<string>;

export function DeleteSession(arg1:string):Promise<void>;

export function GetSessionCount():Promise<number>;

export function GetMemoryMaxBackups():Promise<number>;

export function SetMemoryMaxBackups(arg1:number):Promise<void>;

// Scheduled task management bindings
export function ListScheduledTasks():Promise<Array<any>>;

export function CreateScheduledTask(arg1:string, arg2:string, arg3:number, arg4:number, arg5:number, arg6:number, arg7:number, arg8:string, arg9:string, arg10:string):Promise<string>;

export function UpdateScheduledTask(arg1:string, arg2:any):Promise<void>;

export function DeleteScheduledTask(arg1:string):Promise<void>;

export function PauseScheduledTask(arg1:string):Promise<void>;

export function ResumeScheduledTask(arg1:string):Promise<void>;

export function TriggerScheduledTask(arg1:string):Promise<void>;

// AgentNet P2P network bindings
export function AgentNetEnsureDaemon():Promise<any>;

export function AgentNetStopDaemon():Promise<void>;

export function AgentNetIsRunning():Promise<boolean>;

export function AgentNetGetStatus():Promise<any>;

export function AgentNetGetPeers():Promise<any>;

export function AgentNetGetCredits():Promise<any>;

export function AgentNetCreateTask(arg1:string, arg2:number):Promise<any>;

export function AgentNetSearchKnowledge(arg1:string):Promise<any>;
export function AgentNetPublishKnowledge(arg1:string, arg2:string):Promise<any>;
export function AgentNetSendDM(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetDMInbox():Promise<any>;
export function AgentNetListSwarmSessions():Promise<any>;
export function AgentNetCreateSwarmSession(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetResume():Promise<any>;
export function AgentNetListPredictions():Promise<any>;

export function AgentNetGetBinaryPath():Promise<string>;

export function AgentNetInstallBinary():Promise<any>;

export function AgentNetEnsureDaemonWithDownload():Promise<any>;

export function AgentNetManualUpdate():Promise<any>;

export function AgentNetListTasks(arg1:string):Promise<any>;

// AgentNet extended bindings
export function AgentNetGetProfile():Promise<any>;
export function AgentNetUpdateProfile(arg1:string, arg2:string):Promise<any>;
export function AgentNetSetMotto(arg1:string):Promise<any>;
export function AgentNetListPoIChallenges():Promise<any>;
export function AgentNetRespondToPoI(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetPoIScores():Promise<any>;
export function AgentNetFileDispute(arg1:string, arg2:string):Promise<any>;
export function AgentNetExtractDAG(arg1:string, arg2:string[], arg3:string[]):Promise<any>;
export function AgentNetQueryOntology(arg1:string, arg2:number):Promise<any>;
export function AgentNetListServices():Promise<any>;
export function AgentNetRegisterService(arg1:string, arg2:string, arg3:string, arg4:string[], arg5:string[], arg6:string, arg7:number, arg8:number):Promise<any>;
export function AgentNetUnregisterService(arg1:string):Promise<any>;
export function AgentNetCallService(arg1:string, arg2:string, arg3:string, arg4:string, arg5:Record<string, string>, arg6:string):Promise<any>;
export function AgentNetDiscoverServices(arg1:string):Promise<any>;
export function AgentNetListTopics():Promise<any>;
export function AgentNetCreateTopic(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetTopicMessages(arg1:string):Promise<any>;
export function AgentNetPostTopicMessage(arg1:string, arg2:string):Promise<any>;
export function AgentNetBidOnTask(arg1:string, arg2:number, arg3:string):Promise<any>;
export function AgentNetSubmitTaskDeliverable(arg1:string, arg2:string):Promise<any>;
export function AgentNetApproveTask(arg1:string):Promise<any>;
export function AgentNetRejectTask(arg1:string):Promise<any>;
export function AgentNetCancelTask(arg1:string):Promise<any>;
export function AgentNetGetTaskBids(arg1:string):Promise<any>;
export function AgentNetMatchTasks():Promise<any>;
export function AgentNetGetTaskBoard():Promise<any>;
export function AgentNetGetLeaderboard():Promise<any>;
export function AgentNetGetDaemonInfo():Promise<any>;
export function AgentNetGetDiagnostics():Promise<any>;
export function AgentNetGetCreditsAudit():Promise<any>;
export function AgentNetSelfUpdate():Promise<any>;
export function AgentNetGetKnowledgeFeed(arg1:string, arg2:number):Promise<any>;
export function AgentNetGetDMThread(arg1:string, arg2:number):Promise<any>;
export function AgentNetHasIdentity():Promise<any>;
export function AgentNetExportIdentity():Promise<any>;
export function AgentNetImportIdentity():Promise<any>;
export function AgentNetOnlineBackupKey(arg1:string):Promise<any>;
export function AgentNetOnlineRestoreKey(arg1:string):Promise<any>;

// AgentNet Hub-relayed task discovery
export function AgentNetBrowseNetworkTasks():Promise<any>;
export function AgentNetPublishTasksToHub():Promise<any>;

// AgentNet Auto Task Picker
export function AgentNetAutoPickerGetStatus():Promise<any>;
export function AgentNetAutoPickerConfigure(arg1:boolean, arg2:number, arg3:number, arg4:Array<string>):Promise<any>;
export function AgentNetAutoPickerTriggerNow():Promise<any>;
export function AgentNetManualPickTask(arg1:string):Promise<any>;

// AgentNet extended bindings (Swarm, Knowledge, Resume, etc.)
export function AgentNetUpdateResume(arg1:Array<string>, arg2:Array<string>, arg3:string):Promise<any>;
export function AgentNetJoinSwarm(arg1:string):Promise<any>;
export function AgentNetContributeToSwarm(arg1:string, arg2:string, arg3:string):Promise<any>;
export function AgentNetSynthesizeSwarm(arg1:string):Promise<any>;
export function AgentNetReactKnowledge(arg1:string, arg2:string):Promise<any>;
export function AgentNetReplyKnowledge(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetKnowledgeReplies(arg1:string):Promise<any>;
export function AgentNetPublishKnowledgeFull(arg1:string, arg2:string, arg3:Array<string>):Promise<any>;
export function AgentNetAssignTask(arg1:string, arg2:string):Promise<any>;
export function AgentNetClaimTask(arg1:string):Promise<any>;
export function AgentNetCreateTaskFull(arg1:string, arg2:string, arg3:number, arg4:Array<string>, arg5:string):Promise<any>;
export function AgentNetMatchAgentsForTask(arg1:string):Promise<any>;
export function AgentNetSubmitTaskWork(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetTaskSubmissions(arg1:string):Promise<any>;
export function AgentNetPickTaskWinner(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetOverlayStatus():Promise<any>;
export function AgentNetGetOverlayPeersGeo():Promise<any>;
export function AgentNetCreatePrediction(arg1:string, arg2:Array<string>):Promise<any>;
export function AgentNetPlaceBet(arg1:string, arg2:string, arg3:number):Promise<any>;
export function AgentNetResolvePrediction(arg1:string, arg2:string):Promise<any>;
export function AgentNetAppealPrediction(arg1:string, arg2:string):Promise<any>;
export function AgentNetGetPredictionLeaderboard():Promise<any>;

// AgentNet bundle bindings
export function AgentNetBundleStatus():Promise<any>;
export function AgentNetBundleInstall():Promise<any>;
export function AgentNetBundlePack(arg1:string, arg2:string, arg3:string):Promise<any>;
export function AgentNetBundleUnpack(arg1:string, arg2:string):Promise<any>;

// AI Assistant bindings
export function IsAIAssistantReady():Promise<boolean>;

export function GetAIAssistantInitStatus():Promise<string>;

export function SendAIAssistantMessage(arg1:any):Promise<any>;

export function SubmitAgentView(arg1:any):Promise<any>;

export function DismissAgentView(arg1:any):Promise<any>;

export function SendBtwQuery(arg1:string, arg2:string):Promise<any>;

export function ClearAIAssistantHistory():Promise<void>;

export function FetchNews():Promise<Array<any>>;

export function CancelAIAssistantSession():Promise<string>;

export function InjectAIAssistantSupplementary(arg1:string):Promise<boolean>;

export function ResolveCriticalConfirm(arg1:string,arg2:boolean):Promise<void>;

export function CancelAIAssistantTask(arg1:string):Promise<void>;

export function SelectAIAssistantFile():Promise<string>;

export function SelectAIAssistantFiles():Promise<Array<string>>;

export function StartAIAssistantBackgroundTask(arg1:any):Promise<any>;

export function GetTrialReflectEnabled():Promise<boolean>;

export function GetAIAssistantTrace(arg1:string):Promise<any>;

// Background Loop bindings
export function ListBackgroundLoops():Promise<Array<any>>;

export function StopBackgroundLoop(arg1:string):Promise<void>;

export function StopAllBackgroundLoops():Promise<Array<string>>;

export function StopAllBackgroundTasks():Promise<number>;

export function DismissRemoteSession(arg1:string):Promise<void>;

export function ContinueBackgroundLoop(arg1:string, arg2:number):Promise<void>;

export function GetBackgroundLoopOutput(arg1:string):Promise<Array<string>>;

// Agent Skill compatibility bindings
export function ImportAgentSkillDir(arg1:string):Promise<string>;

export function ExportAgentSkillDir(arg1:string, arg2:string):Promise<void>;

// QQ Bot gateway bindings
export function GetQQBotStatus():Promise<string>;

export function RestartQQBot():Promise<string>;

// Telegram Bot gateway bindings
export function GetTelegramStatus():Promise<string>;

export function RestartTelegram():Promise<string>;

// WeChat gateway bindings
export function GetWeixinStatus():Promise<string>;

export function RestartWeixin():Promise<string>;

export function StopWeixin():Promise<void>;

export function StartWeixinQRLogin():Promise<Record<string, string>>;

export function WaitWeixinQRLogin(arg1:string):Promise<Record<string, string>>;

export function PollWeixinQRStatus(arg1:string):Promise<Record<string, string>>;

export function GetWeixinLocalMode():Promise<boolean>;

export function SetWeixinLocalMode(arg1:boolean):Promise<void>;

export function GetQQBotLocalMode():Promise<boolean>;

export function SetQQBotLocalMode(arg1:boolean):Promise<void>;

export function GetTelegramLocalMode():Promise<boolean>;

export function SetTelegramLocalMode(arg1:boolean):Promise<void>;

// Lansenger gateway bindings
export function GetLansengerStatus():Promise<string>;

export function RestartLansenger():Promise<string>;

export function StopLansenger():Promise<void>;

export function GetLansengerLocalMode():Promise<boolean>;

export function SetLansengerLocalMode(arg1:boolean):Promise<void>;

export function GetThirdPartyGatewayStatus():Promise<string>;

export function RestartThirdPartyGateway():Promise<string>;

export function StopThirdPartyGateway():Promise<void>;

export function GetThirdPartyGatewayLocalMode():Promise<boolean>;

export function SetThirdPartyGatewayLocalMode(arg1:boolean):Promise<void>;

// Gossip bindings
export function GossipSnapshot(arg1:string):Promise<any>;

export function GossipPublish(arg1:string, arg2:string):Promise<any>;

export function GossipComment(arg1:string, arg2:string, arg3:number):Promise<any>;

export function GossipRate(arg1:string, arg2:number):Promise<any>;

export function GossipGetComments(arg1:string, arg2:number):Promise<any>;

export function IsGossipAllowed():Promise<boolean>;

export function GetHubSecurityPolicy():Promise<any>;

export function IsHubSecurityReadOnly():Promise<boolean>;

// NL Skill upload binding
export function UploadNLSkillToMarket(arg1:string):Promise<string>;

export function AuditInstalledSkillQuality(arg1:boolean):Promise<Array<any>>;

export function ListSkillUploadQueue():Promise<Array<any>>;

export function RetrySkillUploadQueue():Promise<void>;

export function RetryBlockedSkillUpload(arg1:string):Promise<void>;

export function GetVectorSearchEnabled():Promise<boolean>;

export function SetVectorSearchEnabled(arg1:boolean):Promise<void>;

export function CheckEmbeddingModel():Promise<{[key:string]:any}>;

export function DownloadEmbeddingModel():Promise<void>;

export function GetASREnabled():Promise<boolean>;

export function SetASREnabled(arg1:boolean):Promise<void>;

export function CheckASRModel():Promise<{[key:string]:any}>;

export function DownloadASRModel():Promise<void>;

export function TranscribeAudioBase64(arg1:string):Promise<string>;

export function NormalizeVoiceCommand(arg1:string):Promise<main.VoiceCommandNormalizationResult>;

export function IsASRReady():Promise<boolean>;

// Screen parsing (OminiParser-V2) bindings
export function GetScreenParsingEnabled():Promise<boolean>;

export function SetScreenParsingEnabled(arg1:boolean):Promise<void>;

export function CheckYOLOModel():Promise<{[key:string]:any}>;

export function DownloadYOLOModel():Promise<void>;

export function QuerySecurityEvents(arg1:number):Promise<Array<any>>;

export function ReadErrorLog():Promise<Array<string>>;

export function GetHubLLMServiceStatus():Promise<any>;
export function RedeemHubLLMService(arg1:string):Promise<any>;
export function OnFloatingButtonClicked():Promise<void>;
export function OnFloatingButtonDragged(arg1:number,arg2:number):Promise<void>;
export function HideFloatingButton():Promise<void>;
export function QuitApp():Promise<void>;

export function DeleteIMAuditMessagesBefore(arg1:number):Promise<number>;
export function ExportIMAuditCSV(arg1:string,arg2:string,arg3:string):Promise<string>;
export function GetIMAuditStats():Promise<any>;
export function GetIMAuditUsers(arg1:string):Promise<Array<string>>;
export function QueryIMAuditMessages(arg1:string,arg2:string,arg3:string,arg4:number):Promise<any>;

export function KnowledgeStats():Promise<any>;

export function KnowledgeDoctor():Promise<any>;

export function KnowledgeHealth(arg1:any):Promise<any>;

export function KnowledgeClearAll():Promise<void>;

export function KnowledgeSourceQualityReport(arg1:any):Promise<any>;

export function KnowledgeSourceQualityMaintenancePlan(arg1:any):Promise<any>;

export function KnowledgeQualityMaintenancePolicies():Promise<any>;

export function KnowledgeExecuteSourceQualityMaintenancePlan(arg1:any):Promise<any>;

export function KnowledgeCapabilities():Promise<any>;

export function KnowledgeListURLDomainPolicies():Promise<Array<any>>;

export function KnowledgeUpdateURLDomainPolicies(arg1:any):Promise<any>;

export function KnowledgeCheckURLDomainPolicy(arg1:string):Promise<any>;

export function KnowledgeMaintain(arg1:boolean):Promise<any>;

export function KnowledgeExportSnapshot(arg1:string,arg2:boolean):Promise<any>;

export function KnowledgeExportSnapshotWithOptions(arg1:any):Promise<any>;

export function KnowledgeImportSnapshot(arg1:any):Promise<any>;

export function KnowledgeListSources(arg1:any):Promise<Array<any>>;

export function KnowledgeListSourceLabels(arg1:any):Promise<Array<any>>;

export function KnowledgeGetSource(arg1:string):Promise<any>;

export function KnowledgeUpdateSourceMetadata(arg1:any):Promise<any>;

export function KnowledgeUpdateSourceLabels(arg1:any):Promise<any>;

export function KnowledgeBackfillSourceAutoLabels(arg1:any):Promise<any>;

export function KnowledgeSearch(arg1:any):Promise<Array<any>>;

export function KnowledgeExplain(arg1:any):Promise<any>;

export function KnowledgeSearchFacets(arg1:any):Promise<any>;

export function KnowledgeTopicRelevance(arg1:any):Promise<any>;

export function KnowledgeContextPack(arg1:any):Promise<any>;

export function KnowledgeFactGraph(arg1:any):Promise<any>;

export function KnowledgeFactIndex(arg1:any):Promise<any>;

export function KnowledgeEntityProfile(arg1:any):Promise<any>;

export function KnowledgeSuggest(arg1:any):Promise<any>;

export function KnowledgeDeleteSource(arg1:string):Promise<void>;

export function KnowledgeDisableSource(arg1:string):Promise<any>;

export function KnowledgeDisableSources(arg1:Array<string>):Promise<any>;

export function KnowledgeDisableSourcesByFilter(arg1:any):Promise<any>;

export function KnowledgeEnableSource(arg1:string):Promise<any>;

export function KnowledgeEnableSources(arg1:Array<string>):Promise<any>;

export function KnowledgeEnableSourcesByFilter(arg1:any):Promise<any>;

export function KnowledgeRefreshSource(arg1:string):Promise<any>;

export function KnowledgePreviewSourceRefresh(arg1:string):Promise<any>;

export function KnowledgePreviewSourcesRefresh(arg1:Array<string>):Promise<any>;

export function KnowledgePreviewSourcesRefreshByFilter(arg1:any):Promise<any>;

export function KnowledgeRefreshChangedSources(arg1:Array<string>):Promise<any>;

export function KnowledgeRefreshChangedSourcesByFilter(arg1:any):Promise<any>;

export function KnowledgeRefreshSources(arg1:Array<string>):Promise<any>;

export function KnowledgeRefreshSourcesByFilter(arg1:any):Promise<any>;

export function KnowledgeRebuildSourceDerived(arg1:string,arg2:string):Promise<any>;

export function KnowledgeRebuildSourcesDerived(arg1:Array<string>,arg2:string):Promise<any>;

export function KnowledgeRebuildSourcesDerivedByFilter(arg1:any,arg2:string):Promise<any>;

export function KnowledgeScanDirectory(arg1:any):Promise<any>;

export function KnowledgeScanFiles(arg1:any,arg2:Array<string>):Promise<any>;

export function KnowledgeImportDirectory(arg1:any):Promise<any>;

export function KnowledgeImportFiles(arg1:any,arg2:Array<string>):Promise<any>;

export function KnowledgeListImportBatches(arg1:number):Promise<Array<any>>;

export function KnowledgeListImportItems(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeRetryImportBatch(arg1:any):Promise<any>;

export function KnowledgeListNodesBySource(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeListSourceVersions(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeListCardsBySource(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeListFactsBySource(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeListSourceLinks(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeSourceGraph(arg1:any,arg2:number):Promise<any>;

export function KnowledgeSourceNeighborhood(arg1:string,arg2:number,arg3:number,arg4:number):Promise<any>;

export function KnowledgeSourcePath(arg1:string,arg2:string,arg3:number,arg4:number):Promise<any>;

export function KnowledgePreviewSourceTopicLinks(arg1:string,arg2:number):Promise<any>;

export function KnowledgeLinkSources(arg1:any):Promise<any>;

export function KnowledgeUnlinkSources(arg1:string,arg2:string,arg3:string):Promise<any>;

export function KnowledgeListSourceLinkEvents(arg1:string,arg2:number):Promise<Array<any>>;

export function KnowledgeSourceTimeline(arg1:string,arg2:number):Promise<any>;

export function KnowledgeSourceDigest(arg1:string,arg2:number,arg3:number,arg4:number,arg5:number):Promise<any>;

export function KnowledgeRefreshSourceTopicLinks(arg1:string,arg2:number):Promise<any>;

export function KnowledgeRefreshSourceTopicLinksByFilter(arg1:any,arg2:number):Promise<any>;

export function KnowledgeListDuplicateCards(arg1:number):Promise<Array<any>>;

export function KnowledgeSuppressDuplicateCards(arg1:any):Promise<any>;

export function KnowledgeSuppressCards(arg1:Array<string>,arg2:string):Promise<any>;

export function KnowledgeRestoreSuppressedCards(arg1:Array<string>):Promise<any>;

export function KnowledgeListSuppressedCards(arg1:number):Promise<Array<any>>;

export function KnowledgeScanSensitiveContent(arg1:number):Promise<any>;

export function KnowledgeDisableSensitiveSources(arg1:number):Promise<any>;

export function KnowledgeStartImportDirectory(arg1:any):Promise<any>;

export function KnowledgeStartImportFiles(arg1:any,arg2:Array<string>):Promise<any>;

export function KnowledgeImportJobStatus(arg1:string):Promise<any>;

export function KnowledgeSaveURL(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<any>;

export function KnowledgeSaveURLs(arg1:Array<string>,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<any>;

export function KnowledgeDiscoverURLs(arg1:any):Promise<any>;

export function KnowledgeSaveText(arg1:any):Promise<any>;

export function SelectKnowledgeDirectory():Promise<string>;

export function SelectKnowledgeFiles():Promise<Array<string>>;

export function ExportTextFile(arg1:string,arg2:string):Promise<string>;

// MIS data service bindings
export function GetMISDataConfig():Promise<any>;
export function SaveMISDataConfig(arg1:any):Promise<void>;
export function TestMISDataConnection(arg1:any):Promise<any>;
