// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddSkill(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddSkill'](arg1, arg2, arg3, arg4, arg5);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function CheckEnvironment(arg1) {
  return window['go']['main']['App']['CheckEnvironment'](arg1);
}

export function CheckToolsStatus() {
  return window['go']['main']['App']['CheckToolsStatus']();
}

export function CheckUpdate(arg1) {
  return window['go']['main']['App']['CheckUpdate'](arg1);
}

export function ClipboardGetText() {
  return window['go']['main']['App']['ClipboardGetText']();
}

export function DeleteSkill(arg1, arg2) {
  return window['go']['main']['App']['DeleteSkill'](arg1, arg2);
}

export function DownloadUpdate(arg1, arg2) {
  return window['go']['main']['App']['DownloadUpdate'](arg1, arg2);
}

export function ActivateRemote(arg1, arg2, arg3) {
  return window['go']['main']['App']['ActivateRemote'](arg1, arg2, arg3);
}

export function ProbeRemoteHub(arg1, arg2) {
  return window['go']['main']['App']['ProbeRemoteHub'](arg1, arg2);
}

export function ClearRemoteActivation() {
  return window['go']['main']['App']['ClearRemoteActivation']();
}

export function VerifyRemoteActivation() {
  return window['go']['main']['App']['VerifyRemoteActivation']();
}

export function GetCurrentProjectPath() {
  return window['go']['main']['App']['GetCurrentProjectPath']();
}

export function GetDownloadsFolder() {
  return window['go']['main']['App']['GetDownloadsFolder']();
}

export function GetEnvCheckInterval() {
  return window['go']['main']['App']['GetEnvCheckInterval']();
}

export function GetLocalCacheDir() {
  return window['go']['main']['App']['GetLocalCacheDir']();
}

export function GetRemoteActivationStatus() {
  return window['go']['main']['App']['GetRemoteActivationStatus']();
}

export function GetRemoteClaudeReadiness(arg1, arg2) {
  return window['go']['main']['App']['GetRemoteClaudeReadiness'](arg1, arg2);
}

export function GetRemoteToolReadiness(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRemoteToolReadiness'](arg1, arg2, arg3);
}

export function GetRemoteConnectionStatus() {
  return window['go']['main']['App']['GetRemoteConnectionStatus']();
}

export function GetRemoteClaudeLaunchProbe(arg1, arg2) {
  return window['go']['main']['App']['GetRemoteClaudeLaunchProbe'](arg1, arg2);
}

export function GetRemoteToolLaunchProbe(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRemoteToolLaunchProbe'](arg1, arg2, arg3);
}

export function GetRemotePTYProbe() {
  return window['go']['main']['App']['GetRemotePTYProbe']();
}

export function GetLastRemoteSmokeReport() {
  return window['go']['main']['App']['GetLastRemoteSmokeReport']();
}

export function StartRemoteClaudeSession(arg1, arg2) {
  return window['go']['main']['App']['StartRemoteClaudeSession'](arg1, arg2);
}

export function StartRemoteSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartRemoteSession'](arg1, arg2, arg3, arg4, arg5);
}

export function StartRemoteHandoffSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartRemoteHandoffSession'](arg1, arg2, arg3, arg4, arg5);
}

export function ListValidProviders(arg1) {
  return window['go']['main']['App']['ListValidProviders'](arg1);
}

export function GetSkillsDir(arg1) {
  return window['go']['main']['App']['GetSkillsDir'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUserHomeDir() {
  return window['go']['main']['App']['GetUserHomeDir']();
}

export function GetBrandInfo() {
  return window['go']['main']['App']['GetBrandInfo']();
}

export function InstallDefaultMarketplace() {
  return window['go']['main']['App']['InstallDefaultMarketplace']();
}

export function InstallSkill(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['InstallSkill'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function InstallTool(arg1) {
  return window['go']['main']['App']['InstallTool'](arg1);
}

export function InstallToolOnDemand(arg1) {
  return window['go']['main']['App']['InstallToolOnDemand'](arg1);
}

export function IsToolBeingInstalled(arg1) {
  return window['go']['main']['App']['IsToolBeingInstalled'](arg1);
}

export function IsWindowsTerminalAvailable() {
  return window['go']['main']['App']['IsWindowsTerminalAvailable']();
}

export function LaunchInstallerAndExit(arg1) {
  return window['go']['main']['App']['LaunchInstallerAndExit'](arg1);
}

export function LaunchTool(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['LaunchTool'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function ListPythonEnvironments() {
  return window['go']['main']['App']['ListPythonEnvironments']();
}

export function ListRemoteHubs(arg1, arg2) {
  return window['go']['main']['App']['ListRemoteHubs'](arg1, arg2);
}

export function ListRemoteSessions() {
  return window['go']['main']['App']['ListRemoteSessions']();
}

export function ListRemoteToolMetadata() {
  return window['go']['main']['App']['ListRemoteToolMetadata']();
}

export function ListSkills(arg1) {
  return window['go']['main']['App']['ListSkills'](arg1);
}

export function ListSkillsWithInstallStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSkillsWithInstallStatus'](arg1, arg2, arg3);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function OpenSystemUrl(arg1) {
  return window['go']['main']['App']['OpenSystemUrl'](arg1);
}

export function PackLog(arg1) {
  return window['go']['main']['App']['PackLog'](arg1);
}

export function ReadBBS() {
  return window['go']['main']['App']['ReadBBS']();
}

export function ReadThanks() {
  return window['go']['main']['App']['ReadThanks']();
}

export function ReadTutorial() {
  return window['go']['main']['App']['ReadTutorial']();
}

export function ReconnectRemoteHub() {
  return window['go']['main']['App']['ReconnectRemoteHub']();
}

export function RunRemoteClaudeSmoke(arg1, arg2) {
  return window['go']['main']['App']['RunRemoteClaudeSmoke'](arg1, arg2);
}

export function RunRemoteToolSmoke(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunRemoteToolSmoke'](arg1, arg2, arg3);
}

export function RecoverCC() {
  return window['go']['main']['App']['RecoverCC']();
}

export function ResizeWindow(arg1, arg2) {
  return window['go']['main']['App']['ResizeWindow'](arg1, arg2);
}

export function RunEnvironmentCheckCLI() {
  return window['go']['main']['App']['RunEnvironmentCheckCLI']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectProjectDir() {
  return window['go']['main']['App']['SelectProjectDir']();
}

export function SelectSkillFile() {
  return window['go']['main']['App']['SelectSkillFile']();
}

export function SendRemoteSessionImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendRemoteSessionImage'](arg1, arg2, arg3);
}

export function CaptureRemoteScreenshot(arg1) {
  return window['go']['main']['App']['CaptureRemoteScreenshot'](arg1);
}

export function CaptureRemoteWindowScreenshot(arg1, arg2) {
  return window['go']['main']['App']['CaptureRemoteWindowScreenshot'](arg1, arg2);
}

export function SendRemoteSessionInput(arg1, arg2) {
  return window['go']['main']['App']['SendRemoteSessionInput'](arg1, arg2);
}

export function SendRemoteSessionRawInput(arg1, arg2) {
  return window['go']['main']['App']['SendRemoteSessionRawInput'](arg1, arg2);
}

export function SetEnvCheckInterval(arg1) {
  return window['go']['main']['App']['SetEnvCheckInterval'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function ShouldCheckEnvironment() {
  return window['go']['main']['App']['ShouldCheckEnvironment']();
}

export function ShowItemInFolder(arg1) {
  return window['go']['main']['App']['ShowItemInFolder'](arg1);
}

export function ShowMessage(arg1, arg2) {
  return window['go']['main']['App']['ShowMessage'](arg1, arg2);
}

export function InterruptRemoteSession(arg1) {
  return window['go']['main']['App']['InterruptRemoteSession'](arg1);
}

export function KillRemoteSession(arg1) {
  return window['go']['main']['App']['KillRemoteSession'](arg1);
}

export function UpdateLastEnvCheckTime() {
  return window['go']['main']['App']['UpdateLastEnvCheckTime']();
}

export function UpdateTool(arg1) {
  return window['go']['main']['App']['UpdateTool'](arg1);
}

export function WindowHide() {
  return window['go']['main']['App']['WindowHide']();
}

// NL Skill management bindings
export function ListNLSkills() {
  return window['go']['main']['App']['ListNLSkills']();
}

export function DiagnoseSkillFiles() {
  return window['go']['main']['App']['DiagnoseSkillFiles']();
}

export function ListExternalSkillDirs() {
  return window['go']['main']['App']['ListExternalSkillDirs']();
}

export function ListExternalSkillDirsDetailed() {
  return window['go']['main']['App']['ListExternalSkillDirsDetailed']();
}

export function AddExternalSkillDir(arg1) {
  return window['go']['main']['App']['AddExternalSkillDir'](arg1);
}

export function RemoveExternalSkillDir(arg1) {
  return window['go']['main']['App']['RemoveExternalSkillDir'](arg1);
}

export function CreateNLSkill(arg1) {
  return window['go']['main']['App']['CreateNLSkill'](arg1);
}

export function UpdateNLSkill(arg1) {
  return window['go']['main']['App']['UpdateNLSkill'](arg1);
}

export function DeleteNLSkill(arg1) {
  return window['go']['main']['App']['DeleteNLSkill'](arg1);
}

export function ImportNLSkillZip() {
  return window['go']['main']['App']['ImportNLSkillZip']();
}

export function ExportLearnedSkillsZip(arg1) {
  return window['go']['main']['App']['ExportLearnedSkillsZip'](arg1);
}

export function ImportLearnedSkillsZip() {
  return window['go']['main']['App']['ImportLearnedSkillsZip']();
}

// MCP management bindings
export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function RegisterMCPServer(arg1) {
  return window['go']['main']['App']['RegisterMCPServer'](arg1);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}

export function UnregisterMCPServer(arg1) {
  return window['go']['main']['App']['UnregisterMCPServer'](arg1);
}

export function GetMCPServerTools(arg1) {
  return window['go']['main']['App']['GetMCPServerTools'](arg1);
}

export function CheckMCPServerHealth(arg1) {
  return window['go']['main']['App']['CheckMCPServerHealth'](arg1);
}

// Local MCP server management bindings
export function ListLocalMCPServers() {
  return window['go']['main']['App']['ListLocalMCPServers']();
}

export function RegisterLocalMCPServer(arg1) {
  return window['go']['main']['App']['RegisterLocalMCPServer'](arg1);
}

export function UpdateLocalMCPServer(arg1) {
  return window['go']['main']['App']['UpdateLocalMCPServer'](arg1);
}

export function UnregisterLocalMCPServer(arg1) {
  return window['go']['main']['App']['UnregisterLocalMCPServer'](arg1);
}

export function SyncLocalMCPServers() {
  return window['go']['main']['App']['SyncLocalMCPServers']();
}

export function GetLocalMCPServerStatuses() {
  return window['go']['main']['App']['GetLocalMCPServerStatuses']();
}

// MaClaw LLM configuration bindings
export function GetMaclawLLMConfig() {
  return window['go']['main']['App']['GetMaclawLLMConfig']();
}

export function SaveMaclawLLMConfig(arg1) {
  return window['go']['main']['App']['SaveMaclawLLMConfig'](arg1);
}

export function GetMaclawLLMProviders() {
  return window['go']['main']['App']['GetMaclawLLMProviders']();
}

export function SaveMaclawLLMProviders(arg1, arg2) {
  return window['go']['main']['App']['SaveMaclawLLMProviders'](arg1, arg2);
}

export function TestMaclawLLM(arg1) {
  return window['go']['main']['App']['TestMaclawLLM'](arg1);
}

export function StartOpenAIOAuth() {
  return window['go']['main']['App']['StartOpenAIOAuth']();
}

export function StartCodeGenSSO() {
  return window['go']['main']['App']['StartCodeGenSSO']();
}

export function StartCodeGenSSOEmbedded() {
  return window['go']['main']['App']['StartCodeGenSSOEmbedded']();
}

export function WaitCodeGenSSOResult() {
  return window['go']['main']['App']['WaitCodeGenSSOResult']();
}

export function CancelCodeGenSSOPolling() {
  return window['go']['main']['App']['CancelCodeGenSSOPolling']();
}

export function FetchCodeGenModels() {
  return window['go']['main']['App']['FetchCodeGenModels']();
}

export function SaveCodeGenModelChoice(arg1, arg2) {
  return window['go']['main']['App']['SaveCodeGenModelChoice'](arg1, arg2);
}

export function GetOpenAIUsage() {
  return window['go']['main']['App']['GetOpenAIUsage']();
}

export function PingMaclawLLM() {
  return window['go']['main']['App']['PingMaclawLLM']();
}

export function GetMaclawAgentMaxIterations() {
  return window['go']['main']['App']['GetMaclawAgentMaxIterations']();
}

export function SetMaclawAgentMaxIterations(arg1) {
  return window['go']['main']['App']['SetMaclawAgentMaxIterations'](arg1);
}

export function GetLLMTrajectoryLogging() {
  return window['go']['main']['App']['GetLLMTrajectoryLogging']();
}

export function SetLLMTrajectoryLogging(arg1) {
  return window['go']['main']['App']['SetLLMTrajectoryLogging'](arg1);
}

export function GetUIZoomFactor() {
  return window['go']['main']['App']['GetUIZoomFactor']();
}

export function SetUIZoomFactor(arg1) {
  return window['go']['main']['App']['SetUIZoomFactor'](arg1);
}

export function GetLLMTokenUsage(arg1) {
  return window['go']['main']['App']['GetLLMTokenUsage'](arg1);
}

export function GetAllLLMTokenUsage() {
  return window['go']['main']['App']['GetAllLLMTokenUsage']();
}

export function ResetLLMTokenUsage(arg1) {
  return window['go']['main']['App']['ResetLLMTokenUsage'](arg1);
}

export function PingSkillHub(arg1) {
  return window['go']['main']['App']['PingSkillHub'](arg1);
}

export function ValidateSkillHub(arg1) {
  return window['go']['main']['App']['ValidateSkillHub'](arg1);
}

// SkillHub market bindings
export function SearchSkillHub(arg1) {
  return window['go']['main']['App']['SearchSkillHub'](arg1);
}

export function InstallHubSkill(arg1, arg2) {
  return window['go']['main']['App']['InstallHubSkill'](arg1, arg2);
}

export function CheckHubSkillUpdates() {
  return window['go']['main']['App']['CheckHubSkillUpdates']();
}

export function UpdateHubSkill(arg1) {
  return window['go']['main']['App']['UpdateHubSkill'](arg1);
}

export function RateHubSkill(arg1, arg2) {
  return window['go']['main']['App']['RateHubSkill'](arg1, arg2);
}

// Memory management bindings
export function ListMemories(arg1, arg2) {
  return window['go']['main']['App']['ListMemories'](arg1, arg2);
}

export function SaveMemory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveMemory'](arg1, arg2, arg3);
}

export function UpdateMemory(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateMemory'](arg1, arg2, arg3, arg4);
}

export function DeleteMemory(arg1) {
  return window['go']['main']['App']['DeleteMemory'](arg1);
}

// Memory compression & backup bindings
export function CompressMemories() {
  return window['go']['main']['App']['CompressMemories']();
}

export function ListMemoryBackups() {
  return window['go']['main']['App']['ListMemoryBackups']();
}

export function RestoreMemoryBackup(arg1) {
  return window['go']['main']['App']['RestoreMemoryBackup'](arg1);
}

export function DeleteMemoryBackup(arg1) {
  return window['go']['main']['App']['DeleteMemoryBackup'](arg1);
}

export function SetAutoCompress(arg1) {
  return window['go']['main']['App']['SetAutoCompress'](arg1);
}

export function GetAutoCompressStatus() {
  return window['go']['main']['App']['GetAutoCompressStatus']();
}

export function GetMemoryMaxBackups() {
  return window['go']['main']['App']['GetMemoryMaxBackups']();
}

export function SetMemoryMaxBackups(arg1) {
  return window['go']['main']['App']['SetMemoryMaxBackups'](arg1);
}

// Scheduled task management bindings
export function ListScheduledTasks() {
  return window['go']['main']['App']['ListScheduledTasks']();
}

export function CreateScheduledTask(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['CreateScheduledTask'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function UpdateScheduledTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateScheduledTask'](arg1, arg2);
}

export function DeleteScheduledTask(arg1) {
  return window['go']['main']['App']['DeleteScheduledTask'](arg1);
}

export function PauseScheduledTask(arg1) {
  return window['go']['main']['App']['PauseScheduledTask'](arg1);
}

export function ResumeScheduledTask(arg1) {
  return window['go']['main']['App']['ResumeScheduledTask'](arg1);
}

export function TriggerScheduledTask(arg1) {
  return window['go']['main']['App']['TriggerScheduledTask'](arg1);
}

// ClawNet P2P network bindings
export function ClawNetEnsureDaemon() {
  return window['go']['main']['App']['ClawNetEnsureDaemon']();
}

export function ClawNetStopDaemon() {
  return window['go']['main']['App']['ClawNetStopDaemon']();
}

export function ClawNetIsRunning() {
  return window['go']['main']['App']['ClawNetIsRunning']();
}

export function ClawNetGetStatus() {
  return window['go']['main']['App']['ClawNetGetStatus']();
}

export function ClawNetGetPeers() {
  return window['go']['main']['App']['ClawNetGetPeers']();
}

export function ClawNetGetCredits() {
  return window['go']['main']['App']['ClawNetGetCredits']();
}

export function ClawNetCreateTask(arg1, arg2) {
  return window['go']['main']['App']['ClawNetCreateTask'](arg1, arg2);
}

export function ClawNetSearchKnowledge(arg1) {
  return window['go']['main']['App']['ClawNetSearchKnowledge'](arg1);
}

export function ClawNetPublishKnowledge(arg1, arg2) {
  return window['go']['main']['App']['ClawNetPublishKnowledge'](arg1, arg2);
}

export function ClawNetSendDM(arg1, arg2) {
  return window['go']['main']['App']['ClawNetSendDM'](arg1, arg2);
}

export function ClawNetGetDMInbox() {
  return window['go']['main']['App']['ClawNetGetDMInbox']();
}

export function ClawNetListSwarmSessions() {
  return window['go']['main']['App']['ClawNetListSwarmSessions']();
}

export function ClawNetCreateSwarmSession(arg1, arg2) {
  return window['go']['main']['App']['ClawNetCreateSwarmSession'](arg1, arg2);
}

export function ClawNetGetResume() {
  return window['go']['main']['App']['ClawNetGetResume']();
}

export function ClawNetListPredictions() {
  return window['go']['main']['App']['ClawNetListPredictions']();
}

export function ClawNetGetBinaryPath() {
  return window['go']['main']['App']['ClawNetGetBinaryPath']();
}

export function ClawNetInstallBinary() {
  return window['go']['main']['App']['ClawNetInstallBinary']();
}

export function ClawNetEnsureDaemonWithDownload() {
  return window['go']['main']['App']['ClawNetEnsureDaemonWithDownload']();
}

export function ClawNetManualUpdate() {
  return window['go']['main']['App']['ClawNetManualUpdate']();
}

export function ClawNetListTasks(arg1) {
  return window['go']['main']['App']['ClawNetListTasks'](arg1);
}

// ClawNet extended bindings
export function ClawNetGetProfile() {
  return window['go']['main']['App']['ClawNetGetProfile']();
}

export function ClawNetUpdateProfile(arg1, arg2) {
  return window['go']['main']['App']['ClawNetUpdateProfile'](arg1, arg2);
}

export function ClawNetSetMotto(arg1) {
  return window['go']['main']['App']['ClawNetSetMotto'](arg1);
}

export function ClawNetListTopics() {
  return window['go']['main']['App']['ClawNetListTopics']();
}

export function ClawNetCreateTopic(arg1, arg2) {
  return window['go']['main']['App']['ClawNetCreateTopic'](arg1, arg2);
}

export function ClawNetGetTopicMessages(arg1) {
  return window['go']['main']['App']['ClawNetGetTopicMessages'](arg1);
}

export function ClawNetPostTopicMessage(arg1, arg2) {
  return window['go']['main']['App']['ClawNetPostTopicMessage'](arg1, arg2);
}

export function ClawNetBidOnTask(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClawNetBidOnTask'](arg1, arg2, arg3);
}

export function ClawNetSubmitTaskResult(arg1, arg2) {
  return window['go']['main']['App']['ClawNetSubmitTaskResult'](arg1, arg2);
}

export function ClawNetApproveTask(arg1) {
  return window['go']['main']['App']['ClawNetApproveTask'](arg1);
}

export function ClawNetRejectTask(arg1) {
  return window['go']['main']['App']['ClawNetRejectTask'](arg1);
}

export function ClawNetCancelTask(arg1) {
  return window['go']['main']['App']['ClawNetCancelTask'](arg1);
}

export function ClawNetGetTaskBids(arg1) {
  return window['go']['main']['App']['ClawNetGetTaskBids'](arg1);
}

export function ClawNetMatchTasks() {
  return window['go']['main']['App']['ClawNetMatchTasks']();
}

export function ClawNetGetTaskBoard() {
  return window['go']['main']['App']['ClawNetGetTaskBoard']();
}

export function ClawNetGetTransactions() {
  return window['go']['main']['App']['ClawNetGetTransactions']();
}

export function ClawNetGetLeaderboard() {
  return window['go']['main']['App']['ClawNetGetLeaderboard']();
}

export function ClawNetGetDaemonInfo() {
  return window['go']['main']['App']['ClawNetGetDaemonInfo']();
}

export function ClawNetGetDiagnostics() {
  return window['go']['main']['App']['ClawNetGetDiagnostics']();
}

export function ClawNetGetCreditsAudit() {
  return window['go']['main']['App']['ClawNetGetCreditsAudit']();
}

export function ClawNetSelfUpdate() {
  return window['go']['main']['App']['ClawNetSelfUpdate']();
}

export function ClawNetGetKnowledgeFeed(arg1, arg2) {
  return window['go']['main']['App']['ClawNetGetKnowledgeFeed'](arg1, arg2);
}

export function ClawNetGetDMThread(arg1, arg2) {
  return window['go']['main']['App']['ClawNetGetDMThread'](arg1, arg2);
}

export function ClawNetHasIdentity() {
  return window['go']['main']['App']['ClawNetHasIdentity']();
}

export function ClawNetExportIdentity() {
  return window['go']['main']['App']['ClawNetExportIdentity']();
}

export function ClawNetImportIdentity() {
  return window['go']['main']['App']['ClawNetImportIdentity']();
}

export function ClawNetOnlineBackupKey(arg1) {
  return window['go']['main']['App']['ClawNetOnlineBackupKey'](arg1);
}

export function ClawNetOnlineRestoreKey(arg1) {
  return window['go']['main']['App']['ClawNetOnlineRestoreKey'](arg1);
}

// ClawNet Hub-relayed task discovery
export function ClawNetBrowseNetworkTasks() {
  return window['go']['main']['App']['ClawNetBrowseNetworkTasks']();
}

export function ClawNetPublishTasksToHub() {
  return window['go']['main']['App']['ClawNetPublishTasksToHub']();
}

export function ClawNetAutoPickerGetStatus() {
  return window['go']['main']['App']['ClawNetAutoPickerGetStatus']();
}

export function ClawNetAutoPickerConfigure(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ClawNetAutoPickerConfigure'](arg1, arg2, arg3, arg4);
}

export function ClawNetAutoPickerTriggerNow() {
  return window['go']['main']['App']['ClawNetAutoPickerTriggerNow']();
}

export function ClawNetManualPickTask(arg1) {
  return window['go']['main']['App']['ClawNetManualPickTask'](arg1);
}

export function ClawNetUpdateResume(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClawNetUpdateResume'](arg1, arg2, arg3);
}

export function ClawNetJoinSwarm(arg1) {
  return window['go']['main']['App']['ClawNetJoinSwarm'](arg1);
}

export function ClawNetContributeToSwarm(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClawNetContributeToSwarm'](arg1, arg2, arg3);
}

export function ClawNetSynthesizeSwarm(arg1) {
  return window['go']['main']['App']['ClawNetSynthesizeSwarm'](arg1);
}

export function ClawNetReactKnowledge(arg1, arg2) {
  return window['go']['main']['App']['ClawNetReactKnowledge'](arg1, arg2);
}

export function ClawNetReplyKnowledge(arg1, arg2) {
  return window['go']['main']['App']['ClawNetReplyKnowledge'](arg1, arg2);
}

export function ClawNetGetKnowledgeReplies(arg1) {
  return window['go']['main']['App']['ClawNetGetKnowledgeReplies'](arg1);
}

export function ClawNetPublishKnowledgeFull(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClawNetPublishKnowledgeFull'](arg1, arg2, arg3);
}

export function ClawNetAssignTask(arg1, arg2) {
  return window['go']['main']['App']['ClawNetAssignTask'](arg1, arg2);
}

export function ClawNetClaimTask(arg1) {
  return window['go']['main']['App']['ClawNetClaimTask'](arg1);
}

export function ClawNetCreateTaskFull(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ClawNetCreateTaskFull'](arg1, arg2, arg3, arg4, arg5);
}

export function ClawNetMatchAgentsForTask(arg1) {
  return window['go']['main']['App']['ClawNetMatchAgentsForTask'](arg1);
}

export function ClawNetSubmitTaskWork(arg1, arg2) {
  return window['go']['main']['App']['ClawNetSubmitTaskWork'](arg1, arg2);
}

export function ClawNetGetTaskSubmissions(arg1) {
  return window['go']['main']['App']['ClawNetGetTaskSubmissions'](arg1);
}

export function ClawNetPickTaskWinner(arg1, arg2) {
  return window['go']['main']['App']['ClawNetPickTaskWinner'](arg1, arg2);
}

export function ClawNetGetOverlayStatus() {
  return window['go']['main']['App']['ClawNetGetOverlayStatus']();
}

export function ClawNetGetOverlayPeersGeo() {
  return window['go']['main']['App']['ClawNetGetOverlayPeersGeo']();
}

export function ClawNetCreatePrediction(arg1, arg2) {
  return window['go']['main']['App']['ClawNetCreatePrediction'](arg1, arg2);
}

export function ClawNetPlaceBet(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClawNetPlaceBet'](arg1, arg2, arg3);
}

export function ClawNetResolvePrediction(arg1, arg2) {
  return window['go']['main']['App']['ClawNetResolvePrediction'](arg1, arg2);
}

export function ClawNetAppealPrediction(arg1, arg2) {
  return window['go']['main']['App']['ClawNetAppealPrediction'](arg1, arg2);
}

export function ClawNetGetPredictionLeaderboard() {
  return window['go']['main']['App']['ClawNetGetPredictionLeaderboard']();
}

// Nutshell bindings
export function ClawNetNutshellStatus() {
  return window['go']['main']['App']['ClawNetNutshellStatus']();
}

export function ClawNetNutshellInstall() {
  return window['go']['main']['App']['ClawNetNutshellInstall']();
}

export function ClawNetNutshellInit(arg1) {
  return window['go']['main']['App']['ClawNetNutshellInit'](arg1);
}

export function ClawNetNutshellCheck(arg1) {
  return window['go']['main']['App']['ClawNetNutshellCheck'](arg1);
}

export function ClawNetNutshellPublish(arg1, arg2) {
  return window['go']['main']['App']['ClawNetNutshellPublish'](arg1, arg2);
}

export function ClawNetNutshellClaim(arg1, arg2) {
  return window['go']['main']['App']['ClawNetNutshellClaim'](arg1, arg2);
}

export function ClawNetNutshellDeliver(arg1) {
  return window['go']['main']['App']['ClawNetNutshellDeliver'](arg1);
}

export function ClawNetNutshellPack(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClawNetNutshellPack'](arg1, arg2, arg3);
}

export function ClawNetNutshellUnpack(arg1, arg2) {
  return window['go']['main']['App']['ClawNetNutshellUnpack'](arg1, arg2);
}

// AI Assistant bindings
export function IsAIAssistantReady() {
  return window['go']['main']['App']['IsAIAssistantReady']();
}

export function GetAIAssistantInitStatus() {
  return window['go']['main']['App']['GetAIAssistantInitStatus']();
}

export function SendAIAssistantMessage(arg1) {
  return window['go']['main']['App']['SendAIAssistantMessage'](arg1);
}

export function ClearAIAssistantHistory() {
  return window['go']['main']['App']['ClearAIAssistantHistory']();
}

export function CancelAIAssistantSession() {
  return window['go']['main']['App']['CancelAIAssistantSession']();
}

export function FetchNews() {
  return window['go']['main']['App']['FetchNews']();
}

// Background Loop bindings
export function ListBackgroundLoops() {
  return window['go']['main']['App']['ListBackgroundLoops']();
}

export function StopBackgroundLoop(arg1) {
  return window['go']['main']['App']['StopBackgroundLoop'](arg1);
}

export function ContinueBackgroundLoop(arg1, arg2) {
  return window['go']['main']['App']['ContinueBackgroundLoop'](arg1, arg2);
}

export function GetBackgroundLoopOutput(arg1) {
  return window['go']['main']['App']['GetBackgroundLoopOutput'](arg1);
}

export function ImportAgentSkillDir(arg1) {
  return window['go']['main']['App']['ImportAgentSkillDir'](arg1);
}

export function ExportAgentSkillDir(arg1, arg2) {
  return window['go']['main']['App']['ExportAgentSkillDir'](arg1, arg2);
}

// QQ Bot gateway bindings
export function GetQQBotStatus() {
  return window['go']['main']['App']['GetQQBotStatus']();
}

export function RestartQQBot() {
  return window['go']['main']['App']['RestartQQBot']();
}

// Telegram Bot gateway bindings
export function GetTelegramStatus() {
  return window['go']['main']['App']['GetTelegramStatus']();
}

export function RestartTelegram() {
  return window['go']['main']['App']['RestartTelegram']();
}

// WeChat gateway bindings
export function GetWeixinStatus() {
  return window['go']['main']['App']['GetWeixinStatus']();
}

export function RestartWeixin() {
  return window['go']['main']['App']['RestartWeixin']();
}

export function StopWeixin() {
  return window['go']['main']['App']['StopWeixin']();
}

export function StartWeixinQRLogin() {
  return window['go']['main']['App']['StartWeixinQRLogin']();
}

export function WaitWeixinQRLogin(arg1) {
  return window['go']['main']['App']['WaitWeixinQRLogin'](arg1);
}

export function GetWeixinLocalMode() {
  return window['go']['main']['App']['GetWeixinLocalMode']();
}

export function SetWeixinLocalMode(arg1) {
  return window['go']['main']['App']['SetWeixinLocalMode'](arg1);
}

export function GetQQBotLocalMode() {
  return window['go']['main']['App']['GetQQBotLocalMode']();
}

export function SetQQBotLocalMode(arg1) {
  return window['go']['main']['App']['SetQQBotLocalMode'](arg1);
}

export function GetTelegramLocalMode() {
  return window['go']['main']['App']['GetTelegramLocalMode']();
}

export function SetTelegramLocalMode(arg1) {
  return window['go']['main']['App']['SetTelegramLocalMode'](arg1);
}

// Gossip bindings
export function GossipSnapshot(arg1) {
  return window['go']['main']['App']['GossipSnapshot'](arg1);
}

export function GossipPublish(arg1, arg2) {
  return window['go']['main']['App']['GossipPublish'](arg1, arg2);
}

export function GossipComment(arg1, arg2, arg3) {
  return window['go']['main']['App']['GossipComment'](arg1, arg2, arg3);
}

export function GossipRate(arg1, arg2) {
  return window['go']['main']['App']['GossipRate'](arg1, arg2);
}

export function GossipGetComments(arg1, arg2) {
  return window['go']['main']['App']['GossipGetComments'](arg1, arg2);
}

export function IsGossipAllowed() {
  return window['go']['main']['App']['IsGossipAllowed']();
}

export function GetHubSecurityPolicy() {
  return window['go']['main']['App']['GetHubSecurityPolicy']();
}

export function IsHubSecurityReadOnly() {
  return window['go']['main']['App']['IsHubSecurityReadOnly']();
}

// NL Skill upload binding
export function UploadNLSkillToMarket(arg1) {
  return window['go']['main']['App']['UploadNLSkillToMarket'](arg1);
}

// Free proxy bindings
export function StartFreeProxy() {
  return window['go']['main']['App']['StartFreeProxy']();
}

export function StopFreeProxy() {
  return window['go']['main']['App']['StopFreeProxy']();
}

export function IsFreeProxyRunning() {
  return window['go']['main']['App']['IsFreeProxyRunning']();
}

export function DetectChrome() {
  return window['go']['main']['App']['DetectChrome']();
}

export function LaunchChromeDebug() {
  return window['go']['main']['App']['LaunchChromeDebug']();
}

export function IsDangbeiLoggedIn() {
  return window['go']['main']['App']['IsDangbeiLoggedIn']();
}

export function DetectBrowser() {
  return window['go']['main']['App']['DetectBrowser']();
}

export function DangbeiLogin() {
  return window['go']['main']['App']['DangbeiLogin']();
}

export function DangbeiFinishLogin() {
  return window['go']['main']['App']['DangbeiFinishLogin']();
}

export function DangbeiEnsureAuth() {
  return window['go']['main']['App']['DangbeiEnsureAuth']();
}

export function GetFreeProxyModels() {
  return window['go']['main']['App']['GetFreeProxyModels']();
}

export function GetFreeProxyModel() {
  return window['go']['main']['App']['GetFreeProxyModel']();
}

export function SetFreeProxyModel(arg1) {
  return window['go']['main']['App']['SetFreeProxyModel'](arg1);
}

export function GetVectorSearchEnabled() {
  return window['go']['main']['App']['GetVectorSearchEnabled']();
}

export function SetVectorSearchEnabled(arg1) {
  return window['go']['main']['App']['SetVectorSearchEnabled'](arg1);
}

export function CheckEmbeddingModel() {
  return window['go']['main']['App']['CheckEmbeddingModel']();
}

export function DownloadEmbeddingModel() {
  return window['go']['main']['App']['DownloadEmbeddingModel']();
}

export function GetASREnabled() {
  return window['go']['main']['App']['GetASREnabled']();
}

export function SetASREnabled(arg1) {
  return window['go']['main']['App']['SetASREnabled'](arg1);
}

export function CheckASRModel() {
  return window['go']['main']['App']['CheckASRModel']();
}

export function DownloadASRModel() {
  return window['go']['main']['App']['DownloadASRModel']();
}
