package catalog

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"clawmatemaker/internal/logging"
)

const latestReleaseURL = "https://api.github.com/repos/" + Repository + "/releases/latest"
const releasesURL = "https://api.github.com/repos/" + Repository + "/releases?per_page=30"
const maxApprovedRedirects = 5
const maxAssetBytes int64 = 128 * 1024 * 1024

// ReleaseChannel is deliberately a tiny allow-list.  A caller cannot turn the
// release client into a general URL downloader by inventing a channel name.
type ReleaseChannel string

const (
	StableChannel ReleaseChannel = "stable"
	BetaChannel   ReleaseChannel = "beta"
)

// These public manifests are generated by the Release workflow before the
// corresponding assets are uploaded to R2 and COS. They are discovery hints,
// not a replacement for the signed .clawfw package verification.
const (
	r2LatestManifestURL  = "https://pub-c837069cbe31469590a5fea6235b436b.r2.dev/latest.json"
	cosLatestManifestURL = "https://maclaw-1252723594.cos.ap-beijing.myqcloud.com/latest.json"
	r2LatestAssetBase    = "https://pub-c837069cbe31469590a5fea6235b436b.r2.dev/latest/"
	cosLatestAssetBase   = "https://maclaw-1252723594.cos.ap-beijing.myqcloud.com/latest/"
)

const cacheLockStaleAfter = 30 * time.Minute
const cacheLockRetryInterval = 100 * time.Millisecond

type releaseResponse struct {
	TagName     string         `json:"tag_name"`
	PublishedAt time.Time      `json:"published_at"`
	Draft       bool           `json:"draft"`
	Prerelease  bool           `json:"prerelease"`
	Assets      []releaseAsset `json:"assets"`
}
type releaseAsset struct {
	Name        string `json:"name"`
	Size        int64  `json:"size"`
	DownloadURL string `json:"browser_download_url"`
	Digest      string `json:"digest"`
}

type mirrorManifest struct {
	Version string                         `json:"version"`
	Tag     string                         `json:"tag"`
	Assets  map[string]mirrorManifestAsset `json:"assets"`
}

type mirrorManifestAsset struct {
	Name   string   `json:"name"`
	Size   int64    `json:"size"`
	SHA256 string   `json:"sha256"`
	URL    string   `json:"url"`
	URLs   []string `json:"urls"`
}

type mirrorSource struct {
	name string
	url  string
}

type mirrorAsset struct {
	source string
	tag    string
	size   int64
	sha256 string
	urls   []string
}

type downloadCandidate struct {
	source  string
	url     string
	latency time.Duration
}

// partialDownloadIdentity binds an on-disk partial object to the exact URL
// and HTTP cache validator that produced it. A byte offset alone is not an
// object identity: a CDN can replace an asset at the same URL between two
// requests. We only resume after the server proves it is serving the same
// ETag or Last-Modified object.
type partialDownloadIdentity struct {
	URL          string `json:"url"`
	ETag         string `json:"etag,omitempty"`
	LastModified string `json:"lastModified,omitempty"`
}

type DownloadedRelease struct {
	JobID string `json:"jobId,omitempty"`
	// PackageRef is an opaque, in-memory capability issued by the desktop
	// application after validation. It is the only firmware handle that the UI
	// may submit to the irreversible flash endpoint.
	PackageRef      string `json:"packageRef,omitempty"`
	BoardID         string `json:"boardId"`
	BoardName       string `json:"boardName"`
	Channel         string `json:"channel"`
	ReleaseTag      string `json:"releaseTag"`
	FirmwareVersion int64  `json:"firmwareVersion,omitempty"`
	PublishedAt     string `json:"publishedAt,omitempty"`
	AssetName       string `json:"assetName"`
	// Path is intentionally not serialized across the Wails boundary. A
	// browser renderer must not learn or submit arbitrary host file paths.
	Path              string `json:"-"`
	Size              int64  `json:"size"`
	SHA256            string `json:"sha256"`
	GitHubDigest      string `json:"githubDigest,omitempty"`
	InstallStatus     string `json:"installStatus"`
	InstallPlan       string `json:"installPlan,omitempty"`
	PreservesUserData bool   `json:"preservesUserData"`
	RequiresRecovery  bool   `json:"requiresRecovery"`
	SafetyNote        string `json:"safetyNote"`
}

// FirmwareUpdate is derived solely from the signed, monotonic integer build
// version. Human-readable tags remain display metadata and are never sorted.
type FirmwareUpdate struct {
	InstalledVersion int64  `json:"installedVersion,omitempty"`
	AvailableVersion int64  `json:"availableVersion,omitempty"`
	Status           string `json:"status"`
}

func CompareFirmwareVersions(installedVersion, availableVersion int64) FirmwareUpdate {
	result := FirmwareUpdate{InstalledVersion: installedVersion, AvailableVersion: availableVersion, Status: "unknown"}
	if installedVersion <= 0 || availableVersion <= 0 {
		return result
	}
	switch {
	case availableVersion > installedVersion:
		result.Status = "upgrade_available"
	case availableVersion == installedVersion:
		result.Status = "up_to_date"
	default:
		result.Status = "installed_newer"
	}
	return result
}

type Client struct {
	cacheDir string
	http     *http.Client
	apiURL   string
	mirrors  []mirrorSource
	channel  ReleaseChannel
}

func NewClient(cacheDir string) *Client {
	client, _ := NewClientForChannel(cacheDir, StableChannel)
	return client
}

// NewClientForChannel constructs a client for one of the two signed public
// channels. Stable remains the default; callers must opt in to beta.
func NewClientForChannel(cacheDir string, channel ReleaseChannel) (*Client, error) {
	channel, err := normalizeReleaseChannel(channel)
	if err != nil {
		return nil, err
	}
	return &Client{
		cacheDir: cacheDir,
		http:     &http.Client{Timeout: 90 * time.Second},
		apiURL:   latestReleaseURL,
		mirrors: []mirrorSource{
			{name: "r2", url: mirrorManifestURL("r2", channel)},
			{name: "cos", url: mirrorManifestURL("cos", channel)},
		},
		channel: channel,
	}, nil
}

func normalizeReleaseChannel(channel ReleaseChannel) (ReleaseChannel, error) {
	switch ReleaseChannel(strings.ToLower(strings.TrimSpace(string(channel)))) {
	case "", StableChannel:
		return StableChannel, nil
	case BetaChannel:
		return BetaChannel, nil
	default:
		return "", fmt.Errorf("unsupported firmware release channel %q", channel)
	}
}

// NormalizeReleaseChannel is the boundary helper used by jobs and the Wails
// application API before a requested channel is persisted in diagnostics.
func NormalizeReleaseChannel(channel ReleaseChannel) (ReleaseChannel, error) {
	return normalizeReleaseChannel(channel)
}

func (c *Client) releaseChannel() (ReleaseChannel, error) {
	if c == nil {
		return "", errors.New("release client is unavailable")
	}
	return normalizeReleaseChannel(c.channel)
}

func mirrorPrefix(channel ReleaseChannel) string {
	if channel == BetaChannel {
		return "beta"
	}
	return "latest"
}

func mirrorManifestURL(source string, channel ReleaseChannel) string {
	name := mirrorPrefix(channel) + ".json"
	if source == "cos" {
		return cosLatestManifestURL[:strings.LastIndex(cosLatestManifestURL, "/")+1] + name
	}
	return r2LatestManifestURL[:strings.LastIndex(r2LatestManifestURL, "/")+1] + name
}

func mirrorAssetBase(source string, channel ReleaseChannel) string {
	base := r2LatestAssetBase
	if source == "cos" {
		base = cosLatestAssetBase
	}
	if channel == BetaChannel {
		return strings.TrimSuffix(base, "latest/") + "beta/"
	}
	return base
}

func (c *Client) DownloadLatest(ctx context.Context, boardID string, emit func(logging.Event)) (DownloadedRelease, error) {
	profile, err := Profile(boardID)
	if err != nil {
		return DownloadedRelease{}, err
	}
	if c == nil || c.http == nil {
		return DownloadedRelease{}, errors.New("release client is unavailable")
	}
	channel, err := c.releaseChannel()
	if err != nil {
		return DownloadedRelease{}, err
	}
	emitEvent(emit, logging.Info, "RELEASE_DISCOVERY_STARTED", "Discovering latest official firmware release.", map[string]any{"boardId": boardID, "channel": channel})
	apiURL := c.apiURL
	if apiURL == "" {
		apiURL = latestReleaseURL
	}
	if apiURL != latestReleaseURL {
		return DownloadedRelease{}, errors.New("custom release endpoints are not permitted")
	}
	release, asset, err := c.discoverRelease(ctx, apiURL, profile.AssetName, channel, emit)
	if err != nil {
		return DownloadedRelease{}, err
	}
	emitEvent(emit, logging.Info, "RELEASE_ASSET_SELECTED", "Selected exact allow-listed firmware asset.", map[string]any{"boardId": boardID, "asset": asset.Name, "release": release.TagName, "bytes": asset.Size})
	if asset.Size <= 0 || asset.Size > maxAssetBytes {
		return DownloadedRelease{}, fmt.Errorf("release asset size %d is outside permitted bounds", asset.Size)
	}
	if !isApprovedDownloadURL(asset.DownloadURL) {
		return DownloadedRelease{}, errors.New("release asset URL is not an approved firmware HTTPS host")
	}
	dir := filepath.Join(c.cacheDir, profile.ID, safeSegment(release.TagName))
	if err := os.MkdirAll(dir, 0700); err != nil {
		return DownloadedRelease{}, fmt.Errorf("create firmware cache: %w", err)
	}
	destination := filepath.Join(dir, profile.AssetName)
	releaseLock, waited, err := acquireAssetLock(ctx, destination)
	if err != nil {
		return DownloadedRelease{}, err
	}
	defer releaseLock()
	if waited {
		emitEvent(emit, logging.Info, "RELEASE_CACHE_WAIT_COMPLETED", "Another download task completed access to this firmware cache entry; validating its result.", map[string]any{"boardId": boardID, "asset": asset.Name, "release": release.TagName})
	}
	if sum, size, ok := cachedAsset(destination, asset.Size, asset.Digest); ok {
		emitEvent(emit, logging.Info, "RELEASE_CACHE_HIT", "Using cached firmware after SHA-256 verification.", map[string]any{"boardId": boardID, "asset": asset.Name, "release": release.TagName, "bytes": size, "sha256": "sha256:" + sum, "cached": true})
		return DownloadedRelease{BoardID: profile.ID, BoardName: profile.Name, Channel: string(channel), ReleaseTag: release.TagName, PublishedAt: release.PublishedAt.UTC().Format(time.RFC3339), AssetName: profile.AssetName, Path: destination, Size: size, SHA256: "sha256:" + sum, GitHubDigest: asset.Digest, InstallStatus: "downloaded_unverified", SafetyNote: "Using cached firmware. Signature and hardware compatibility must be verified before installation."}, nil
	}
	candidates := c.discoverDownloadCandidates(ctx, profile.AssetName, release.TagName, asset, emit)
	var sum string
	var size int64
	var lastErr error
	for index, candidate := range candidates {
		if index > 0 {
			fallbackFields := map[string]any{
				"boardId":  boardID,
				"asset":    asset.Name,
				"source":   candidate.source,
				"endpoint": safeEndpoint(candidate.url),
			}
			if previous := candidates[index-1]; previous.source != "" {
				fallbackFields["failedSource"] = previous.source
				fallbackFields["failedEndpoint"] = safeEndpoint(previous.url)
			}
			emitEvent(emit, logging.Info, "MIRROR_FALLBACK", "The previous verified download source failed; trying the next verified source.", fallbackFields)
		}
		sum, size, lastErr = c.download(ctx, candidate.url, destination, asset.Size)
		if lastErr == nil && asset.Digest != "" && !strings.EqualFold(asset.Digest, "sha256:"+sum) {
			_ = os.Remove(destination)
			lastErr = errors.New("GitHub release digest does not match downloaded asset")
		}
		if lastErr == nil {
			break
		}
		removePartialDownload(destination)
	}
	if len(candidates) == 0 {
		return DownloadedRelease{}, errors.New("no approved firmware download source is available")
	}
	if lastErr != nil {
		return DownloadedRelease{}, fmt.Errorf("download firmware from all verified sources: %w", lastErr)
	}
	emitEvent(emit, logging.Info, "RELEASE_DOWNLOAD_COMPLETED", "Firmware downloaded and SHA-256 computed.", map[string]any{"boardId": boardID, "asset": asset.Name, "release": release.TagName, "bytes": size, "sha256": "sha256:" + sum})
	return DownloadedRelease{BoardID: profile.ID, BoardName: profile.Name, Channel: string(channel), ReleaseTag: release.TagName, PublishedAt: release.PublishedAt.UTC().Format(time.RFC3339), AssetName: profile.AssetName, Path: destination, Size: size, SHA256: "sha256:" + sum, GitHubDigest: asset.Digest, InstallStatus: "downloaded_unverified", SafetyNote: "Download complete. Firmware signature and hardware compatibility must be verified before installation."}, nil
}

// discoverRelease keeps the GitHub Release API as the preferred source of
// release identity. If GitHub discovery is temporarily unavailable, two
// independently served workflow manifests may recover availability only when
// they agree exactly on the requested immutable asset metadata. Package
// signature and catalog validation still run after this discovery step.
func (c *Client) discoverRelease(ctx context.Context, apiURL, assetName string, channel ReleaseChannel, emit func(logging.Event)) (releaseResponse, *releaseAsset, error) {
	if channel == BetaChannel {
		// GitHub's /releases/latest endpoint intentionally excludes
		// prereleases. Beta selection must therefore enumerate releases rather
		// than accidentally installing the latest stable package.
		recent, err := c.fetchRecentReleases(ctx)
		if err == nil {
			if beta, asset, found := newestBetaReleaseWithAsset(recent, assetName); found {
				emitEvent(emit, logging.Info, "RELEASE_BETA_SELECTED", "Selected the newest beta GitHub release containing the exact firmware asset.", map[string]any{"asset": asset.Name, "release": beta.TagName, "channel": channel})
				return beta, asset, nil
			}
			err = fmt.Errorf("no recent beta GitHub release includes official asset %s", assetName)
		}
		githubErr := err
		emitEvent(emit, logging.Warn, "RELEASE_GITHUB_DISCOVERY_FAILED", "GitHub Release discovery did not yield an exact firmware asset; checking synchronized mirror manifests.", map[string]any{"asset": assetName, "channel": channel})
		fallback, fallbackErr := c.discoverReleaseFromMirrors(ctx, assetName, channel, emit)
		if fallbackErr != nil {
			return releaseResponse{}, nil, fmt.Errorf("discover official beta firmware: GitHub: %w; mirrors: %v", githubErr, fallbackErr)
		}
		emitEvent(emit, logging.Warn, "RELEASE_MIRROR_DISCOVERY_SELECTED", "GitHub beta Release discovery was unavailable; selected exact metadata agreed by synchronized mirrors. Package signature verification remains required.", map[string]any{"asset": assetName, "release": fallback.TagName, "bytes": fallback.Asset.Size, "channel": channel})
		asset := fallback.Asset
		asset.DownloadURL = fallback.URLs[0]
		return releaseResponse{TagName: fallback.TagName, Assets: []releaseAsset{asset}}, &asset, nil
	}
	release, err := c.fetchRelease(ctx, apiURL)
	if err == nil && strings.TrimSpace(release.TagName) != "" {
		if asset := exactReleaseAsset(release, assetName); asset != nil {
			return release, asset, nil
		}
		emitEvent(emit, logging.Info, "RELEASE_LATEST_MISSING_ASSET", "Latest GitHub release does not yet contain this board's exact firmware asset; checking recent stable releases.", map[string]any{"asset": assetName, "release": release.TagName})
		recent, listErr := c.fetchRecentReleases(ctx)
		if listErr == nil {
			if fallback, asset, found := newestStableReleaseWithAsset(recent, assetName); found {
				emitEvent(emit, logging.Info, "RELEASE_FALLBACK_SELECTED", "Selected the newest stable GitHub release containing the exact firmware asset.", map[string]any{"asset": asset.Name, "release": fallback.TagName})
				return fallback, asset, nil
			}
		}
		if listErr != nil {
			err = fmt.Errorf("release %s does not include official asset %s; list recent releases: %w", release.TagName, assetName, listErr)
		} else {
			err = fmt.Errorf("no recent stable GitHub release includes official asset %s", assetName)
		}
	} else if err == nil {
		err = errors.New("GitHub release has no tag")
	}
	githubErr := err
	emitEvent(emit, logging.Warn, "RELEASE_GITHUB_DISCOVERY_FAILED", "GitHub Release discovery did not yield an exact firmware asset; checking synchronized mirror manifests.", map[string]any{"asset": assetName})
	fallback, fallbackErr := c.discoverReleaseFromMirrors(ctx, assetName, channel, emit)
	if fallbackErr != nil {
		return releaseResponse{}, nil, fmt.Errorf("discover official firmware: GitHub: %w; mirrors: %v", githubErr, fallbackErr)
	}
	emitEvent(emit, logging.Warn, "RELEASE_MIRROR_DISCOVERY_SELECTED", "GitHub Release discovery was unavailable; selected exact metadata agreed by synchronized mirrors. Package signature verification remains required.", map[string]any{"asset": assetName, "release": fallback.TagName, "bytes": fallback.Asset.Size})
	asset := fallback.Asset
	asset.DownloadURL = fallback.URLs[0]
	return releaseResponse{TagName: fallback.TagName, Assets: []releaseAsset{asset}}, &asset, nil
}

type mirrorReleaseFallback struct {
	TagName string
	Asset   releaseAsset
	URLs    []string
}

func (c *Client) discoverReleaseFromMirrors(ctx context.Context, assetName string, channel ReleaseChannel, emit func(logging.Event)) (mirrorReleaseFallback, error) {
	if len(c.mirrors) < 2 {
		return mirrorReleaseFallback{}, errors.New("at least two independent mirror manifests are required")
	}
	results := make(chan mirrorAsset, len(c.mirrors))
	var group sync.WaitGroup
	for _, source := range c.mirrors {
		source := source
		group.Add(1)
		go func() {
			defer group.Done()
			mirror, err := c.fetchMirrorAsset(ctx, source, assetName, channel)
			if err != nil {
				emitEvent(emit, logging.Info, "MIRROR_MANIFEST_FAILED", "A firmware mirror manifest was unavailable or invalid.", map[string]any{"asset": assetName, "source": source.name})
				return
			}
			results <- mirror
		}()
	}
	group.Wait()
	close(results)
	mirrors := make([]mirrorAsset, 0, len(c.mirrors))
	for mirror := range results {
		mirrors = append(mirrors, mirror)
	}
	if len(mirrors) < 2 {
		return mirrorReleaseFallback{}, errors.New("fewer than two valid mirror manifests are available")
	}
	baseline := mirrors[0]
	for _, mirror := range mirrors[1:] {
		if mirror.tag != baseline.tag || mirror.size != baseline.size || !strings.EqualFold(mirror.sha256, baseline.sha256) {
			emitEvent(emit, logging.Warn, "MIRROR_METADATA_CONFLICT", "Mirror metadata conflicted during release discovery; no firmware was selected.", map[string]any{"asset": assetName})
			return mirrorReleaseFallback{}, errors.New("mirror manifests disagree on tag, size, or SHA-256")
		}
	}
	urls := make([]string, 0, len(mirrors)*2)
	for _, mirror := range mirrors {
		urls = append(urls, mirror.urls...)
	}
	urls = uniqueApprovedMirrorURLs(urls)
	if len(urls) == 0 {
		return mirrorReleaseFallback{}, errors.New("valid mirror manifests contain no approved asset URL")
	}
	return mirrorReleaseFallback{TagName: baseline.tag, Asset: releaseAsset{Name: assetName, Size: baseline.size, Digest: "sha256:" + baseline.sha256}, URLs: urls}, nil
}

// acquireAssetLock uses an adjacent lock directory, which is atomically
// created by all supported desktop filesystems. Unlike an in-memory mutex it
// also prevents two running instances of the application from appending to a
// shared .part file. A lock is reclaimed only after a conservative timeout;
// package hash/signature validation remains mandatory after acquisition.
func acquireAssetLock(ctx context.Context, destination string) (release func(), waited bool, err error) {
	if ctx == nil {
		ctx = context.Background()
	}
	lockPath := filepath.Clean(destination) + ".lock"
	for {
		err := os.Mkdir(lockPath, 0700)
		if err == nil {
			return func() { _ = os.Remove(lockPath) }, waited, nil
		}
		if !os.IsExist(err) {
			return nil, waited, fmt.Errorf("create firmware cache lock: %w", err)
		}
		waited = true
		if info, statErr := os.Stat(lockPath); statErr == nil && time.Since(info.ModTime()) > cacheLockStaleAfter {
			// The directory is intentionally empty. Remove never traverses
			// content, so it cannot affect the adjacent firmware package.
			_ = os.Remove(lockPath)
			continue
		}
		select {
		case <-ctx.Done():
			return nil, waited, fmt.Errorf("wait for firmware cache lock: %w", ctx.Err())
		case <-time.After(cacheLockRetryInterval):
		}
	}
}

func (c *Client) fetchRelease(ctx context.Context, apiURL string) (releaseResponse, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, apiURL, nil)
	if err != nil {
		return releaseResponse{}, err
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "ClawMateMaker/0.1")
	resp, err := c.http.Do(req)
	if err != nil {
		return releaseResponse{}, fmt.Errorf("discover GitHub release: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return releaseResponse{}, fmt.Errorf("discover GitHub release: HTTP %d", resp.StatusCode)
	}
	var release releaseResponse
	if err := json.NewDecoder(io.LimitReader(resp.Body, 2*1024*1024)).Decode(&release); err != nil {
		return releaseResponse{}, fmt.Errorf("decode GitHub release: %w", err)
	}
	return release, nil
}

func (c *Client) fetchRecentReleases(ctx context.Context) ([]releaseResponse, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, releasesURL, nil)
	if err != nil {
		return nil, err
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "ClawMateMaker/0.1")
	resp, err := c.http.Do(req)
	if err != nil {
		return nil, fmt.Errorf("list GitHub releases: %w", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("list GitHub releases: HTTP %d", resp.StatusCode)
	}
	var releases []releaseResponse
	if err := json.NewDecoder(io.LimitReader(resp.Body, 8*1024*1024)).Decode(&releases); err != nil {
		return nil, fmt.Errorf("decode GitHub release list: %w", err)
	}
	return releases, nil
}

func exactReleaseAsset(release releaseResponse, name string) *releaseAsset {
	for i := range release.Assets {
		if release.Assets[i].Name == name {
			return &release.Assets[i]
		}
	}
	return nil
}

// newestStableReleaseWithAsset trusts GitHub's release-list ordering (newest
// first) only after filtering out drafts/prereleases and selecting the exact
// catalog asset name. The signed package verification remains mandatory.
func newestStableReleaseWithAsset(releases []releaseResponse, assetName string) (releaseResponse, *releaseAsset, bool) {
	for _, release := range releases {
		if release.Draft || release.Prerelease || strings.TrimSpace(release.TagName) == "" {
			continue
		}
		if asset := exactReleaseAsset(release, assetName); asset != nil {
			return release, asset, true
		}
	}
	return releaseResponse{}, nil, false
}

func newestBetaReleaseWithAsset(releases []releaseResponse, assetName string) (releaseResponse, *releaseAsset, bool) {
	for _, release := range releases {
		if release.Draft || !release.Prerelease || strings.TrimSpace(release.TagName) == "" {
			continue
		}
		if asset := exactReleaseAsset(release, assetName); asset != nil {
			return release, asset, true
		}
	}
	return releaseResponse{}, nil, false
}

// discoverDownloadCandidates treats GitHub's Release API as the authority for
// release identity. R2 and COS are accepted only when their workflow-produced
// manifests exactly agree with that release and point at an allow-listed URL.
// A malicious or stale mirror manifest can therefore reduce availability, but
// cannot select a different package or bypass signature verification.
func (c *Client) discoverDownloadCandidates(ctx context.Context, assetName, releaseTag string, asset *releaseAsset, emit func(logging.Event)) []downloadCandidate {
	// Mirror discovery and probing run concurrently. Emit through a local gate
	// so callers may safely append to an event stream without having to make
	// their callback concurrency-aware.
	var emitMu sync.Mutex
	safeEmit := func(event logging.Event) {
		if emit == nil {
			return
		}
		emitMu.Lock()
		defer emitMu.Unlock()
		emit(event)
	}
	primary := downloadCandidate{source: downloadSource(asset.DownloadURL), url: asset.DownloadURL}
	if !isApprovedDownloadURL(primary.url) {
		return nil
	}
	channel, err := c.releaseChannel()
	if err != nil {
		return c.probeDownloadCandidates(ctx, asset.Size, []downloadCandidate{primary}, safeEmit)
	}
	emitEvent(safeEmit, logging.Info, "MIRROR_DISCOVERY_STARTED", "Checking firmware mirror metadata and measuring verified download nodes.", map[string]any{"asset": assetName, "release": releaseTag})
	if len(c.mirrors) == 0 {
		return c.probeDownloadCandidates(ctx, asset.Size, []downloadCandidate{primary}, safeEmit)
	}

	results := make(chan mirrorAsset, len(c.mirrors))
	var group sync.WaitGroup
	for _, mirror := range c.mirrors {
		mirror := mirror
		group.Add(1)
		go func() {
			defer group.Done()
			candidate, err := c.fetchMirrorAsset(ctx, mirror, assetName, channel)
			if err != nil {
				emitEvent(safeEmit, logging.Info, "MIRROR_MANIFEST_FAILED", "A firmware mirror manifest was unavailable or invalid.", map[string]any{"asset": assetName, "source": mirror.name})
				return
			}
			emitEvent(safeEmit, logging.Info, "MIRROR_MANIFEST_AVAILABLE", "A firmware mirror manifest contains the exact requested asset.", map[string]any{"asset": assetName, "release": candidate.tag, "source": mirror.name, "bytes": candidate.size})
			results <- candidate
		}()
	}
	group.Wait()
	close(results)

	var mirrors []mirrorAsset
	for candidate := range results {
		mirrors = append(mirrors, candidate)
	}
	if len(mirrors) == 0 {
		return c.probeDownloadCandidates(ctx, asset.Size, []downloadCandidate{primary}, safeEmit)
	}
	baseline := mirrors[0]
	conflict := baseline.tag != releaseTag || baseline.size != asset.Size || (asset.Digest != "" && !strings.EqualFold(asset.Digest, "sha256:"+baseline.sha256))
	for _, mirror := range mirrors[1:] {
		if mirror.tag != baseline.tag || mirror.size != baseline.size || !strings.EqualFold(mirror.sha256, baseline.sha256) {
			conflict = true
		}
	}
	if conflict {
		emitEvent(safeEmit, logging.Warn, "MIRROR_METADATA_CONFLICT", "Mirror metadata did not agree with the official release; all mirrors were rejected.", map[string]any{"asset": assetName, "release": releaseTag})
		return c.probeDownloadCandidates(ctx, asset.Size, []downloadCandidate{primary}, safeEmit)
	}
	candidates := []downloadCandidate{primary}
	for _, mirror := range mirrors {
		for _, candidateURL := range mirror.urls {
			candidates = append(candidates, downloadCandidate{source: downloadSource(candidateURL), url: candidateURL})
		}
	}
	return c.probeDownloadCandidates(ctx, asset.Size, candidates, safeEmit)
}

func (c *Client) fetchMirrorAsset(parent context.Context, source mirrorSource, assetName string, channel ReleaseChannel) (mirrorAsset, error) {
	ctx, cancel := context.WithTimeout(parent, 6*time.Second)
	defer cancel()
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, source.url, nil)
	if err != nil {
		return mirrorAsset{}, err
	}
	req.Header.Set("User-Agent", "ClawMateMaker/0.1")
	client := *c.http
	client.CheckRedirect = approvedRedirect
	resp, err := client.Do(req)
	if err != nil {
		return mirrorAsset{}, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return mirrorAsset{}, fmt.Errorf("manifest HTTP %d", resp.StatusCode)
	}
	var manifest mirrorManifest
	if err := json.NewDecoder(io.LimitReader(resp.Body, 2*1024*1024)).Decode(&manifest); err != nil {
		return mirrorAsset{}, err
	}
	tag := strings.TrimSpace(manifest.Tag)
	if tag == "" {
		tag = strings.TrimSpace(manifest.Version)
	}
	item, ok := manifest.Assets[assetName]
	if !ok || item.Name != assetName {
		return mirrorAsset{}, errors.New("exact asset is missing")
	}
	sha, ok := normalizedSHA256(item.SHA256)
	if tag == "" || !ok || item.Size <= 0 || item.Size > maxAssetBytes {
		return mirrorAsset{}, errors.New("invalid mirror asset metadata")
	}
	urls := make([]string, 0, len(item.URLs)+1)
	urls = append(urls, item.URLs...)
	urls = append(urls, item.URL)
	if !validMirrorAssetTopology(item, assetName, channel) {
		return mirrorAsset{}, errors.New("mirror asset URLs do not match the required R2/COS topology")
	}
	urls = []string{mirrorAssetBase("r2", channel) + assetName, mirrorAssetBase("cos", channel) + assetName}
	return mirrorAsset{source: source.name, tag: tag, size: item.Size, sha256: sha, urls: urls}, nil
}

// validMirrorAssetTopology verifies the same immutable two-origin layout
// generated by the protected release workflow. The mirror manifest is only a
// discovery hint; still, accepting arbitrary allow-listed paths would let a
// stale or misconfigured index pollute candidate selection.
func validMirrorAssetTopology(item mirrorManifestAsset, assetName string, channel ReleaseChannel) bool {
	if item.Name != assetName {
		return false
	}
	expected := []string{mirrorAssetBase("r2", channel) + assetName, mirrorAssetBase("cos", channel) + assetName}
	return len(item.URLs) == len(expected) && item.URLs[0] == expected[0] && item.URLs[1] == expected[1] && item.URL == expected[1]
}

func (c *Client) probeDownloadCandidates(parent context.Context, expectedSize int64, candidates []downloadCandidate, emit func(logging.Event)) []downloadCandidate {
	unique := make(map[string]downloadCandidate, len(candidates))
	for _, candidate := range candidates {
		if isApprovedDownloadURL(candidate.url) {
			unique[candidate.url] = candidate
		}
	}
	measured := make(chan downloadCandidate, len(unique))
	var group sync.WaitGroup
	for _, candidate := range unique {
		candidate := candidate
		group.Add(1)
		go func() {
			defer group.Done()
			emitEvent(emit, logging.Info, "MIRROR_PROBE_STARTED", "Measuring an approved firmware download node.", map[string]any{"asset": safeAssetName(candidate.url), "source": candidate.source, "endpoint": safeEndpoint(candidate.url)})
			latency, err := c.probeDownloadCandidate(parent, candidate.url, expectedSize)
			if err != nil {
				emitEvent(emit, logging.Info, "MIRROR_PROBE_FAILED", "A firmware download node was not suitable for this package.", map[string]any{"source": candidate.source, "endpoint": safeEndpoint(candidate.url)})
				return
			}
			candidate.latency = latency
			emitEvent(emit, logging.Info, "MIRROR_PROBE_SUCCEEDED", "A firmware download node is available.", map[string]any{"source": candidate.source, "endpoint": safeEndpoint(candidate.url), "durationMs": latency.Milliseconds(), "bytes": expectedSize})
			measured <- candidate
		}()
	}
	group.Wait()
	close(measured)
	result := make([]downloadCandidate, 0, len(unique))
	for candidate := range measured {
		result = append(result, candidate)
	}
	sort.Slice(result, func(i, j int) bool { return result[i].latency < result[j].latency })
	if len(result) > 0 {
		selected := result[0]
		emitEvent(emit, logging.Info, "MIRROR_SELECTED", "Selected the fastest verified firmware download node.", map[string]any{"source": selected.source, "endpoint": safeEndpoint(selected.url), "durationMs": selected.latency.Milliseconds(), "bytes": expectedSize})
	}
	return result
}

func (c *Client) probeDownloadCandidate(parent context.Context, rawURL string, expectedSize int64) (time.Duration, error) {
	ctx, cancel := context.WithTimeout(parent, 5*time.Second)
	defer cancel()
	start := time.Now()
	request := func(method string, rangeProbe bool) (*http.Response, error) {
		req, err := http.NewRequestWithContext(ctx, method, rawURL, nil)
		if err != nil {
			return nil, err
		}
		req.Header.Set("User-Agent", "ClawMateMaker/0.1")
		if rangeProbe {
			req.Header.Set("Range", "bytes=0-0")
		}
		client := *c.http
		client.CheckRedirect = approvedRedirect
		return client.Do(req)
	}
	resp, err := request(http.MethodHead, false)
	if err != nil {
		return 0, err
	}
	if resp.StatusCode == http.StatusMethodNotAllowed || resp.StatusCode == http.StatusForbidden {
		resp.Body.Close()
		resp, err = request(http.MethodGet, true)
		if err != nil {
			return 0, err
		}
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusPartialContent {
		return 0, fmt.Errorf("probe HTTP %d", resp.StatusCode)
	}
	if resp.ContentLength > 0 && resp.StatusCode == http.StatusOK && resp.ContentLength != expectedSize {
		return 0, errors.New("probe content length disagrees with release")
	}
	if resp.StatusCode == http.StatusPartialContent && !validContentRange(resp.Header.Get("Content-Range"), 0, expectedSize) {
		return 0, errors.New("probe content range disagrees with release")
	}
	return time.Since(start), nil
}

func normalizedSHA256(raw string) (string, bool) {
	value := strings.TrimPrefix(strings.ToLower(strings.TrimSpace(raw)), "sha256:")
	if len(value) != sha256.Size*2 {
		return "", false
	}
	if _, err := hex.DecodeString(value); err != nil {
		return "", false
	}
	return value, true
}

func uniqueApprovedMirrorURLs(values []string) []string {
	seen := make(map[string]bool, len(values))
	result := make([]string, 0, len(values))
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || seen[value] || !isApprovedDownloadURL(value) {
			continue
		}
		seen[value] = true
		result = append(result, value)
	}
	return result
}

func cachedAsset(path string, expectedSize int64, expectedDigest string) (string, int64, bool) {
	info, err := os.Stat(path)
	if err != nil || info.Size() != expectedSize || expectedSize <= 0 {
		return "", 0, false
	}
	f, err := os.Open(path)
	if err != nil {
		return "", 0, false
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, io.LimitReader(f, maxAssetBytes+1)); err != nil {
		return "", 0, false
	}
	sum := hex.EncodeToString(h.Sum(nil))
	if expectedDigest != "" && !strings.EqualFold(expectedDigest, "sha256:"+sum) {
		return "", 0, false
	}
	return sum, info.Size(), true
}

func emitEvent(emit func(logging.Event), severity logging.Severity, code, detail string, fields map[string]any) {
	if emit == nil {
		return
	}
	emit(logging.Event{Timestamp: time.Now().UTC(), Severity: severity, Stage: "download", Component: "catalog", Code: code, MessageKey: "catalog." + strings.ToLower(code), Detail: detail, Fields: logging.SafeFields(fields)})
}
func (c *Client) download(ctx context.Context, rawURL, destination string, expectedSize int64) (string, int64, error) {
	temporary := destination + ".part"
	identity, resumeAt, err := resumablePartialIdentity(temporary, rawURL, expectedSize)
	if err != nil {
		return "", 0, err
	}
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, rawURL, nil)
	if err != nil {
		return "", 0, err
	}
	req.Header.Set("User-Agent", "ClawMateMaker/0.1")
	if resumeAt > 0 {
		req.Header.Set("Range", fmt.Sprintf("bytes=%d-", resumeAt))
		if identity.ETag != "" {
			req.Header.Set("If-Range", identity.ETag)
		} else {
			req.Header.Set("If-Range", identity.LastModified)
		}
	}
	client := *c.http
	client.CheckRedirect = approvedRedirect
	resp, err := client.Do(req)
	if err != nil {
		return "", 0, fmt.Errorf("download release asset: %w", err)
	}
	defer resp.Body.Close()
	if resumeAt > 0 && resp.StatusCode == http.StatusRequestedRangeNotSatisfiable {
		if sum, size, ok := cachedAsset(temporary, expectedSize, ""); ok {
			if err := os.Rename(temporary, destination); err != nil {
				return "", 0, err
			}
			_ = os.Remove(partialMetadataPath(temporary))
			return sum, size, nil
		}
		removePartialDownload(destination)
		return c.download(ctx, rawURL, destination, expectedSize)
	}
	if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusPartialContent {
		return "", 0, fmt.Errorf("download release asset: HTTP %d", resp.StatusCode)
	}
	if resumeAt > 0 && resp.StatusCode != http.StatusPartialContent {
		// A server that ignores Range is safe to use only by restarting from
		// zero. Never append a whole asset to a partial cache file.
		removePartialDownload(destination)
		return c.download(ctx, rawURL, destination, expectedSize)
	}
	remaining := expectedSize - resumeAt
	if remaining <= 0 || remaining > maxAssetBytes || resp.ContentLength > remaining || resp.ContentLength > maxAssetBytes {
		return "", 0, errors.New("release asset content length is invalid")
	}
	if resumeAt > 0 && !validContentRange(resp.Header.Get("Content-Range"), resumeAt, expectedSize) {
		// Do not append when the CDN's range response is ambiguous. Discard
		// the old prefix and give this source one clean, non-range attempt.
		removePartialDownload(destination)
		return c.download(ctx, rawURL, destination, expectedSize)
	}
	if resumeAt > 0 && !samePartialIdentity(identity, responsePartialIdentity(rawURL, resp)) {
		removePartialDownload(destination)
		return c.download(ctx, rawURL, destination, expectedSize)
	}
	if resumeAt == 0 {
		// Saving a partial response without a validator would make a future
		// range request ambiguous. The current transfer can finish normally,
		// but an interrupted transfer will be restarted from zero.
		responseIdentity := responsePartialIdentity(rawURL, resp)
		if responseIdentity.ETag != "" || responseIdentity.LastModified != "" {
			if err := writePartialIdentity(temporary, responseIdentity); err != nil {
				return "", 0, err
			}
		} else {
			_ = os.Remove(partialMetadataPath(temporary))
		}
	}
	flags := os.O_CREATE | os.O_WRONLY
	if resumeAt > 0 {
		flags |= os.O_APPEND
	} else {
		flags |= os.O_TRUNC
	}
	out, err := os.OpenFile(temporary, flags, 0600)
	if err != nil {
		return "", 0, err
	}
	n, copyErr := io.Copy(out, io.LimitReader(resp.Body, remaining+1))
	closeErr := out.Close()
	if copyErr != nil {
		return "", 0, copyErr
	}
	if closeErr != nil {
		return "", 0, closeErr
	}
	if n != remaining || n+resumeAt > maxAssetBytes {
		return "", 0, fmt.Errorf("downloaded asset has unexpected size: %d", n+resumeAt)
	}
	sum, size, ok := cachedAsset(temporary, expectedSize, "")
	if !ok || size != expectedSize {
		return "", 0, errors.New("downloaded asset failed local size/hash validation")
	}
	if err := os.Rename(temporary, destination); err != nil {
		return "", 0, err
	}
	_ = os.Remove(partialMetadataPath(temporary))
	return sum, size, nil
}

func resumablePartialIdentity(path, rawURL string, expectedSize int64) (partialDownloadIdentity, int64, error) {
	info, err := os.Stat(path)
	if os.IsNotExist(err) {
		return partialDownloadIdentity{}, 0, nil
	}
	if err != nil {
		return partialDownloadIdentity{}, 0, err
	}
	if info.IsDir() || info.Size() < 0 || info.Size() >= expectedSize || info.Size() > maxAssetBytes {
		removePartialDownload(strings.TrimSuffix(path, ".part"))
		return partialDownloadIdentity{}, 0, nil
	}
	metadata, err := readPartialIdentity(path)
	if err != nil || metadata.URL != rawURL || (metadata.ETag == "" && metadata.LastModified == "") {
		removePartialDownload(strings.TrimSuffix(path, ".part"))
		return partialDownloadIdentity{}, 0, nil
	}
	return metadata, info.Size(), nil
}

func partialMetadataPath(temporary string) string { return temporary + ".meta" }

func readPartialIdentity(temporary string) (partialDownloadIdentity, error) {
	raw, err := os.ReadFile(partialMetadataPath(temporary))
	if err != nil {
		return partialDownloadIdentity{}, err
	}
	var identity partialDownloadIdentity
	if err := json.Unmarshal(raw, &identity); err != nil {
		return partialDownloadIdentity{}, err
	}
	identity.URL = strings.TrimSpace(identity.URL)
	identity.ETag = strings.TrimSpace(identity.ETag)
	identity.LastModified = strings.TrimSpace(identity.LastModified)
	return identity, nil
}

func writePartialIdentity(temporary string, identity partialDownloadIdentity) error {
	raw, err := json.Marshal(identity)
	if err != nil {
		return err
	}
	metadata := partialMetadataPath(temporary)
	staging := metadata + ".new"
	if err := os.WriteFile(staging, raw, 0600); err != nil {
		return err
	}
	if err := os.Rename(staging, metadata); err != nil {
		_ = os.Remove(staging)
		return err
	}
	return nil
}

func responsePartialIdentity(rawURL string, response *http.Response) partialDownloadIdentity {
	return partialDownloadIdentity{URL: rawURL, ETag: strings.TrimSpace(response.Header.Get("ETag")), LastModified: strings.TrimSpace(response.Header.Get("Last-Modified"))}
}

func samePartialIdentity(previous, current partialDownloadIdentity) bool {
	if previous.URL != current.URL {
		return false
	}
	if previous.ETag != "" {
		return current.ETag == previous.ETag
	}
	return previous.LastModified != "" && current.LastModified == previous.LastModified
}

func removePartialDownload(destination string) {
	_ = os.Remove(destination + ".part")
	_ = os.Remove(destination + ".part.meta")
	_ = os.Remove(destination + ".part.meta.new")
}

func validContentRange(value string, start, total int64) bool {
	var gotStart, gotEnd, gotTotal int64
	if _, err := fmt.Sscanf(strings.TrimSpace(value), "bytes %d-%d/%d", &gotStart, &gotEnd, &gotTotal); err != nil {
		return false
	}
	return gotStart == start && gotEnd >= gotStart && gotTotal == total
}
func isGitHubReleaseURL(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme != "https" || u.User != nil {
		return false
	}
	host := strings.ToLower(u.Hostname())
	return host == "github.com" || host == "objects.githubusercontent.com" || host == "release-assets.githubusercontent.com"
}

func isApprovedDownloadURL(raw string) bool {
	u, err := url.Parse(raw)
	if err != nil || u.Scheme != "https" || u.User != nil || u.Host == "" || u.Port() != "" {
		return false
	}
	switch strings.ToLower(u.Hostname()) {
	case "github.com", "objects.githubusercontent.com", "release-assets.githubusercontent.com", "pub-c837069cbe31469590a5fea6235b436b.r2.dev", "maclaw-1252723594.cos.ap-beijing.myqcloud.com":
		return true
	default:
		return false
	}
}

func downloadSource(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return "unknown"
	}
	switch strings.ToLower(u.Hostname()) {
	case "pub-c837069cbe31469590a5fea6235b436b.r2.dev":
		return "r2"
	case "maclaw-1252723594.cos.ap-beijing.myqcloud.com":
		return "cos"
	default:
		return "github"
	}
}

func approvedRedirect(req *http.Request, via []*http.Request) error {
	if len(via) >= maxApprovedRedirects {
		return errors.New("firmware download exceeded approved redirect limit")
	}
	if !isApprovedDownloadURL(req.URL.String()) {
		return errors.New("redirected outside approved firmware download hosts")
	}
	return nil
}

// safeEndpoint deliberately emits only the host. Mirror URLs may include
// signed query strings, which must never appear in diagnostic logs.
func safeEndpoint(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return "invalid"
	}
	return strings.ToLower(u.Hostname())
}

func safeAssetName(raw string) string {
	u, err := url.Parse(raw)
	if err != nil {
		return ""
	}
	return filepath.Base(u.Path)
}
func safeSegment(value string) string {
	value = strings.Map(func(r rune) rune {
		if (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '.' || r == '-' || r == '_' {
			return r
		}
		return '_'
	}, value)
	if value == "" {
		return "unknown"
	}
	return value
}
