/data/soft/hub/data/logs/*.out.log /data/soft/hubcenter/*.out /data/soft/hubcenter/data/logs/*.log {
    weekly
    rotate 4
    compress
    missingok
    notifempty
    copytruncate
    maxsize 512M
}
/data/soft/hub/data/logs/hub.log /data/soft/hub/data/logs/registration.log {
    weekly
    rotate 4
    compress
    missingok
    notifempty
    copytruncate
    maxsize 64M
}
