package llmservice

import (
	"context"
	"fmt"
	"math"
	"net/http"
	"strings"

	"github.com/RapidAI/CodeClaw/corelib/llmpool"
)

type OfficialForwardMeta struct {
	// RequestID is generated by Hub before forwarding and ties the HubCenter
	// attempt to Hub's idempotent user settlement.
	RequestID       string
	WorkloadClass   string
	ClassSource     string
	ResolvedModel   string
	Preview         string
	WorkflowType    string
	PhaseKind       string
	TaskType        string
	OpenCodeSession string
	RuleClass       string
	RuleSource      string
	HeadClass       string
	HeadMaxP        float64
	HeadUsed        bool
	Passthrough     bool
}

type officialForwardMetaKey struct{}

func WithOfficialForwardMeta(ctx context.Context, meta OfficialForwardMeta) context.Context {
	if ctx == nil {
		return ctx
	}
	return context.WithValue(ctx, officialForwardMetaKey{}, meta)
}

func OfficialForwardMetaFrom(ctx context.Context) OfficialForwardMeta {
	if ctx == nil {
		return OfficialForwardMeta{}
	}
	meta, _ := ctx.Value(officialForwardMetaKey{}).(OfficialForwardMeta)
	return meta
}

func (g *ModelServiceGroup) IsDynamic() bool {
	return g != nil && llmpool.IsDynamicKind(g.Kind)
}

func (g *ModelServiceGroup) ToPoolGroup() llmpool.ServiceGroup {
	if g == nil {
		return llmpool.ServiceGroup{}
	}
	models := make([]llmpool.ModelConfig, 0, len(g.Models))
	for _, model := range g.Models {
		configs := make([]llmpool.ModelProviderConfig, 0, len(model.ProviderConfigs))
		for _, cfg := range model.ProviderConfigs {
			configs = append(configs, llmpool.ModelProviderConfig{
				ProviderID:           cfg.ProviderID,
				Model:                cfg.Model,
				BillingMode:          cfg.BillingMode,
				CapabilityTags:       append([]string(nil), cfg.CapabilityTags...),
				Priority:             cfg.Priority,
				ResolutionTier:       cfg.ResolutionTier,
				CreditMultiplier:     cfg.CreditMultiplier,
				TokenPricingOverride: cfg.TokenPricingOverride,
				TokenPricing:         cfg.TokenPricing,
			})
		}
		models = append(models, llmpool.ModelConfig{
			Name:             model.Name,
			ProviderIDs:      append([]string(nil), model.ProviderIDs...),
			ProviderConfigs:  configs,
			CapabilityTags:   append([]string(nil), model.CapabilityTags...),
			Priority:         model.Priority,
			ResolutionTier:   model.ResolutionTier,
			CreditMultiplier: model.CreditMultiplier,
		})
	}
	return llmpool.ServiceGroup{
		ID:            g.ID,
		Name:          g.Name,
		Description:   g.Description,
		AccessPolicy:  g.AccessPolicy,
		Kind:          g.Kind,
		QualityFloor:  g.QualityFloor,
		ExposedModels: append([]string(nil), g.ExposedModels...),
		Routes:        append([]llmpool.WorkloadRoute(nil), g.Routes...),
		Models:        models,
	}
}

func (r *Registry) ValidateDynamicGroups() error {
	if r == nil {
		return nil
	}
	for i := range r.ModelServiceGroups {
		group := &r.ModelServiceGroups[i]
		if group.BillingGroupMultiplier < 0 || math.IsNaN(group.BillingGroupMultiplier) || math.IsInf(group.BillingGroupMultiplier, 0) {
			return fmt.Errorf("service group %s: billing_group_multiplier must be a finite positive number", group.ID)
		}
		for _, model := range group.Models {
			for _, cfg := range model.ProviderConfigs {
				if err := llmpool.ValidateRouteBilling(cfg.BillingMode, cfg.TokenPricing); err != nil {
					return fmt.Errorf("service group %s model %s provider %s: %w", group.ID, model.Name, cfg.ProviderID, err)
				}
			}
		}
		if !group.IsDynamic() {
			continue
		}
		if IsBuiltinServiceGroup(group.ID) {
			return fmt.Errorf("builtin official group %s must stay static", group.ID)
		}
		pool := group.ToPoolGroup()
		if err := llmpool.ValidateDynamicServiceGroup(&pool); err != nil {
			return fmt.Errorf("service group %s: %w", group.ID, err)
		}
		for _, model := range group.Models {
			for _, cfg := range model.ProviderConfigs {
				if !IsBuiltinProvider(cfg.ProviderID) {
					continue
				}
				if strings.TrimSpace(cfg.Model) == "" {
					return fmt.Errorf("service group %s: official provider on %s requires official-high, official-mid, or official-low", group.ID, model.Name)
				}
				if llmpool.NormalizeOfficialTier(cfg.Model) == "" {
					return fmt.Errorf("service group %s: official provider model %q must be official-high, official-mid, or official-low", group.ID, cfg.Model)
				}
			}
		}
	}
	return nil
}

func (r *Registry) FirstDynamicGroup(ids []string) *ModelServiceGroup {
	if r == nil {
		return nil
	}
	for _, id := range ids {
		group := r.FindModelServiceGroup(id)
		if group != nil && group.IsDynamic() {
			return group
		}
	}
	return nil
}

func SelectDynamicGroup(r *Registry, authorizedIDs []string, requestedGroupID string) *ModelServiceGroup {
	if r == nil {
		return nil
	}
	requestedGroupID = strings.TrimSpace(requestedGroupID)
	if requestedGroupID != "" {
		for _, id := range authorizedIDs {
			if strings.EqualFold(strings.TrimSpace(id), requestedGroupID) {
				if group := r.FindModelServiceGroup(id); group != nil && group.IsDynamic() {
					return group
				}
			}
		}
	}
	return r.FirstDynamicGroup(authorizedIDs)
}

func ResolveDynamicAuthorizedModel(header http.Header, body map[string]any, models []AuthorizedModel, reg *Registry, requestedGroupID string) (*AuthorizedModel, string, *llmpool.WorkloadDecision, error) {
	return ResolveDynamicAuthorizedModelWithHead(header, body, models, reg, requestedGroupID, nil)
}

func ResolveDynamicAuthorizedModelWithHead(header http.Header, body map[string]any, models []AuthorizedModel, reg *Registry, requestedGroupID string, runtime *llmpool.HeadRuntime) (*AuthorizedModel, string, *llmpool.WorkloadDecision, error) {
	requested, _ := body["model"].(string)
	requested = strings.TrimSpace(requested)
	if len(models) == 0 {
		return nil, requested, nil, fmt.Errorf("no active model service entitlement")
	}
	groupIDs := authorizedGroupIDs(models)
	if !llmpool.IsAutoModel(requested) {
		class, source := llmpool.ClassifyWorkload(llmpool.ClassifyInput{Header: header, Body: body})
		if selected := findAuthorizedModelInGroups(models, requested, requestedGroupID); selected != nil && authorizedModelServesGroups(selected, requestedGroupID) {
			clone := cloneAuthorizedModel(selected)
			pinChargedGroup(clone, reg, requestedGroupID)
			clone.AvailabilityFallbacks = siblingAuthorizedModels(models, clone, class)
			dec := llmpool.WorkloadDecision{
				Class:         class,
				Source:        source,
				ResolvedModel: clone.Name,
				Quality:       llmpool.QualityForOfficialTier(clone.Name),
				Passthrough:   true,
			}
			dec.Attribution = llmpool.AttributionFrom(dec, requestedGroupID, requested)
			return clone, requested, &dec, nil
		}
		if fallback := fallbackAuthorizedOfficialModel(models, requested, class, requestedGroupID); fallback != nil {
			clone := cloneAuthorizedModel(fallback)
			pinChargedGroup(clone, reg, requestedGroupID)
			clone.AvailabilityFallbacks = siblingAuthorizedModels(models, clone, class)
			dec := llmpool.WorkloadDecision{
				Class:                class,
				Source:               source,
				ResolvedModel:        clone.Name,
				Quality:              llmpool.QualityForOfficialTier(clone.Name),
				AvailabilityFallback: true,
				Passthrough:          true,
			}
			dec.Attribution = llmpool.AttributionFrom(dec, requestedGroupID, requested)
			return clone, requested, &dec, nil
		}
		return nil, requested, nil, fmt.Errorf("model %q is not authorized for this account", requested)
	}
	if group := SelectDynamicGroup(reg, groupIDs, requestedGroupID); group != nil {
		pool := group.ToPoolGroup()
		dec := llmpool.ClassifyAndRouteWithHead(header, body, &pool, requested, runtime)
		if strings.TrimSpace(dec.ResolvedModel) == "" {
			return nil, requested, &dec, fmt.Errorf("dynamic service group %s did not resolve a logical model", group.ID)
		}
		selected := findAuthorizedModelInGroups(models, dec.ResolvedModel, group.ID)
		if selected != nil && !authorizedModelServesGroups(selected, group.ID) {
			selected = nil
		}
		if selected == nil {
			if fallback := fallbackAuthorizedOfficialModel(models, dec.ResolvedModel, dec.Class, group.ID); fallback != nil {
				selected = fallback
				dec.ResolvedModel = fallback.Name
				if q := llmpool.QualityForOfficialTier(fallback.Name); q != "" {
					dec.Quality = q
				}
				dec.AvailabilityFallback = true
			}
		}
		if selected != nil {
			if upgraded := upgradePlanAwayFromLow(models, selected, dec.Class, group.ID); upgraded != nil && upgraded != selected {
				selected = upgraded
				dec.ResolvedModel = upgraded.Name
				if q := llmpool.QualityForOfficialTier(upgraded.Name); q != "" {
					dec.Quality = q
				}
				dec.AvailabilityFallback = true
			}
		}
		if selected == nil {
			return nil, requested, &dec, fmt.Errorf("resolved model %q is not authorized for this account", dec.ResolvedModel)
		}
		clone := cloneAuthorizedModel(selected)
		clone.ChargedServiceGroupIDs = []string{group.ID}
		clone.Kind = llmpool.ServiceGroupKindDynamic
		restrictAuthorizedModelToChargedGroup(clone)
		clone.AvailabilityFallbacks = siblingAuthorizedModels(models, clone, dec.Class)
		dec.BindRequestedGroup(group.ID)
		return clone, clone.Name, &dec, nil
	}
	class, source := llmpool.ClassifyWorkload(llmpool.ClassifyInput{Header: header, Body: body})
	selected := SelectBestModelForRequest(body, models)
	if selected == nil {
		selected = &models[0]
	}
	if upgraded := upgradePlanAwayFromLow(models, selected, class, requestedGroupID); upgraded != nil {
		selected = upgraded
	}
	clone := cloneAuthorizedModel(selected)
	pinChargedGroup(clone, reg, requestedGroupID)
	clone.AvailabilityFallbacks = siblingAuthorizedModels(models, clone, class)
	dec := llmpool.WorkloadDecision{
		Class:         class,
		Source:        source,
		ResolvedModel: clone.Name,
		Quality:       llmpool.QualityForOfficialTier(clone.Name),
		Passthrough:   true,
	}
	dec.Attribution = llmpool.AttributionFrom(dec, requestedGroupID, requested)
	return clone, clone.Name, &dec, nil
}

func authorizedGroupIDs(models []AuthorizedModel) []string {
	out := make([]string, 0)
	seen := map[string]struct{}{}
	for _, model := range models {
		for _, id := range model.ServiceGroupIDs {
			id = strings.TrimSpace(id)
			if id == "" {
				continue
			}
			key := strings.ToLower(id)
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			out = append(out, id)
		}
	}
	return out
}

func findAuthorizedModel(models []AuthorizedModel, name string) *AuthorizedModel {
	return findAuthorizedModelInGroups(models, name)
}

func findAuthorizedModelInGroups(models []AuthorizedModel, name string, groupIDs ...string) *AuthorizedModel {
	name = strings.TrimSpace(name)
	if name == "" {
		return nil
	}
	seed := authorizedGroupSeed(groupIDs...)
	for i := range models {
		if !strings.EqualFold(strings.TrimSpace(models[i].Name), name) {
			continue
		}
		if seed == nil || sharesAuthorizedGroup(seed, &models[i]) {
			return &models[i]
		}
	}
	return nil
}

func cloneAuthorizedModel(model *AuthorizedModel) *AuthorizedModel {
	if model == nil {
		return nil
	}
	clone := *model
	clone.ProviderIDs = append([]string(nil), model.ProviderIDs...)
	clone.ServiceGroupIDs = append([]string(nil), model.ServiceGroupIDs...)
	clone.ChargedServiceGroupIDs = append([]string(nil), model.ChargedServiceGroupIDs...)
	clone.CapabilityTags = append([]string(nil), model.CapabilityTags...)
	clone.ProviderCapabilityTags = cloneStringSliceMap(model.ProviderCapabilityTags)
	clone.ProviderPriorities = cloneIntMap(model.ProviderPriorities)
	clone.ProviderResolutionTiers = cloneIntMap(model.ProviderResolutionTiers)
	clone.ProviderServiceGroups = cloneStringSliceMap(model.ProviderServiceGroups)
	clone.ProviderCreditMultipliers = cloneFloat64Map(model.ProviderCreditMultipliers)
	clone.ProviderUpstreamModels = cloneStringMap(model.ProviderUpstreamModels)
	clone.ProviderUpstreamRouteModels = cloneNestedStringMap(model.ProviderUpstreamRouteModels)
	clone.ProviderServiceGroupUpstreams = cloneNestedStringMap(model.ProviderServiceGroupUpstreams)
	clone.ProviderBillingModes = cloneStringMap(model.ProviderBillingModes)
	clone.ProviderTokenPricing = cloneTokenPricingMap(model.ProviderTokenPricing)
	clone.ProviderRouteBilling = cloneProviderRouteBillingMap(model.ProviderRouteBilling)
	if len(model.AvailabilityFallbacks) > 0 {
		clone.AvailabilityFallbacks = make([]AuthorizedModel, 0, len(model.AvailabilityFallbacks))
		for i := range model.AvailabilityFallbacks {
			fb := cloneAuthorizedModel(&model.AvailabilityFallbacks[i])
			if fb == nil {
				continue
			}
			fb.AvailabilityFallbacks = nil
			clone.AvailabilityFallbacks = append(clone.AvailabilityFallbacks, *fb)
		}
	} else {
		clone.AvailabilityFallbacks = nil
	}
	return &clone
}

func upgradePlanAwayFromLow(models []AuthorizedModel, selected *AuthorizedModel, class string, groupIDs ...string) *AuthorizedModel {
	if selected == nil || llmpool.QualityForOfficialTier(selected.Name) != llmpool.QualityLow {
		return selected
	}
	if class != llmpool.WorkloadClassPlan && class != llmpool.WorkloadClassDesign {
		return selected
	}
	for _, name := range []string{llmpool.OfficialTierMid, llmpool.OfficialTierHigh} {
		if found := findAuthorizedModelInGroups(models, name, groupIDs...); found != nil && authorizedModelServesGroups(found, groupIDs...) {
			return found
		}
	}
	return selected
}

func fallbackAuthorizedOfficialModel(models []AuthorizedModel, selected, class string, groupIDs ...string) *AuthorizedModel {
	seed := authorizedGroupSeed(groupIDs...)
	if seed == nil {
		return nil
	}
	quality := llmpool.QualityForOfficialTier(selected)
	if quality == "" {
		quality = llmpool.NormalizeQuality(selected)
	}
	for _, band := range llmpool.QualityAvailabilityChain(quality, class) {
		name := llmpool.OfficialTierForQuality(band)
		if name == "" || strings.EqualFold(name, selected) {
			continue
		}
		found := findAuthorizedModelInGroups(models, name, groupIDs...)
		if found == nil || !authorizedModelServesGroups(found, groupIDs...) {
			continue
		}
		return found
	}
	return nil
}

func authorizedGroupSeed(groupIDs ...string) *AuthorizedModel {
	ids := make([]string, 0, len(groupIDs))
	for _, id := range groupIDs {
		if trimmed := strings.TrimSpace(id); trimmed != "" {
			ids = append(ids, trimmed)
		}
	}
	if len(ids) == 0 {
		return nil
	}
	return &AuthorizedModel{ServiceGroupIDs: ids, ChargedServiceGroupIDs: ids}
}

func siblingAuthorizedModels(models []AuthorizedModel, selected *AuthorizedModel, class string) []AuthorizedModel {
	if selected == nil {
		return nil
	}
	quality := llmpool.QualityForOfficialTier(selected.Name)
	if quality == "" {
		return nil
	}
	var out []AuthorizedModel
	seen := map[string]struct{}{strings.ToLower(strings.TrimSpace(selected.Name)): {}}
	groupIDs := authorizedModelGroupIDs(selected)
	for _, band := range llmpool.QualityAvailabilityChain(quality, class) {
		name := llmpool.OfficialTierForQuality(band)
		if name == "" {
			continue
		}
		candidate := findAuthorizedModelInGroups(models, name, groupIDs...)
		if candidate == nil || !sharesAuthorizedGroup(selected, candidate) || !authorizedModelServesGroups(candidate, groupIDs...) {
			continue
		}
		key := strings.ToLower(strings.TrimSpace(candidate.Name))
		if _, ok := seen[key]; ok {
			continue
		}
		seen[key] = struct{}{}
		clone := cloneAuthorizedModel(candidate)
		clone.AvailabilityFallbacks = nil
		if len(selected.ChargedServiceGroupIDs) > 0 {
			clone.ChargedServiceGroupIDs = append([]string(nil), selected.ChargedServiceGroupIDs...)
		}
		if selected.Kind != "" {
			clone.Kind = selected.Kind
		}
		restrictAuthorizedModelToChargedGroup(clone)
		if len(selected.ProviderIDs) > 0 && len(clone.ProviderIDs) == 0 {
			continue
		}
		out = append(out, *clone)
	}
	return out
}

func sharesAuthorizedGroup(a, b *AuthorizedModel) bool {
	if a == nil || b == nil {
		return false
	}
	for _, id := range authorizedModelGroupIDs(a) {
		id = strings.TrimSpace(id)
		if id == "" {
			continue
		}
		for _, other := range b.ServiceGroupIDs {
			if strings.EqualFold(strings.TrimSpace(other), id) {
				return true
			}
		}
		for _, other := range b.ChargedServiceGroupIDs {
			if strings.EqualFold(strings.TrimSpace(other), id) {
				return true
			}
		}
	}
	return false
}

// CloneAuthorizedModel returns a request-safe copy of an authorized model.
// Routing and admission paths narrow ProviderIDs and may add charged-group
// context; none of those per-request mutations may alter a cached model.
func CloneAuthorizedModel(model *AuthorizedModel) *AuthorizedModel {
	return cloneAuthorizedModel(model)
}

func cloneStringSliceMap(source map[string][]string) map[string][]string {
	if source == nil {
		return nil
	}
	cloned := make(map[string][]string, len(source))
	for key, values := range source {
		cloned[key] = append([]string(nil), values...)
	}
	return cloned
}

func cloneIntMap(source map[string]int) map[string]int {
	if source == nil {
		return nil
	}
	cloned := make(map[string]int, len(source))
	for key, value := range source {
		cloned[key] = value
	}
	return cloned
}

func cloneFloat64Map(source map[string]float64) map[string]float64 {
	if source == nil {
		return nil
	}
	cloned := make(map[string]float64, len(source))
	for key, value := range source {
		cloned[key] = value
	}
	return cloned
}

func cloneStringMap(source map[string]string) map[string]string {
	if source == nil {
		return nil
	}
	cloned := make(map[string]string, len(source))
	for key, value := range source {
		cloned[key] = value
	}
	return cloned
}

func cloneNestedStringMap(source map[string]map[string]string) map[string]map[string]string {
	if source == nil {
		return nil
	}
	cloned := make(map[string]map[string]string, len(source))
	for key, values := range source {
		cloned[key] = cloneStringMap(values)
	}
	return cloned
}

func cloneTokenPricingMap(source map[string]llmpool.TokenPricing) map[string]llmpool.TokenPricing {
	if source == nil {
		return nil
	}
	cloned := make(map[string]llmpool.TokenPricing, len(source))
	for key, pricing := range source {
		cloned[key] = cloneTokenPricing(pricing)
	}
	return cloned
}

func cloneProviderRouteBillingMap(source map[string]map[string]ProviderRouteBilling) map[string]map[string]ProviderRouteBilling {
	if source == nil {
		return nil
	}
	cloned := make(map[string]map[string]ProviderRouteBilling, len(source))
	for providerID, routes := range source {
		clonedRoutes := make(map[string]ProviderRouteBilling, len(routes))
		for upstreamModel, route := range routes {
			route.TokenPricing = cloneTokenPricing(route.TokenPricing)
			clonedRoutes[upstreamModel] = route
		}
		cloned[providerID] = clonedRoutes
	}
	return cloned
}

func cloneTokenPricing(pricing llmpool.TokenPricing) llmpool.TokenPricing {
	pricing.PriceSchedule = append([]llmpool.TokenPriceWindow(nil), pricing.PriceSchedule...)
	for i := range pricing.PriceSchedule {
		pricing.PriceSchedule[i].Days = append([]int(nil), pricing.PriceSchedule[i].Days...)
	}
	return pricing
}

func authorizedModelGroupIDs(model *AuthorizedModel) []string {
	if model == nil {
		return nil
	}
	if len(model.ChargedServiceGroupIDs) > 0 {
		return append([]string(nil), model.ChargedServiceGroupIDs...)
	}
	return append([]string(nil), model.ServiceGroupIDs...)
}

func pinChargedGroup(model *AuthorizedModel, reg *Registry, preferredGroupIDs ...string) {
	if model == nil || reg == nil || len(model.ChargedServiceGroupIDs) > 0 {
		return
	}
	pin := func(id string) bool {
		group := reg.FindModelServiceGroup(id)
		if group == nil || !group.IsDynamic() {
			return false
		}
		model.ChargedServiceGroupIDs = []string{group.ID}
		model.Kind = llmpool.ServiceGroupKindDynamic
		restrictAuthorizedModelToChargedGroup(model)
		return true
	}
	try := func(ids []string, requireServe bool) bool {
		for _, id := range ids {
			if !sharesAuthorizedGroup(authorizedGroupSeed(id), model) {
				continue
			}
			if requireServe && !authorizedModelServesGroups(model, id) {
				continue
			}
			if pin(id) {
				return true
			}
		}
		return false
	}
	if try(preferredGroupIDs, true) || try(model.ServiceGroupIDs, true) {
		return
	}
	_ = try(preferredGroupIDs, false) || try(model.ServiceGroupIDs, false)
}

func restrictAuthorizedModelToChargedGroup(model *AuthorizedModel) {
	if model == nil || len(model.ChargedServiceGroupIDs) == 0 || len(model.ProviderServiceGroups) == 0 {
		return
	}
	charged := map[string]struct{}{}
	for _, id := range model.ChargedServiceGroupIDs {
		id = strings.ToLower(strings.TrimSpace(id))
		if id != "" {
			charged[id] = struct{}{}
		}
	}
	if len(charged) == 0 {
		return
	}
	keep := make([]string, 0, len(model.ProviderIDs))
	seen := map[string]struct{}{}
	for _, providerID := range model.ProviderIDs {
		key := normalizedProviderKey(providerID)
		if key == "" {
			continue
		}
		if _, ok := seen[key]; ok {
			continue
		}
		if !providerSharesChargedGroup(model, providerID, charged) {
			continue
		}
		seen[key] = struct{}{}
		keep = append(keep, providerID)
	}
	model.ProviderIDs = keep
}

func providerSharesChargedGroup(model *AuthorizedModel, providerID string, charged map[string]struct{}) bool {
	if model == nil || len(charged) == 0 {
		return false
	}
	for _, id := range model.ProviderServiceGroups[normalizedProviderKey(providerID)] {
		if _, ok := charged[strings.ToLower(strings.TrimSpace(id))]; ok {
			return true
		}
	}
	return false
}

func authorizedModelServesGroups(model *AuthorizedModel, groupIDs ...string) bool {
	if model == nil {
		return false
	}
	if len(model.ProviderIDs) == 0 || len(model.ProviderServiceGroups) == 0 {
		return true
	}
	charged := map[string]struct{}{}
	for _, id := range groupIDs {
		id = strings.ToLower(strings.TrimSpace(id))
		if id != "" {
			charged[id] = struct{}{}
		}
	}
	if len(charged) == 0 {
		return true
	}
	for _, providerID := range model.ProviderIDs {
		if providerSharesChargedGroup(model, providerID, charged) {
			return true
		}
	}
	return false
}

func ChargedServiceGroupIDs(model *AuthorizedModel, providerID string) []string {
	if model != nil && len(model.ChargedServiceGroupIDs) > 0 {
		return append([]string(nil), model.ChargedServiceGroupIDs...)
	}
	return ServiceGroupIDsForProvider(model, providerID)
}

func OfficialUpstreamModel(model *AuthorizedModel, providerID string) string {
	if model == nil {
		return ""
	}
	providerKey := normalizedProviderKey(providerID)
	if byGroup := model.ProviderServiceGroupUpstreams[providerKey]; len(byGroup) > 0 {
		for _, groupID := range ChargedServiceGroupIDs(model, providerID) {
			if upstream := strings.TrimSpace(byGroup[strings.ToLower(strings.TrimSpace(groupID))]); upstream != "" {
				return upstream
			}
		}
	}
	return OfficialUpstreamModelForLogicalModel(model, providerID, model.Name)
}

// OfficialUpstreamModelForLogicalModel returns the concrete official route for
// a logical model. The per-model mapping is needed when a provider appears in
// more than one model under the same authorization.
func OfficialUpstreamModelForLogicalModel(model *AuthorizedModel, providerID, logicalModel string) string {
	if model == nil {
		return ""
	}
	providerKey := normalizedProviderKey(providerID)
	if byLogical := model.ProviderUpstreamRouteModels[providerKey]; len(byLogical) > 0 {
		if upstream := strings.TrimSpace(byLogical[strings.ToLower(strings.TrimSpace(logicalModel))]); upstream != "" {
			return upstream
		}
	}
	if name := strings.TrimSpace(model.ProviderUpstreamModels[providerKey]); name != "" {
		return name
	}
	if llmpool.IsOfficialTierName(model.Name) {
		return llmpool.NormalizeOfficialTier(model.Name)
	}
	return ""
}

func ShouldPassthroughOfficialAuto(model *AuthorizedModel, reg *Registry) bool {
	if model == nil || !llmpool.IsAutoModel(model.Name) {
		return false
	}
	for _, id := range model.ServiceGroupIDs {
		group := reg.FindModelServiceGroup(id)
		if group == nil {
			continue
		}
		if group.IsDynamic() {
			return false
		}
		if !IsBuiltinServiceGroup(group.ID) {
			return false
		}
	}
	return true
}

func PublicAuthorizedModels(models []AuthorizedModel, reg *Registry) []AuthorizedModel {
	out := make([]AuthorizedModel, 0, len(models))
	for _, model := range models {
		if model.HiddenFromCatalog || shouldHideDynamicInternalModel(model, reg) {
			continue
		}
		out = append(out, model)
	}
	return out
}

func shouldHideDynamicInternalModel(model AuthorizedModel, reg *Registry) bool {
	if llmpool.IsAutoModel(model.Name) || reg == nil {
		return false
	}
	sawDynamic := false
	sawStatic := false
	exposed := false
	for _, id := range model.ServiceGroupIDs {
		group := reg.FindModelServiceGroup(id)
		if group == nil {
			continue
		}
		if !group.IsDynamic() {
			sawStatic = true
			continue
		}
		sawDynamic = true
		for _, name := range llmpool.PublicCatalogModels(&llmpool.ServiceGroup{Kind: group.Kind, ExposedModels: group.ExposedModels}) {
			if strings.EqualFold(name, model.Name) {
				exposed = true
			}
		}
	}
	return sawDynamic && !sawStatic && !exposed
}
