package im

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net/http"
	"strings"
	"time"
)

// Small host-agnostic helpers shared by the MaClawSrv and GUI third-party
// gateway servers. They used to live as verbatim per-host copies; keep the
// single implementation here next to the protocol structs.

// ThirdPartyTruncateRunes caps text at max runes. max <= 0 leaves text unchanged.
func ThirdPartyTruncateRunes(text string, max int) string {
	if max <= 0 {
		return text
	}
	runes := []rune(text)
	if len(runes) <= max {
		return text
	}
	return string(runes[:max])
}

// ThirdPartyOutgoingMIME returns the effective MIME of an outgoing message:
// the explicit mimeType wins over the legacy contentType field.
func ThirdPartyOutgoingMIME(msg ThirdPartyOutgoingMessage) string {
	if strings.TrimSpace(msg.MimeType) != "" {
		return msg.MimeType
	}
	return msg.ContentType
}

// NewThirdPartyGatewayRequestID returns the standard "gw_" request identifier
// every gateway response carries for support correlation.
func NewThirdPartyGatewayRequestID() string {
	return fmt.Sprintf("gw_%d", time.Now().UnixNano())
}

// RandomThirdPartyToken generates a 16-byte hex token (media tokens, short-lived
// secrets). Gateway integration tokens that need 32 bytes are generated by the
// hosts separately.
func RandomThirdPartyToken() (string, error) {
	var buf [16]byte
	if _, err := rand.Read(buf[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(buf[:]), nil
}

// ThirdPartyBearerToken extracts the bearer credential from the Authorization
// header, or "" when absent or not a Bearer scheme.
func ThirdPartyBearerToken(r *http.Request) string {
	auth := strings.TrimSpace(r.Header.Get("Authorization"))
	if !strings.HasPrefix(strings.ToLower(auth), "bearer ") {
		return ""
	}
	return strings.TrimSpace(auth[len("Bearer "):])
}

// ThirdPartyForwardedHeaderFirst returns the first entry of a possibly
// comma-separated forwarded header value.
func ThirdPartyForwardedHeaderFirst(value string) string {
	if idx := strings.Index(value, ","); idx >= 0 {
		value = value[:idx]
	}
	return strings.TrimSpace(value)
}

// ThirdPartyForwardedScheme resolves the external scheme from X-Forwarded-Proto,
// falling back to TLS detection and finally plain http.
func ThirdPartyForwardedScheme(value string, isTLS bool) string {
	scheme := strings.ToLower(ThirdPartyForwardedHeaderFirst(value))
	switch scheme {
	case "https":
		return "https"
	case "http":
		return "http"
	}
	if isTLS && scheme == "" {
		return "https"
	}
	return "http"
}

// ThirdPartyForwardedHost sanitizes a (possibly forwarded) Host value. Anything
// empty or containing characters that could smuggle a path/authority split
// degrades to the loopback default.
func ThirdPartyForwardedHost(value string) string {
	host := ThirdPartyForwardedHeaderFirst(value)
	if host == "" || strings.ContainsAny(host, " \t\r\n/@?#\\%\"'") {
		return "127.0.0.1"
	}
	return host
}

// ThirdPartyGatewayBaseURL builds the externally visible base URL of the
// gateway API from the current request, honoring reverse-proxy headers.
func ThirdPartyGatewayBaseURL(r *http.Request) string {
	scheme := ThirdPartyForwardedScheme(r.Header.Get("X-Forwarded-Proto"), r.TLS != nil)
	host := ThirdPartyForwardedHost(firstNonEmptyString(r.Header.Get("X-Forwarded-Host"), r.Host))
	return scheme + "://" + host + "/api/im-gateway/v1"
}

func firstNonEmptyString(values ...string) string {
	for _, value := range values {
		if strings.TrimSpace(value) != "" {
			return strings.TrimSpace(value)
		}
	}
	return ""
}

// ThirdPartyPruneAckedMessages eagerly removes acknowledged entries before
// enforcing the hard per-client cap. This prevents delivered reply history
// from evicting an unacknowledged control message while a client is briefly
// offline. Acked bookkeeping for every message that leaves the store is
// dropped with it, so the acked map stays bounded. The returned slice
// replaces the stored one; the cursor stays monotonic.
func ThirdPartyPruneAckedMessages(messages []ThirdPartyOutgoingMessage, acked map[string]string, max int) []ThirdPartyOutgoingMessage {
	if len(messages) == 0 {
		return messages
	}
	kept := messages[:0]
	for _, message := range messages {
		if acked[message.ID] != "" {
			delete(acked, message.ID)
			continue
		}
		kept = append(kept, message)
	}
	if max > 0 && len(kept) > max {
		drop := len(kept) - max
		for _, message := range kept[:drop] {
			delete(acked, message.ID)
		}
		copy(kept, kept[drop:])
		kept = kept[:max]
	}
	return kept
}
