const zh = {
  "adminConsole": "管理控制台",
  "logout": "退出",
  "overview": "总览",
  "sandbox": "沙箱",
  "logs": "日志",
  "config": "服务配置",
  "tenants": "租户与用户",
  "accounts": "管理员",
  "knowledge": "知识与技能来源",
  "ops": "运维",
  "setup": "初始化管理员",
  "login": "管理员登录",
  "refresh": "刷新",
  "save": "保存",
  "run": "运行",
  "validate": "校验",
  "exportPlan": "导出方案",
  "detect": "检测",
  "smoke": "冒烟检测",
  "diagnose": "诊断并保存报告",
  "installPlan": "安装方案",
  "changePassword": "修改密码",
  "sessions": "会话",
  "users": "用户",
  "status": "状态",
  "action": "操作",
  "confirm": "确认",
  "raw": "原始数据",
  "password": "密码",
  "username": "用户名",
  "setupToken": "初始化令牌",
  "displayName": "显示名",
  "language": "语言",
  "adminSecret": "Admin Secret 或会话 Token",
  "loginHint": "登录后所有操作都通过 Admin API 完成。",
  "setupHint": "首次启动需要创建 owner 管理员；如服务设置了 MACLAW_ADMIN_SETUP_TOKEN，请输入初始化令牌。",
  "noToken": "未登录",
  "loaded": "已加载",
  "failed": "请求失败",
  "dangerous": "危险操作",
  "suspend": "暂停",
  "activate": "启用",
  "revoke": "吊销",
  "effective": "当前生效",
  "environment": "环境变量",
  "draft": "草稿",
  "report": "报告",
  "sandboxNonePrompt": "输入 DISABLE SANDBOX 确认关闭沙箱",
  "useSecret": "使用 Secret",
  "cancelJobConfirm": "确认取消这个任务？",
  "revokeCredentialConfirm": "确认吊销这个凭据？",
  "deleteBlocked": "删除被阻止",
  "deleteTenantConfirm": "确认删除租户并清理其数据？",
  "deleteUserConfirm": "确认删除用户并清理其数据？",
  "revokeSessionConfirm": "确认吊销这个会话？",
  "clearKnowledgeConfirm": "清理此租户的所有知识数据？",
  "tenantIDRequired": "需要 tenant_id",
  "deleteKnowledgeAccessConfirm": "确认删除此知识访问覆盖？",
  "deleteSkillTenantConfirm": "确认删除租户技能源覆盖？",
  "deleteSkillUserConfirm": "确认删除用户技能源覆盖？",
  "deleteSnapshotConfirm": "确认删除此快照？",
  "installRun": "执行安装",
  "installRunPrompt": "输入 INSTALL SANDBOX 确认执行安装命令",
  "deleteSandboxReportConfirm": "确认删除此沙箱报告？",
  "rollback": "回滚",
  "sandboxRollbackConfirm": "确认清除运行时沙箱覆盖并回到环境配置？",
  "deleteSandboxProfileConfirm": "确认删除此沙箱 profile？",
  "profileName": "Profile 名称",
  "editProfile": "编辑 Profile",
  "profileJSON": "Profile JSON",
  "eventStatus": "事件状态",
  "eventBackend": "事件 Backend",
  "supportBundle": "支持包",
  "serviceSupportBundle": "服务支持包",
  "importRunPrompt": "输入 IMPORT STATE 确认执行导入",
  "restoreRunPrompt": "输入 RESTORE SNAPSHOT 确认恢复快照",
  "exportSecretPrompt": "输入 EXPORT SECRETS 确认导出敏感密钥",
  "snapshotSecretPrompt": "输入 SNAPSHOT SECRETS 确认创建含密钥快照",
  "securityRisks": "安全风险",
  "riskEvents": "风险事件",
  "bySeverity": "按严重程度",
  "byKind": "按类型",
  "all": "全部",
  "clear": "清除",
  "total": "总数",
  "allRisks": "全部风险",
  "generatedAt": "生成时间",
  "invalidRiskLimit": "风险条数必须在 1 到 500 之间",
  "empty": "空",
  "view": "查看",
  "delete": "删除",
  "cancel": "取消",
  "noReports": "暂无报告",
  "redactions": "脱敏项",
  "dataRoot": "数据根目录",
  "overviewHint": "运行状态、就绪状态、调度器和异步任务",
  "sandboxHint": "检测、切换、诊断和安装指引",
  "logsHint": "已脱敏的服务日志尾部，支持来源和文本过滤",
  "runtimeLabel": "运行时",
  "runGC": "运行 GC",
  "goroutines": "Goroutine",
  "downloadGoroutines": "下载 Goroutine",
  "heapProfile": "Heap Profile",
  "downloadHeapProfile": "下载 Heap",
  "readiness": "就绪",
  "scheduler": "调度器",
  "asyncJobs": "异步任务",
  "jobs": "任务",
  "security": "安全",
  "mode": "模式",
  "effectiveBackend": "生效后端",
  "strict": "严格模式",
  "backends": "后端",
  "capabilities": "能力",
  "profiles": "Profiles",
  "events": "事件",
  "sources": "来源",
  "open": "打开",
  "search": "搜索",
  "level": "级别",
  "text": "文本",
  "lines": "行",
  "truncated": "已截断",
  "reason": "原因",
  "profile": "Profile",
  "audit": "审计",
  "export": "导出",
  "import": "导入",
  "snapshots": "快照",
  "create": "创建",
  "createTenant": "创建租户",
  "createUser": "创建用户",
  "createAdmin": "创建管理员",
  "credentials": "凭据",
  "knowledgeStats": "知识统计",
  "knowledgeSources": "知识来源",
  "knowledgeAccess": "知识访问",
  "skillSources": "技能来源",
  "global": "全局",
  "tenantOverride": "租户覆盖",
  "userOverride": "用户覆盖",
  "oldPassword": "旧密码",
  "newPassword": "新密码",
  "deleteProtected": "删除保护",
  "protectionReason": "保护原因",
  "allowCrossTenant": "允许跨租户范围",
  "clearTenantKnowledge": "清理租户知识",
  "restartRequired": "需要重启",
  "runtimeOnly": "仅运行时",
  "warnings": "警告",
  "errors": "错误",
  "notes": "备注",
  "recommendations": "建议",
  "dryRun": "预演",
  "restore": "恢复",
  "overwrite": "覆盖",
  "secrets": "密钥",
  "messages": "消息",
  "runs": "运行",
  "name": "名称",
  "email": "邮箱",
  "configHint": "Schema 驱动的草稿、校验和导出方案",
  "tenantsHint": "创建、暂停、凭据、删除检查和清理",
  "accountsHint": "管理员操作员和会话",
  "knowledgeHint": "知识访问、租户清理和技能源策略",
  "opsHint": "审计、导出/导入、风险事件和服务快照",
  "serviceConfig": "服务配置",
  "manualApply": "手动应用",
  "willExecute": "将执行",
  "createCredential": "创建凭据",
  "listCredentials": "列出凭据",
  "crossTenant": "跨租户",
  "skillSourcePolicy": "技能源策略",
  "inherit": "继承",
  "enabledState": "启用",
  "disabledState": "停用",
  "unknown": "未知",
  "noReport": "暂无报告",
  "highMedium": "高 {high} / 中 {medium}",
  "allOption": "全部",
  "kindPlaceholder": "类型",
  "tenantID": "tenant_id",
  "userID": "user_id",
  "actionName": "操作",
  "apiKeyOptional": "API key（可选）",
  "apiSecretOptional": "API secret（可选）",
  "userEmail": "用户邮箱",
  "pasteExportedJSON": "粘贴导出的 JSON",
  "invalidJSON": "JSON 格式无效",
  "invalidLimit": "条数必须在 {min} 到 {max} 之间",
  "resolve": "解析",
  "restart": "重启",
  "runtime": "运行时",
  "sensitive": "敏感",
  "owner": "owner",
  "operator": "operator",
  "ownerOnly": "仅 owner 可操作",
  "summary": "摘要",
  "deleteCheck": "删除检查",
  "retirePlan": "退役方案",
  "profileJSONInvalid": "Profile JSON 格式无效",
  "recentErrors": "最近错误",
  "includeWarnings": "包含警告",
  "searchAllLogs": "搜索全部日志",
  "download": "下载",
  "rotateLog": "\u8f6c\u50a8\u65e5\u5fd7",
  "rotateLogConfirm": "\u786e\u8ba4\u8f6c\u50a8\u5f53\u524d\u65e5\u5fd7\u5e76\u521b\u5efa\u65b0\u6587\u4ef6\uff1f",
  "rotateSecret": "轮换密钥",
  "rotateKey": "轮换公钥"
};
const en = {
  "adminConsole": "Admin Console",
  "logout": "Logout",
  "overview": "Overview",
  "sandbox": "Sandbox",
  "logs": "Logs",
  "config": "Service Config",
  "tenants": "Tenants & Users",
  "accounts": "Admins",
  "knowledge": "Knowledge & Skill Sources",
  "ops": "Ops",
  "setup": "Initialize Admin",
  "login": "Admin Login",
  "refresh": "Refresh",
  "save": "Save",
  "run": "Run",
  "validate": "Validate",
  "exportPlan": "Export Plan",
  "detect": "Detect",
  "smoke": "Smoke Test",
  "diagnose": "Diagnose and Save",
  "installPlan": "Install Plan",
  "changePassword": "Change Password",
  "sessions": "Sessions",
  "users": "Users",
  "status": "Status",
  "action": "Action",
  "confirm": "Confirm",
  "raw": "Raw",
  "password": "Password",
  "username": "Username",
  "setupToken": "Setup Token",
  "displayName": "Display Name",
  "language": "Language",
  "adminSecret": "Admin Secret or Session Token",
  "loginHint": "After login, every operation goes through Admin API.",
  "setupHint": "First boot creates an owner admin. Enter the setup token when MACLAW_ADMIN_SETUP_TOKEN is configured.",
  "noToken": "Not signed in",
  "loaded": "Loaded",
  "failed": "Request failed",
  "dangerous": "Dangerous",
  "suspend": "Suspend",
  "activate": "Activate",
  "revoke": "Revoke",
  "effective": "Effective",
  "environment": "Environment",
  "draftDiff": "Draft diff",
  "clearDraft": "Clear draft",
  "clearDraftConfirm": "Clear the service config draft?",
  "draft": "Draft",
  "report": "Report",
  "sandboxNonePrompt": "Type DISABLE SANDBOX to confirm disabling sandbox",
  "useSecret": "Use Secret",
  "cancelJobConfirm": "Cancel this job?",
  "revokeCredentialConfirm": "Revoke this credential?",
  "deleteBlocked": "Delete blocked",
  "deleteTenantConfirm": "Delete tenant and cleanup data?",
  "deleteUserConfirm": "Delete user and cleanup data?",
  "revokeSessionConfirm": "Revoke this session?",
  "clearKnowledgeConfirm": "Clear all knowledge for this tenant?",
  "tenantIDRequired": "tenant_id required",
  "deleteKnowledgeAccessConfirm": "Delete this knowledge access override?",
  "deleteSkillTenantConfirm": "Delete tenant skill source override?",
  "deleteSkillUserConfirm": "Delete user skill source override?",
  "deleteSnapshotConfirm": "Delete this snapshot?",
  "installRun": "Run Install",
  "installRunPrompt": "Type INSTALL SANDBOX to confirm running install commands",
  "deleteSandboxReportConfirm": "Delete this sandbox report?",
  "rollback": "Rollback",
  "sandboxRollbackConfirm": "Clear runtime sandbox overrides and return to environment config?",
  "deleteSandboxProfileConfirm": "Delete this sandbox profile?",
  "profileName": "Profile Name",
  "editProfile": "Edit Profile",
  "profileJSON": "Profile JSON",
  "eventStatus": "Event Status",
  "eventBackend": "Event Backend",
  "supportBundle": "Support Bundle",
  "serviceSupportBundle": "Service Bundle",
  "importRunPrompt": "Type IMPORT STATE to confirm importing state",
  "restoreRunPrompt": "Type RESTORE SNAPSHOT to confirm restoring snapshot",
  "exportSecretPrompt": "Type EXPORT SECRETS to confirm exporting sensitive secrets",
  "snapshotSecretPrompt": "Type SNAPSHOT SECRETS to confirm creating a snapshot with secrets",
  "securityRisks": "Security Risks",
  "riskEvents": "Risk Events",
  "bySeverity": "By severity",
  "byKind": "By kind",
  "all": "all",
  "clear": "Clear",
  "total": "total",
  "allRisks": "all risks",
  "generatedAt": "Generated",
  "invalidRiskLimit": "Risk limit must be between 1 and 500",
  "empty": "Empty",
  "view": "View",
  "delete": "Delete",
  "cancel": "Cancel",
  "noReports": "No reports",
  "redactions": "Redactions",
  "dataRoot": "Data Root",
  "overviewHint": "Runtime, readiness, scheduler and async jobs",
  "sandboxHint": "Detect, switch, diagnose and install guidance",
  "logsHint": "Redacted service log tail with source and text filters",
  "runtimeLabel": "Runtime",
  "runGC": "Run GC",
  "goroutines": "Goroutines",
  "downloadGoroutines": "Download goroutines",
  "heapProfile": "Heap profile",
  "downloadHeapProfile": "Download heap",
  "readiness": "Readiness",
  "scheduler": "Scheduler",
  "asyncJobs": "Async Jobs",
  "jobs": "Jobs",
  "security": "Security",
  "mode": "Mode",
  "effectiveBackend": "Effective",
  "strict": "Strict",
  "backends": "Backends",
  "capabilities": "Capabilities",
  "profiles": "Profiles",
  "events": "Events",
  "sources": "Sources",
  "open": "Open",
  "search": "Search",
  "level": "level",
  "text": "text",
  "lines": "lines",
  "truncated": "truncated",
  "reason": "reason",
  "profile": "Profile",
  "audit": "Audit",
  "export": "Export",
  "import": "Import",
  "snapshots": "Snapshots",
  "create": "Create",
  "createTenant": "Create Tenant",
  "createUser": "Create User",
  "createAdmin": "Create Admin",
  "credentials": "Credentials",
  "knowledgeStats": "Knowledge Stats",
  "knowledgeSources": "Knowledge Sources",
  "knowledgeAccess": "Knowledge Access",
  "skillSources": "Skill Sources",
  "global": "Global",
  "tenantOverride": "Tenant Override",
  "userOverride": "User Override",
  "oldPassword": "Old password",
  "newPassword": "New password",
  "deleteProtected": "delete protected",
  "protectionReason": "Protection reason",
  "allowCrossTenant": "allow cross-tenant scopes",
  "clearTenantKnowledge": "Clear tenant knowledge",
  "restartRequired": "Restart required",
  "runtimeOnly": "Runtime only",
  "warnings": "Warnings",
  "errors": "Errors",
  "notes": "Notes",
  "recommendations": "Recommendations",
  "dryRun": "dry run",
  "restore": "Restore",
  "overwrite": "overwrite",
  "secrets": "secrets",
  "messages": "messages",
  "runs": "runs",
  "name": "Name",
  "email": "Email",
  "configHint": "Schema-driven draft, validation and export plan",
  "tenantsHint": "Create, pause, credentials, delete-check and cleanup",
  "accountsHint": "Admin operators and sessions",
  "knowledgeHint": "Knowledge access, tenant cleanup and skill source policy",
  "opsHint": "Audit, export/import, risk events and service snapshots",
  "serviceConfig": "Service Config",
  "manualApply": "manual apply",
  "willExecute": "will execute",
  "createCredential": "Create credential",
  "listCredentials": "List credentials",
  "crossTenant": "Cross Tenant",
  "skillSourcePolicy": "Skill Source Policy",
  "inherit": "Inherit",
  "enabledState": "Enabled",
  "disabledState": "Disabled",
  "unknown": "Unknown",
  "noReport": "No report",
  "highMedium": "High {high} / medium {medium}",
  "allOption": "All",
  "kindPlaceholder": "Kind",
  "tenantID": "tenant_id",
  "userID": "user_id",
  "actionName": "Action",
  "apiKeyOptional": "API key (optional)",
  "apiSecretOptional": "API secret (optional)",
  "userEmail": "User email",
  "pasteExportedJSON": "Paste exported JSON",
  "invalidJSON": "Invalid JSON",
  "invalidLimit": "Limit must be between {min} and {max}",
  "resolve": "Resolve",
  "restart": "Restart",
  "runtime": "Runtime",
  "sensitive": "Sensitive",
  "owner": "owner",
  "operator": "operator",
  "ownerOnly": "Owner only",
  "summary": "Summary",
  "deleteCheck": "Delete check",
  "retirePlan": "Retire plan",
  "profileJSONInvalid": "Invalid profile JSON",
  "recentErrors": "Recent errors",
  "includeWarnings": "Include warnings",
  "searchAllLogs": "Search all logs",
  "download": "Download",
  "rotateLog": "Rotate log",
  "rotateLogConfirm": "Rotate the current log and create a new file?",
  "rotateSecret": "Rotate secret",
  "rotateKey": "Rotate key"
};
const dicts = {"zh-CN": zh, "en-US": en};
const state = { locale: localStorage.getItem("maclaw.admin.locale") || "zh-CN", token: localStorage.getItem("maclaw.admin.token") || "", section: "overview", me: null, pendingRiskFilter: null, locales: [{locale:"zh-CN",label:"zh-CN"},{locale:"en-US",label:"English"}] };
const $ = (id) => document.getElementById(id);
const t = (k, vars) => { let out=(dicts[state.locale] || zh)[k] || k; for(const [name,value] of Object.entries(vars||{})) out=out.replaceAll(`{${name}}`, String(value)); return out; };
const esc = (v) => String(v ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const pretty = (v) => JSON.stringify(v, null, 2);
function toast(msg){ const el=$("toast"); el.textContent=msg; el.classList.remove("hidden"); clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.classList.add("hidden"),3500); }
function headers(json=true){ const h={}; if(json) h["Content-Type"]="application/json"; if(state.token) h["X-MaClaw-Admin-Secret"]=state.token; return h; }
async function api(path, opts={}){ const res=await fetch(path,{...opts,headers:{...headers(opts.body!==undefined),...(opts.headers||{})}}); const text=await res.text(); let body=text; try{ body=text?JSON.parse(text):{} }catch{} if(!res.ok){ const err=new Error(body?.error || text || res.statusText); err.status=res.status; err.body=body; throw err; } return body; }
async function downloadAdmin(path, fallbackName="maclaw-admin-download"){ const res=await fetch(path,{headers:headers(false)}); const blob=await res.blob(); if(!res.ok){ let msg=res.statusText; try{msg=(await blob.text())||msg}catch{} throw new Error(msg); } const cd=res.headers.get("content-disposition")||""; const m=cd.match(/filename="?([^";]+)"?/i); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download=m?.[1]||fallbackName; document.body.appendChild(a); a.click(); setTimeout(()=>{URL.revokeObjectURL(a.href); a.remove();},1000); }
async function textAdmin(path){ const res=await fetch(path,{headers:headers(false)}); const text=await res.text(); if(!res.ok) throw new Error(text || res.statusText); return text; }
function setTitle(title,hint=""){ $("pageTitle").textContent=title; $("pageHint").textContent=hint; }
function isOwner(){ return state.me?.auth_type==="admin_secret" || state.me?.admin?.role==="owner"; }
function applyOwnerGuards(){ if(isOwner()) return; const tip=t("ownerOnly"); ["runRuntimeGC","rotateLog","saveSandbox","rollbackSandbox","installSandboxRun","saveSandboxProfile","createTenant","createTenantUser","createCredential","saveCfg","exportCfg","clearCfgDraft","clearTenantKnowledge","saveKnowledgeCrossTenant","saveKnowledgeAccess","deleteKnowledgeAccess","saveSkillGlobal","saveSkillTenant","deleteSkillTenant","saveSkillUser","deleteSkillUser","runImport","createSnapshot","pruneSnapshots"].forEach(id=>{ const el=$(id); if(el){ el.disabled=true; el.title=tip; }}); document.querySelectorAll("[data-job-cancel],[data-tenant-status],[data-tenant-delete],[data-user-status],[data-user-delete],[data-credential-status],[data-credential-secret],[data-credential-key],[data-credential-revoke],[data-admin-toggle],[data-session-revoke],[data-sandbox-report-delete],[data-sandbox-profile-delete],[data-snapshot-restore-run],[data-snapshot-delete]").forEach(el=>{ el.disabled=true; el.title=tip; }); }
function renderShell(){ document.documentElement.lang=state.locale; const localeSelect=$("localeSelect"); if(localeSelect){ localeSelect.innerHTML=(state.locales||[]).map(x=>`<option value="${esc(x.locale)}">${esc(x.label||x.locale)}</option>`).join(""); localeSelect.value=state.locale; } document.querySelectorAll("[data-i18n]").forEach(n=>n.textContent=t(n.dataset.i18n)); const nav=["overview","sandbox","logs","config","tenants","accounts","knowledge","ops"]; $("nav").innerHTML=nav.map(id=>`<button class="${state.section===id?"active":""}" data-section="${id}">${t(id)}</button>`).join(""); $("nav").querySelectorAll("button").forEach(b=>b.onclick=()=>{state.section=b.dataset.section; render();}); $("authBadge").textContent=state.me?.admin?.username || state.me?.auth_type || (state.token ? "admin" : t("noToken")); }
function renderLogin(){ setTitle(t("login"), t("loginHint")); $("loginPanel").classList.remove("hidden"); $("loginPanel").innerHTML=`<h2>${t("login")}</h2><div class="form-grid"><div class="field"><label>${t("username")}</label><input id="loginUser" autocomplete="username"></div><div class="field"><label>${t("password")}</label><input id="loginPass" type="password" autocomplete="current-password"></div><div class="field"><label>${t("adminSecret")}</label><input id="secretToken" value="${esc(state.token)}"></div></div><div class="row mt-12"><button id="loginSubmit">${t("login")}</button><button class="secondary" id="secretSubmit">${t("useSecret")}</button></div>`; $("loginSubmit").onclick=async()=>{try{const out=await api("/api/v1/admin/auth/login",{method:"POST",body:JSON.stringify({username:$("loginUser").value,password:$("loginPass").value})}); state.token=out.token; localStorage.setItem("maclaw.admin.token",state.token); await loadMe(); await loadLocales().catch(()=>{}); render();}catch(e){toast(`${t("failed")}: ${e.message}`)}}; $("secretSubmit").onclick=async()=>{state.token=$("secretToken").value.trim(); localStorage.setItem("maclaw.admin.token",state.token); await loadMe().catch(()=>{}); await loadLocales().catch(()=>{}); render();}; }
function renderBootstrap(status){ setTitle(t("setup"), t("setupHint")); $("bootstrapPanel").classList.remove("hidden"); $("bootstrapPanel").innerHTML=`<h2>${t("setup")}</h2><div class="form-grid"><div class="field"><label>${t("setupToken")}</label><input id="setupToken"></div><div class="field"><label>${t("username")}</label><input id="setupUser" value="admin"></div><div class="field"><label>${t("password")}</label><input id="setupPass" type="password"></div><div class="field"><label>${t("displayName")}</label><input id="setupName" value="Owner"></div><div class="field"><label>${t("language")}</label><select id="setupLocale">${localeOptions()}</select></div></div><div class="row mt-12"><button id="setupSubmit">${t("setup")}</button><span class="muted">min ${status.password_policy?.min_length || 12}</span></div>`; $("setupSubmit").onclick=async()=>{try{await api("/api/v1/admin/bootstrap/initialize",{method:"POST",body:JSON.stringify({setup_token:$("setupToken").value,username:$("setupUser").value,password:$("setupPass").value,display_name:$("setupName").value,locale:$("setupLocale").value})}); toast(t("loaded")); render();}catch(e){toast(`${t("failed")}: ${e.message}`)}}; }
async function loadMe(){ if(!state.token){state.me=null; return;} state.me=await api("/api/v1/admin/auth/me"); if(!localStorage.getItem("maclaw.admin.locale")&&state.me?.admin?.locale){ state.locale=state.me.admin.locale; } }
function localeOptions(){ return (state.locales||[]).map(x=>`<option value="${esc(x.locale)}">${esc(x.label||x.locale)}</option>`).join(""); }
async function loadLocales(){ if(!state.token) return; const out=await api("/api/v1/admin/i18n/locales"); state.locales=out.locales||state.locales; if(!localStorage.getItem("maclaw.admin.locale")){ state.locale=state.me?.admin?.locale||out.default_locale||state.locale; } }
async function startup(){ renderShell(); try{ const bs=await api("/api/v1/admin/bootstrap/status",{headers:{}}); if(!bs.initialized){ hideMain(); renderBootstrap(bs); return; } }catch(e){} if(state.token){ await loadMe().catch(()=>{state.me=null}); await loadLocales().catch(()=>{}); } render(); }
function hideMain(){ $("content").innerHTML=""; $("loginPanel").classList.add("hidden"); $("bootstrapPanel").classList.add("hidden"); renderShell(); }
async function render(){ hideMain(); if(!state.token){ renderLogin(); return; } renderShell(); const f={overview,sandbox,logs,config,tenants,accounts,knowledge,ops}[state.section] || overview; try{ await f(); applyOwnerGuards(); }catch(e){ if(e.status===401){state.token="";localStorage.removeItem("maclaw.admin.token");renderLogin();return;} $("content").innerHTML=`<div class="panel"><h2>${t("failed")}</h2><pre class="code">${esc(e.message)}\n${esc(pretty(e.body||{}))}</pre></div>`; } }
async function overview(){ setTitle(t("overview"), t("overviewHint")); const [rt,dash,ready,scheduler,jobs,security]=await Promise.all([api("/api/v1/admin/runtime/status"),api("/api/v1/admin/dashboard").catch(e=>({error:e.message})),api("/api/v1/admin/system/readiness"),api("/api/v1/admin/scheduler/status").catch(e=>({error:e.message,recent_tasks:[]})),api("/api/v1/admin/jobs?limit=50").catch(e=>({error:e.message,items:[]})),api("/api/v1/admin/security/summary").catch(e=>({error:e.message,status:"unknown",counts:{},recent:[]}))]); $("content").innerHTML=`<div class="grid"><div class="card metric"><span>${t("runtimeLabel")}</span><b class="${rt.readiness?.status==='ok'||rt.ready?"status-ok":"status-warn"}">${esc(rt.readiness?.status||rt.status||rt.ready)}</b></div><div class="card metric"><span>${t("sandbox")}</span><b>${esc(rt.sandbox?.effective_backend||rt.sandbox?.mode||"-")}</b><span>${esc(rt.last_sandbox_report?.status||t("noReport"))}</span></div><div class="card metric"><span>${t("jobs")}</span><b>${esc(Object.values(rt.jobs||{}).reduce((a,b)=>a+b,0))}</b></div><div class="card metric"><span>${t("scheduler")}</span><b>${esc(scheduler.enabled?t("enabledState"):t("disabledState"))}</b></div><div class="card metric"><span>${t("security")}</span><b class="${security.status==='ok'?'status-ok':'status-warn'}">${esc(security.status||t("unknown"))}</b><span>${esc(t("highMedium",{high:security.counts?.high||0,medium:security.counts?.medium||0}))}</span></div></div><div class="card"><h2>${t("securityRisks")}</h2>${riskFilterSummary(security)}<h3>${t("bySeverity")}</h3>${riskCountChips(security.counts,"severity")}<h3>${t("byKind")}</h3>${riskCountChips(security.kind_counts)}${riskEventsTable(security.recent||[])}</div><div class="card"><h2>${t("asyncJobs")}</h2><div class="row"><select id="jobStatus"><option value="">${t("allOption")}</option><option>pending</option><option>running</option><option>succeeded</option><option>failed</option><option>canceled</option></select><input id="jobKind" placeholder="${t("kindPlaceholder")}"><input id="jobTenant" placeholder="${t("tenantID")}"><input id="jobUser" placeholder="${t("userID")}"><button id="loadJobs">${t("refresh")}</button></div><div id="jobsTable">${jobTable(jobs.items||[])}</div></div><div class="card"><h2>${t("scheduler")}</h2>${table(scheduler.recent_tasks||[],["id","name","status","next_run_at","last_error"],null)}</div><div class="card"><h2>${t("raw")}</h2><button class="secondary" id="runRuntimeGC">${t("runGC")}</button><button class="secondary" id="viewGoroutines">${t("goroutines")}</button><button class="secondary" id="downloadGoroutines">${t("downloadGoroutines")}</button><button class="secondary" id="viewHeapProfile">${t("heapProfile")}</button><button class="secondary" id="downloadHeapProfile">${t("downloadHeapProfile")}</button><button class="secondary" id="serviceSupportBundle">${t("serviceSupportBundle")}</button><button class="secondary" id="serviceSupportBundleDownload">${t("download")}</button><pre id="overviewOut" class="code">${esc(pretty({runtime:rt,dashboard:dash,readiness:ready,scheduler,jobs,security}))}</pre></div>`; bindJobActions(); bindRiskCountChips(); bindRiskEventActions(security.recent||[]); $("runRuntimeGC").onclick=async()=>{$("overviewOut").textContent=pretty(await api("/api/v1/admin/runtime/gc",{method:"POST"}));}; $("viewGoroutines").onclick=async()=>{try{$("overviewOut").textContent=await textAdmin("/api/v1/admin/runtime/goroutines?debug=1");}catch(e){$("overviewOut").textContent=`${t("failed")}: ${e.message}`; toast(`${t("failed")}: ${e.message}`);}}; $("downloadGoroutines").onclick=()=>downloadAdmin("/api/v1/admin/runtime/goroutines?debug=2&download=true","goroutines.txt").catch(e=>toast(`${t("failed")}: ${e.message}`)); $("viewHeapProfile").onclick=async()=>{try{$("overviewOut").textContent=await textAdmin("/api/v1/admin/runtime/profiles/heap?debug=1&gc=true");}catch(e){$("overviewOut").textContent=`${t("failed")}: ${e.message}`; toast(`${t("failed")}: ${e.message}`);}}; $("downloadHeapProfile").onclick=()=>downloadAdmin("/api/v1/admin/runtime/profiles/heap?debug=1&gc=true&download=true","heap.txt").catch(e=>toast(`${t("failed")}: ${e.message}`)); $("serviceSupportBundle").onclick=async()=>{$("overviewOut").textContent=pretty(await api("/api/v1/admin/support-bundle"));}; $("serviceSupportBundleDownload").onclick=()=>downloadAdmin("/api/v1/admin/support-bundle?download=true","maclaw-support-bundle.json").catch(e=>toast(`${t("failed")}: ${e.message}`)); $("loadJobs").onclick=async()=>{const q=new URLSearchParams({limit:"50"}); if($("jobStatus").value) q.set("status",$("jobStatus").value); if($("jobKind").value) q.set("kind",$("jobKind").value); if($("jobTenant").value) q.set("tenant_id",$("jobTenant").value); if($("jobUser").value) q.set("user_id",$("jobUser").value); const out=await api(`/api/v1/admin/jobs?${q}`); $("jobsTable").innerHTML=jobTable(out.items||[]); $("overviewOut").textContent=pretty(out); bindJobActions(); applyOwnerGuards();}; }
function jobTable(items){ return table(items,["id","kind","status","tenant_id","user_id","created_at"],x=>`<button class="warn" data-job-cancel="${esc(x.id)}" ${x.status==='pending'||x.status==='running'?"":"disabled"}>${t("cancel")}</button>`); }
function bindJobActions(){ document.querySelectorAll("[data-job-cancel]").forEach(b=>b.onclick=async()=>{if(b.disabled) return; if(confirm(t("cancelJobConfirm"))){const out=await api(`/api/v1/admin/jobs/${encodeURIComponent(b.dataset.jobCancel)}/cancel`,{method:"POST"}); $("overviewOut").textContent=pretty(out); $("loadJobs")?.click();}}); }
async function sandbox(){ setTitle(t("sandbox"), t("sandboxHint")); const [st,cfg,reports,events,profiles]=await Promise.all([api("/api/v1/admin/sandbox/status"),api("/api/v1/admin/sandbox/config"),api("/api/v1/admin/sandbox/reports").catch(()=>({items:[]})),api("/api/v1/admin/sandbox/events?limit=20").catch(()=>({items:[]})),api("/api/v1/admin/sandbox/profiles").catch(()=>({items:[]}))]); $("content").innerHTML=`<div class="split"><div class="card stack"><h2>${t("status")}</h2><div class="grid"><div class="metric"><span>${t("mode")}</span><b>${esc(st.mode)}</b><span>${esc(st.mode_source||"")}</span></div><div class="metric"><span>${t("effectiveBackend")}</span><b>${esc(st.effective_backend)}</b><span>${esc(st.fallback_reason||"")}</span></div><div class="metric"><span>${t("strict")}</span><b>${esc(st.strict)}</b><span>${esc(st.strict_source||"")}</span></div></div><label>${t("mode")}</label><select id="sandboxMode"><option value="auto">auto</option><option value="landlock">landlock</option><option value="bwrap">bwrap</option><option value="nsjail">nsjail</option><option value="none">none</option></select><label>${t("strict")}</label><select id="sandboxStrict"><option value="">default</option><option value="true">true</option><option value="false">false</option></select><label>${t("profile")}</label><input id="sandboxProfile" placeholder="default" list="sandboxProfileList"><datalist id="sandboxProfileList">${(profiles.items||[]).map(p=>`<option value="${esc(p.name)}"></option>`).join("")}</datalist><input id="sandboxReason" placeholder="${t("reason")}"><div class="row"><button id="saveSandbox">${t("save")}</button><button class="secondary" id="detectSandbox">${t("detect")}</button><button class="secondary" id="smokeSandbox">${t("smoke")}</button><button class="warn" id="diagnoseSandbox">${t("diagnose")}</button><button class="secondary" id="rollbackSandbox">${t("rollback")}</button><button class="secondary" id="installSandbox">${t("installPlan")}</button><button class="secondary" id="sandboxSupportBundle">${t("supportBundle")}</button><button class="secondary" id="sandboxSupportBundleDownload">${t("download")}</button><button class="danger" id="installSandboxRun">${t("installRun")}</button></div><h2>${t("backends")}</h2>${table(st.backends||[],["name","available","smoke_status","reason","version"],null)}<h2>${t("capabilities")}</h2>${table(st.capabilities||[],["name","status","detail","raw"],null)}<h2>${t("profiles")}</h2>${sandboxProfilesTable(profiles.items||[])}${sandboxProfileEditor()}</div><div class="card"><h2>${t("report")}</h2>${sandboxReportsTable(reports.items||[])}<h2>${t("events")}</h2><div class="row"><select id="sandboxEventStatus"><option value="">${t("allOption")}</option><option value="pass">pass</option><option value="warn">warn</option><option value="fail">fail</option></select><input id="sandboxEventBackend" placeholder="${t("eventBackend")}"><button class="secondary" id="loadSandboxEvents">${t("refresh")}</button></div><div id="sandboxEventsTable">${sandboxEventsTable(events.items||[])}</div><div id="sandboxOut" class="code">${esc(pretty({config:cfg,events,profiles}))}</div></div></div>`; $("sandboxMode").value=cfg.mode?.value||cfg.mode||"auto"; $("sandboxStrict").value=cfg.strict?.value===undefined?"":String(cfg.strict.value); $("sandboxReason").value=cfg.reason||""; $("sandboxProfile").value="default"; bindSandboxReportActions(); bindSandboxEventActions(events.items||[]); bindSandboxProfileActions(profiles.items||[]); $("saveSandbox").onclick=async()=>{const mode=$("sandboxMode").value; const strict=$("sandboxStrict").value; const body={mode,reason:$("sandboxReason").value}; if(mode==="none"){const typed=prompt(t("sandboxNonePrompt")); if(typed!=="DISABLE SANDBOX") return; body.confirm_unsafe=true;} if(strict!=="") body.strict=strict==="true"; $("sandboxOut").innerHTML=`<pre>${esc(pretty(await api("/api/v1/admin/sandbox/switch",{method:"POST",body:JSON.stringify(body)})))}</pre>`;}; $("detectSandbox").onclick=async()=>{$("sandboxOut").innerHTML=sandboxStatusView(await api("/api/v1/admin/sandbox/detect",{method:"POST",body:"{}"}));}; $("smokeSandbox").onclick=async()=>{$("sandboxOut").innerHTML=sandboxReportView(await api("/api/v1/admin/sandbox/smoke-test",{method:"POST",body:"{}"}));}; $("diagnoseSandbox").onclick=async()=>{$("sandboxOut").innerHTML=sandboxReportView(await api("/api/v1/admin/sandbox/diagnose",{method:"POST",body:JSON.stringify({write_report:true,include_mcp_stdio_test:true,profile:$("sandboxProfile").value.trim()||"default"})}));}; $("rollbackSandbox").onclick=async()=>{if(confirm(t("sandboxRollbackConfirm"))){$("sandboxOut").innerHTML=`<pre>${esc(pretty(await api("/api/v1/admin/sandbox/rollback",{method:"POST",body:JSON.stringify({reason:$("sandboxReason").value})})))}</pre>`; render();}}; $("installSandbox").onclick=async()=>{$("sandboxOut").innerHTML=sandboxInstallView(await api(`/api/v1/admin/sandbox/install-plan?backend=${encodeURIComponent($("sandboxMode").value)}`));}; $("sandboxSupportBundle").onclick=async()=>{const bundle=await api("/api/v1/admin/sandbox/support-bundle"); $("sandboxOut").innerHTML=sandboxSupportBundleView(bundle); bindRiskEventActions(bundle.security_risks?.recent||[]); bindSandboxReportActions(); applyOwnerGuards();}; $("sandboxSupportBundleDownload").onclick=()=>downloadAdmin("/api/v1/admin/sandbox/support-bundle?download=true","maclaw-sandbox-support-bundle.json").catch(e=>toast(`${t("failed")}: ${e.message}`)); $("installSandboxRun").onclick=async()=>{const typed=prompt(t("installRunPrompt")); if(typed!=="INSTALL SANDBOX") return; try{$("sandboxOut").innerHTML=sandboxInstallView(await api("/api/v1/admin/sandbox/install",{method:"POST",body:JSON.stringify({backend:$("sandboxMode").value,mode:"run",confirm:true})}));}catch(e){$("sandboxOut").innerHTML=`<pre>${esc(t("failed"))}: ${esc(e.message)}\n${esc(pretty(e.body||{}))}</pre>`;}}; }
function sandboxReportsTable(items){ if(!items.length) return `<p class="muted">${t("noReports")}</p>`; return table(items,["report_id","status","effective_backend","profile","generated_at"],x=>`<button class="secondary" data-sandbox-report="${esc(x.report_id)}">${t("view")}</button> <button class="danger" data-sandbox-report-delete="${esc(x.report_id)}">${t("delete")}</button>`); }
function bindSandboxReportActions(){ document.querySelectorAll("[data-sandbox-report]").forEach(b=>b.onclick=async()=>{$("sandboxOut").innerHTML=sandboxReportView(await api(`/api/v1/admin/sandbox/reports/${encodeURIComponent(b.dataset.sandboxReport)}`));}); document.querySelectorAll("[data-sandbox-report-delete]").forEach(b=>b.onclick=async()=>{if(confirm(t("deleteSandboxReportConfirm"))){$("sandboxOut").innerHTML=`<pre>${esc(pretty(await api(`/api/v1/admin/sandbox/reports/${encodeURIComponent(b.dataset.sandboxReportDelete)}?confirm=true`,{method:"DELETE"})))}</pre>`; render();}}); }
function riskCountChips(counts,type="kind"){ const entries=Object.entries(counts||{}).filter(([,v])=>v>0).sort((a,b)=>b[1]-a[1]); if(!entries.length) return `<p class="muted">${t("empty")}</p>`; const attr=type==="severity"?"data-risk-severity":"data-risk-kind"; return `<div class="row riskCountChips">${entries.map(([k,v])=>`<button class="secondary" ${attr}="${esc(k)}">${esc(k)} ${esc(v)}</button>`).join("")}</div>`; }
function riskKindOptions(counts){ return Object.keys(counts||{}).sort().map(k=>`<option value="${esc(k)}"></option>`).join(""); }
function goToRiskOps(filter){ state.pendingRiskFilter=filter; state.section="ops"; render(); }
function bindRiskCountChips(){ document.querySelectorAll("[data-risk-kind]").forEach(btn=>btn.onclick=()=>{ if(!$("riskKind")) return goToRiskOps({kind:btn.dataset.riskKind}); $("riskKind").value=btn.dataset.riskKind; loadRiskEventsFromFilters(); }); document.querySelectorAll("[data-risk-severity]").forEach(btn=>btn.onclick=()=>{ if(!$("riskSeverity")) return goToRiskOps({severity:btn.dataset.riskSeverity}); $("riskSeverity").value=btn.dataset.riskSeverity; loadRiskEventsFromFilters(); }); }
function riskEventsTable(items){ if(!items.length) return `<p class="muted">${t("empty")}</p>`; return table(items,["severity","kind","summary","created_at"],x=>`<button class="secondary" data-risk-event="${esc(x.id)}">${t("view")}</button>`); }
function riskDetailTarget(){ return $("opsOut")||$("overviewOut")||$("sandboxOut"); }
function bindRiskEventActions(items){ const byId=new Map((items||[]).map(x=>[x.id,x])); document.querySelectorAll("[data-risk-event]").forEach(btn=>btn.onclick=()=>{ const out=riskDetailTarget(); if(out) out.textContent=pretty(byId.get(btn.dataset.riskEvent)||{}); }); }
function validRiskTimeRange(){ const since=$("riskSince")?.value; const until=$("riskUntil")?.value; if(since&&until&&new Date(since)>new Date(until)){ toast("since must be before or equal to until"); return false; } return true; }
function validRiskLimit(){ const el=$("riskLimit"); if(!el) return true; const n=Number(el.value||50); if(!Number.isInteger(n)||n<1||n>500){ toast(t("invalidRiskLimit")); return false; } return true; }
function toLocalDateTimeInput(d){ const pad=n=>String(n).padStart(2,"0"); return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`; }
function setRiskTimePreset(hours){ if(!$("riskSince")||!$("riskUntil")) return; if(!hours){ $("riskSince").value=""; $("riskUntil").value=""; loadRiskEventsFromFilters(); return; } const until=new Date(); const since=new Date(until.getTime()-hours*60*60*1000); $("riskSince").value=toLocalDateTimeInput(since); $("riskUntil").value=toLocalDateTimeInput(until); loadRiskEventsFromFilters(); }
async function loadRiskEventsFromFilters(){ if(!validRiskTimeRange()||!validRiskLimit()) return; const q=new URLSearchParams(); if($("riskSeverity")?.value) q.set("severity",$("riskSeverity").value); if($("riskKind")?.value) q.set("kind",$("riskKind").value.trim()); if($("riskSince")?.value) q.set("since",new Date($("riskSince").value).toISOString()); if($("riskUntil")?.value) q.set("until",new Date($("riskUntil").value).toISOString()); q.set("limit",$("riskLimit")?.value||"50"); const risks=await api(`/api/v1/admin/security/risk-events?${q}`); $("riskSeverityCounts").innerHTML=riskCountChips(risks.counts,"severity"); $("riskKindCounts").innerHTML=riskCountChips(risks.kind_counts); if($("riskKindOptions")) $("riskKindOptions").innerHTML=riskKindOptions(risks.kind_counts); bindRiskCountChips(); if($("riskFilterStatus")) $("riskFilterStatus").innerHTML=riskFilterSummary(risks); $("riskEventsList").innerHTML=riskEventsTable(risks.items||[]); bindRiskEventActions(risks.items||[]); $("opsOut").textContent=pretty(risks); }
function clearRiskFilters(){ ["riskSeverity","riskKind","riskSince","riskUntil"].forEach(id=>{ if($(id)) $(id).value=""; }); if($("riskLimit")) $("riskLimit").value="50"; loadRiskEventsFromFilters(); }
function riskFilterSummary(risks){ const f=risks.filters||{}; const parts=[]; const severity=f.severity||$("riskSeverity")?.value; const kind=f.kind||$("riskKind")?.value?.trim(); const since=f.since||$("riskSince")?.value; const until=f.until||$("riskUntil")?.value; const limit=f.limit||$("riskLimit")?.value; if(severity) parts.push(`severity=${severity}`); if(kind) parts.push(`kind=${kind}`); if(since) parts.push(`since=${since}`); if(until) parts.push(`until=${until}`); if(limit) parts.push(`limit=${limit}`); return `<p class="muted">${t("total")} ${esc(risks.total??(risks.items||[]).length)}${risks.generated_at?" · "+t("generatedAt")+" "+esc(risks.generated_at):""}${parts.length?" · "+esc(parts.join(" · ")):" · "+t("allRisks")}</p>`; }
function applyPendingRiskFilter(){ const f=state.pendingRiskFilter; if(!f) return false; state.pendingRiskFilter=null; if(f.severity&&$("riskSeverity")) $("riskSeverity").value=f.severity; if(f.kind&&$("riskKind")) $("riskKind").value=f.kind; loadRiskEventsFromFilters(); return true; }
function sandboxEventsTable(items){ if(!items.length) return `<p class="muted">${t("empty")}</p>`; return table(items,["action","resource_type","resource_id","created_at"],x=>`<button class="secondary" data-sandbox-event="${esc(x.id)}">${t("view")}</button>`); }
function sandboxProfilesTable(items){ if(!items.length) return `<p class="muted">${t("empty")}</p>`; return table(items,["name","backend","network","updated_at"],x=>`<button class="secondary" data-sandbox-profile="${esc(x.name)}">${t("view")}</button> <button class="danger" data-sandbox-profile-delete="${esc(x.name)}">${t("delete")}</button>`); }
function sandboxProfileEditor(){ return `<div class="panel stack"><h2>${t("editProfile")}</h2><div class="form-grid"><input id="sandboxProfileName" placeholder="${t("profileName")}"><select id="sandboxProfileBackend"><option value="bwrap">bwrap</option><option value="landlock">landlock</option><option value="nsjail">nsjail</option></select><select id="sandboxProfileNetwork"><option value="default">default</option><option value="disabled">disabled</option><option value="host">host</option></select></div><textarea id="sandboxProfileJSON" placeholder="${t("profileJSON")}">{
  "readonly_paths": [],
  "writable_paths": [],
  "env_allowlist": []
}</textarea><div class="row"><button class="secondary" id="validateSandboxProfile">${t("validate")}</button><button id="saveSandboxProfile">${t("save")}</button></div></div>`; }
function sandboxStatusView(st){ return `<h2>${esc(st.effective_backend||st.mode)}</h2><p class="muted">${esc(st.fallback_reason||"")}</p>${table(st.backends||[],["name","available","smoke_status","reason","version"],null)}${table(st.capabilities||[],["name","status","detail","raw"],null)}<pre>${esc(pretty(st))}</pre>`; }
function sandboxReportView(r){ return `<h2 class="${r.status==='fail'?'status-bad':r.status==='warn'?'status-warn':'status-ok'}">${esc(r.status)} · ${esc(r.effective_backend||r.mode)}</h2><p>${esc(r.summary||"")}</p>${table(r.checks||[],["id","title","status","severity","expected","actual"],null)}${(r.warnings||[]).length?`<h2>${t("warnings")}</h2><pre>${esc((r.warnings||[]).join("\n"))}</pre>`:""}${(r.recommendations||[]).length?`<h2>${t("recommendations")}</h2><pre>${esc((r.recommendations||[]).join("\n"))}</pre>`:""}<pre>${esc(pretty(r))}</pre>`; }
function sandboxInstallView(p){ return `<h2>${esc(p.backend)} · ${esc(p.platform)}</h2><p class="muted">requires privilege: ${esc(p.requires_privilege)} · ${t("willExecute")}: ${esc(p.will_execute)}</p><pre>${esc((p.commands||[]).join("\n"))}</pre>${(p.notes||[]).length?`<h2>${t("notes")}</h2><pre>${esc((p.notes||[]).join("\n"))}</pre>`:""}`; }
function sandboxSupportBundleView(b){ const risks=b.security_risks||{}; const redactions=(b.redactions||[]).map(x=>`<code>${esc(x)}</code>`).join(" ")||t("empty"); const dataRoot=`${esc(b.data_root_name||"")}${b.data_root_redacted?" · redacted":""}`; return `<h2>${t("supportBundle")}</h2><p class="muted">${esc(b.generated_at||"")} · reports ${esc(b.report_count||0)} · events ${esc(b.event_count||0)} · profiles ${esc(b.profile_count||0)}</p><h2>${t("dataRoot")}</h2><p class="muted">${dataRoot}</p><h2>${t("redactions")}</h2><p class="muted">${redactions}</p><h2>${t("recentErrors")}</h2>${recentLogTable(b.recent_log_errors||[])}<h2>${t("securityRisks")}</h2>${riskFilterSummary(risks)}<h3>${t("bySeverity")}</h3>${riskCountChips(risks.counts,"severity")}<h3>${t("byKind")}</h3>${riskCountChips(risks.kind_counts)}${riskEventsTable(risks.recent||[])}<h2>${t("report")}</h2>${sandboxReportsTable(b.reports||[])}<pre>${esc(pretty(b))}</pre>`; }
async function logs(){ setTitle(t("logs"), t("logsHint")); const [src,recent]=await Promise.all([api("/api/v1/admin/logs/sources"),api("/api/v1/admin/logs/errors/recent?limit=20").catch(e=>({error:e.message,items:[]}))]); $("content").innerHTML=`<div class="card"><h2>${t("sources")}</h2>${table(src.items||[],["id","name","exists","size_bytes","modified_at"],x=>`<button class="secondary" data-log-source="${esc(x.id)}">${t("open")}</button>`)}</div><div class="card stack"><h2>${t("recentErrors")}</h2><label class="row"><input id="logIncludeWarn" type="checkbox" class="w-auto"> ${t("includeWarnings")}</label><button class="secondary" id="loadRecentErrors">${t("refresh")}</button><div id="recentErrors">${recentLogTable(recent.items||[])}</div></div><div class="card stack"><div class="row"><select id="logSource">${(src.items||[]).map(s=>`<option value="${esc(s.id)}">${esc(s.name||s.id)}</option>`).join("")}</select><select id="logLevel"><option value="">${t("allOption")}</option><option value="error">error</option><option value="warn">warn</option><option value="info">info</option></select><input id="logQuery" placeholder="${t("search")}"><input id="logTail" type="number" value="200" class="w-narrow"><button id="loadLog">${t("refresh")}</button><button class="secondary" id="searchLogs">${t("searchAllLogs")}</button><button class="secondary" id="downloadLog">${t("download")}</button><button class="warn" id="rotateLog">${t("rotateLog")}</button></div><div id="logMeta" class="muted"></div><div id="logLines"></div><pre id="logOut" class="code hidden"></pre></div>`; document.querySelectorAll("[data-log-source]").forEach(b=>b.onclick=()=>{$("logSource").value=b.dataset.logSource; $("loadLog").click();}); $("loadRecentErrors").onclick=async()=>{const q=new URLSearchParams({limit:"20",include_warn:String($("logIncludeWarn").checked)}); const out=await api(`/api/v1/admin/logs/errors/recent?${q}`); $("recentErrors").innerHTML=recentLogTable(out.items||[]); $("logOut").textContent=pretty(out);}; $("rotateLog").onclick=async()=>{const id=$("logSource").value; if(!confirm(t("rotateLogConfirm"))) return; const out=await api(`/api/v1/admin/logs/${encodeURIComponent(id)}/rotate?confirm=true`,{method:"POST"}); $("logOut").textContent=pretty(out); await logs();}; $("downloadLog").onclick=()=>{let tail; try{tail=numberInRange("logTail",200,1,2000);}catch{return;} const id=$("logSource").value; const q=new URLSearchParams({tail:String(tail)}); if($("logLevel").value) q.set("level",$("logLevel").value); if($("logQuery").value) q.set("q",$("logQuery").value); downloadAdmin(`/api/v1/admin/logs/${encodeURIComponent(id)}/download?${q}`,`${id}.log`).catch(e=>toast(`${t("failed")}: ${e.message}`));}; $("searchLogs").onclick=async()=>{let tail; try{tail=numberInRange("logTail",200,1,2000);}catch{return;} const body={q:$("logQuery").value,level:$("logLevel").value,tail,limit:100}; const out=await api("/api/v1/admin/logs/search",{method:"POST",body:JSON.stringify(body)}); $("logMeta").textContent=`${out.items?.length||0} ${t("lines")}`; $("logLines").innerHTML=recentLogTable(out.items||[]); $("logOut").textContent=pretty(out);}; $("loadLog").onclick=async()=>{const id=$("logSource").value; let tail; try{tail=numberInRange("logTail",200,1,2000);}catch{return;} const q=new URLSearchParams({tail:String(tail)}); if($("logLevel").value) q.set("level",$("logLevel").value); if($("logQuery").value) q.set("q",$("logQuery").value); const out=await api(`/api/v1/admin/logs/${encodeURIComponent(id)}?${q}`); $("logMeta").textContent=`${out.source?.path||id} ? ${out.lines?.length||0} ${t("lines")}${out.truncated?" ? "+t("truncated"):""}`; $("logLines").innerHTML=logLineTable(out.lines||[]); $("logOut").textContent=pretty(out);}; $("loadLog").click(); }
function logLineTable(lines){ if(!lines.length) return `<p class="muted">${t("empty")}</p>`; return `<table><thead><tr><th>#</th><th>${t("level")}</th><th>${t("text")}</th></tr></thead><tbody>${lines.map(x=>`<tr><td>${esc(x.number)}</td><td class="${x.level==='error'?'status-bad':x.level==='warn'?'status-warn':'status-ok'}">${esc(x.level)}</td><td><code>${esc(x.text)}</code></td></tr>`).join("")}</tbody></table>`; }
async function config(){ setTitle(t("config"), t("configHint")); const [eff,draftResp,schemaResp,envResp,diffResp]=await Promise.all([api("/api/v1/admin/service-config/effective"),api("/api/v1/admin/service-config/draft"),api("/api/v1/admin/service-config/schema"),api("/api/v1/admin/service-config/environment"),api("/api/v1/admin/service-config/diff")]); const draft=draftResp.draft||{values:{}}; const schema=schemaResp.items||[]; $("content").innerHTML=`<div class="split"><div class="card stack"><h2>${t("draft")}</h2><div id="cfgFields" class="stack">${configFields(schema,draft.values||{},eff.fields||{})}</div><label>${t("reason")}</label><input id="cfgReason" value="${esc(draft.reason||"")}" placeholder="${t("reason")}"><div class="row"><button id="saveCfg">${t("save")}</button><button class="secondary" id="validateCfg">${t("validate")}</button><button class="secondary" id="exportCfg">${t("exportPlan")}</button><button class="danger" id="clearCfgDraft">${t("clearDraft")}</button></div></div><div class="card"><h2>${t("effective")}</h2>${table(Object.values(eff.fields||{}).map((v,i)=>({key:Object.keys(eff.fields||{})[i],value:JSON.stringify(v.value),source:v.source,restart_required:v.restart_required,mutable_at_runtime:v.mutable_at_runtime})),["key","value","source","restart_required","mutable_at_runtime"],null)}<h2>${t("environment")}</h2>${table(envResp.items||[],["key","env_key","configured","value","default","source"],null)}<h2>${t("draftDiff")}</h2>${table(diffResp.items||[],["key","env_key","configured","changed","current","desired","restart_required"],null)}<h2>${t("raw")}</h2><pre id="cfgOut" class="code">${esc(pretty({draft:draftResp, schema:schemaResp, environment:envResp, diff:diffResp}))}</pre></div></div>`; const values=()=>buildConfigValues(schema); $("saveCfg").onclick=async()=>$("cfgOut").innerHTML=configValidationView(await api("/api/v1/admin/service-config/draft",{method:"PATCH",body:JSON.stringify({values:values(),reason:$("cfgReason").value})})); $("validateCfg").onclick=async()=>$("cfgOut").innerHTML=configValidationView(await api("/api/v1/admin/service-config/validate",{method:"POST",body:JSON.stringify({values:values()})})); $("exportCfg").onclick=async()=>$("cfgOut").innerHTML=configExportView(await api("/api/v1/admin/service-config/export-plan",{method:"POST",body:JSON.stringify({values:values()})})); $("clearCfgDraft").onclick=async()=>{if(!confirm(t("clearDraftConfirm"))) return; $("cfgOut").textContent=pretty(await api("/api/v1/admin/service-config/draft?confirm=true",{method:"DELETE"})); render();}; }
function configFields(schema,draft,effective){ return schema.map(f=>{const writable=!!f.writable; const hasDraft=Object.prototype.hasOwnProperty.call(draft,f.key); const effectiveValue=effective[f.key]?.value; const current=hasDraft?draft[f.key]:(f.sensitive?"":(effectiveValue ?? f.default ?? "")); const checked=hasDraft?"checked":""; const disabled=writable?"":"disabled"; let input=""; if(f.type==="bool"){ input=`<label class="row"><input id="cfg_${esc(f.key)}" type="checkbox" ${current===true?"checked":""} ${disabled} class="w-auto"> ${esc(f.env_key||f.key)}</label>`; } else if(f.type==="enum"){ input=`<select id="cfg_${esc(f.key)}" ${disabled}>${(f.allowed_values||[]).map(v=>`<option value="${esc(v)}" ${String(current)===v?"selected":""}>${esc(v)}</option>`).join("")}</select>`; } else { input=`<input id="cfg_${esc(f.key)}" value="${esc(current)}" ${disabled} ${f.sensitive?'type="password"':''}>`; } return `<div class="panel"><div class="row"><label class="row"><input id="cfgUse_${esc(f.key)}" type="checkbox" ${checked} ${writable?"":"disabled"} class="w-auto"> <strong>${esc(f.key)}</strong></label><span class="badge">${esc(f.type)}</span>${f.restart_required?`<span class="badge">${t("restart")}</span>`:""}${f.mutable_at_runtime?`<span class="badge">${t("runtime")}</span>`:""}${f.sensitive?`<span class="badge">${t("sensitive")}</span>`:""}</div><p class="muted">${esc(f.description||"")}</p>${input}</div>`; }).join(""); }
function buildConfigValues(schema){ const out={}; for(const f of schema){ const use=$(`cfgUse_${f.key}`); if(!use||!use.checked) continue; const el=$(`cfg_${f.key}`); if(!el) continue; out[f.key]=f.type==="bool"?!!el.checked:el.value; } return out; }
function configValidationView(x){ const validation=x.validation||x; return `<h2 class="${validation.valid?'status-ok':'status-bad'}">${validation.valid?'valid':'invalid'}</h2>${(validation.errors||[]).length?`<h2>${t("errors")}</h2><pre>${esc((validation.errors||[]).join("\n"))}</pre>`:""}${(validation.warnings||[]).length?`<h2>${t("warnings")}</h2><pre>${esc((validation.warnings||[]).join("\n"))}</pre>`:""}${table(validation.env_plan||[],["key","env_key","value","sensitive","action"],null)}<pre>${esc(pretty(x))}</pre>`; }
function configExportView(p){ return `<h2>${p.restart_required?t("restartRequired"):t("runtimeOnly")}</h2><p class="muted">${t("manualApply")}: ${esc(p.requires_manual_apply)} · ${t("willExecute")}: ${esc(p.will_execute)}</p><h2>.env</h2><pre>${esc(p.dotenv_content||"")}</pre><h2>systemd</h2><pre>${esc(p.systemd_dropin_content||"")}</pre>${configValidationView(p.validation||{})}`; }
async function tenants(){ setTitle(t("tenants"), t("tenantsHint")); const [ten,user]=await Promise.all([api("/api/v1/admin/tenants?limit=100"),api("/api/v1/admin/users?limit=100").catch(e=>({error:e.message,items:[]}))]); const tenantOptions=(ten.items||[]).map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.id)}</option>`).join(""); const userOptions=(user.items||[]).map(x=>`<option value="${esc(x.tenant_id)}:${esc(x.id)}">${esc((x.name||x.id)+" / "+x.tenant_id)}</option>`).join(""); $("content").innerHTML=`<div class="card stack"><h2>${t("createTenant")}</h2><div class="form-grid"><input id="tenantName" placeholder="${t("name")}"><label class="row"><input id="tenantProtected" type="checkbox" class="w-auto"> ${t("deleteProtected")}</label><input id="tenantProtectReason" placeholder="${t("protectionReason")}"></div><button id="createTenant">${t("create")}</button></div><div class="card"><h2>${t("tenants")}</h2>${table(ten.items||[],["id","name","status","delete_protected","created_at"], tenantActions)}</div><div class="card stack"><h2>${t("createUser")}</h2><div class="form-grid"><select id="userTenant">${tenantOptions}</select><input id="userName" placeholder="${t("name")}"><input id="userEmail" placeholder="${t("email")}"><label class="row"><input id="userProtected" type="checkbox" class="w-auto"> ${t("deleteProtected")}</label><input id="userProtectReason" placeholder="${t("protectionReason")}"></div><button id="createTenantUser">${t("create")}</button></div><div class="card"><h2>${t("users")}</h2>${table(user.items||[],["tenant_id","id","name","email","status","delete_protected"], userActions)}</div><div class="card stack"><h2>${t("credentials")}</h2><div class="form-grid"><select id="credentialUser">${userOptions}</select><input id="credentialName" placeholder="${t("name")}"><input id="credentialKey" placeholder="API key (optional)"><input id="credentialSecret" placeholder="API secret (optional)"><input id="credentialExpires" type="datetime-local"></div><div class="row"><button id="createCredential">${t("createCredential")}</button><button class="secondary" id="listCredentials">${t("listCredentials")}</button></div></div><div class="card"><h2>${t("raw")}</h2><pre id="tenantOut" class="code">${esc(pretty({tenants:ten,users:user}))}</pre></div>`; bindTenantActions(); $("createTenant").onclick=async()=>{await api("/api/v1/admin/tenants",{method:"POST",body:JSON.stringify({name:$("tenantName").value,delete_protected:$("tenantProtected").checked,delete_protection_reason:$("tenantProtectReason").value})}); render();}; $("createTenantUser").onclick=async()=>{const tenant=$("userTenant").value; await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users`,{method:"POST",body:JSON.stringify({name:$("userName").value,email:$("userEmail").value,delete_protected:$("userProtected").checked,delete_protection_reason:$("userProtectReason").value})}); render();}; $("createCredential").onclick=async()=>{const [tenant,userId]=($("credentialUser").value||":").split(":"); const body={name:$("credentialName").value,api_key:$("credentialKey").value,api_secret:$("credentialSecret").value}; if($("credentialExpires").value) body.expires_at=new Date($("credentialExpires").value).toISOString(); $("tenantOut").textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(userId)}/credentials`,{method:"POST",body:JSON.stringify(body)}));}; $("listCredentials").onclick=async()=>{const [tenant,userId]=($("credentialUser").value||":").split(":"); await showCredentials(tenant,userId);}; }
function tenantActions(x){ return `<button class="secondary" data-tenant-summary="${esc(x.id)}">${t("summary")}</button> <button data-tenant-status="${esc(x.id)}:${x.status==='active'?'disabled':'active'}">${x.status==='active'?t("suspend"):t("activate")}</button> <button class="secondary" data-tenant-audit="${esc(x.id)}">${t("audit")}</button> <button class="secondary" data-tenant-check="${esc(x.id)}">${t("deleteCheck")}</button> <button class="danger" data-tenant-delete="${esc(x.id)}">${t("delete")}</button>`; }
function userActions(x){ return `<button data-user-status="${esc(x.tenant_id)}:${esc(x.id)}:${x.status==='active'?'disabled':'active'}">${x.status==='active'?t("suspend"):t("activate")}</button> <button class="secondary" data-user-credentials="${esc(x.tenant_id)}:${esc(x.id)}">${t("credentials")}</button> <button class="secondary" data-user-audit="${esc(x.tenant_id)}:${esc(x.id)}">${t("audit")}</button> <button class="secondary" data-user-check="${esc(x.tenant_id)}:${esc(x.id)}">${t("deleteCheck")}</button> <button class="secondary" data-user-plan="${esc(x.tenant_id)}:${esc(x.id)}">${t("retirePlan")}</button> <button class="danger" data-user-delete="${esc(x.tenant_id)}:${esc(x.id)}">${t("delete")}</button>`; }
function credentialActions(tenant,userId,x){ return `<button data-credential-status="${esc(tenant)}:${esc(userId)}:${esc(x.id)}:${x.status==='active'?'suspended':'active'}">${x.status==='active'?t("suspend"):t("activate")}</button> <button class="secondary" data-credential-secret="${esc(tenant)}:${esc(userId)}:${esc(x.id)}">${t("rotateSecret")}</button> <button class="secondary" data-credential-key="${esc(tenant)}:${esc(userId)}:${esc(x.id)}">${t("rotateKey")}</button> <button class="danger" data-credential-revoke="${esc(tenant)}:${esc(userId)}:${esc(x.id)}">${t("revoke")}</button>`; }
async function showCredentials(tenant,userId){ const creds=await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(userId)}/credentials?limit=100`); $("tenantOut").innerHTML=table(creds.items||[],["id","name","status","api_key_hint","expires_at","created_at"], x=>credentialActions(tenant,userId,x)); bindCredentialActions(); applyOwnerGuards(); }
function bindCredentialActions(){ document.querySelectorAll("[data-credential-status]").forEach(b=>b.onclick=async()=>{const [tenant,userId,id,status]=b.dataset.credentialStatus.split(":"); await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(userId)}/credentials/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status})}); await showCredentials(tenant,userId);}); document.querySelectorAll("[data-credential-secret]").forEach(b=>b.onclick=async()=>{const [tenant,userId,id]=b.dataset.credentialSecret.split(":"); $("tenantOut").textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(userId)}/credentials/${encodeURIComponent(id)}/rotate-secret`,{method:"POST",body:"{}"}));}); document.querySelectorAll("[data-credential-key]").forEach(b=>b.onclick=async()=>{const [tenant,userId,id]=b.dataset.credentialKey.split(":"); $("tenantOut").textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(userId)}/credentials/${encodeURIComponent(id)}/rotate-key`,{method:"POST",body:"{}"}));}); document.querySelectorAll("[data-credential-revoke]").forEach(b=>b.onclick=async()=>{const [tenant,userId,id]=b.dataset.credentialRevoke.split(":"); if(confirm(t("revokeCredentialConfirm"))){await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(userId)}/credentials/${encodeURIComponent(id)}`,{method:"DELETE"}); await showCredentials(tenant,userId);}}); }
async function showTenantAudit(tenant,user=""){ const q=new URLSearchParams({tenant_id:tenant,limit:"100"}); if(user) q.set("user_id",user); $("tenantOut").textContent=pretty(await api(`/api/v1/admin/audit-events?${q}`)); }
function bindTenantActions(){ const out=()=>$("tenantOut"); document.querySelectorAll("[data-tenant-summary]").forEach(b=>b.onclick=async()=>out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(b.dataset.tenantSummary)}/summary`))); document.querySelectorAll("[data-tenant-status]").forEach(b=>b.onclick=async()=>{const [tenant,status]=b.dataset.tenantStatus.split(":"); const action=status==="disabled"?"pause":"resume"; await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/${action}`,{method:"POST",body:"{}"}); render();}); document.querySelectorAll("[data-tenant-audit]").forEach(b=>b.onclick=async()=>showTenantAudit(b.dataset.tenantAudit)); document.querySelectorAll("[data-tenant-check]").forEach(b=>b.onclick=async()=>out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(b.dataset.tenantCheck)}/delete-check`))); document.querySelectorAll("[data-tenant-delete]").forEach(b=>b.onclick=async()=>{const id=b.dataset.tenantDelete; const check=await api(`/api/v1/admin/tenants/${encodeURIComponent(id)}/delete-check`); out().textContent=pretty(check); if(check.can_delete===false){toast(t("deleteBlocked")); return;} if(confirm(t("deleteTenantConfirm"))){out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(id)}?confirm=true`,{method:"DELETE"})); render();}}); document.querySelectorAll("[data-user-status]").forEach(b=>b.onclick=async()=>{const [tenant,user,status]=b.dataset.userStatus.split(":"); const action=status==="disabled"?"pause":"resume"; await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(user)}/${action}`,{method:"POST",body:"{}"}); render();}); document.querySelectorAll("[data-user-credentials]").forEach(b=>b.onclick=async()=>{const [tenant,user]=b.dataset.userCredentials.split(":"); await showCredentials(tenant,user);}); document.querySelectorAll("[data-user-audit]").forEach(b=>b.onclick=async()=>{const [tenant,user]=b.dataset.userAudit.split(":"); await showTenantAudit(tenant,user);}); document.querySelectorAll("[data-user-check]").forEach(b=>b.onclick=async()=>{const [tenant,user]=b.dataset.userCheck.split(":"); out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(user)}/delete-check`));}); document.querySelectorAll("[data-user-plan]").forEach(b=>b.onclick=async()=>{const [tenant,user]=b.dataset.userPlan.split(":"); out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(user)}/retire-plan`));}); document.querySelectorAll("[data-user-delete]").forEach(b=>b.onclick=async()=>{const [tenant,user]=b.dataset.userDelete.split(":"); const check=await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(user)}/delete-check`); out().textContent=pretty(check); if(check.can_delete===false){toast(t("deleteBlocked")); return;} if(confirm(t("deleteUserConfirm"))){out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/users/${encodeURIComponent(user)}?confirm=true`,{method:"DELETE"})); render();}}); }
async function accounts(){ setTitle(t("accounts"), t("accountsHint")); if(!isOwner()){ $("content").innerHTML=`<div class="card stack"><h2>${t("changePassword")}</h2><p class="muted">${t("ownerOnly")}: ${t("users")} / ${t("sessions")}</p><div class="form-grid"><input id="oldPass" type="password" placeholder="${t("oldPassword")}"><input id="newPass" type="password" placeholder="${t("newPassword")}"></div><button id="changePass">${t("save")}</button></div>`; $("changePass").onclick=async()=>{await api("/api/v1/admin/auth/change-password",{method:"POST",body:JSON.stringify({old_password:$("oldPass").value,new_password:$("newPass").value})}); toast(t("loaded"));}; return; } const [users,sessions]=await Promise.all([api("/api/v1/admin/auth/users"),api("/api/v1/admin/auth/sessions")]); $("content").innerHTML=`<div class="card"><h2>${t("users")}</h2>${table(users.items||[],["username","display_name","role","status","locale","last_login_at"], x=>`<button data-admin-toggle="${esc(x.id)}:${x.status==='active'?'suspended':'active'}">${x.status==='active'?t("suspend"):t("activate")}</button>`)}</div><div class="card stack"><h2>${t("createAdmin")}</h2><div class="form-grid"><input id="newAdminUser" placeholder="${t("username")}"><input id="newAdminPass" type="password" placeholder="${t("password")}"><input id="newAdminName" placeholder="${t("displayName")}"><select id="newAdminRole"><option value="operator">${t("operator")}</option><option value="owner">${t("owner")}</option></select><select id="newAdminLocale">${localeOptions()}</select></div><button id="createAdmin">${t("create")}</button></div><div class="card"><h2>${t("sessions")}</h2>${table(sessions.items||[],["username","active","created_at","expires_at","remote_ip"], x=>`<button class="danger" data-session-revoke="${esc(x.id)}">${t("revoke")}</button>`)}</div><div class="card stack"><h2>${t("changePassword")}</h2><div class="form-grid"><input id="oldPass" type="password" placeholder="${t("oldPassword")}"><input id="newPass" type="password" placeholder="${t("newPassword")}"></div><button id="changePass">${t("save")}</button></div>`; document.querySelectorAll("[data-admin-toggle]").forEach(b=>b.onclick=async()=>{const [id,status]=b.dataset.adminToggle.split(":"); await api(`/api/v1/admin/auth/users/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({status,confirm_unsafe:true})}); render();}); document.querySelectorAll("[data-session-revoke]").forEach(b=>b.onclick=async()=>{if(confirm(t("revokeSessionConfirm"))){await api(`/api/v1/admin/auth/sessions/${encodeURIComponent(b.dataset.sessionRevoke)}?confirm=true`,{method:"DELETE"}); render();}}); $("createAdmin").onclick=async()=>{await api("/api/v1/admin/auth/users",{method:"POST",body:JSON.stringify({username:$("newAdminUser").value,password:$("newAdminPass").value,display_name:$("newAdminName").value,role:$("newAdminRole").value,locale:$("newAdminLocale").value})}); render();}; $("changePass").onclick=async()=>{await api("/api/v1/admin/auth/change-password",{method:"POST",body:JSON.stringify({old_password:$("oldPass").value,new_password:$("newPass").value})}); toast(t("loaded"));}; }
async function knowledge(){ setTitle(t("knowledge"), t("knowledgeHint")); const [stats,sources,cross,available,globalCfg]=await Promise.all([api("/api/v1/admin/knowledge/stats").catch(e=>({error:e.message})),api("/api/v1/admin/knowledge/sources").catch(e=>({error:e.message,sources:[]})),api("/api/v1/admin/knowledge-access/cross-tenant").catch(e=>({error:e.message,enabled:false})),api("/api/v1/admin/skill-sources/available").catch(e=>({error:e.message,sources:["skillhub","clawhub","github"]})),api("/api/v1/admin/skill-sources/global").catch(e=>({error:e.message,enabled:false,allowed_sources:[]}))]); const sourceItems=sources.sources||sources.items||[]; $("content").innerHTML=`<div class="grid"><div class="card metric"><span>${t("knowledgeSources")}</span><b>${esc(sources.total ?? sourceItems.length ?? "-")}</b></div><div class="card metric"><span>${t("crossTenant")}</span><b class="${cross.enabled?"status-warn":"status-ok"}">${esc(cross.enabled?t("enabledState"):t("disabledState"))}</b></div><div class="card metric"><span>${t("skillSourcePolicy")}</span><b>${esc(globalCfg.enabled?t("global"):t("inherit"))}</b></div></div><div class="card"><h2>${t("knowledgeStats")}</h2><pre class="code">${esc(pretty(stats))}</pre></div><div class="card"><h2>${t("knowledgeSources")}</h2>${table(sourceItems,["id","tenant_id","owner_id","title","updated_at"],null)}</div><div class="card stack danger-zone"><h2>${t("dangerous")}</h2><div class="form-grid"><input id="knowledgeClearTenant" placeholder="${t("tenantID")}"></div><button class="danger" id="clearTenantKnowledge">${t("clearTenantKnowledge")}</button></div><div class="card stack"><h2>${t("knowledgeAccess")}</h2><label class="row"><input id="knowledgeCrossTenant" type="checkbox" ${cross.enabled?"checked":""} class="w-auto"> ${t("allowCrossTenant")}</label><button id="saveKnowledgeCrossTenant">${t("save")}</button><div class="form-grid"><input id="knowledgeTenant" placeholder="${t("tenantID")}"><input id="knowledgeUser" placeholder="${t("userID")}"></div><textarea id="knowledgeScopes" placeholder='[{"tenant_id":"tenant-a","owner_id":"user-a","name":"team"}]'></textarea><div class="row"><label class="row"><input id="knowledgeEnabled" type="checkbox" checked class="w-auto"> ${t("enabledState")}</label><button id="getKnowledgeAccess">${t("view")}</button><button id="saveKnowledgeAccess">${t("save")}</button><button class="secondary" id="resolveKnowledgeAccess">${t("resolve")}</button><button class="danger" id="deleteKnowledgeAccess">${t("delete")}</button></div></div><div class="card stack"><h2>${t("skillSources")}</h2><div class="panel stack"><h2>${t("global")}</h2>${skillSourceChecks("skillGlobal",available.sources||[],globalCfg)}<button id="saveSkillGlobal">${t("save")}</button></div><div class="panel stack"><h2>${t("tenantOverride")}</h2><input id="skillTenant" placeholder="${t("tenantID")}">${skillSourceChecks("skillTenantCfg",available.sources||[],{})}<div class="row"><button id="loadSkillTenant">${t("view")}</button><button id="saveSkillTenant">${t("save")}</button><button class="danger" id="deleteSkillTenant">${t("delete")}</button></div></div><div class="panel stack"><h2>${t("userOverride")}</h2><input id="skillUserEmail" placeholder="${t("userEmail")}">${skillSourceChecks("skillUserCfg",available.sources||[],{})}<div class="row"><button id="loadSkillUser">${t("view")}</button><button id="saveSkillUser">${t("save")}</button><button class="secondary" id="resolveSkillUser">${t("resolve")}</button><button class="danger" id="deleteSkillUser">${t("delete")}</button></div></div></div><div class="card"><h2>${t("raw")}</h2><pre id="knowledgeOut" class="code">${esc(pretty({stats,sources,cross,available,global:globalCfg}))}</pre></div>`; bindKnowledgeActions(available.sources||[]); }
function skillSourceChecks(prefix,sources,cfg){ const allowed=new Set(cfg.allowed_sources||sources||[]); return `<label class="row"><input id="${prefix}_enabled" type="checkbox" ${cfg.enabled?"checked":""} class="w-auto"> ${t("enabledState")}</label><div class="row">${(sources||[]).map(s=>`<label class="row"><input id="${prefix}_${esc(s)}" type="checkbox" ${allowed.has(s)?"checked":""} class="w-auto"> ${esc(s)}</label>`).join("")}</div>`; }
function skillSourceBody(prefix,sources){ return {enabled:!!$(`${prefix}_enabled`)?.checked, allowed_sources:(sources||[]).filter(s=>$(`${prefix}_${s}`)?.checked)}; }
function applySkillSource(prefix,sources,cfg){ if($(`${prefix}_enabled`)) $(`${prefix}_enabled`).checked=!!cfg.enabled; for(const s of sources||[]){ const el=$(`${prefix}_${s}`); if(el) el.checked=(cfg.allowed_sources||[]).includes(s); } }
function knowledgeIds(){ return {tenant:$('knowledgeTenant').value.trim(), user:$('knowledgeUser').value.trim()}; }
function bindKnowledgeActions(sources){ const out=()=>$('knowledgeOut'); $('saveKnowledgeCrossTenant').onclick=async()=>out().textContent=pretty(await api('/api/v1/admin/knowledge-access/cross-tenant',{method:'PUT',body:JSON.stringify({enabled:$('knowledgeCrossTenant').checked})})); $('clearTenantKnowledge').onclick=async()=>{const tenant=$('knowledgeClearTenant').value.trim(); if(!tenant) return toast(t("tenantIDRequired")); if(confirm(t("clearKnowledgeConfirm"))) out().textContent=pretty(await api(`/api/v1/admin/tenants/${encodeURIComponent(tenant)}/knowledge?confirm=true`,{method:'DELETE'}));}; $('getKnowledgeAccess').onclick=async()=>{const ids=knowledgeIds(); const cfg=await api(`/api/v1/admin/knowledge-access/tenants/${encodeURIComponent(ids.tenant)}/users/${encodeURIComponent(ids.user)}`); $('knowledgeEnabled').checked=!!cfg.enabled; $('knowledgeScopes').value=pretty(cfg.read_scopes||[]); out().textContent=pretty(cfg);}; $('saveKnowledgeAccess').onclick=async()=>{const ids=knowledgeIds(); let scopes; try{scopes=parseJSONField("knowledgeScopes","[]");}catch{return;} out().textContent=pretty(await api(`/api/v1/admin/knowledge-access/tenants/${encodeURIComponent(ids.tenant)}/users/${encodeURIComponent(ids.user)}`,{method:'PUT',body:JSON.stringify({enabled:$('knowledgeEnabled').checked,read_scopes:scopes})}));}; $('resolveKnowledgeAccess').onclick=async()=>{const ids=knowledgeIds(); out().textContent=pretty(await api(`/api/v1/admin/knowledge-access/tenants/${encodeURIComponent(ids.tenant)}/users/${encodeURIComponent(ids.user)}/resolve`));}; $('deleteKnowledgeAccess').onclick=async()=>{const ids=knowledgeIds(); if(confirm(t("deleteKnowledgeAccessConfirm"))) out().textContent=pretty(await api(`/api/v1/admin/knowledge-access/tenants/${encodeURIComponent(ids.tenant)}/users/${encodeURIComponent(ids.user)}`,{method:'DELETE'}));}; $('saveSkillGlobal').onclick=async()=>out().textContent=pretty(await api('/api/v1/admin/skill-sources/global',{method:'PUT',body:JSON.stringify(skillSourceBody('skillGlobal',sources))})); $('loadSkillTenant').onclick=async()=>{const cfg=await api(`/api/v1/admin/skill-sources/tenant/${encodeURIComponent($('skillTenant').value.trim())}`); applySkillSource('skillTenantCfg',sources,cfg); out().textContent=pretty(cfg);}; $('saveSkillTenant').onclick=async()=>out().textContent=pretty(await api(`/api/v1/admin/skill-sources/tenant/${encodeURIComponent($('skillTenant').value.trim())}`,{method:'PUT',body:JSON.stringify(skillSourceBody('skillTenantCfg',sources))})); $('deleteSkillTenant').onclick=async()=>{if(confirm(t("deleteSkillTenantConfirm"))) out().textContent=pretty(await api(`/api/v1/admin/skill-sources/tenant/${encodeURIComponent($('skillTenant').value.trim())}`,{method:'DELETE'}));}; $('loadSkillUser').onclick=async()=>{const cfg=await api(`/api/v1/admin/skill-sources/user/${encodeURIComponent($('skillUserEmail').value.trim())}`); applySkillSource('skillUserCfg',sources,cfg); out().textContent=pretty(cfg);}; $('saveSkillUser').onclick=async()=>out().textContent=pretty(await api(`/api/v1/admin/skill-sources/user/${encodeURIComponent($('skillUserEmail').value.trim())}`,{method:'PUT',body:JSON.stringify(skillSourceBody('skillUserCfg',sources))})); $('resolveSkillUser').onclick=async()=>{const email=$('skillUserEmail').value.trim(); const tenant=$('skillTenant').value.trim(); const q=tenant?`?tenant_id=${encodeURIComponent(tenant)}`:''; out().textContent=pretty(await api(`/api/v1/admin/skill-sources/resolve/${encodeURIComponent(email)}${q}`));}; $('deleteSkillUser').onclick=async()=>{if(confirm(t("deleteSkillUserConfirm"))) out().textContent=pretty(await api(`/api/v1/admin/skill-sources/user/${encodeURIComponent($('skillUserEmail').value.trim())}`,{method:'DELETE'}));}; }
async function ops(){ setTitle(t("ops"), t("opsHint")); const [audit,snaps,risks]=await Promise.all([api("/api/v1/admin/audit-events?limit=50").catch(e=>({error:e.message,items:[]})),api("/api/v1/admin/snapshots?limit=50").catch(e=>({error:e.message,items:[]})),api("/api/v1/admin/security/risk-events?limit=50").catch(e=>({error:e.message,items:[]}))]); $("content").innerHTML=`<div class="grid"><div class="card stack"><h2>${t("audit")}</h2><div class="form-grid"><input id="auditAction" placeholder="${t("actionName")}"><input id="auditTenant" placeholder="${t("tenantID")}"><input id="auditUser" placeholder="${t("userID")}"><input id="auditActorUser" placeholder="actor_user_id"><input id="auditLimit" type="number" value="50"></div><button id="loadAudit">${t("refresh")}</button></div><div class="card stack"><h2>${t("export")}</h2><div class="form-grid"><input id="exportTenant" placeholder="${t("tenantID")}"><input id="exportUser" placeholder="${t("userID")}"><label class="row"><input id="exportMessages" type="checkbox" checked class="w-auto"> ${t("messages")}</label><label class="row"><input id="exportRuns" type="checkbox" checked class="w-auto"> ${t("runs")}</label><label class="row"><input id="exportAudit" type="checkbox" checked class="w-auto"> ${t("audit")}</label><label class="row"><input id="exportSecrets" type="checkbox" class="w-auto"> ${t("secrets")}</label></div><button id="runExport">${t("export")}</button></div><div class="card stack"><h2>${t("import")}</h2><textarea id="importText" placeholder="${t("pasteExportedJSON")}"></textarea><div class="row"><label class="row"><input id="importOverwrite" type="checkbox" class="w-auto"> ${t("overwrite")}</label><label class="row"><input id="importDryRun" type="checkbox" checked class="w-auto"> ${t("dryRun")}</label><button id="runImport">${t("import")}</button></div></div><div class="card stack"><h2>${t("snapshots")}</h2><div class="form-grid"><input id="snapshotName" placeholder="${t("name")}"><input id="snapshotTenant" placeholder="${t("tenantID")}"><input id="snapshotUser" placeholder="${t("userID")}"><label class="row"><input id="snapshotMessages" type="checkbox" checked class="w-auto"> ${t("messages")}</label><label class="row"><input id="snapshotRuns" type="checkbox" checked class="w-auto"> ${t("runs")}</label><label class="row"><input id="snapshotAudit" type="checkbox" checked class="w-auto"> ${t("audit")}</label><label class="row"><input id="snapshotSecrets" type="checkbox" class="w-auto"> ${t("secrets")}</label></div><div class="row"><button id="createSnapshot">${t("create")}</button><button class="secondary" id="refreshSnapshots">${t("refresh")}</button><input id="pruneKeep" type="number" value="10" class="w-narrow"><button class="warn" id="pruneSnapshots">${t("dryRun")}</button></div></div></div><div class="card"><h2>${t("riskEvents")}</h2><div class="row"><select id="riskSeverity"><option value="">${t("all")}</option><option>high</option><option>medium</option><option>low</option></select><input id="riskKind" placeholder="${t("kindPlaceholder")}" list="riskKindOptions"><datalist id="riskKindOptions">${riskKindOptions(risks.kind_counts)}</datalist><input id="riskSince" type="datetime-local"><input id="riskUntil" type="datetime-local"><input id="riskLimit" type="number" min="1" max="500" value="50" class="w-narrow"><button class="secondary" id="loadRisks">${t("refresh")}</button><button class="secondary" id="clearRiskFilters">${t("clear")}</button></div><div class="row"><button class="secondary" data-risk-preset="1">1h</button><button class="secondary" data-risk-preset="24">24h</button><button class="secondary" data-risk-preset="168">7d</button><button class="secondary" data-risk-preset="all">${t("all")}</button></div><div id="riskFilterStatus">${riskFilterSummary(risks)}</div><h3>${t("bySeverity")}</h3><div id="riskSeverityCounts">${riskCountChips(risks.counts,"severity")}</div><h3>${t("byKind")}</h3><div id="riskKindCounts">${riskCountChips(risks.kind_counts)}</div><div id="riskEventsList">${riskEventsTable(risks.items||[])}</div></div><div class="card"><h2>${t("snapshots")}</h2>${snapshotTable(snaps.items||[])}</div><div class="card"><h2>${t("raw")}</h2><pre id="opsOut" class="code">${esc(pretty({audit,snapshots:snaps,security_risks:risks}))}</pre></div>`; bindOpsSnapshotActions(); bindRiskEventActions(risks.items||[]); bindRiskCountChips(); $("loadRisks").onclick=loadRiskEventsFromFilters; $("clearRiskFilters").onclick=clearRiskFilters; document.querySelectorAll("[data-risk-preset]").forEach(btn=>btn.onclick=()=>setRiskTimePreset(btn.dataset.riskPreset==="all"?0:Number(btn.dataset.riskPreset))); applyPendingRiskFilter(); $("loadAudit").onclick=async()=>{const q=new URLSearchParams(); if($("auditAction").value) q.set("action",$("auditAction").value); if($("auditTenant").value) q.set("tenant_id",$("auditTenant").value); if($("auditUser").value) q.set("user_id",$("auditUser").value); if($("auditActorUser").value) q.set("actor_user_id",$("auditActorUser").value); let auditLimit; try{auditLimit=numberInRange("auditLimit",50,1,500);}catch{return;} q.set("limit",String(auditLimit)); $("opsOut").textContent=pretty(await api(`/api/v1/admin/audit-events?${q}`));}; $("runExport").onclick=async()=>{const q=exportParams("export"); if($("exportSecrets").checked){const typed=prompt(t("exportSecretPrompt")); if(typed!=="EXPORT SECRETS") return; q.set("confirm","true");} $("opsOut").textContent=pretty(await api(`/api/v1/admin/export?${q}`));}; $("runImport").onclick=async()=>{let data; try{data=parseJSONField("importText","{}");}catch{return;} const q=new URLSearchParams({overwrite:String($("importOverwrite").checked),dry_run:String($("importDryRun").checked)}); if(!$("importDryRun").checked){const typed=prompt(t("importRunPrompt")); if(typed!=="IMPORT STATE") return; q.set("confirm","true");} $("opsOut").textContent=pretty(await api(`/api/v1/admin/import?${q}`,{method:"POST",body:JSON.stringify({data,overwrite:$("importOverwrite").checked,dry_run:$("importDryRun").checked})}));}; $("createSnapshot").onclick=async()=>{const body={name:$("snapshotName").value,tenant_id:$("snapshotTenant").value,user_id:$("snapshotUser").value,include_messages:$("snapshotMessages").checked,include_runs:$("snapshotRuns").checked,include_audit:$("snapshotAudit").checked,include_secrets:$("snapshotSecrets").checked}; let path="/api/v1/admin/snapshots"; if(body.include_secrets){const typed=prompt(t("snapshotSecretPrompt")); if(typed!=="SNAPSHOT SECRETS") return; path+="?confirm=true";} $("opsOut").textContent=pretty(await api(path,{method:"POST",body:JSON.stringify(body)})); render();}; $("refreshSnapshots").onclick=()=>render(); $("pruneSnapshots").onclick=async()=>{$("opsOut").textContent=pretty(await api("/api/v1/admin/snapshots/prune",{method:"POST",body:JSON.stringify({keep_latest:numberInRange("pruneKeep",10,1,1000),dry_run:true})}));}; }
function exportParams(prefix){ const q=new URLSearchParams(); const tenant=$(prefix+"Tenant").value; const user=$(prefix+"User").value; if(tenant) q.set("tenant_id",tenant); if(user) q.set("user_id",user); q.set("include_messages",String($(prefix+"Messages").checked)); q.set("include_runs",String($(prefix+"Runs").checked)); q.set("include_audit",String($(prefix+"Audit").checked)); q.set("include_secrets",String($(prefix+"Secrets").checked)); return q; }
function snapshotTable(items){ return table(items,["id","name","scope","tenant_id","user_id","size_bytes","created_at"],x=>`<button class="secondary" data-snapshot-get="${esc(x.id)}">${t("view")}</button> <button class="warn" data-snapshot-restore="${esc(x.id)}">${t("restore")} ${t("dryRun")}</button> <button class="warn" data-snapshot-restore-run="${esc(x.id)}">${t("restore")}</button> <button class="danger" data-snapshot-delete="${esc(x.id)}">${t("delete")}</button>`); }
function bindOpsSnapshotActions(){ document.querySelectorAll("[data-snapshot-get]").forEach(b=>b.onclick=async()=>$("opsOut").textContent=pretty(await api(`/api/v1/admin/snapshots/${encodeURIComponent(b.dataset.snapshotGet)}`))); document.querySelectorAll("[data-snapshot-restore]").forEach(b=>b.onclick=async()=>$("opsOut").textContent=pretty(await api(`/api/v1/admin/snapshots/${encodeURIComponent(b.dataset.snapshotRestore)}/restore?dry_run=true`,{method:"POST",body:JSON.stringify({dry_run:true})}))); document.querySelectorAll("[data-snapshot-restore-run]").forEach(b=>b.onclick=async()=>{const typed=prompt(t("restoreRunPrompt")); if(typed!=="RESTORE SNAPSHOT") return; $("opsOut").textContent=pretty(await api(`/api/v1/admin/snapshots/${encodeURIComponent(b.dataset.snapshotRestoreRun)}/restore?confirm=true`,{method:"POST",body:JSON.stringify({dry_run:false})}));}); document.querySelectorAll("[data-snapshot-delete]").forEach(b=>b.onclick=async()=>{if(confirm(t("deleteSnapshotConfirm"))){ $("opsOut").textContent=pretty(await api(`/api/v1/admin/snapshots/${encodeURIComponent(b.dataset.snapshotDelete)}?confirm=true`,{method:"DELETE"})); render(); }}); }
function table(items, cols, action){ if(!items.length) return `<p class="muted">${t("empty")}</p>`; return `<table><thead><tr>${cols.map(c=>`<th>${esc(c)}</th>`).join("")}<th>${t("action")}</th></tr></thead><tbody>${items.map(x=>`<tr>${cols.map(c=>`<td>${esc(x[c])}</td>`).join("")}<td>${action?action(x):""}</td></tr>`).join("")}</tbody></table>`; }
$("localeSelect").onchange=()=>{state.locale=$("localeSelect").value; localStorage.setItem("maclaw.admin.locale",state.locale); render();};
$("logoutBtn").onclick=async()=>{try{ if(state.token) await api("/api/v1/admin/auth/logout",{method:"POST"}); }catch{} state.token=""; state.me=null; localStorage.removeItem("maclaw.admin.token"); render();};
startup();

async function loadSandboxEventsFromFilters(){ const q=new URLSearchParams({limit:"20"}); if($("sandboxEventStatus")?.value) q.set("status",$("sandboxEventStatus").value); if($("sandboxEventBackend")?.value) q.set("backend",$("sandboxEventBackend").value.trim()); const events=await api(`/api/v1/admin/sandbox/events?${q}`); $("sandboxEventsTable").innerHTML=sandboxEventsTable(events.items||[]); bindSandboxEventActions(events.items||[]); $("sandboxOut").innerHTML=`<pre>${esc(pretty(events))}</pre>`; }
function bindSandboxEventActions(items){ const byId=new Map((items||[]).map(x=>[x.id,x])); document.querySelectorAll("[data-sandbox-event]").forEach(b=>b.onclick=()=>{$("sandboxOut").innerHTML=`<pre>${esc(pretty(byId.get(b.dataset.sandboxEvent)||{}))}</pre>`;}); if($("loadSandboxEvents")) $("loadSandboxEvents").onclick=loadSandboxEventsFromFilters; }

function readSandboxProfileEditor(){ let extra; try{extra=parseJSONField("sandboxProfileJSON","{}");}catch(e){ toast(t("profileJSONInvalid")); throw e; } return {...extra,name:$("sandboxProfileName").value.trim(),backend:$("sandboxProfileBackend").value,network:$("sandboxProfileNetwork").value}; }
function fillSandboxProfileEditor(profile){ if(!profile) profile={backend:"bwrap",network:"default",readonly_paths:[],writable_paths:[],env_allowlist:[]}; $("sandboxProfileName").value=profile.name||""; $("sandboxProfileBackend").value=profile.backend||"bwrap"; $("sandboxProfileNetwork").value=profile.network||"default"; const {name,backend,network,updated_at,...extra}=profile; $("sandboxProfileJSON").value=pretty(extra); }
function bindSandboxProfileActions(items){ const byName=new Map((items||[]).map(x=>[x.name,x])); document.querySelectorAll("[data-sandbox-profile]").forEach(b=>b.onclick=async()=>{const out=await api(`/api/v1/admin/sandbox/profiles/${encodeURIComponent(b.dataset.sandboxProfile)}`); const profile=out.profile||out; fillSandboxProfileEditor(profile); $("sandboxProfile").value=profile.name||"default"; $("sandboxOut").innerHTML=`<pre>${esc(pretty(out))}</pre>`;}); document.querySelectorAll("[data-sandbox-profile-delete]").forEach(b=>b.onclick=async()=>{if(confirm(t("deleteSandboxProfileConfirm"))){$("sandboxOut").innerHTML=`<pre>${esc(pretty(await api(`/api/v1/admin/sandbox/profiles/${encodeURIComponent(b.dataset.sandboxProfileDelete)}?confirm=true`,{method:"DELETE"})))}</pre>`; render();}}); $("validateSandboxProfile").onclick=async()=>{const body=readSandboxProfileEditor(); if(!body.name) return toast(t("profileName")); $("sandboxOut").innerHTML=`<pre>${esc(pretty(await api(`/api/v1/admin/sandbox/profiles/${encodeURIComponent(body.name)}/validate`,{method:"POST",body:JSON.stringify(body)})))}</pre>`;}; $("saveSandboxProfile").onclick=async()=>{const body=readSandboxProfileEditor(); if(!body.name) return toast(t("profileName")); $("sandboxOut").innerHTML=`<pre>${esc(pretty(await api(`/api/v1/admin/sandbox/profiles/${encodeURIComponent(body.name)}`,{method:"PUT",body:JSON.stringify(body)})))}</pre>`; render();}; }
