#!/usr/bin/env python3
"""Run each testdata case through onnxruntime and write outputs.json.

Cases are directories under corelib/onnxrt/testdata/ containing model.onnx
and inputs.json (generated by cmd/gengolden). Additionally handles the two
real OCR models (inputs generated here with a fixed numpy seed) when they
exist under .tmp/ocr-models/.

Usage: python corelib/onnxrt/testdata/run_golden.py
"""
import base64
import json
import os
import sys

import numpy as np
import onnxruntime as ort

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))


def decode_td(td):
    raw = base64.b64decode(td["data"])
    dt = np.dtype("<f4") if td["dtype"] == "float32" else np.dtype("<i8")
    return np.frombuffer(raw, dtype=dt).reshape(td["shape"])


def encode_td(arr):
    shape = list(arr.shape)  # capture before ascontiguousarray: NumPy 2.x promotes 0-d to (1,)
    arr = np.ascontiguousarray(arr)
    if arr.dtype in (np.float32, np.float64):
        arr = arr.astype("<f4")
        dt = "float32"
    else:
        arr = arr.astype("<i8")
        dt = "int64"
    return {
        "shape": shape,
        "dtype": dt,
        "data": base64.b64encode(arr.tobytes()).decode("ascii"),
    }


def run_case(model_path, inputs, out_path):
    sess = ort.InferenceSession(model_path, providers=["CPUExecutionProvider"])
    names = [o.name for o in sess.get_outputs()]
    results = sess.run(names, inputs)
    outputs = {n: encode_td(r) for n, r in zip(names, results)}
    with open(out_path, "w") as f:
        json.dump({"outputs": outputs}, f)
    return {n: (r.shape, r.dtype) for n, r in zip(names, results)}


def run_tree(base):
    """Run every case directory under base through onnxruntime."""
    count = 0
    if not os.path.isdir(base):
        return 0
    for name in sorted(os.listdir(base)):
        d = os.path.join(base, name)
        if not os.path.isdir(d):
            continue
        mp = os.path.join(d, "model.onnx")
        ip = os.path.join(d, "inputs.json")
        if not (os.path.exists(mp) and os.path.exists(ip)):
            continue
        with open(ip) as f:
            inputs = {k: decode_td(v) for k, v in json.load(f)["inputs"].items()}
        info = run_case(mp, inputs, os.path.join(d, "outputs.json"))
        print(f"{os.path.relpath(d, HERE)}: {info}")
        count += 1
    return count


def main():
    count = run_tree(HERE)
    # randomized differential cases from cmd/genfuzz live one level deeper
    count += run_tree(os.path.join(HERE, "fuzz"))

    # real OCR models (skip silently if not downloaded)
    for tag, fname, shape in [
        ("real_det", "ppocrv6_small_det.onnx", (1, 3, 128, 128)),
        ("real_rec", "ppocrv6_small_rec.onnx", (1, 3, 48, 320)),
    ]:
        mp = os.path.join(ROOT, ".tmp", "ocr-models", fname)
        if not os.path.exists(mp):
            print(f"skip {tag}: model missing")
            continue
        d = os.path.join(HERE, tag)
        os.makedirs(d, exist_ok=True)
        rng = np.random.RandomState(1234)
        x = (rng.rand(*shape).astype(np.float32) * 2 - 1)
        td = encode_td(x)
        with open(os.path.join(d, "inputs.json"), "w") as f:
            json.dump({"inputs": {"x": td}}, f)
        info = run_case(mp, {"x": x}, os.path.join(d, "outputs.json"))
        print(f"{tag}: {info}")
        count += 1
    print(f"{count} cases")


if __name__ == "__main__":
    sys.exit(main())
