import type { ClipboardEvent, CSSProperties, Dispatch, KeyboardEvent, MouseEvent, PointerEvent, ReactNode, Ref, SetStateAction } from "react";
import type { AttachmentInfo } from "./useBufferQueue";
import type { UseVoiceInputResult } from "./useVoiceInput";
import type { Theme } from "./aiAssistantPanelTheme";

export interface AssistantInputComposerProps {
    browseFile: () => void;
    canSend: boolean;
    attachButtonTestId?: string;
    cancelPending: boolean;
    cancelSession?: unknown;
    clearSelectedFile?: () => void;
    exitHistoryBrowsing: () => boolean;
    finishVoicePointer: (event: PointerEvent<HTMLButtonElement>) => void;
    handleCancel: () => void;
    handlePaste: (event: ClipboardEvent<HTMLTextAreaElement>) => void;
    handleSend: () => void;
    handleTextareaClick?: (event: MouseEvent<HTMLTextAreaElement>) => void;
    handleTextareaKeyDownBefore?: (event: KeyboardEvent<HTMLTextAreaElement>) => boolean;
    handleTextareaKeyUp?: (event: KeyboardEvent<HTMLTextAreaElement>) => void;
    handleVoiceClick: () => void;
    handleVoicePointerDown: (event: PointerEvent<HTMLButtonElement>) => void;
    handleVoicePointerLeave: (event: PointerEvent<HTMLButtonElement>) => void;
    inputAreaHeight: number | null;
    inputLocked: boolean;
    inputBarTestId?: string;
    inputRef: Ref<HTMLTextAreaElement>;
    inputOverlay?: ReactNode;
    inputRowTestId?: string;
    inputValue: string;
    inline: boolean;
    isBusy: boolean;
    isSelectionCollapsedAtBoundary: (direction: "up" | "down") => boolean;
    lang: string;
    pendingAttachments: AttachmentInfo[];
    pendingAttachmentsTestId?: string;
    placeholderText: string;
    ready: boolean;
    recallHistory: (direction: "up" | "down") => boolean;
    rememberHistoryEdit: (value: string) => void;
    removeSelectedFile?: (index: number) => void;
    resizeInput: () => void;
    selectedFilePaths: string[];
    setPendingAttachments: Dispatch<SetStateAction<AttachmentInfo[]>>;
    showBusySpinner: boolean;
    showMemoryUsage?: boolean;
    showVoiceInput?: boolean;
    sendButtonTestId?: string;
    sendButtonStyle?: CSSProperties;
    textareaAriaLabel?: string;
    textareaTestId?: string;
    theme: Theme;
    themeMode: "light" | "dark";
    toolbarTestId?: string;
    updateInputValue: (value: string) => void;
    voiceInput: UseVoiceInputResult;
}
