// AUTO-GENERATED by cmd/genphasemeta. DO NOT EDIT.
//
// Regenerate with: go generate ./...
// Source of truth: corelib/workflow/templates.go (RegisterBuiltinTemplates).

export interface GeneratedPhaseMeta {
  id: string;
  name: string;
  index: number;
  expectsDocument: boolean;
  canSkip: boolean;
  needsConfirm: boolean;
  kind: string;
  toolPolicy: string;
  mutationScope: string;
  activatesOrchestrator: boolean;
}

export const WORKFLOW_PHASE_META: Record<string, GeneratedPhaseMeta[]> = {
  "bid_response": [
    { id: "tender_analysis", name: "招标解析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "qualification", name: "资质响应", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "technical", name: "技术方案", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "commercial", name: "商务报价", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "assembly", name: "文件组装", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "business_plan": [
    { id: "market_analysis", name: "市场分析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "business_model", name: "商业模式", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "financial_plan", name: "财务规划", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "operations", name: "运营计划", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "risk_assessment", name: "风险评估", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "changjiang_scholar": [
    { id: "cj_profile", name: "申请人基本信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_foundation", name: "学术成就与代表性成果", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_plan", name: "聘期研究计划", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_phase4", name: "人才培养与团队建设", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_assembly", name: "推荐意见与申报书整合", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "changjiang_scholar_review": [
    { id: "cj_completeness_check", name: "基本信息完整性检测", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_achievement_evaluation", name: "学术成果质量评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_plan_feasibility", name: "研究计划可行性评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_narrative_quality", name: "材料撰写质量评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "cj_improvement_report", name: "综合评估与修改建议报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "coding": [
    { id: "requirements", name: "需求文档", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "document_planning", toolPolicy: "doc_only", mutationScope: "workflow_doc", activatesOrchestrator: false },
    { id: "design", name: "技术设计", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "document_planning", toolPolicy: "doc_only", mutationScope: "workflow_doc", activatesOrchestrator: false },
    { id: "tasks", name: "任务分解", index: 2, expectsDocument: true, canSkip: true, needsConfirm: true, kind: "code_planning", toolPolicy: "planning", mutationScope: "workflow_doc", activatesOrchestrator: false },
    { id: "implementation", name: "编码执行", index: 3, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "execution", toolPolicy: "full", mutationScope: "project", activatesOrchestrator: true },
    { id: "review", name: "验收确认", index: 4, expectsDocument: true, canSkip: true, needsConfirm: true, kind: "review", toolPolicy: "doc_only", mutationScope: "workflow_doc", activatesOrchestrator: false },
  ],
  "coding_subagent": [
    { id: "coding_subagent_execution", name: "简化编程", index: 0, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "competitive_analysis": [
    { id: "competitor_id", name: "竞品识别", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "comparison", name: "维度对比", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "swot", name: "SWOT 分析", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "differentiation", name: "差异化策略", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "action_plan", name: "行动建议", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "compliance_audit": [
    { id: "scope", name: "审计范围", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "assessment", name: "合规评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "risk_rating", name: "风险评级", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "remediation", name: "整改计划", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "report", name: "审计报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "contract_review": [
    { id: "parsing", name: "合同解析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "risk_analysis", name: "条款风险", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "compliance", name: "合规审查", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "suggestions", name: "修改建议", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "opinion", name: "审查意见", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "due_diligence": [
    { id: "company_profile", name: "公司画像", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "business_dd", name: "商业尽调", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "financial_dd", name: "财务尽调", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "legal_dd", name: "法律尽调", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "conclusion", name: "尽调结论", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "event_planning": [
    { id: "positioning", name: "目标定位", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "creative", name: "创意策划", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "execution_plan", name: "执行方案", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "budget_schedule", name: "预算排期", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "contingency", name: "应急预案", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "experiment_design": [
    { id: "hypothesis", name: "假设提出", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "design", name: "实验方案", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "variables", name: "变量控制", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "data_plan", name: "数据采集", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "analysis_plan", name: "结果分析", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "gaokao_application": [
    { id: "gaokao_profile", name: "考生信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gaokao_data_search", name: "录取数据检索与证据整理", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "gaokao_candidate_ranking", name: "候选院校专业排序", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "gaokao_final_plan", name: "填报参考资料与建议", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "grant_proposal": [
    { id: "topic", name: "选题论证", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "foundation", name: "研究基础", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "methodology", name: "方案设计", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "budget", name: "预算编制", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "proposal", name: "申请书", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "innovation": [
    { id: "trend_analysis", name: "趋势分析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "opportunity", name: "机会识别", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "solution", name: "方案设计", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "feasibility", name: "可行性评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "roadmap", name: "路线图", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "literature_review": [
    { id: "topic_definition", name: "主题界定", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "search_strategy", name: "检索策略", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "screening", name: "文献筛选", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "analysis", name: "内容分析", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "synthesis", name: "综述撰写", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "maintenance": [
    { id: "maint_analysis", name: "影响分析与方案", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "maint_execution", name: "重构执行", index: 1, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "maint_verification", name: "验证", index: 2, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_distinguished_youth": [
    { id: "dy_profile", name: "申请人基本信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_foundation", name: "研究工作基础与学术贡献", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_plan", name: "研究方案与创新点", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_phase4", name: "预期成果与经费预算", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_assembly", name: "申请书整合与润色", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_distinguished_youth_review": [
    { id: "dy_review_completeness", name: "完整性检测", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_review_achievements", name: "学术成果评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_review_plan", name: "研究计划评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_review_quality", name: "撰写质量评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "dy_review_report", name: "综合评估报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_excellent_youth": [
    { id: "ey_profile", name: "申请人基本信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_foundation", name: "研究积累与发展潜力", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_plan", name: "研究方案与关键科学问题", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_phase4", name: "预期成果与经费预算", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_assembly", name: "申请书整合与润色", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_excellent_youth_review": [
    { id: "ey_review_completeness", name: "完整性检测", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_review_achievements", name: "学术成果评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_review_plan", name: "研究计划评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_review_quality", name: "撰写质量评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ey_review_report", name: "综合评估报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_general": [
    { id: "gp_profile", name: "申请人基本信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gp_foundation", name: "研究基础与工作条件", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "gp_plan", name: "研究方案与技术路线", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gp_phase4", name: "经费预算与年度计划", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gp_assembly", name: "申请书整合与润色", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_general_review": [
    { id: "gen_review_completeness", name: "完整性检测", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gen_review_achievements", name: "学术成果评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gen_review_plan", name: "研究计划评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gen_review_quality", name: "撰写质量评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "gen_review_report", name: "综合评估报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_key": [
    { id: "kp_profile", name: "申请人基本信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "kp_foundation", name: "研究团队与工作基础", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "kp_plan", name: "研究方案与课题设置", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "kp_phase4", name: "经费预算与管理计划", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "kp_assembly", name: "申请书整合与润色", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_key_review": [
    { id: "key_review_completeness", name: "完整性检测", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "key_review_achievements", name: "学术成果评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "key_review_plan", name: "研究计划评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "key_review_quality", name: "撰写质量评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "key_review_report", name: "综合评估报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_youth": [
    { id: "yf_profile", name: "申请人基本信息采集", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_foundation", name: "研究基础与可行性", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_plan", name: "研究方案与技术路线", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_phase4", name: "经费预算", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_assembly", name: "申请书整合与润色", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "nsfc_youth_review": [
    { id: "yf_review_completeness", name: "完整性检测", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_review_achievements", name: "学术成果评估", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_review_plan", name: "研究计划评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_review_quality", name: "撰写质量评估", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "yf_review_report", name: "综合评估报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "ops_maintenance": [
    { id: "ops_intake", name: "Ops Intake", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "readonly_collection", name: "Read-only Collection", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "artifact_plan", name: "Maintenance Artifacts", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "risk_policy", name: "Risk Policy Gate", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "controlled_execution", name: "Controlled Execution", index: 4, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "paper_reproduction": [
    { id: "paper_analysis", name: "论文深度解读", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "reproduction_plan", name: "复现规划", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "env_and_data", name: "环境搭建与数据准备", index: 2, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "baseline_reproduction", name: "基线实验复现", index: 3, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "iterative_improvement", name: "迭代改进", index: 4, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "experiment_report", name: "实验报告", index: 5, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "paper_writing": [
    { id: "outline", name: "大纲设计", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "literature", name: "文献梳理", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "drafting", name: "正文撰写", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "figures", name: "图表制作", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "polishing", name: "润色定稿", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "patent_analysis": [
    { id: "tech_parsing", name: "技术解析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "prior_art", name: "现有技术", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "infringement", name: "侵权评估", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "strategy", name: "策略建议", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "report", name: "分析报告", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "patent_application": [
    { id: "pa_disclosure_parsing", name: "申请材料解析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "pa_prior_art_search", name: "查新/近似检索分析", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "pa_claims_drafting", name: "权利要求/保护要点", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "pa_figures_organization", name: "附图/图片整理", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "pa_description_writing", name: "说明书/简要说明", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "pa_document_assembly", name: "申请文件组装与检查", index: 5, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "presentation_design": [
    { id: "audience_goal", name: "受众与目标", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "outline", name: "内容大纲", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "slide_scripting", name: "逐页脚本", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "ppt_generation", name: "PPT 生成", index: 3, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "artifact_generation", toolPolicy: "full", mutationScope: "artifact", activatesOrchestrator: false },
  ],
  "product_design": [
    { id: "problem_discovery", name: "问题发现", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "user_research", name: "用户研究", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "solution_design", name: "方案设计", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "prototype", name: "原型设计", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "project_proposal": [
    { id: "background", name: "背景分析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "objectives", name: "目标定义", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "plan", name: "方案规划", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "budget", name: "资源预算", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "risk_plan", name: "风险预案", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "remote_coding_subagent": [
    { id: "remote_coding_subagent_execution", name: "远程编程", index: 0, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "research_report": [
    { id: "problem_definition", name: "问题定义", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "methodology", name: "方法论", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "data_collection", name: "数据收集", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "analysis", name: "分析论证", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "conclusion", name: "结论建议", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
  ],
  "testing": [
    { id: "test_strategy", name: "测试策略", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "test_cases", name: "用例设计", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "test_environment", name: "环境准备", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "doc_only", mutationScope: "", activatesOrchestrator: false },
    { id: "test_execution", name: "执行测试", index: 3, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "defect_report", name: "缺陷报告", index: 4, expectsDocument: false, canSkip: false, needsConfirm: false, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
  "us_patent_application": [
    { id: "us_disclosure_analysis", name: "Disclosure Analysis / 交底书解析", index: 0, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "us_prior_art_search", name: "Prior Art Search / 查新检索", index: 1, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "us_claims_drafting", name: "Claims Drafting / 权利要求撰写", index: 2, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "us_drawings", name: "Drawings / 附图生成与整理", index: 3, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "us_specification_writing", name: "Specification Writing / 说明书撰写", index: 4, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
    { id: "us_application_assembly", name: "Application Assembly / 申请文件组装", index: 5, expectsDocument: true, canSkip: false, needsConfirm: true, kind: "", toolPolicy: "full", mutationScope: "", activatesOrchestrator: false },
  ],
};
