// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckEnvironment(arg1:boolean):Promise<void>;

export function CheckToolsStatus():Promise<Array<main.ToolStatus>>;

export function CheckUpdate(arg1:string):Promise<main.UpdateResult>;

export function ClipboardGetText():Promise<string>;

export function DeleteSkill(arg1:string,arg2:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function ActivateRemote(arg1:string,arg2:string,arg3:string):Promise<any>;

export function ProbeRemoteHub(arg1:string,arg2:string):Promise<any>;

export function ClearRemoteActivation():Promise<void>;

export function GetCurrentProjectPath():Promise<string>;

export function GetDownloadsFolder():Promise<string>;

export function GetEnvCheckInterval():Promise<number>;

export function GetLocalCacheDir():Promise<string>;

export function GetRemoteActivationStatus():Promise<any>;

export function GetRemoteClaudeReadiness(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolReadiness(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemoteConnectionStatus():Promise<any>;

export function GetRemoteClaudeLaunchProbe(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolLaunchProbe(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemotePTYProbe():Promise<any>;

export function GetLastRemoteSmokeReport():Promise<any>;

export function StartRemoteClaudeSession(arg1:string,arg2:boolean):Promise<any>;

export function StartRemoteSession(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<any>;

export function StartRemoteHandoffSession(arg1:string,arg2:string,arg3:boolean,arg4:string):Promise<any>;

export function ListValidProviders(arg1:string):Promise<any>;

export function GetSkillsDir(arg1:string):Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUserHomeDir():Promise<string>;

export function InstallDefaultMarketplace():Promise<void>;

export function InstallSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function InstallTool(arg1:string):Promise<void>;

export function InstallToolOnDemand(arg1:string):Promise<void>;

export function IsToolBeingInstalled(arg1:string):Promise<boolean>;

export function IsWindowsTerminalAvailable():Promise<boolean>;

export function LaunchInstallerAndExit(arg1:string):Promise<void>;

export function LaunchTool(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ListPythonEnvironments():Promise<Array<main.PythonEnvironment>>;

export function ListRemoteHubs(arg1:string,arg2:string):Promise<Array<any>>;

export function ListRemoteSessions():Promise<Array<any>>;

export function ListRemoteToolMetadata():Promise<Array<any>>;

export function ListSkills(arg1:string):Promise<Array<main.Skill>>;

export function ListSkillsWithInstallStatus(arg1:string,arg2:string,arg3:string):Promise<Array<main.Skill>>;

export function LoadConfig():Promise<main.AppConfig>;

export function OpenSystemUrl(arg1:string):Promise<void>;

export function PackLog(arg1:string):Promise<string>;

export function ReadBBS():Promise<string>;

export function ReadThanks():Promise<string>;

export function ReadTutorial():Promise<string>;

export function ReconnectRemoteHub():Promise<void>;

export function RunRemoteClaudeSmoke(arg1:string,arg2:boolean):Promise<any>;

export function RunRemoteToolSmoke(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function RecoverCC():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RunEnvironmentCheckCLI():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SelectSkillFile():Promise<string>;

export function SendRemoteSessionImage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CaptureRemoteScreenshot(arg1:string):Promise<void>;

export function CaptureRemoteWindowScreenshot(arg1:string,arg2:string):Promise<void>;

export function SendRemoteSessionInput(arg1:string,arg2:string):Promise<void>;

export function SendRemoteSessionRawInput(arg1:string,arg2:string):Promise<void>;

export function SetEnvCheckInterval(arg1:number):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShouldCheckEnvironment():Promise<boolean>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function InterruptRemoteSession(arg1:string):Promise<void>;

export function KillRemoteSession(arg1:string):Promise<void>;

export function UpdateLastEnvCheckTime():Promise<void>;

export function UpdateTool(arg1:string):Promise<void>;

export function WindowHide():Promise<void>;

// NL Skill management bindings
export function ListNLSkills():Promise<Array<any>>;

export function CreateNLSkill(arg1:any):Promise<void>;

export function UpdateNLSkill(arg1:any):Promise<void>;

export function DeleteNLSkill(arg1:string):Promise<void>;

// MCP management bindings
export function ListMCPServers():Promise<Array<any>>;

export function RegisterMCPServer(arg1:any):Promise<void>;

export function UpdateMCPServer(arg1:any):Promise<void>;

export function UnregisterMCPServer(arg1:string):Promise<void>;

export function GetMCPServerTools(arg1:string):Promise<Array<any>>;

export function CheckMCPServerHealth(arg1:string):Promise<void>;

// Local MCP server management bindings
export function ListLocalMCPServers():Promise<Array<any>>;

export function RegisterLocalMCPServer(arg1:any):Promise<void>;

export function UpdateLocalMCPServer(arg1:any):Promise<void>;

export function UnregisterLocalMCPServer(arg1:string):Promise<void>;

export function SyncLocalMCPServers():Promise<void>;

export function GetLocalMCPServerStatuses():Promise<Array<any>>;

// MaClaw LLM configuration bindings
export function GetMaclawLLMConfig():Promise<any>;

export function SaveMaclawLLMConfig(arg1:any):Promise<void>;

export function GetMaclawLLMProviders():Promise<any>;

export function SaveMaclawLLMProviders(arg1:any, arg2:string):Promise<void>;

export function TestMaclawLLM(arg1:any):Promise<string>;

export function GetMaclawAgentMaxIterations():Promise<number>;

export function SetMaclawAgentMaxIterations(arg1:number):Promise<void>;

export function PingMaclawLLM():Promise<any>;

export function PingSkillHub(arg1:string):Promise<any>;

export function ValidateSkillHub(arg1:string):Promise<any>;

// SkillHub market bindings
export function SearchSkillHub(arg1:string):Promise<Array<any>>;

export function InstallHubSkill(arg1:string, arg2:string):Promise<void>;

export function CheckHubSkillUpdates():Promise<Array<any>>;

export function UpdateHubSkill(arg1:string):Promise<void>;

// Memory management bindings
export function ListMemories(arg1:string, arg2:string):Promise<Array<any>>;

export function SaveMemory(arg1:string, arg2:string, arg3:Array<string>):Promise<void>;

export function UpdateMemory(arg1:string, arg2:string, arg3:string, arg4:Array<string>):Promise<void>;

export function DeleteMemory(arg1:string):Promise<void>;

// Memory compression & backup bindings
export function CompressMemories():Promise<any>;

export function ListMemoryBackups():Promise<Array<any>>;

export function RestoreMemoryBackup(arg1:string):Promise<void>;

export function DeleteMemoryBackup(arg1:string):Promise<void>;

export function SetAutoCompress(arg1:boolean):Promise<void>;

export function GetAutoCompressStatus():Promise<any>;

// Scheduled task management bindings
export function ListScheduledTasks():Promise<Array<any>>;

export function CreateScheduledTask(arg1:string, arg2:string, arg3:number, arg4:number, arg5:number, arg6:number, arg7:string, arg8:string):Promise<string>;

export function UpdateScheduledTask(arg1:string, arg2:any):Promise<void>;

export function DeleteScheduledTask(arg1:string):Promise<void>;

export function PauseScheduledTask(arg1:string):Promise<void>;

export function ResumeScheduledTask(arg1:string):Promise<void>;
