// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CheckEnvironment(arg1:boolean):Promise<void>;

export function CheckToolsStatus():Promise<Array<main.ToolStatus>>;

export function CheckUpdate(arg1:string):Promise<main.UpdateResult>;

export function ClipboardGetText():Promise<string>;

export function DeleteSkill(arg1:string,arg2:string):Promise<void>;

export function DownloadUpdate(arg1:string,arg2:string):Promise<string>;

export function ActivateRemote(arg1:string):Promise<any>;

export function ClearRemoteActivation():Promise<void>;

export function GetCurrentProjectPath():Promise<string>;

export function GetDownloadsFolder():Promise<string>;

export function GetEnvCheckInterval():Promise<number>;

export function GetLocalCacheDir():Promise<string>;

export function GetRemoteActivationStatus():Promise<any>;

export function GetRemoteClaudeReadiness(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolReadiness(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemoteConnectionStatus():Promise<any>;

export function GetRemoteClaudeLaunchProbe(arg1:string,arg2:boolean):Promise<any>;

export function GetRemoteToolLaunchProbe(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetRemotePTYProbe():Promise<any>;

export function GetLastRemoteSmokeReport():Promise<any>;

export function StartRemoteClaudeSession(arg1:string,arg2:boolean):Promise<any>;

export function StartRemoteSession(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function StartRemoteHandoffSession(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function GetSkillsDir(arg1:string):Promise<string>;

export function GetSystemInfo():Promise<main.SystemInfo>;

export function GetUserHomeDir():Promise<string>;

export function InstallDefaultMarketplace():Promise<void>;

export function InstallSkill(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<void>;

export function InstallTool(arg1:string):Promise<void>;

export function InstallToolOnDemand(arg1:string):Promise<void>;

export function IsToolBeingInstalled(arg1:string):Promise<boolean>;

export function IsWindowsTerminalAvailable():Promise<boolean>;

export function LaunchInstallerAndExit(arg1:string):Promise<void>;

export function LaunchTool(arg1:string,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string,arg6:string,arg7:boolean):Promise<void>;

export function ListPythonEnvironments():Promise<Array<main.PythonEnvironment>>;

export function ListRemoteHubs(arg1:string,arg2:string):Promise<Array<any>>;

export function ListRemoteSessions():Promise<Array<any>>;

export function ListRemoteToolMetadata():Promise<Array<any>>;

export function ListSkills(arg1:string):Promise<Array<main.Skill>>;

export function ListSkillsWithInstallStatus(arg1:string,arg2:string,arg3:string):Promise<Array<main.Skill>>;

export function LoadConfig():Promise<main.AppConfig>;

export function OpenSystemUrl(arg1:string):Promise<void>;

export function PackLog(arg1:string):Promise<string>;

export function ReadBBS():Promise<string>;

export function ReadThanks():Promise<string>;

export function ReadTutorial():Promise<string>;

export function ReconnectRemoteHub():Promise<void>;

export function RunRemoteClaudeSmoke(arg1:string,arg2:boolean):Promise<any>;

export function RunRemoteToolSmoke(arg1:string,arg2:string,arg3:boolean):Promise<any>;

export function RecoverCC():Promise<void>;

export function ResizeWindow(arg1:number,arg2:number):Promise<void>;

export function RunEnvironmentCheckCLI():Promise<void>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function SelectProjectDir():Promise<string>;

export function SelectSkillFile():Promise<string>;

export function SendRemoteSessionInput(arg1:string,arg2:string):Promise<void>;

export function SetEnvCheckInterval(arg1:number):Promise<void>;

export function SetLanguage(arg1:string):Promise<void>;

export function ShouldCheckEnvironment():Promise<boolean>;

export function ShowItemInFolder(arg1:string):Promise<void>;

export function ShowMessage(arg1:string,arg2:string):Promise<void>;

export function InterruptRemoteSession(arg1:string):Promise<void>;

export function KillRemoteSession(arg1:string):Promise<void>;

export function UpdateLastEnvCheckTime():Promise<void>;

export function UpdateTool(arg1:string):Promise<void>;

export function WindowHide():Promise<void>;
